### ISSUE TITLE
customize / delete background pictures at login screen

### ISSUE THREAD

**Issue by jalapeno1083** [Fallenbagel/jellyseerr#1002]
### Description

The background of the login screen are cover pictures of shows and movies. The pictures are changing every few seconds. Is there any way to customize these pictures or to delete them completely and replace them with a static color? 

I am worried as I do not hold the copyright to these pictures. So for an  instance of Jellyseerr which is exposed to the internet it would be great if we could customize or change these pictures. 

### Desired Behavior

Have an option to customize or delete the background pictures which are shown on the Jellyseerr login page. 

### Additional Context

I already tried customizing the files in /app/public as recommended for changing the logo and I managed to change the logo, but the background pictures were unchanged. 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
These pictures come from themoviedb. It's public posters. Copyright won't really be applied to that.
