### ISSUE TITLE
no matching manifest for linux/arm/v8 in the manifest list entries

### ISSUE THREAD

**Issue by Lorgie1984** [Fallenbagel/jellyseerr#1007]
### Description

Trying to update from 1.9.2 to 2.0.0 on a RPi4.

no matching manifest for linux/arm/v8 in the manifest list entries

### Version

2.0.0

### Steps to Reproduce

Using Portainer CE to manage Docker.
Pulling the new image failes with given error

### Logs

```shell
Error	Failure	
no matching manifest for linux/arm/v8 in the manifest list entries
2024-10-15 20:32:18

Error	Failure	
Unable to create container: No such image: fallenbagel/jellyseerr:2.0.0
2024-10-15 20:32:00
```

### Platform

desktop

### Device

RPi4

### Operating System

Debian 6.1.21-v8+ aarch64

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Are you on armv7? We dropped support for armv7. Only aarch64 supported. We were forced to do so as nextjs dropped support for jt

**Comment by Fallenbagel** [comment]
Can you run `uname -m`

**Comment by Powerbless** [comment]
I am in aarch64 on Raspberry Pi 3B+ and can Not Install via docker. Got the Same error

**Comment by Fallenbagel** [comment]
> I am in aarch64 on Raspberry Pi 3B+ and can Not Install via docker. Got the Same error

Hop onto discord for support.
