### ISSUE TITLE
/avatarproxy prefer hostname/ip address over external url if provided

### ISSUE THREAD

**Issue by Hujgo** [Fallenbagel/jellyseerr#1012]
### Description

The user avatar in Jellyfin is retrieved from the path `/avatarproxy/jellyfin.domain.com`

### Desired Behavior

The user avatar can be retrieved from the hostname/IP address using the following path: `/avatarproxy/http://hostname:port`

### Additional Context

Tested the path using `/avatarproxy/http://jellyfin:8096/...` for Jellyfin user avatar and it works. This was not an issue in v1.19.2

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
If this a bug please reopen with the proper template. If this is a feature request, please elaborate what desired behavior you want

**Comment by Hujgo** [comment]
Yep

**Comment by kokojako** [comment]
omfg, thanks man, i believed I was mad
I have same errors and thought was my settings 

![jellyseer_1](https://github.com/user-attachments/assets/3d61592d-d6f7-40ac-8ee6-5402239d0990)
![jellyseer_2](https://github.com/user-attachments/assets/a8835e14-e0e9-49c0-87e8-a38354c56412)

**Comment by kokojako** [comment]
I dont use jellyfin but plex and its the same issue

**Comment by Fallenbagel** [comment]
> omfg, thanks man, i believed I was mad
> I have same errors and thought was my settings 
> 
> ![jellyseer_1](https://github.com/user-attachments/assets/3d61592d-d6f7-40ac-8ee6-5402239d0990)
> ![jellyseer_2](https://github.com/user-attachments/assets/a8835e14-e0e9-49c0-87e8-a38354c56412)
> 

Do you have imageproxy turned on in settings? If not can you turn on and check? If turned off vice versa. And send logs
