### ISSUE TITLE
Avatar Proxy allows requesting any resource from literally every origin

### ISSUE THREAD

**Issue by rflrkn** [Fallenbagel/jellyseerr#1013]
### Description

I just noticed that the avatar proxy allows proxying/loading literally any request - no matter the original ressource's origin or filetype. 

### Version

2.0.0

### Steps to Reproduce

Try requesting (e. g.): 
https://{YOUR-JELLYSEER-HOST}/avatarproxy/https://ash-speed.hetzner.com/100MB.bin

### Platform

desktop

### Device

MacBook Pro (doesn't matter tho)

### Operating System

macOS 15.0.1

### Browser

Zen Browser (Firefox)

### Additional Context

The avatar proxy should only allow loading ressources from the configured Jellyfin host (or it's external URL) and maybe also check MIME types

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by kokojako** [comment]
Hi, same as https://github.com/Fallenbagel/jellyseerr/issues/1012

**Comment by gauthier-th** [comment]
Hi, yep I'm fixing it. A patch will be available very soon
