### ISSUE TITLE
[Bug] Wrong user picture in request list

### ISSUE THREAD

**Issue by pafade89** [Fallenbagel/jellyseerr#1017]
### Description

Jellyseerr get the wrong picture for user in the request list

### Version

2.0.0

### Steps to Reproduce

1. Goto Requests
2. Look to the user changes

### Screenshots

![image](https://github.com/user-attachments/assets/810fb335-1eed-49c6-b58a-951220813686)

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
After #1016 is in and release, make that user log out and log back in and their avatar should refresh. (feel free to reopen if not)

**Comment by pafade89** [comment]
Thank you very much.

**Comment by pafade89** [comment]
@Fallenbagel Unfortunately it doesn't worked as accepted. Same issue like before.

Cheers P

**Comment by Fallenbagel** [comment]
> @Fallenbagel Unfortunately it doesn't worked as accepted. Same issue like before.
> 
> Cheers P

did the user log out and back in? is the user a jellyfin user?

**Comment by pafade89** [comment]
For both points, a yes.

**Comment by Fallenbagel** [comment]
@pafade89 Also i would suggest hopping onto discord so we can debug this easily as I cannot seem to replicate it. This might actually be an issue as we recently added an avatar caching and it could be that in the ticket list its not removing the invalidated image
