### ISSUE TITLE
building v2.0.0/v2.0.1 crashes with npm ERR! Override without name: sqlite3/node-gyp

### ISSUE THREAD

**Issue by Wurzelmann** [Fallenbagel/jellyseerr#1020]
### Description

I've been building and hosting jellyseerr for a year now, never had any trouble with the building process, but since v2.0.0 I cannot build the newest version, it is always the same error:

`npm ERR! Override without name: sqlite3/node-gyp`

### Version

1.9.2

### Steps to Reproduce

1. follow the installation/upgrade steps from https://docs.jellyseerr.dev/getting-started/buildfromsource?versions=latest
2. error occurs

### Logs

```shell
41 error Override without name: sqlite3/node-gyp
42 verbose exit 1
43 timing npm Completed in 76ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /opt/tintenwish/.npm/_logs/2024-10-17T14_26_26_917Z-debug-0.log
```

### Platform

desktop

### Device

server

### Operating System

Debian 12.7

### Browser

not applicable

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You cannot use latest instructions. You'll have to use develop tab instructions. Documentation is not updated yet.

https://docs.jellyseerr.dev/getting-started/buildfromsource?versions=develop
