### ISSUE TITLE
Login with Jellyfin not working after update to 2.0.1

### ISSUE THREAD

**Issue by p-rintz** [Fallenbagel/jellyseerr#1023]
### Description

Trying to login to Jellyseerr with Jellyfin login fails after update to 2.0.1 with the following error message:
`Something went wrong while trying to sign in.`

In the log it will give the following two lines in regards to the failure:
```
Oct 17 15:34:56 jellyseerr node[162701]: 2024-10-17T15:34:56.720Z [debug][Jellyfin API]: Failed to authenticate with headers: Failed to parse URL from http://undefined:undefinedundefined/Users/AuthenticateByName {"ip":"10.2.100.128"}
Oct 17 15:34:56 jellyseerr node[162701]: 2024-10-17T15:34:56.721Z [warn][Auth]: Failed login attempt from user with incorrect Jellyfin credentials {"account":{"ip":"::ffff:10.2.100.128","email":"my@email.example.com","password":"__REDACTED__"}}
```

Not sure why everything is now undefined after the upgrade in regards to the Jellyfin instance.

### Version

2.0.1

### Steps to Reproduce

1. Upgrade to 2.0.1
2. Go to login
3. Try to login
4. Fail

### Platform

desktop

### Device

Linux PC

### Operating System

Ubuntu 22.04

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
`http://undefined:undefinedundefined/`

can you check your settings.json and see the jellyfin section. See if the ip and port is set correctly

**Comment by p-rintz** [comment]
I looked through Discord to see if others had this issue and found somebody who had postet their settings.json.
Their settings.json had some things which mine lacked.

Here is the diff from my backed-up settings.json and the settings.json that now works:

```
 "jellyfin": {							 "jellyfin": {
  "name": "Jellyfin",					      |	  "name": "",
  "hostname": "http://10.2.100.100:8096",		      |	  "hostname": "http://10.2.100.100",
  "externalHostname": "https://domain.was.here.com",			  "externalHostname": "https://domain.was.here.com",
  "jellyfinForgotPasswordUrl": "",			      |	  "libraries": [],
  "libraries": [					      |	  "serverId": "0101010101010101010101001010101010101"
   {							      <
    "id": "0202020202020202",		      <
    "name": "Anime",					      <
    "enabled": true,					      <
    "type": "show"					      <
   },							      <
   {							      <
    "id": "030303030303030",		      <
    "name": "Movies",					      <
    "enabled": true,					      <
    "type": "movie"					      <
   },							      <
   {							      <
    "id": "040404040404040",		      <
    "name": "Shows",					      <
    "enabled": true,					      <
    "type": "show"					      <
   }							      <
  ],							      <
  "serverId": "0101010101010101010101001010101010101",	      <
  "ip": "10.9.200.100",					      <
  "useSsl": false,					      <
  "urlBase": "",					      <
  "apiKey": "APIKEYWASHERE",		      <
  "port": 8096						      <
 },								 },
```


It was completely missing the ip,usessl,urlbase,apikey and port part.

**Comment by p-rintz** [comment]
It worked before 2.0.1. Not sure if there is supposed to be some migration happening or something.

**Comment by Fallenbagel** [comment]
there is supposed to be migrations happening in 2.0.0 and 2.0.1. I guess the migrations failed on your instance for some reason

**Comment by Fallenbagel** [comment]
Please close the issue if fixed c:

**Comment by Fallenbagel** [comment]
> Alright. Didnt want to just close it in case you wanted logs or anything the like.

The migration wouldnt log anything. We are thinking of adding a check when migration fails to not start jellyseerr to avoid migration failures for people migrating from 1.9.2 -> 2.x.x in the future

**Comment by lluisd** [comment]
I have the same problem

**Comment by deeerow** [comment]
Yah I am currently having that issues, will try and figure out if i have a back up of my previous settings.json

**Comment by deeerow** [comment]
for me I just had to add the ip/port/apiKey(which i just generated from jellyfin's dashboard). Question for the "useSsl" variable, is that for the IP or the externalhostname?

**Comment by gauthier-th** [comment]
`useSsl` is for the IP.

**Comment by dotbanana** [comment]
I had exactly the same problem.  
This should be noted somewhere more prominent that migration broke among updates

**Comment by Fallenbagel** [comment]
> I had exactly the same problem.  
> Couldn't fix it even when adding the missing parameters above. Broke my whole setup basically. 
> Well done.
> This should be noted somewhere more prominent that migration brakes everything and that people shouldn't update carelessly.    
> 

We literally just added a fix.
And if you actually hopped onto discord we could have helped you fix this. This is not affecting everybody just a select few. You should always backup anyways before you upgrade especially a major upgrade from v1 to v2.

**Comment by Fallenbagel** [comment]
> This should be noted somewhere more prominent that migration brakes everything and that people shouldn't update carelessly.

Please don't misinform people. Migrations are just for settings.json. breaking settings.json doesn't break the everything. It's literally designed to be editable to fix at any time. You can even replace it with a new settings.json and it will still work.

**Comment by ice-92** [comment]
In case it helps anyone, this is what I had to do to get it to work.

Add these lines under the "jellyfin" entry:

  "ip": "192.168.XX.XX",
  "useSsl": false,
  "urlBase": "",
  "apiKey": "Generate new api key here from jellyfin",
  "port": "8096"

Remove the port from "hostname"
Empty "name" entry
