### ISSUE TITLE
Cannot pass BasicAuth in URLs

### ISSUE THREAD

**Issue by danwilldev** [Fallenbagel/jellyseerr#1027]
### Description

When trying to connect a service, jellyseerr no longer accepts basic auth credentials as part of the URL string.

### Version

2.0.1

### Steps to Reproduce

Try to connect any service eg Sonarr to Jellyseerr. Pass basic auth as part of the string and observe the below log-line after failing to connect.

### Logs

```shell
[error][Radarr]: [Radarr] Failed to retrieve profiles: Request cannot be constructed from a URL that includes credentials: https://username:Password@urlhere/radarr/api/v3/qualityProfile?apikey=apiKeyHere
```

### Platform

desktop

### Device

Server

### Operating System

Ubuntu

### Browser

Firefox

### Additional Context

As per @Fallenbagel on discord. "2.0.0 introduced fetch and url constructor doesn't like basic auth in url."

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
@danwilldev could you test `:preview-fix-basic-auth` to see if it works now?
The tag should be available in about half an hour

**Comment by danwilldev** [comment]
@Fallenbagel I have tested on my machine and can now connect services with basic auth. Thanks for the fix guys :D
