### ISSUE TITLE
Add an option to filter out pornographic films from reccomendations and search results

### ISSUE THREAD

**Issue by CheezyFriez12** [Fallenbagel/jellyseerr#1033]
### Description

I have been very satisfied with this software, as it provides a very simple way to add downloads to my arrs, both for me and for the few i share my server with. My only complaint is that I have no way of filtering out the (mostly korean?) pornographic content, which makes it difficult to share with certain people who are more uncomfortable about that.

### Desired Behavior

A toggle that would filter out such content while not restricting mature or adult rated films.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
We already filter out adult stuff. The problem is some stuff are not properly tagged on tmdb. That is why introduced blacklist feature. You can blacklist it now. 

And this issue is a duplicate as well
