### ISSUE TITLE
Trending page full of actors

### ISSUE THREAD

**Issue by jmarsh88** [Fallenbagel/jellyseerr#1037]
### Description

Since upgrading to v2.0.1 the trending page is full of actors, there are no TV shows or Series being displayed.

### Version

2.0.1

### Steps to Reproduce

1. Log in to Jellyseerr as any user, desktop or mobile
2. Select Discover
3. Select Trending

### Screenshots

![brave_aGiGhA85QE](https://github.com/user-attachments/assets/df75eee3-fc71-4009-90a8-418e5a3625ee)

### Platform

desktop

### Device

Desktop, Pixel 9 Pro, iPhone 17 Pro

### Operating System

Windows, Android 15, iOS 18

### Browser

Brave, Safari

### Additional Context

Discover language is set to English, region is set to Australia. 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by PH1L900D** [comment]
Same

**Comment by LuUuLzZz** [comment]
Can confirm have the same issue with the Actors showing in Trending section.

**Comment by Fallenbagel** [comment]
https://www.themoviedb.org/talk/6711c96f097c3d7760f87c6a
