### ISSUE TITLE
Allow hiding requested items

### ISSUE THREAD

**Issue by nupulu** [Fallenbagel/jellyseerr#1041]
### Description

when using Jellyseer to consider media items to be requested or not, it helps if the view only shows items that are not already available and not already successfully requested (and not blacklisted). So it shows only items, where no decision has yet been made and they actually can still be requested. This makes the consideration process much quicker. Hiding/Showing requested items should be an option at the user level. 

### Desired Behavior

If the option to Hide requested items is enabled, items that have already been successfully request by some user should be hidden.

### Additional Context

This feature is similar to hiding already available items, and it complements this functionality.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
There's already an option to hide available media

**Comment by Fallenbagel** [comment]
> > There's already an option to hide available media
> 
> @Fallenbagel the existing option to hide available media does not hide media that are requesed but not yet available. media can be in this status for a long time. how can I hide them with the current version? If I cannot, please re-open my issue.

A feature request for that already exists in #336 making this duplicate
