### ISSUE TITLE
Failed to Build Package from AUR using yay

### ISSUE THREAD

**Issue by SirMaxwellSmart** [Fallenbagel/jellyseerr#1043]
### Description

yay fails to update Jellyseerr to 2.0.1 as it fails to build the package.

Without npm installed locally
`/bin/sh: line 1: npx: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: jellyseerr-exit status 4`
 
 With npm installed locally
`npm error Override without name: sqlite3/node-gyp
npm error A complete log of this run can be found in: /home/kks/.npm/_logs/2024-10-21T20_56_58_418Z-debug-0.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: jellyseerr-exit status 4`

### Version

2.0.1

### Steps to Reproduce

1. Try to update the Jellyseerr using yay
2. Receive error

### Logs

```shell
==> Making package: jellyseerr 2.0.1-1 (Tue 22 Oct 2024 04:50:08)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found jellyseerr-2.0.1.tar.gz
  -> Found jellyseerr.sysusers
  -> Found jellyseerr.tmpfiles
  -> Found jellyseerr.service
  -> Found jellyseerr.conf.d
  -> Found no-prepare-husky.patch
==> Validating source files with sha256sums...
    jellyseerr-2.0.1.tar.gz ... Passed
    jellyseerr.sysusers ... Passed
    jellyseerr.tmpfiles ... Passed
    jellyseerr.service ... Passed
    jellyseerr.conf.d ... Passed
    no-prepare-husky.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting jellyseerr-2.0.1.tar.gz with bsdtar
==> Sources are ready.
==> Making package: jellyseerr 2.0.1-1 (Tue 22 Oct 2024 04:50:09)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
patching file package.json
Hunk #1 succeeded at 21 with fuzz 1 (offset 3 lines).
yarn install v1.22.22
warning ../../../../../package.json: No license field
info No lockfile found.
$ npx only-allow pnpm
/bin/sh: line 1: npx: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: jellyseerr-exit status 4
```

### Platform

desktop

### Device

Desktop 

### Operating System

Arch Linux

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
We don't maintain aur package. It's maintained by a third party. Not us.

**Comment by SirMaxwellSmart** [comment]
Sure I understand.
Not sure why it's mentioned so officially on the Github readme and website then.
Mentioning that it's 3rd party maintained there would certainly be helpful.

**Comment by Fallenbagel** [comment]
> Sure I understand.
> Not sure why it's mentioned so officially on the Github readme and website then.
> Mentioning that it's 3rd party maintained there would certainly be helpful.

Docs are a work in progress. We recently deployed the docs. It's not finished yet. But yeah the only official supported methods are:
- docker
- build from source
