### ISSUE TITLE
Specifying a reason for declining a request

### ISSUE THREAD

**Issue by Altheran88** [Fallenbagel/jellyseerr#1051]
### Description

Current situation : You decline a content, that's it, a generic notification is sent.

### Desired Behavior

Display a text dialog on decline to optionally provide a reason for declining the request. This "reason" would be added to the notification.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
Duplicate of #988.
