### ISSUE TITLE
Empty logs

### ISSUE THREAD

**Issue by Mavyre** [Fallenbagel/jellyseerr#1054]
### Description

The log file, stdout and the log tabs in settings are completely empty

### Version

2.0.1

### Steps to Reproduce

1. Launch docker container with `LOG_LEVEL` var set to `debug`
2. Check the log file

### Screenshots

![image](https://github.com/user-attachments/assets/7d785f5b-e10d-443c-a788-4d882c40f867)

### Platform

desktop

### Device

Desktop PC

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Probably a config perm issue. Check if the logs folder exist in the configuration folder.

And please hop onto discord for support queries.
