### ISSUE TITLE
External URL validation is too strict

### ISSUE THREAD

**Issue by SyfSchydea** [Fallenbagel/jellyseerr#1068]
### Description

My Jellyfin, Radarr and Sonarr are all accessed on `http://melorae` within my local network. But attempting to enter this in the "External URL" doesn't work because "You must provide a valid URL".

### Version

2.0.1

### Steps to Reproduce

Settings -> Jellyfin -> External URL
enter any domain without a suffix

### Platform

desktop

### Device

PC

### Operating System

Ubuntu 24 (server), Windows 10 (client)

### Browser

Firefox

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

**Comment by SyfSchydea** [comment]
The internal URL is based on the containers' hostnames, which are not the same as the external hostname.

**Comment by Fallenbagel** [comment]
> The internal URL is based on the containers' hostnames, which are not the same as the external hostname.

For the time being, you can set it directly on settings.json file

**Comment by gauthier-th** [comment]
It's easy to do a fix for this one, but I'm afraid this would cause less experienced people to fill in wrong values.
@Fallenbagel wdyt?

**Comment by Fallenbagel** [comment]
> It's easy to do a fix for this one, but I'm afraid this would cause less experienced people to fill in wrong values.
> @Fallenbagel wdyt?

We could add a stricter validation here where it allows:
`http://domain`
`http://domain.com`
`http://domain.com:9999`
`http://domain.com/base`
`http://domain.com:9999/base`
`http://x.x.x.x:9999`
^etc with ofc protocol check too for http:// https://?

**Comment by gauthier-th** [comment]
> > It's easy to do a fix for this one, but I'm afraid this would cause less experienced people to fill in wrong values.
> > @Fallenbagel wdyt?
> 
> We could add a stricter validation here where it allows: `http://domain` `http://domain.com` `http://domain.com:9999` `http://domain.com/base` `http://domain.com:9999/base` `http://x.x.x.x:9999` ^etc with ofc protocol check too for http:// https://?
> 
> Sounds like regex hell though. We could look into if yup validator allows such a thing

In this case we can just allow everything starting with `http://` or `https://`?

**Comment by Fallenbagel** [comment]
> > > It's easy to do a fix for this one, but I'm afraid this would cause less experienced people to fill in wrong values.
> > > @Fallenbagel wdyt?
> > 
> > We could add a stricter validation here where it allows: `http://domain` `http://domain.com` `http://domain.com:9999` `http://domain.com/base` `http://domain.com:9999/base` `http://x.x.x.x:9999` ^etc with ofc protocol check too for http:// https://?
> > 
> > Sounds like regex hell though. We could look into if yup validator allows such a thing
> 
> In this case we can just allow everything starting with `http://` or `https://`?

Yes

**Comment by gauthier-th** [comment]
> > > > It's easy to do a fix for this one, but I'm afraid this would cause less experienced people to fill in wrong values.
> > > > @Fallenbagel wdyt?
> > > 
> > > 
> > > We could add a stricter validation here where it allows: `http://domain` `http://domain.com` `http://domain.com:9999` `http://domain.com/base` `http://domain.com:9999/base` `http://x.x.x.x:9999` ^etc with ofc protocol check too for http:// https://?
> > > Sounds like regex hell though. We could look into if yup validator allows such a thing
> > 
> > 
> > In this case we can just allow everything starting with `http://` or `https://`?
> 
> Yes and no. What if its http://@hdhskl:!@

Yes, I mean just a regular URL
