### ISSUE TITLE
Jellyseerr fails to fetch profiles when SSL is enabled and using certs signed by internal CA

### ISSUE THREAD

**Issue by lordairivis** [Fallenbagel/jellyseerr#1069]
### Description

I recently set up Radarr and Sonarr to use SSL with a certificate signed by my internal CA. I installed the full CA chain (root and intermediate signing CA certs) on the LXC running Jellyseerr, but when I change the port/protocol of the services in Jellyseerr to use the SSL port, Jellyseerr errors out:
`2024-11-02T18:38:44.135Z [error][Radarr]: [Radarr] Failed to retrieve profiles: fetch failed`

If I run `openssl s_client -connect <radarr:SSL port> -state -nbio 2>&1 | grep "^SSL"` from the container running Jellyseerr it appears to connect and handshake successfully, so not sure why Jellyseerr isn't able to fetch the profiles.

Connection works as expected when using the non-SSL port to the same instance of Radarr or Sonarr.

### Version

2.0.1

### Steps to Reproduce

1. Configure SSL in Radarr/Sonarr and import full chain CA certificates to system running Jellyseerr
2. Add service to Jellyseerr using SSL port/protocol
3. Attempt to test connection

### Platform

desktop

### Device

PC

### Operating System

Ubuntu 24.04.1

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
In case anyone comes across this issue, this has been fixed by doing this:

> i added Environment=NODE_EXTRA_CA_CERTS=[your CA certificate file path] with the path to the .crt in /usr/local/share/ca-certificates/ and it worked
> in the service file

*From @lordairivis on Discord*
