### ISSUE TITLE
Inability to Download the Netflix Series "Monsters" Due to Matching Issue

### ISSUE THREAD

**Issue by Nabstar3** [Fallenbagel/jellyseerr#1071]
### Description

When attempting to download the Netflix series "Monsters," Jellyseerr does not automatically match it to the correct series. When prompted to select the correct match manually, it still cannot find the appropriate series. After selecting the Monsters (2022) series it only shows season 1 and is still unable to fulfill the request

### Version

2.0.1

### Steps to Reproduce

1. Go to the Jellyseerr series request page.
2. Search for the Netflix series "Monsters."
3. Observe the inability to match the series automatically.
4. Attempt to manually select the correct match from the provided options but find no correct option available.

### Screenshots

![image](https://github.com/user-attachments/assets/ffaf8557-f883-4d29-864c-673b8d62c212)
![image](https://github.com/user-attachments/assets/10738575-5097-4ce8-92a2-6010b7f74f14)

### Platform

desktop

### Device

Samsung ultrabook

### Operating System

Windows 11

### Browser

Chrome

### Additional Context

https://thetvdb.com/series/monster-the-jeffrey-dahmer-story/seasons/official/2#general

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is not an issue with jellyseerr. Tmdb is missing the external id. You need to go add it in tmdb.

**Comment by Nabstar3** [comment]
> This is not an issue with jellyseerr. Tmdb is missing the external id (tvdbid). You need to go add it in tmdb (it's open source).

I created a support ticket to resolve the misclassifcation issue on TMDB [here](https://www.themoviedb.org/talk/67284c75554578c90de30249).

I didn't see any sort of "Suggest an edit section" and I believe I can only suggest/add new series/movies.

**Comment by Fallenbagel** [comment]
> > This is not an issue with jellyseerr. Tmdb is missing the external id (tvdbid). You need to go add it in tmdb (it's open source).
> 
> I created a support ticket to resolve the misclassifcation issue on TMDB [here](https://www.themoviedb.org/talk/67284c75554578c90de30249).
> 
> I didn't see any sort of "Suggest an edit section" and I believe I can only suggest/add new series/movies.

You can edit the external ids of shows once you login. You need to press edit. I have added external ids like that to many shows as well

**Comment by Nabstar3** [comment]
> > > This is not an issue with jellyseerr. Tmdb is missing the external id (tvdbid). You need to go add it in tmdb (it's open source).
> > 
> > 
> > I created a support ticket to resolve the misclassifcation issue on TMDB [here](https://www.themoviedb.org/talk/67284c75554578c90de30249).
> > I didn't see any sort of "Suggest an edit section" and I believe I can only suggest/add new series/movies.
> 
> You can edit the external ids of shows once you login. You need to press edit. I have added external ids like that to many shows as well
> 
> Tmdb is open source. You don't suggest an edit. You can edit. Let me check this show
> 
> ![Screenshot_20241104_185258_Firefox Beta.jpg](https://private-user-images.githubusercontent.com/98979876/382728139-6469f3ec-cc7f-49fa-b615-f10a90704913.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODAwODEsIm5iZiI6MTczMDc3OTc4MSwicGF0aCI6Ii85ODk3OTg3Ni8zODI3MjgxMzktNjQ2OWYzZWMtY2M3Zi00OWZhLWI2MTUtZjEwYTkwNzA0OTEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA0MDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZjI1MzA1Zjk3NzliOTU5YzFjNDU2MWRiODI0ZjUxMDg3NjVmYzhjZmQxMGE3MGMwNDFhZjRmZDllODJiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sCROaWPa-2sjerZelrWD09F8ICRFm9MJhSfw-rAEnpY)
> 
> ![Screenshot_20241104_185317_Firefox Beta.jpg](https://private-user-images.githubusercontent.com/98979876/382728138-ca0e93cb-5c23-47d5-8433-1b343592e6be.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODAwODEsIm5iZiI6MTczMDc3OTc4MSwicGF0aCI6Ii85ODk3OTg3Ni8zODI3MjgxMzgtY2EwZTkzY2ItNWMyMy00N2Q1LTg0MzMtMWIzNDM1OTJlNmJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA0MDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZDYyMzE2ODc1ZmI2YjYwNDk1YjNmZThhMGI5M2RkOWMyZTJiYTFkNjJhZjE2ZTQ0ZDg0MTgxOGZmOWY1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JeEHQ62Hhur_bFi4yauexRfSMlExIvYZ5WS6m4-iUmA)

Thanks for pointing this out. 

The correct series is [here](https://www.themoviedb.org/tv/225634-monsters-the-lyle-and-erik-menendez-story/edit?active_nav_item=external_ids)

I'm not sure why on my end I can't edit the external ID's.

![image](https://github.com/user-attachments/assets/860976f8-e115-4219-89ea-fc589b9e3761)

I also see a potential issue from the way TVDB decided to categorize the series compared to other databases. 
I'm not sure what other API Jellyseerr uses but the TVDB decided to designate it as a seperate series compared to IMDB and thetvdb. More information [here](https://www.themoviedb.org/tv/113988-dahmer-monster-the-jeffrey-dahmer-story/discuss/66ccf0c787d0e713456eb45b?page=1).

**Comment by Nabstar3** [comment]
Looking at `sonarr.ts` under `api`, correct me if I'm wrong, but jellyseerr submits a request to add a new series based on the TVDB id?

If my presumption is correct, then just the TVDB ID needs to be updated for the series in TMDB?

I always thought this was based on series title.

**Comment by Fallenbagel** [comment]
> Looking at `sonarr.ts` under `api`, correct me if I'm wrong, but jellyseerr submits a request to add a new series based on the TVDB id?
> 
> If my presumption is correct, then just the TVDB ID needs to be updated for the series in TMDB?
> 
> I always thought this was based on series title.

Yes tvdbid. Not title. Because series title can be different for the same series in different databases
