### ISSUE TITLE
Filtering out main screen suggestions by Parental Rating / genre

### ISSUE THREAD

**Issue by molly78** [Fallenbagel/jellyseerr#1074]
### Description

It would be great if the ability to filter out certain genres / parental ratings based on user profiles was possible

### Desired Behavior

On the main screen it would be great if one could filter out suggestions for upcoming, etc based on parental ratings or genre tags

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate of #204
