### ISSUE TITLE
Jellyseerr not marking downloaded season as available

### ISSUE THREAD

**Issue by ultimateguy** [Fallenbagel/jellyseerr#1078]
### Description

A series request was put in for one season of a show. The season is fully downloaded and Sonarr indicates it is available. It's also available in Jellyfin. But Jellyseerr still has its status as 'Requested' instead of 'Available'. I have many other series with no issues - just this one. I tried removing it and re-requesting it, but same result. Also ran the scan library job.

### Version

2.0.1

### Steps to Reproduce

Request single season of show and wait for it to download.

### Screenshots

Jellyseer:
![image](https://github.com/user-attachments/assets/5abb0613-7313-4492-9e10-d45f62e019c0)

Sonarr:
![image](https://github.com/user-attachments/assets/3dc70380-4444-4995-8870-0e17ed8c98b1)

### Platform

desktop

### Device

Firefox - Jellyfin running in Docker on server

### Operating System

Docker/Ubuntu 24.04

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is most likely a configuration issue. Support requests should go to discord. Please hop onto discord.
