### ISSUE TITLE
[Feature Request] Remove Requirement for Jellyfin Passwords

### ISSUE THREAD

**Issue by CyferShepard** [Fallenbagel/jellyseerr#108]
### Description

I noticed that when I try to login with a Jellyfin user that doesn't have a password set, Jellyseerr fails to login. I cant seem to find any setting that can be used to toggle password requirements aswell. 

Is there some way where we can login using Jellyfin accounts without passwords?

### Desired Behavior

Login to Jellyseerr using a Jellyfin account that does not have a set password.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
@CyferShepard hi what happened to the pull request for this issue?

**Comment by CyferShepard** [comment]
Hi, sorry, I was up till 3 am and some stuff happened with git when I was trying to push commits to a seperate branch, I'm gonna have to push this again later as I also added a new job but it merged on the same branch in my repo

**Comment by stayingarmed** [comment]
Is there something I have to do to enable this….because I’m still unable to login without a password

**Comment by stayingarmed** [comment]
> @stayingarmed are you on latest or develop?

Jellyseer stable v1.1.0

**Comment by Fallenbagel** [comment]
This fix has not yet been released in the stable. Its only been implemented in the develop branch

**Comment by stayingarmed** [comment]
> This fix has not yet been released in the stable. Its only been implemented in the develop branch

Ok, my apologies….I thought it was pushed to the stable release.

**Comment by NicolaiVdS** [comment]
> This fix has not yet been released in the stable. Its only been implemented in the develop branch

not yet in development stil need to be merged, normally today after some testing

**Comment by NicolaiVdS** [comment]
> > This fix has not yet been released in the stable. Its only been implemented in the develop branch
> 
> Ok, my apologies….I thought it was pushed to the stable release.

if you want you can join the discord server and become a tester ;)
