### ISSUE TITLE
Can't set up local dev env without docker

### ISSUE THREAD

**Issue by bonswouar** [Fallenbagel/jellyseerr#1085]
### Description

As it seems the git hook for prettier doesn't run automatically from Docker (my PR has prettier warnings in the github action), I wanted to set up a local dev env as per the instructions.

### Version

develop

### Steps to Reproduce

1. Install node/pnpm
2. Checkout
3. `pnpm install` (not just `pnpm` without any arg as it says in the [readme](https://github.com/fallenbagel/jellyseerr/blob/develop/CONTRIBUTING.md), as it returns the Help)

### Logs

```shell
$ pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +2027
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERR_PNPM_READ_FROM_STORE  Unexpected end of JSON input
Progress: resolved 2027, reused 0, downloaded 0, added 0
```

### Platform

desktop

### Device

pc

### Operating System

linux

### Browser

nope

### Additional Context

```bash
$ node -v
v20.18.0
```
```bash
$ pnpm -v
9.12.3
```

Also I've tried the other pnpm command just in case:
```bash
$ pnpm dev

> jellyseerr@0.1.0 dev /home/bonswouar/git/jellyseerr
> nodemon -e ts --watch server --watch overseerr-api.yml -e .json,.ts,.yml -x ts-node -r tsconfig-paths/register --files --project server/tsconfig.json server/index.ts

sh: 1: nodemon: not found
 ELIFECYCLE  Command failed.
```

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
This is probably an issue or your side, I can't reproduce this on any of my machine.
Try to cleanup your store with `pnpm store prune`: https://github.com/pnpm/pnpm/issues/8381

**Comment by bonswouar** [comment]
```bash
$ pnpm store prune
Removed all cached metadata files
Removed 69493 files
 ERROR  Unexpected end of JSON input while parsing empty string in ../../.local/share/pnpm/store/v3/files/02/13b9414723f2596b6c6d3d89684f536076d38275c673de2fc910995a2b4accbe4a38f5b24f2023287a714a1c1a61f82f452e840272fa124c440e26800e2615-index.json

pnpm: Unexpected end of JSON input while parsing empty string in ../../.local/share/pnpm/store/v3/files/02/13b9414723f2596b6c6d3d89684f536076d38275c673de2fc910995a2b4accbe4a38f5b24f2023287a714a1c1a61f82f452e840272fa124c440e26800e2615-index.json
```

But despite the error it seems it worked, thanks!!
