### ISSUE TITLE
Form validation causes background to stretch giving a zooming in appearance 

### ISSUE THREAD

**Issue by txtsd** [Fallenbagel/jellyseerr#1087]
### Description

When receiving form validation errors on the /setup page, the background seems to zoom in as it seems dynamically dependent on the height of the page.

### Version

2.0.1

### Steps to Reproduce

1. Go to /setup
2. Mistype a form field that has validation
3. See the background zoom

### Platform

desktop

### Device

Desktop computer

### Operating System

Arch Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I cannot reproduce this. Can you post a video

**Comment by txtsd** [comment]
I should've recorded it right then. I'm unable to reproduce it again.
