### ISSUE TITLE
Warning for unset E-mail

### ISSUE THREAD

**Issue by TyxTang** [Fallenbagel/jellyseerr#1088]
### Description

Is it normal to create a new local user and the email cannot be changed or added once it is set or not set during the new user creation process?

> If the email is not set during the user creation process, a warning that the email is not set will appear when logging in and the user will not be able to add a new email.

### Version

2.0.1

### Steps to Reproduce

1. Create a new local user
2. Fill in only the username and password
3.Logging in new user prompts no E-mail settings
4. Personal settings to add E-mail and save
5.Refresh the page, the E-mail disappears, and the warning about not setting E-mail still exists.
6. Use the administrator account to modify the user interface with the same error as above.

### Platform

desktop

### Device

Macbook Pro

### Operating System

MacOS 12.6.6(User),Ubuntu 22.04(Server Docker)

### Browser

Edge

### Additional Context

This feature works fine in version 1.9.3

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
It's not normal. I can reproduce the issue.
You should be able to change the email of a local user.
