### ISSUE TITLE
Unable to get queue from Sonarr and Radarr servers randomly

### ISSUE THREAD

**Issue by sv-giampa** [Fallenbagel/jellyseerr#1091]
### Description

The Radarr and Sonarr servers gets unreachable at random times, apparently. When this event occurs, Jellyseerr UI becomes unaccessible, showing "500 Internal Server Error" and in the container logs appear the messages "Unable to get queue from Radarr server: radarr" and "Unable to get queue from Sonarr server: sonarr". The bug seems to happean after doing many requests to the web server (e.g., after many refreshes of a page or after many API requests).

I discovered this bug from version 2.0.0, but it is present at version 2.0.1 too. For now i solved it by downgrading to version 1.9.2.

### Version

2.0.1

### Steps to Reproduce

Try to reproduce the error by submitting many requests to the web server of Jellyseerr (e.g., many refreshes of a page or many API requests).

### Logs

```shell
Unable to get queue from Radarr server: radarr
Unable to get queue from Sonarr server: sonarr
```

### Platform

desktop

### Device

Desktop Computer

### Operating System

Windows 11

### Browser

Chrome

### Additional Context

My Radarr and Sonarr servers are in their containers instantiated in the same Docker Compose stack where my Jellyseerr container lies. My Jellyseerr instance accesses Radarr and Sonarr by their containers' hostnames over http protocol through the compose stack network (i.e. http://radarr:7878 and http://sonarr:8989)

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This might be fixed by #1084 (v2.1.0)
We discovered an issue where multiple requests were being made for blacklist modal for every series/movies card that makes the browser give up on requesting. So multiple refreshes as you mentioned should add up these requests thus server becoming overloaded and what you discovered happening.

Please feel free to re-open after testing on 2.1.0.
