### ISSUE TITLE
Jellyseerr won't start after latest update

### ISSUE THREAD

**Issue by jordan-dalby** [Fallenbagel/jellyseerr#1095]
### Description

I updated both Jellyfin and Jellyseerr today to their latest versions and Jellyseerr will no longer start. Please see attached photo for logging.

### Version

v2.1.0

### Steps to Reproduce

1. Start with a previous version of Jellyseerr
2. Update to the latest version

### Screenshots

![image](https://github.com/user-attachments/assets/162755db-0155-4d3a-962b-e6db0f144a51)

### Logs

```shell
2024-11-13T10:22:30.510Z [info]: Commit Tag: $GIT_SHA 
2024-11-13T10:22:30.984Z [info]: Starting Overseerr version 2.1.0 
2024-11-13T10:22:31.512Z [error][Jellyfin API]: Something went wrong while creating an API key from the Jellyfin server {"error":"Unauthorized"}
2024-11-13T10:22:30.510Z [info]: Commit Tag: $GIT_SHA 
2024-11-13T10:22:30.984Z [info]: Starting Overseerr version 2.1.0 
2024-11-13T10:22:31.512Z [error][Jellyfin API]: Something went wrong while creating an API key from the Jellyfin server {"error":"Unauthorized"}
... repeats hundreds of times
```

### Platform

desktop

### Device

Any

### Operating System

Unraid 7.0.0-beta.2

### Browser

Edge, but n/a

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
For anyone reading this issue having the same issue, you can read the log error it tells you what to do. In this case, have to add `apiKey` key to settings.json's jellyfin block and you can obtain the apikey from jellyfin dashboard

**Comment by grannymaster** [comment]
For everyone as confused as me, this is how I fixed this issue for me.

1.	Go to your jellyFIN, click on "person" icon in top right corner, then "Dashboard" and then "API Keys" on the bottom left.
2.	Here create a new API key, name it whatever.
3.	Bring down your jellySEER container.
4.	Go to "/config/" folder and open/edit "settings.json".
5.	You should have a configuration block like this
```
  "jellyfin": {
  "name": "",
  "externalHostname": "",
  "jellyfinForgotPasswordUrl": "",
  "libraries": [
   {
    "id": "1231231231231231212312",
    "name": "Movies",
    "enabled": true,
    "type": "movie"
   },
   {
    "id": "1231231231231231212312",
    "name": "Shows",
    "enabled": true,
    "type": "show"
   }
  ],
  "serverId": "1231231231231231212312",
  "ip": "192.168.50.71",
  "port": "8096",
  "apiKey": "supersecretapikey123",
  "useSsl": false,
  "urlBase": ""
 },
```
6. You are probably missing the    `"apiKey": "supersecretapikey123",` row. This is where I added the API key I created in jellyFIN.
7. After I added the  `"apiKey": "supersecretapikey123",` , jellyFIN came up without a problem.

**Comment by gauthier-th** [comment]
@Fallenbagel we should add this to the docs

**Comment by Fallenbagel** [comment]
> @Fallenbagel we should add this to the docs

Yeah and we can link the docs url in the error message

**Comment by balla2185** [comment]
im using portainer and cant figure out how to access that if I look under inspect  text under "Config":  { there is no 'jellyfin'section

**Comment by Fallenbagel** [comment]
> im using portainer and cant figure out how to access that if I look under inspect  text under "Config":  { there is no 'jellyfin'section

It's whereever you mounted your config folder. If you didn't mount your config folder, that's not a proper setup.

**Comment by balla2185** [comment]
mine looked a bit different but literally just adding that section under serverid worked

**Comment by grannymaster** [comment]
I don't think you can do this change with Portainer, or at least I don't know how to.

My docker-compose looks like this:

```
version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Narnia
       ports:
            - 5055:5055
       volumes:
            - ./config:/app/config
       restart: unless-stopped
```

So for me the `config` folder is located in the same location as `docker-compose.yml` i.e. root.

![image](https://github.com/user-attachments/assets/ce8d4de4-0082-4556-8553-96dd18a3d74d)

**Comment by balla2185** [comment]
Yep I just went to the jellyseer folder in root and added it under the
server

**Comment by Fallenbagel** [comment]
> I don't think you can do this change with Portainer, or at least I don't know how to.
> 
You can. Even if you use docker volumes you can just mount that volume into another container like running debian image or alpine image and then just access the shell and delete settings.json or edit it.

**Comment by grannymaster** [comment]
Ah I see, thanks for the tip!
