### ISSUE TITLE
Avatars not displaying when hostname local HTTP and External URL HTTPS

### ISSUE THREAD

**Issue by BonzTM** [Fallenbagel/jellyseerr#110]
### Description

My Jellyseerr is set up as https://jellyseerr.url via reverseproxy.  My Jellyfin instance setup in Jellyseerr initially with http://localP:port, but I have an http://fully.qualified.domainname set as my External URL.

Users in Jellyfin who have an Avatar are missing.  The URL is being rewritten to https due to the mixed content, but the hostname is still the internal URL and does not reflect the External URL when set.

### Version

v1.1.0

### Steps to Reproduce

1. Set up jellyseer with https scheme hostname
2. Jellyfin configuration in Jellyseerr set up as http://localip:port
3. Set up External URL for Jellyfin as https://externalurl
4. User avatars are missing
5. User avatars are using hostname, not externalHostname
6. User avatars are missing because of the HTTPS/HTTP mixed content being rewritten to HTTPS://localip:httpport

### Screenshots

![image](https://user-images.githubusercontent.com/514931/170353173-19deb8ee-501a-42a8-ae38-d8f6d0636b66.png)

![image](https://user-images.githubusercontent.com/514931/170353384-ade5758e-a6b9-4f40-959c-3cd11331c534.png)

### Platform

desktop

### Device

Desktop

### Operating System

Windows 11, macOS

### Browser

Chrome, Edge, Firefox

### Additional Context

https://github.com/Fallenbagel/jellyseerr/blob/4f972be8584e48f544268aef9d1d05769ba2e38e/server/routes/user/index.ts#L508
https://github.com/Fallenbagel/jellyseerr/blob/4f972be8584e48f544268aef9d1d05769ba2e38e/server/routes/settings/index.ts#L324
https://github.com/Fallenbagel/jellyseerr/blob/4f972be8584e48f544268aef9d1d05769ba2e38e/server/routes/auth.ts#L247

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This has been fixed in the new commit to develop branch, you can now set the external hostname in settings and any user that signs in for first time now will use the external hostname and any existing users can be re-imported to update their avatar url.
