### ISSUE TITLE
Emby avatars missing after 2.1.0 update

### ISSUE THREAD

**Issue by MrSmoke** [Fallenbagel/jellyseerr#1101]
### Description

After upgrading to `2.1.0`, users added via emby users no longer have avatars. Initially they were showing as broken images, but after logging into those user accounts they now show the default avatar image. The admin account (user 1) avatar still works however.

I do not have `Enable Image Caching` enabled.

### Version

2.1.0

### Steps to Reproduce

Either: 
1. Visit `/users` and note no avatars
2. Visit `/requests` and note no avatars

### Screenshots

![image](https://github.com/user-attachments/assets/4319de93-de01-482d-b74d-bfb5d228de28)

### Platform

desktop

### Device

desktop

### Operating System

win10

### Browser

firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is not a bug. It's just a missing implementation as the api endpoint we use to get avatars from jellyfin does not exist in emby.

We will be implementing it for next version
