### ISSUE TITLE
User group and LDAP support

### ISSUE THREAD

**Issue by ThomasRochette** [Fallenbagel/jellyseerr#1107]
### Description

Hello it would be nice to be able to have groups of user so we can manage permission at the group level instead of user level. It would bé a real plus if user could be affected in different groups with LDAP. For instance WE could have 3 groups of user : requester (only able to request media) , validator (also able to validate requests) and admin. 

### Desired Behavior

I use LDAP for my jellyfin users. I have 5 different type of user. First user type just have a jellyfin Access, they have a watcher group on their LDAP profile, i don't want those too be imported in jellyseerr. Second type of user also have Access to jellyseerr but only to request new media, they have a requester LDAP group on their LDAP profile. Third type have a validator group on their LDAP profile, they can request and validate pending requests. Fourth type are jellyfin admin and the last type IS just thé local admin account. 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Can't this already be achieved using the permissions.
First group of users you give request permisiom
Second group you give manage requests permission
And the last group ofcourse all the permissions.
