### ISSUE TITLE
Specials aren't visible or requestable

### ISSUE THREAD

**Issue by ToasterUwU** [Fallenbagel/jellyseerr#1120]
### Description

I just ran into an issue with Dr Stone having a special that is not an optional side story, but an actual important part of the story. So when I was like "Ohh ok, guess I'm gonna watch that special now" i realized I don't have it, and that's because jellyseerr doesn't show or request specials, so sonarr was aware of its existence, but didn't think it was worth monitoring.

I checked if sonarr maybe ignores specials by default and if that's changeable by setting, but I couldn't find anything along the lines of that, so I'm pretty sure it's an issue coming from the jellyseerr side of things. 

### Desired Behavior

I want "Specials" to show up next to the seasons, and let it be requestable.
I understand that most of the time specials aren't a coherent extra season, so maybe it makes sense to make individual specials requestable, but that's something for you to decide, I just wanna avoid having this issue again in the future. 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This has already been added into develop and should be ready for next version

**Comment by hacshacdgacs** [comment]
> This has already been added into develop and should be ready for next version

I think this may be the change that's causing my issue. Is there any way to have it so that Specials is a separate setting from include all seasons? I have Allow Partial Series Requests off because I like my server to have every season available but I don't really consider 'specials' to be a part of that.
