### ISSUE TITLE
unable to wiew request from the user

### ISSUE THREAD

**Issue by xbon60** [Fallenbagel/jellyseerr#1121]
### Description

after the upgrade of jellyseer on the 2.1.0, i can't wiew the request on the main page and the request tab. 

### Version

2.1.0

### Steps to Reproduce

1. Upgrade to the 2.1.0

### Screenshots

![image](https://github.com/user-attachments/assets/136ee384-a6bb-4dba-9005-9fedce1cee81)
![image](https://github.com/user-attachments/assets/f55f85f0-8c21-471c-b611-32e8ad583ce9)

### Platform

desktop

### Device

Assembled computer

### Operating System

Windows 11 24h2

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
So you need to make sure you services > radarr/sonarr is setup and reachable correctly. This issue occurs because of the newly added delete from *arr button not taking care to conditionally show. So when *arr has a problem, requests don't load.

**Comment by xbon60** [comment]
thanks, i have one *arr app not reachable.

**Comment by RecoX** [comment]
It could be clearer if the error could be handled and show a text saying: There is an error with the arr suite, please check

**Comment by Fallenbagel** [comment]
> It could be clearer if the error could be handled and show a text saying: There is an error with the arr suite, please check

This is already fixed in develop. There is no error to show.
