### ISSUE TITLE
Application Title has no effect

### ISSUE THREAD

**Issue by andrew-manger** [Fallenbagel/jellyseerr#1123]
### Description

After updating the application title, saving changes, and restarting the container, the Application title still shows “Jellyseerr” when logging in and browsing. 

### Version

2.1.0

### Steps to Reproduce

1. Note the title in the top left corner of the window when browsing on desktop
2. Update the application title and save changes in settings
3. Restart docker container
4. Check the title again

### Platform

desktop

### Device

MacBook Air

### Operating System

15.1

### Browser

Arc Browser

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Not a bug. Application title is for browser tab name, and the name used in notifications and such. It does not change our logo
