### ISSUE TITLE
Not released movies fail to request

### ISSUE THREAD

**Issue by lughino** [Fallenbagel/jellyseerr#1124]
### Description

I have Jellyseerr configured successfully with Radarr and Sonarr. All requests of movies and TV series work properly, except the movies that are not yet released. When I request them I get status failed.

### Version

2.1.0

### Steps to Reproduce

- Search for a movie like `avatar fire and ash`
- request the movie (no matter if normal or 4k request)
- refresh the page and you'll see that the request failed

Weird enough, I added the movie directly on radarr, but jellyseerr still don't see the movie as already present on the catalog.
I also checked the tmdb id and both jellyseerr and radarr point to the same id `83533`.

### Platform

desktop

### Device

mac

### Operating System

mac os sonoma

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This sounds like a configuration issue and I would recommend hopping onto discord.

I just tried to request it and worked
![Screenshot_20241126_105740_Chrome Dev.jpg](https://github.com/user-attachments/assets/5acf1124-1f28-4f41-a766-4f6126e3a55f)

**Comment by Fallenbagel** [comment]
Hop onto discord and open a support thread there. Then share your logs after trying to request (make sure the movie doesn't exist in radarr so we can get a fresh look at it). Share both radarr and jellyseerr logs.
