### ISSUE TITLE
Media availability job does not clean series

### ISSUE THREAD

**Issue by NicolaSmaniotto** [Fallenbagel/jellyseerr#1126]
### Description

When scanning Jellyfin for available media, Jellyseerr correctly detects removed movies, but not seasons. They can no longer be requested because they "already" are.

### Version

2.1.0 (docker `:latest`)

### Steps to Reproduce

1. Request a season
1. Wait for the season be added to Jellyfin. After a sync Jellyseerr shows it as "Available"
1. Delete the season from the disk. After another sync Jellyseerr still shows it as "Requested", so it can't be requested again. The "Play on Jellyfin" button is visible, but does not link to any content

### Platform

desktop

### Device

Any

### Operating System

Any

### Browser

Any

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is a misconfiguration. Please hop onto discord for support issues.
