### ISSUE TITLE
Jellyseerr not using "External URL" for avatar images

### ISSUE THREAD

**Issue by Spiritreader** [Fallenbagel/jellyseerr#113]
### Description

When fetching image data, jellyseerr attempts to retrieve the user avatars from jellyfin via the internal URL, instead of the external one that is reachable by teh clients

### Version

1.1.0

### Steps to Reproduce

Use an internal url for jellyfin (for example if jellyfin is at http://localhost:10002), then attempt to view avatars in a different machine

http://localhost:10002/Users/XXX/Images/Primary/?tag=XXX&quality=90
The url above is a local address and not available when using the External URL that can be set

### Screenshots

![image](https://user-images.githubusercontent.com/18438899/170559905-c2094934-422b-4bb1-9673-ebcca0e79645.png)
![image](https://user-images.githubusercontent.com/18438899/170559934-77980eac-3109-45d7-addc-80aa1d88e445.png)

### Platform

desktop

### Device

Desktop

### Operating System

Win10 21H1

### Browser

Chromium-based

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
#111

**Comment by Fallenbagel** [comment]
This has been fixed in the new commit to develop branch (the docker image will be updated in a while), you can now set the external hostname in settings and any user that signs in for first time now will use the external hostname and any existing users can be re-imported to update their avatar url.

**Comment by zeroquinc** [comment]
> This has been fixed in the new commit to develop branch (the docker image will be updated in a while), you can now set the external hostname in settings and any user that signs in for first time now will use the external hostname and any existing users can be re-imported to update their avatar url.

How to reimport the Owner tho?
![jaySj6iyjx](https://user-images.githubusercontent.com/39315068/180762728-33643bc3-0827-47d5-888d-a115a1dfd47a.png)
