### ISSUE TITLE
Anime Series Type set to Standard but is sending Anime

### ISSUE THREAD

**Issue by kenjibailly** [Fallenbagel/jellyseerr#1131]
### Description

I have Anime Series Type set to standard for sonarr, but when I request an anime show the Series Type is set to Anime / Absolute

### Version

2.1.0

### Steps to Reproduce

1. Go to Jellyseerr settings
2. Go to Services
3. Click Sonarr
4. Set Anime Series Type to Standard
5. Choose an anime show and request
6. Go to Sonarr
7. Go to the anime show that's just been requested
8. Click on Edit
9. Series Type is set to Anime / Absolute instead of Standard

### Platform

desktop

### Device

Windows PC

### Operating System

Ubuntu Docker / Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Go to services>sonarr and press test. Set it to anime. Save. Then Set it back to standard. Should work then from what I've heard

**Comment by kenjibailly** [comment]
> Go to services>sonarr and press test. Set it to anime. Save. Then Set it back to standard. Should work then from what I've heard
> 
> Source: https://discord.com/channels/952656177924300932/1300731099764228156

I tried it with one show and it didn't work.
I tried it with another show and that seemed to work.
I guess I'll have to do more testing to make sure it works from now on.

Thanks for pointing that out, I'll close this issue for now. If it happens again I'll comment here again.
