### ISSUE TITLE
Pushbullet shows up for every user, even when the agent is deactived

### ISSUE THREAD

**Issue by lukenukemmp3** [Fallenbagel/jellyseerr#1136]
### Description

Pushbullet is now visible to every user, it doesn't matter if it is activated or not.

### Version

2.1.0

### Steps to Reproduce

1. Go to User
2. Click Edit on any user
3. See Pushbullet as an option even when deactivated

### Screenshots

global setting
<img width="1104" alt="global" src="https://github.com/user-attachments/assets/1a2a1447-5c52-4ea0-b20e-5d0229b6a195">

user setting
<img width="1003" alt="user" src="https://github.com/user-attachments/assets/5ae53984-ff2b-4000-8797-3f72c9b4bc32">

### Platform

desktop

### Device

any

### Operating System

any

### Browser

any

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Not a bug. This is expected default behaviour. Pushbullet and Pushover would always be visible.

**Comment by lukenukemmp3** [comment]
Thank you very much for the ultra fast answer!
I am very thankful for the great work of yours!
