### ISSUE TITLE
request 3D Version of movie.

### ISSUE THREAD

**Issue by binarygeek119** [Fallenbagel/jellyseerr#1158]
### Description

i would like movies to have a option to request 3D movies.
i have setup a radarr that is optimize for 3d only.
right now i have it setup as a 4k option in jellyseerr. but a option for 3D would be nice.
a long term option would be a way to only request 3D movies that have been released in 3D. but im unware of a database for that other then this Wikipedia pages.
https://en.wikipedia.org/wiki/List_of_3D_films_(2005%E2%80%93present)
https://en.wikipedia.org/wiki/List_of_3D_films_(1914%E2%80%932004)
https://en.wikipedia.org/wiki/Category:American_3D_films

### Desired Behavior

we could pull that data from the Wikipedia and when new ones are added just ask for a update to the list.
like
3D Movie List Update Request.
then link to the movie on tmdb and any other info. then a dev would need to add it to a list that jellyseerr pulls it from and applys to it the movie page.
like if i request iron man 3 it would have a option to do Request or 4k Request or 3D Request
but if i ask for iron man 1 or 2 it just be Request or 4k Request

### Additional Context

sample of how it would look
![image](https://github.com/user-attachments/assets/e2d0d5b7-0ba2-4087-9756-f886c7418eec)

![image](https://github.com/user-attachments/assets/e48c1a6b-47e8-4f9d-8ba2-73fb1868f225)

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
I don't want to be rude, but I doubt very much that this will ever be implemented. 3d movies are a niche feature, which are watched very little.
Having another type of setup only for 3d movies requires a huge refactor of the application, and we won't do it for just a tiny amount of users.

**Comment by staticdev** [comment]
@gauthier-th this is not at all a bad idea, new projectors in general support 3d movies. There are 3d movies as old as 1952 (https://www.imdb.com/list/ls079585337/?sort=release_date%2Casc). It would be great to be able to select you want the 3d version to be downloaded somehow, not necessarily as proposed above.

**Comment by gauthier-th** [comment]
You can still configure you quality profiles in Radarr to do so
