### ISSUE TITLE
Add an option to proxy images via Jellyseerr itself

### ISSUE THREAD

**Issue by gallyamb** [Fallenbagel/jellyseerr#1160]
### Description

First of all, worth to mention that there is already "Cache images" option in configuration, that is a workaround for my issue. Thank you for introducing such option!

### Problem

In countries with applied restriction to access the IMDB it's impossible to load images directly from IMDB. Therefore I have to enable image caching, because my installation is deployed through Docker and uses VPN to load images

But as mentioned in the description of the Cache images option, it requires an extra disk space

### Desired Behavior

It'll be great to have an option to proxy image loading through Jellyseerr server, so images are loaded via VPN within Docker (or whatever is configured)

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
**Image caching** is for this process. Its not a workaround as it was developed to achieve exactly this 😅
Image caching should clean the expired images using the job and cache wouldnt get that relatively big from my experience. This feature was specifically implemented for this exact same issue.

Http proxy settings also exist where you can just pass in your vpn as an http proxy to proxy the tmdb connection

**we don't support imdb**

**Comment by gallyamb** [comment]
> we don't support imdb

My fault. Just started to use Jellyseerr/Jellyfin/Radarr and a got little bit confused

> Image caching is for this process. Its not a workaround as it was developed to achieve exactly this 😅

But why we need a cache, if we only need to proxy requests to the images? Or there are any plans to allow some configuration over cache/only proxy?

> Http proxy settings also exist

I didn't find any documentation about this option and decided to leave it alone so that I wouldn't accidentally broke something 😅

If I understand you right, I can configure a proxy (could you suggest one?) and all image URLs will contain that proxy's host instead of tmdb API?

**Comment by gauthier-th** [comment]
> But why we need a cache, if we only need to proxy requests to the images? Or there are any plans to allow some configuration over cache/only proxy?

Cache is cache. Its goal is not to proxy things, but to cache images on the server for better efficiency in some cases. "Proxy" is just a side effect, because it's the server that retrieves the images and not the client.

> If I understand you right, I can configure a proxy (could you suggest one?) and all image URLs will contain that proxy's host instead of tmdb API?

HTTP Proxy will have a behavior similar to your VPN configuration. With HTTP proxy, your requests will pass through that proxy, a bit like a VPN (but that only works for HTTP requests). A popular HTTP proxy is Squid.

> But as mentioned in the description of the Cache images option, it requires an extra disk space

The amount of storage this will take is not that huge. The image cache is cleaned everyday. Keep your cache enabled so users in your country can see the images.

**Comment by gallyamb** [comment]
> Cache is cache. Its goal is not to proxy things

When a wrote "why we need a cache", I mean that within the context of my original request we discussing about a proxying images through Jellyseerr but not a caching

> HTTP Proxy will have a behavior similar to your VPN configuration. With HTTP proxy, your requests will pass through that proxy, a bit like a VPN (but that only works for HTTP requests)

I understand how forward proxies works. My question was about the mechanism implemented within Jellyseerr. I tried to start Squid and configure Jellyseerr to use it as an HTTP Proxy, but this way Jellyseerr still use `image.tmdb.org` host. I don't get how proxy settings **within** Jellyseerr could help me with proxying images. Seems like Jellyseerr internally uses that proxy to make all outgoing requests, but images continue to be served directly from tmdb. And to use my Squid I need to configure end users' browser/OS

> The amount of storage this will take is not that huge. The image cache is cleaned everyday. Keep your cache enabled so users in your country can see the images

Well, this option is enough for me. You guys also clarified to me that the disk space is not a real problem. So I think it's time to close the issue. Thank y'all for your replies!

**Comment by gauthier-th** [comment]
Let me clarify things if someone reads this later:

> I tried to start Squid and configure Jellyseerr to use it as an HTTP Proxy, but this way Jellyseerr still use image.tmdb.org host.

This is because of a configuration issue on your side. The goal of the HTTP Proxy is to proxy **all** requests, and the requests for images are included.

> Seems like Jellyseerr internally uses that proxy to make all outgoing requests, but images continue to be served directly from tmdb.

No. Images are served from TMDB when cache is disabled. When cache is enabled, images are served from the Jellyseerr server, which will use the configured proxy settings.

> And to use my Squid I need to configure end users' browser/OS

You don't if you configure Jellyseerr to use the HTTP Proxy from Squid, and have Image Caching enabled.

**Comment by Fallenbagel** [comment]
> And to use my Squid I need to configure end users' browser/OS

Thats not how Http proxy works. It's works to proxy all requests that jellyseerr make to tmdb to go through the proxy. This means when the server makes a request to the tmdb api. It does not concern the end users.

**Comment by gallyamb** [comment]
> configure Jellyseerr to use the HTTP Proxy from Squid, **and** have Image Caching enabled

Exactly! But I **do not** want (does not want previously 😄) to enable caching. I just wanted to proxy images through Jellyseerr itself, so all requests are made within Jellyseerr's network within docker (which is routed through VPN automatically)

In such configuration there is no need for a proxy. And enabling the proxy without caching does not solve the task

> proxy all requests that jellyseerr make to tmdb

Only those requests, that are made by Jellyseerr server, but not that are made at a client side (browser). Jellyseerr makes requests to the TMDB only when caching is enabled

So proxy settings are useless for images, when caching is disabled

----

To be clear, my original intent was to proxy images through Jellyseerr server, but not to cache them. Jellyseerr server already configured in a way to use VPN connection. Therefore, no proxy is needed

Something like:
```
Settings
  - Proxy images through Jellyseerr (enabled)
  - Cache images (disabled)
```

But for now those two options are merged into one `Cache images` option

**Comment by gallyamb** [comment]
> Something like

`Cache images` options, ofc, disabled, if `Proxy images` is unchecked

**Comment by Fallenbagel** [comment]
> To be clear, my original intent was to proxy images through Jellyseerr server, but not to cache them. Jellyseerr server already configured in a way to use VPN connection. Therefore, no proxy is needed\n\nSomething like:\n\nSettings\n  - Proxy images through Jellyseerr (checked)\n  - Cache images (unchecked)\nBut for now those two options are merged into one Cache images option

Ah I see

**Comment by gallyamb** [comment]
> But when it's just proxying images without cachings, it's gonna be 5× api hits for the same pic by the same server

Good point! From a TMDB perspective, I think there isn't much difference (either way, it will have to serve images 5 times), but perhaps they have a rate limiter for the same IP address and this could affect Jellyseer users

Anyway, I think caching is the desired solution in my case

**Comment by Fallenbagel** [comment]
> Good point! From a TMDB perspective, I think there isn't much difference (either way, it will have to serve images 5 times), but perhaps they have a rate limiter for the same IP address and this could affect Jellyseer users
> 

Yes. You will get rate limited by ip if you hammer the tmdb api too much. Proxying without caching would do that as it'd be same server ip hitting 5 times instead of 5 different 

> Anyway, I think caching is the desired solution in my case

Glad it works for you though 😊
