### ISSUE TITLE
API documentation correction: should be jellyfinUserIds instead of jellyfinIds

### ISSUE THREAD

**Issue by starlingfire** [Fallenbagel/jellyseerr#1161]
### Description

In the API documentation, importing a user from jellyfin using the `/user/import-from-jellyfin` endpoint notes that it requires the parameter named `jellyfinIds` when in reality that parameter's name should be `jellyfinUserIds`. 

I only found the one instance of it used in the `overseerr-api.yaml` file:
https://github.com/Fallenbagel/jellyseerr/blob/66a5ab41ab646501f72a658782e8a89f9faf939f/overseerr-api.yml#L3876

### Version

2.1.0

### Steps to Reproduce

1. Try to run the command using `jellyfinIds`:
```
curl -X POST http://localhost:5055/api/v1/user/import-from-jellyfin \
  -H "X-Api-Key:API_KEY_HERE" \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"jellyfinIds":["USER_ID_FROM_JELLYFIN"]}'`
```
It returns the error: 
`{"message":"body.jellyfinUserIds is not iterable"}`
2. Try to run it using `jellyfinUserIds`:
```
curl -X POST http://localhost:5055/api/v1/user/import-from-jellyfin \
  -H "X-Api-Key:API_KEY_HERE" \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"jellyfinUserIds":["USER_ID_FROM_JELLYFIN"]}'`
```
It returns the imported user.

### Screenshots

![image](https://github.com/user-attachments/assets/1abfaa8c-5e0a-4505-8767-ebe430646b8c)

### Platform

desktop

### Database

None

### Device

PC

### Operating System

Solus

### Browser

Firefox

### Additional Context

It's just the API documentation that is incorrect.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
This is not the place to ask. Please hop onto Discord for support.
