### ISSUE TITLE
Able to log in to jellyseerr with jellyfin user even after jellyfin user is deleted

### ISSUE THREAD

**Issue by fshrr** [Fallenbagel/jellyseerr#1162]
### Description

I am new to jellyseerr, so I am not sure if this is expected behavior.

When a user is removed from jellyfin, the persisting "jellyfin user" can still log into jellyseerr by using "Use Your Jellyseerr Account" during login. While the user is listed as "jellyfin user" in the user dashboard of jellyseerr, it is allowing login as a local user.

### Version

2.1.0

### Steps to Reproduce

1. Create a new user in jellyfin.
2. Log into jellyseerr using the new user.
3. Log out of jellyseerr.
4. Delete the user from jellyfin.
5. Log into jellyseerr using "Use Your Jellyseerr Account" during login.

### Platform

desktop

### Database

None

### Device

Macbook pro

### Operating System

Mac OS 15

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
This is not a bug. You can disable this by unchecking "Enable New Jellyfin Sign-In" in the Users settings.

**Comment by fshrr** [comment]
Wouldn’t unchecking “Enable New Jellyfin Sign-In” only stop new users from being automatically created in Jellyseerr using Jellyfin credentials?

In my case, I noticed that after deleting a user from Jellyfin, they can still log in to Jellyseerr using “Use Your Jellyseerr Account”, even though their user type shows as “Jellyfin User” in the dashboard.

Does this setting also change the user type from “Jellyfin User” to “Local User” when the user is no longer in Jellyfin? If so, that would explain the behavior. However, in the UI, the user type still says “Jellyfin User”, which seems inconsistent.

**Comment by gauthier-th** [comment]
Oh, I misunderstood that, sorry.
That's weird, let me check if I can reproduce that.

**Comment by Fallenbagel** [comment]
It's not weird. That's expected. Deleted jellyfin users will not be synced back to jellyseerr. Deleted jellyfin users will not be able to use jellyfin login form to authenticate. They can use local jellyseerr login form because that user is also a local user.

One thing to understand is, every user is both a media server user and a local user.

If you don't want local logins, just disable local logins. If you want local logins but the user to delete it, just delete the user on jellyseerr or

**Comment by fshrr** [comment]
@Fallenbagel that clears things up. Thanks!
