### ISSUE TITLE
Anonymize requests

### ISSUE THREAD

**Issue by smark91** [Fallenbagel/jellyseerr#1170]
### Description

It will be useful to be able to anonymize the requested user.
Some users complain about their privacy because everyone can see who requested a content

### Desired Behavior

Having an option in the settings to remove requested in the UI and some API response to grant more privacy to users
The option may avoid pass the name or to avoid breaking change just send generated random names

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
> Some users complain about their privacy because everyone can see who requested a content

This is not true.
You can configure the "View Request" permissions of the users.

**Comment by smark91** [comment]
Sorry you are right about normal user but users complain the admin can see the requester.
I don't think that can be suppressed.

**Comment by smark91** [comment]
Another point can be that anonymizing request is not like giving permission.
I may want user to be able to see requests and issues sent from other user but make this anonymous

**Comment by gauthier-th** [comment]
I'm sorry, but this will not be implemented.
An admin user is well, an admin. He can view, edit, create and delete everything on the app, as he as full control over it. This includes viewing who requested some content.
If you don't want to see it, just create a regular user for yourself.

**Comment by smark91** [comment]
> Another point can be that anonymizing request is not like giving permission. I may want user to be able to see requests and issues sent from other user but make this anonymous

What about this
