### ISSUE TITLE
User Based Root Folder Assignment

### ISSUE THREAD

**Issue by BostonBella** [Fallenbagel/jellyseerr#1186]
### Description

Currently request from all users default to the same folder but there is the ability to manually choose a different folder when making the request.

### Desired Behavior

A setting to choose either the default show/anime folder for each user or a different root folder.
 
<img width="793" alt="Screenshot 2024-12-27 at 2 09 02 PM" src="https://github.com/user-attachments/assets/7b5b47cb-e3f8-463c-a1b9-86b041d05d7c" />

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Isn't this a duplicate of #171

**Comment by BostonBella** [comment]
You're right, I did a search to make sure i wasn't duplicating a request but I didn't search well enough, sorry about that.
