### ISSUE TITLE
Seasons that aren't available are marked as partially available when synced with Jellyfin

### ISSUE THREAD

**Issue by CarnageDevs** [Fallenbagel/jellyseerr#119]
### Description

On every show I have with multiple seasons with only some downloaded, Jellyseerr incorrectly marks the missing seasons as "partially available" which prevents anyone from requesting them. I have noticed this happens only when doing a library scan with Jellyfin.

![image](https://user-images.githubusercontent.com/17109829/170871223-2a47cf39-37fc-45d6-89f4-767e1a5256e3.png)

Without doing a library scan with Jellyfin and instead first setting up Sonarr with the "Enable scan" feature and running a Sonarr scan in Jobs & Cache, it correctly detects the undownloaded seasons as "Not requested". This can also be replicated by clearing data for the particular show and running a Sonarr scan - though it once again regresses to "partially available" once the Jellyfin library scan runs.

![image](https://user-images.githubusercontent.com/17109829/170870806-b9570a92-de02-4c42-ab83-501218fbc757.png)

### Version

1.10

### Steps to Reproduce

1. Have one or only some seasons of a show available and downloaded
2. Run Jellyfin library scan

### Screenshots

How the show looks like in Sonarr (as you can see, only one season is downloaded):

![image](https://user-images.githubusercontent.com/17109829/170871090-4094a7d7-659c-4991-8799-940a38457475.png)

And in Jellyfin, where you can see only the same one season is available:

![image](https://user-images.githubusercontent.com/17109829/170871142-d86d56dd-ff81-40d6-a10f-6cb9131404bf.png)

### Platform

desktop

### Device

PC

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Hm. That is odd. Does that happen when you have like let's say season 4 without 1-3?
Because I also have several series w half downloaded but that hasn't happened to me 
![Screenshot_20220602-033402_nzb360.jpg](https://user-images.githubusercontent.com/98979876/171512857-beda9606-9c06-4e22-86f2-675aa664c148.jpg)

(Trying to replicate this error to figure it out)

**Comment by Fallenbagel** [comment]
I just tried the other way too. Having season 3 without season 1-2 for example and i could not replicate the error.

![Screenshot_20220602-083550_nzb360.jpg](https://user-images.githubusercontent.com/98979876/171548056-e2900abf-8a7d-4629-95c3-d2461ec4683c.jpg)
![Screenshot_20220602-083537_nzb360.jpg](https://user-images.githubusercontent.com/98979876/171548069-e1231603-7223-4ad1-93d3-617b6c668872.jpg)

Could you try recreating jellyseerr and checking if the same thing happens? Or try the `develop` tag?

**Comment by Fallenbagel** [comment]
> My feeling is that it is caused by jellyfin keeping some metadata about deleted seasons/episodes, however the jellyfin web ui can correctly determine so and wont show anything in the UI. On the other hand, jellyseerr does not handle this case and thus shows partially available / available status.

This what I have been thinking as well. There might be metadata leftover of some deleted seasons or episodes or like metadata there w no media. Jellyfin won't pick it up but jellyseerr would as it would look for the metadata instead of the video file

**Comment by sambartik** [comment]
Shouldn't be this marked as bug then? Jellyseer needs to do some validation or something else, because even 3rd party jellyfin clients don't display the series which jellyseerr sees as (partially) available - suggesting that this can be determined by the Jellyfin API.

**Comment by Fallenbagel** [comment]
> Yes I have the same issued and I was wondering what it is about. Is there any solution to this?

One temporary solution I could think of is, deleting any leftover metadata from jellyfin and then removing the data of that show from jellyseerr and rescanning. That was jellyseerr will only see the season that is available and everything else will be seen as not requested
