### ISSUE TITLE
[Feature Request] Add Email field to user profiles

### ISSUE THREAD

**Issue by nerdalertdk** [Fallenbagel/jellyseerr#122]
### Description

Hi

Since there is no email field in jellyfin, would it be possible to add it to jellyfin users in jellyseerr ?
Can't juse the Email notification without :/

### Desired Behavior

Email notification working with jellyfin users

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The email field was removed for `v1.1.0` due to popular request to remove that as being required, however, we have taken into consideration that a lot of users also do use SMTP server for notification so we have been working on an alternative method

**Comment by Fallenbagel** [comment]
Hi. So there is a workaround to get email notifications working in the current version until an alternative method is introduced. 

### Pre-requisites (**_Required_**)
- Make sure your admin account's email was not replaced (as in do not use the import jellyfin button). If it was, you will have to recreate jellyseerr.
- Also this workaround requires you to know the password (atleast temporarily) of the jellyfin user

### Steps to follow
1. Delete the users that you want the email notifications to be sent to.
2. Go to `http://localhost:5055/api-docs/#/auth/post_auth_jellyfin` (sign in using jellyfin username and password)
3. Press try now
4. in the request body, add the following (remember to replace username with the user's username and password and email too.)
```json
{
  "username": "jellyfinusername",
  "password": "jellyfinpassword",
  "email": "emailaddressoftheuser"
}
```
5. Press execute and it should log in the user with their email (now you can set up SMTP server how you normally would)
