### ISSUE TITLE
[Feature Request] Validate whether the user is a local network user and only allow log in locally

### ISSUE THREAD

**Issue by Kreach37** [Fallenbagel/jellyseerr#123]
### Description

I can login with an user that is only for local use only using external URL.

Jellyseerr was set up using jellyfin local ip.

"Allow remote connections to this server" is uncheck in jellyfin config for the user.

I'm running the develop branch on docker and have set the external URL to fix profile picture and play on jellyfin button.

This is a security concern for my use case since that user doesn't have a password.

What I would like:
1. ability to use that user locally when accessing jellyseerr from my local ip.
2. not being able to access jellyseerr from external URL with that user.

Possible quick fix:
Use external URL for the login process, that would resolve my security concern but not allow local user when on local network.

I will add a password to the user for now!

### Version

5298e5fd901f4481b1095c90b87530a380db7451

### Steps to Reproduce

1. setup a local user in jellyfin with or without a password
2. login with the local user on jellyseerr using external URL

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I'm not sure I understand but I'm guessing what you want is when the user with no password tries to log in, not allow him to be logged in?

You could do that by going into jellyseerr settings and turning off `enable new jellyfin login`. That way that user won't be able to log in, and you can have everyone else imported using the import user button

**Comment by Kreach37** [comment]
Thanks for the suggestion! This should work.


[jellyfin settings in the dashboard](https://imgur.com/a/W3HxemV)

My problem was that using an external Url lets say jellyseerr.domain.com, I should not be able to login with my username "NoPassword", since jellyfin (jellyfin.domain.com) would not allow it, because that user is local only.

**Comment by Fallenbagel** [comment]
Ohh I think I get it. Currently it does not validate whether the user is local or remote. Have to try and see how to implement that through api

Let me change the tag to feature request
