### ISSUE TITLE
[Feature Request] Season start and end indication

### ISSUE THREAD

**Issue by nomandera** [Fallenbagel/jellyseerr#131]
### Description

When placing or reviewing a season request there is no apparent method to determine if the season is in a pending, airing or ended state.

If the desire is to only act when a season is complete i.e. binge watch, without some indication it has ended you need to leave jellyseerr each time to check online data sources (not ideal).

### Desired Behavior

Some indication of airing status of a season at time of request and post request e.g.

- start and end dates
- days until season premier and season finale

Ideally some way to filter requests to those that are season/series complete.

### Additional Context

This shows the current difference between onboarding a season in OMBI versus jellyseer. A full season list may well be overkill (images for reference only and not a proposal for a specific solution).

OMBI

![image](https://user-images.githubusercontent.com/1133344/172724750-c0a79d7e-0bcd-4827-be4a-9178947da9d1.png)

jellyseer

![image](https://user-images.githubusercontent.com/1133344/172724817-8361eeb0-1606-4aae-8ce0-eb2c189ac4c8.png)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This has been fixed in the new develop branch
