### ISSUE TITLE
[Feature Request] Add filters

### ISSUE THREAD

**Issue by bosci9** [Fallenbagel/jellyseerr#135]
### Description

It would be very useful to have a way to filter the movies and the series. For example I would like to watch only series which are ended, but the only way to browse through them is to open all the series one by one and check their status.

### Desired Behavior

Show only the media that match one (or multiple) criteria.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by IsThisUsernameFree** [comment]
Also an ability to hide movies and series already available, and show only movies or series would be cool!

**Comment by Fallenbagel** [comment]
> Also an ability to hide movies and series already available, and show only movies or series would be cool! 

This is feature is already available. It's the hide available media feature in settings

**Comment by IsThisUsernameFree** [comment]
> > Also an ability to hide movies and series already available, and show only movies or series would be cool!
> 
> This is feature is already available. It's the hide available media feature in settings

Ha! How unfortunate this app does not provide glasses!

**Comment by Fallenbagel** [comment]
This feature should be available in the next release (its currently live on develop)
