### ISSUE TITLE
[Feature Request] Discord Notifications

### ISSUE THREAD

**Issue by Kyrunner** [Fallenbagel/jellyseerr#138]
### Description

Send Notifications to different discord channels/servers 

### Desired Behavior

Would like to be able to send discord notifications to different discord channels and servers. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sypion** [comment]
@Fallenbagel I would love this addition as well. Makes it easier for me to manage reported issues on Jellyseerr on a channel that isn't also filled with requests.

**Comment by Fallenbagel** [comment]
It can be done currently too for the time being using webhooks for issues

**Comment by sypion** [comment]
Had an error because the message couldn't be empty but then I realized it was because the template needed to be modified. Thanks!

**Comment by Fallenbagel** [comment]
Will be closing this as technically that can be handled using a combination of discord and webhook agents. Feel free to re-open if you disagree c:
