### ISSUE TITLE
Season Folders not being created.

### ISSUE THREAD

**Issue by Dubwize** [Fallenbagel/jellyseerr#140]
### Description

When requesting a new show.  There is no option to check off to be able to set everything to be within season folders.

In sonarr newly requested shows from jellyseerr do not have this set.
![image](https://user-images.githubusercontent.com/16105140/173969555-eb408038-1456-435e-9ef7-5cb5eef155f6.png)

So all episodes go into the shows main folder, after that Jellyfin only sees the first episode.

### Version

1.1.0

### Steps to Reproduce

Request and approve a new show in jellyseerr
Check Sonarr for the season folder option.  It will be off
Wait for episodes to download, and check your storage everything will be in the shows man folder.

### Platform

desktop

### Device

Windows

### Operating System

Debian 11

### Browser

Brave/chrome/firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Xaque8787** [comment]
In jellyseer setting, go to services>sonar>edit and scroll down to Season Folders and check it.

I'd also suggest using discord for help as the devs are super responsive there.

**Comment by Dubwize** [comment]
Thank you for the quick response, clearly missed that setting when I originally set things up.
