### ISSUE TITLE
We couldn't automatically match your request. (but exact match found)

### ISSUE THREAD

**Issue by nomandera** [Fallenbagel/jellyseerr#162]
### Description

I believe this may be a bug or a misunderstanding on my behalf.

The only two unusual things I can see are that the show has a `:` which I tested and alternate show successfully (so not that) and that TVDB does not carry info on this show.

### Version

1.1.1

### Steps to Reproduce

Search for `Jack and Kelly Osbourne`
Click `Request` for the single correct match `Request Jack and Kelly Osbourne: Night of Terror` 
Error: `We couldn't automatically match your request. Please select the correct match from the list below.`

### Screenshots

![image](https://user-images.githubusercontent.com/1133344/174740673-67a49523-da5a-4528-9fbc-1733ec48ee20.png)

### Platform

desktop

### Device

Desktop

### Operating System

Windows 10

### Browser

Firefox 101.0.1 (64-bit)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is because of the differneces between tmdb and tvdb. Not a bug. Occurs when jellyseerr/overseerr cannot find the matching tv show in tmdb and the popup one matches usually, HOWEVER, this case is different.

Let me explain.

The show `Jack and Kelly Osbourne: Night of Terror` is considered as a separate tv show in tmdb, therefore, you're able to search for it and see it to press request. However, in tvdb (which is what sonarr uses) has this listed as a specials episode in `The Osbournes Want to Believe`. Therefore, in the list to match, the show `Jack and Kelly Osbourne: Night of Terror` could not be found. More commonly it will be found but this special case does not allow it so due to tvdb considering it as a special episode and not a separate tv show.

**Comment by danshilm** [comment]
This lookup is also done using the first Sonarr server you have added in Overseerr. This is what it looks like when you have one: 
![image](https://user-images.githubusercontent.com/20923978/174767585-11b709d6-de9b-428e-bfd6-c868496ba642.png)

**Comment by nomandera** [comment]
I only have an Emby server nothing else.

Is this a misunderstanding or lack of infrastructure on my behalf rather than a bug? My assumed/expected behavior was clicking a show specific request would complete.

**Comment by Fallenbagel** [comment]
> I only have an Emby server nothing else.
 
You dont have sonarr/radarr?

**Comment by nomandera** [comment]
Correct. I currently use JellySeerr to decode, dedupe, standardize and consolidate inbound requests but have no outbound automation.

From the screenshot above though it seems that even with integration it is not able to add the show?

**Comment by nomandera** [comment]
Excellent, that seems to solve why this specific show acts differently.

I think, whilst not being an expert user, the expected behavior when pressing the purple request button on a specific series would not be a request match error.

If you refer to my initial screen shot we can see that the search string has returned a perfect match and is offering the purple request button directly. I would expect this button to either work or for the error message to be less generic. Certainly the suggested action of `Please select the correct match from the list below.` isnt viable since the exact match has already be made.

Saying all that this might just be too edge case to care about.

**Comment by d1ddle** [comment]
Unfortunately I get this issue with the renewed Animaniacs TV Show. I have the whole Arrs system setup and working, but The 2020 Animaniacs doesn't show in the list to select the correct match after clicking request.

**Comment by Fallenbagel** [comment]
> Unfortunately I get this issue with the renewed Animaniacs TV Show. I have the whole Arrs system setup and working, but The 2020 Animaniacs doesn't show in the list to select the correct match after clicking request. 

That's because tvdb doesn't treat 2020 animaniacs as a seperate series but as seaosn 6, 7, 8.
