### ISSUE TITLE
Add email address to imported Emby / Jellyfin users

### ISSUE THREAD

**Issue by darkorion6661** [Fallenbagel/jellyseerr#164]
### Description

I imported my users from Emby, but it seems that the import into Jellyseerr doesn't bring in the Emby Connect email address. I also don't specifically have email addresses for each user that I want to associate with an Emby Connect account.

Would it be at all possible to add additional fields in Jellyseerr for all users, such as "Email address" for the purposes of email notifications, please? I noticed that once a local user is created, you can't seem to change their registered email either. 

### Desired Behavior

Add email address field to the "notification settings" or "general settings" for all users. 

For importing users from Emby / Jellyfin:
1. Import users from Emby / Jellyfin
2. If user has an Emby Connect email address, import this into an email address field in Jellyseer, else email address field is blank.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by darkorion6661** [comment]
Please note, this is the first time I've logged a feature request on GitHub. I apologise if this has been done incorrectly.

**Comment by Fallenbagel** [comment]
Which version are you on because this has been a feature since 1.1.1

You can change the email address of users as well as let all your users know that they require to add an email address in the profile page

#123

**Comment by darkorion6661** [comment]
Thanks for that. I'm on version 1.1.0. My apologies, I just pulled the latest docker on the Unraid Community Apps page after the latest Ibracorp video about your work, but I didn't realise it was that little bit behind.

I will update right away!
