### ISSUE TITLE
On initial install, recently added/full library scan jobs are not scheduled

### ISSUE THREAD

**Issue by sfwr** [Fallenbagel/jellyseerr#170]
### Description

It looks like because of the [mediaservertype check](https://github.com/Fallenbagel/jellyseerr/blob/develop/server/job/schedule.ts#L63) which is triggered on startup, and undefined on initial install, the jobs `Jellyfin Recently Added Scan` and `Jellyfin Full Library Scan` are not put into the scheduler.

Workaround is to restart the jellyseerr server and everything works well, but it provides for a confusing user experience for new users.

### Version

1.1.1

### Steps to Reproduce

Create new jellyseerr server (via docker, in my case)
Configure server with Sonarr
Start adding shows, they will never come out of "requested" state, and looking at http://jelly.seerr/settings/jobs, you will see the missing tasks.

### Platform

desktop

### Device

pc

### Operating System

unraid

### Browser

chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Oh. Interesting. Will look into that
