### ISSUE TITLE
Webhook notifications (for integrating with all common chat services)

### ISSUE THREAD

**Issue by sunjam** [Fallenbagel/jellyseerr#173]
### Description

Related to #138, but webhooks are used by all common services, which [include Discord notifications (see this documentation)](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks) in addition to:

[Matrix](https://matrix-webhooks.com/)
[Slack](https://api.slack.com/legacy/custom-integrations/messaging/webhooks)
[Rocket.chat](https://docs.rocket.chat/guides/omnichannel/webhooks-managers-guide)
[Mattermost](https://docs.mattermost.com/developer/webhooks-incoming.html)
[IFTTT](https://ifttt.com/maker_webhooks)
etc.

### Desired Behavior

Adding webhooks support and clear documentation will make it possible to add support for all of the various chat notification services out there.  Thanks for considering!

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Webhooks and discord notificationa already exists

**Comment by Fallenbagel** [comment]
I'm going to close this as webhook notifications already exists in both overseerr and jellyseerr c:
