### ISSUE TITLE
Delete / Have Watched Request

### ISSUE THREAD

**Issue by DK2Maverick** [Fallenbagel/jellyseerr#175]
### Description

Thank for this.  I Have been waiting for a good Emby version for a long time.  I set it up and gave it to all my users and boom they have been going nuts adding obscure 15 years old low rated b movies.  It would be really helpful if a user could go back and mark their request as done or watched. That  info could be sorted on  by an admin and those movies / shows could be deleted from radarr / sonarr via a button click. 

### Desired Behavior

Allow A user to mark their requests as watched - no longer needed.  Allow the admin  to have a sorted list of requested movies / shows that have been marked as watched. Have a button to remove those items from sonarr / radarr if desired. Of if the admin wants to let the item remain, an ignore button to remove the request.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Hi. Just wanted to see whether why you'd opt to delete from jellyseerr as opposed to using something like, [Media Cleaner - Python script to delete watched content on Jellyfin and Emby for one or more users](https://github.com/terrelsa13/MUMC) which would be more efficient and work much better

**Comment by DK2Maverick** [comment]
Nice tool. I could see that working for me by just setting up lists for the users that use jellyseer.  One thing  that I need to try out is that it deletes from emby and not the arr's. If the item is monitored the arr's would just add it back?  While not as efficient as the script, my thoughts were , it added by jellyfin , has the graphic ui in place to see the requests and the connection to the arr's to delete.  I look at Jelly daily ( thanks again for it ) so as the offending users  mark their B movies as watched I can make a spot call if its worth keeping. I usually have the users text or message me on discord when they have watched something so I can go look it up and decide if it needs to be removed.

**Comment by Fallenbagel** [comment]
> If the item is monitored the arr's would just add it back? 

You can set in the media management settings of arr's theres an option that unmonitore any deleted media automatically

**Comment by DK2Maverick** [comment]
Thanks - I will give it a try

**Comment by DK2Maverick** [comment]
can Jellyseer apply a tag to movie or series that a user requests?  Customizable by user.  If user ben requests a movie, jellyseer could tag it ben. Medea cleaner could then use that tag for a blacklist.  I Dont want to delete everything Ben watches, just the stuff he request and watches.

**Comment by Fallenbagel** [comment]
> can Jellyseer apply a tag to movie or series that a user requests?  Customizable by user.  If user ben requests a movie, jellyseer could tag it ben. Medea cleaner could then use that tag for a blacklist.  I Dont want to delete everything Ben watches, just the stuff he request and watches.

Jellyseerr can tag but the admin has to edit the request before approval to add the tag

**Comment by Fallenbagel** [comment]
#182 adds a media delete button through jellyseerr which might interest you c:

**Comment by DK2Maverick** [comment]
thank you !!
