### ISSUE TITLE
Recurring Discord notifications

### ISSUE THREAD

**Issue by CarnageDevs** [Fallenbagel/jellyseerr#176]
### Description

The "Request Available" Discord notification gets repeatedly sent every 24 hours for requested & available shows that have episodes without an absolute episode number. It should only be sent once when the show is available and no longer sent thereafter.

This bug only affects shows that are requested/available where the requested/available episodes do not have an absolute episode number.

It can also be manually reproduced once by running the "Sonarr Scan" in "Jobs & Cache".

Two example afflicted shows I have are Yuki Yuna Is a Hero and Sword Art Online Alternative: Gun Gale Online where both shows had all seasons requested. The Special season (which cannot be/wasn't requested) for both shows has downloaded episodes which lack an absolute episode number, thus causing this issue.

### Version

develop

### Steps to Reproduce

1. Have Discord notifications enabled for "Request Available"
2. Request all seasons of a show that has a Special season in Sonarr (not requestable in Jellyseerr)
3. Fulfill the requested seasons, and download episode(s) for the Special season too
4. The downloaded special episodes should not have an absolute episode number, and there should be a warning in Sonarr beside them saying so
5. You'll receive Discord notifications that the series request is available every 24 hours (which is when the Sonarr scan runs)

### Screenshots

The request notification that keeps getting sent every 24 hours:

![image](https://user-images.githubusercontent.com/17109829/177244946-3f327dd1-c7e6-4968-932f-7d9d8b62c724.png)

The request of one of the shows in Jellyseerr (the other show's request is identical):

![image](https://user-images.githubusercontent.com/17109829/177245072-a107dee9-c164-4aa3-95f2-c7b37fc4d666.png)

The show in Sonarr:

![image](https://user-images.githubusercontent.com/17109829/177245398-99b1782c-23d8-4fd6-8edb-9c35881c7c8c.png)

You can see that all requested seasons/season 1 is available, but there is also a Special season which is available that has an episode which lacks an absolute episode number (notice the warning icon beside it)

### Platform

desktop

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
It seems I have the same issue with a particular series (which also has specials that are not listed in jellyseerr), however, I cannot manually produce the problem by manually scanning. The notification only appears every 24hours but automatically. Never manually.

This happened before too but i was able to fix it by moving it out of jellyfin and removing the data from jellyseerr and re-scanning. Should look into why this is happening (but this is not an ideal workaround). Thanks for reporting!

**Comment by Fallenbagel** [comment]
A temporary workaround is that you could go to that media, delete all data and let it rescan as available and it should no longer send

**Comment by sho-87** [comment]
@Fallenbagel have you had a chance to look deeper into this? I'm having the same issue, but with a different series (Lost). One thing in particular with that series is that Sonarr had downloaded a full season pack, but then I manually used sonarr to redownload a couple of specific seasons. Could redownloads like that be triggering multiple "Request Available" alerts?

**Comment by PCJones** [comment]
Sadly I'm still experiencing this exact bug on 1.5.0. Every night at 04:30 (Scheduled Sonarr Scan) I get a request available notification for the same two TV shows. I'll gladly provide more info if needed
