### ISSUE TITLE
Not all libraries importing on scan

### ISSUE THREAD

**Issue by callumgourlay** [Fallenbagel/jellyseerr#178]
### Description

I have been running scans but some shows which are availiable are missing

### Version

1.1.1

### Steps to Reproduce

Unsure

### Screenshots

![image](https://user-images.githubusercontent.com/65352339/177552960-688aa66d-42eb-4017-9d66-c96da970f962.png)
![image](https://user-images.githubusercontent.com/65352339/177553043-2266b8a3-66cf-423b-b86e-94f195b74aaf.png)
Two screenshots of same server one with local ip one with external
![image](https://user-images.githubusercontent.com/65352339/177552033-d0344c42-fdc1-425a-a431-132c7269ace1.png)
![10 20 1 8 5056-Logs-Settings-Jellyseerr(1)](https://user-images.githubusercontent.com/65352339/177552667-76c531b9-47c3-4bc2-929a-c09d7127cecf.png)

### Logs

```shell
{
 "errorMessage": "Invalid auth token",
 "jellyfinitem": {
  "AirDays": [],
  "BackdropImageTags": [
   "1a165b1f9765221fad044f139951d7df"
  ],
  "ChannelId": null,
  "CommunityRating": 8.8,
  "Id": "af2fea42a66a765c626fb50f14d36ed2",
  "ImageBlurHashes": {
   "Backdrop": {
    "1a165b1f9765221fad044f139951d7df": "WAC?fccrD$?GIB-o~q%e%1xb$zRkRkMyn5nixC,.T2RpIAMwv~#l"
   },
   "Logo": {
    "3053b828b227792d0dabc6b25e8a659c": "NbKb@1F^AUSdI.r@Z+V?I.NFNss:0KwKt7oztQt7"
   },
   "Primary": {
    "770eb48751a1399f69a4293a1c3a9b44": "dMBg-y.Q$.%5yrToV~bx*JtievWItlb.n.WHTwX%krbw"
   }
  },
  "ImageTags": {
   "Logo": "3053b828b227792d0dabc6b25e8a659c",
   "Primary": "770eb48751a1399f69a4293a1c3a9b44"
  },
  "IsFolder": true,
  "LocationType": "FileSystem",
  "Name": "JoJo's Bizarre Adventure",
  "OfficialRating": "GB-15",
  "PremiereDate": "2012-10-06T00:00:00.0000000Z",
  "ProductionYear": 2012,
  "RunTimeTicks": 14400000000,
  "ServerId": "04c23de9861e4fb6874aca44df361aa1",
  "Status": "Continuing",
  "Type": "Series",
  "UserData": {
   "IsFavorite": false,
   "Key": "262954",
   "PlayCount": 0,
   "PlaybackPositionTicks": 0,
   "Played": false,
   "UnplayedItemCount": 12
  }
 }
}

2022-07-06T12:30:49.371Z [error][Jellyfin API]: Something went wrong while getting the list of seasons from the Jellyfin server: getaddrinfo EAI_AGAIN mediajelly-node2.callumg.xyz
```

### Platform

desktop

### Device

Desktop PC

### Operating System

Server - Unraid Desktop - Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you also send the logs from your config folder? full logs?

**Comment by callumgourlay** [comment]
Yeah, here you ar
[overseerr.log](https://github.com/Fallenbagel/jellyseerr/files/9062695/overseerr.log)
[overseerr-2022-07-07.log](https://github.com/Fallenbagel/jellyseerr/files/9062696/overseerr-2022-07-07.log)
e

**Comment by Fallenbagel** [comment]
Okay i know what the issue is. Could you hop onto our discord so i can guide you

**Comment by callumgourlay** [comment]
Yeah, what is the link?
