### ISSUE TITLE
Allow Self-Signed Certificates not respected

### ISSUE THREAD

**Issue by dawsoc2** [Fallenbagel/jellyseerr#187]
### Description

When setting up email notifications, the check box for "Allow Self-Signed Certificates" is checked. However no emails are sent, with the error:

```
2022-07-18T22:57:35.826Z [error][Notifications]: Error sending email notification
{
  "errorMessage":"self signed certificate",
  "recipient":"xerxes",
  "subject":"Test Notification",
  "type":"TEST_NOTIFICATION"
}
```

For reference, these exact settings work with another service I have, i.e. another service can send emails using a self-signed certificate

### Version

v1.1.0

### Steps to Reproduce

1. Must use an email server using a self-signed certificate.
2. Settings
3. Notifications
4. Email
5. Check "Allow Self-Signed Certificates"
6. Send test email

### Screenshots

![Screenshot from 2022-07-18 18-02-45](https://user-images.githubusercontent.com/16887517/179631356-30fb2ff4-3838-4b83-b85f-0e1f840646c3.png)
![Screenshot from 2022-07-18 18-04-17](https://user-images.githubusercontent.com/16887517/179631409-e537e69d-26fa-4ec8-bb45-6d1558bd2d44.png)

### Logs

```shell
{
 "errorMessage": "self signed certificate",
 "recipient": "xerxes",
 "subject": "Test Notification",
 "type": "TEST_NOTIFICATION"
}
```

### Platform

desktop

### Device

Desktop

### Operating System

Pop!_OS 22.04 LTS

### Browser

Firefox 102.0.1 (64-bit)

### Additional Context

Using docker from fallenbagel/jellyseerr:develop

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Hi. Could you test to see if it works in 1.1.1. Because 1.1.0 3 months old

**Comment by dawsoc2** [comment]
Sorry; I was indeed _not_ using 1.1.0, and was using a development version from who-knows-when. I pulled v1.1.1 and I get exactly the same behavior I described

![Screenshot from 2022-07-19 07-44-55](https://user-images.githubusercontent.com/16887517/179753354-f8e12cbb-2ea6-4154-ac34-c71f287cd921.png)
![Screenshot from 2022-07-19 07-45-53](https://user-images.githubusercontent.com/16887517/179753515-119881c3-5f5a-4db8-abd4-3889d41adf50.png)

**Comment by Fallenbagel** [comment]
Hm. I've never tried self signed certs, could be an overseerr bug too. I'll check overseerr and see. Thanks for the report!

**Comment by Fallenbagel** [comment]
@dawsoc2 
Hi I think someone found a fix for self signed certificates.

> Ah, I've found a "fix."
> for anyone with the same issue:
> You cannot use STARTTLS without some certificate. In my extremely niche use case, I have a local relay email server that encrypts and sends emails out to the real server (proton).
> Because this relay only signs a certificate for '127.0.0.1', even selecting "Allow Self-Signed Certificates" will not work because the self-signed certificate was not for the IP address or local FQDN of my mail server.
> 
> Disabling STARTTLS or possibly using TLS fixes the issue.
> 
> PS: If you run Jellyseerr on the same server (not containerized, or at least not with the default docker bridge), using STARTTLS should work fine for you.

**Comment by dawsoc2** [comment]
Disabling TLS entirely at least allows me to send emails. The protonmail-bridge running on a separate container is exactly my situation; thanks for finding this.

**Comment by Fallenbagel** [comment]
Closing this issue then c:

**Comment by FibreTTP** [comment]
For future reference, you can now (or have been able to for a while) configure protonmail-bridge with an external TLS certificate in its CLI. I imported my Let's Encrypt cert and it works perfectly with STARTTLS (no longer signed for `127.0.0.1`, but my domain instead).
