### ISSUE TITLE
[Feature Request ] Donation link to support the Jellyseerr project's further development

### ISSUE THREAD

**Issue by teambvd** [Fallenbagel/jellyseerr#192]
### Description

I'm loving the work you all are doing, and I'd like to be able to support the project directly.

### Desired Behavior

 A donation URL within the github would be great!

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
There is a donation link in the dockerhub. I probably should add it to github as well 🤔
