### ISSUE TITLE
Availability of media doesn't change after a full scan.

### ISSUE THREAD

**Issue by zeroquinc** [Fallenbagel/jellyseerr#193]
### Description

After deleting media in Jellyfin, Jellyseerr still marks the media as Available. So you can't request it a 2nd time.
Even when running a manual Full Library scan it still marks it as Available.

### Version

1.1

### Steps to Reproduce

1. Request media in Jellyseerr.
2. Delete it from Sonarr/Radarr/Jellyfin.
3. Notice that Jellyfin doesn't show the movie anymore in the library.
4. Do a Full Manual Library Scan in Jellyseerr.

### Screenshots

![msedge_ONI1ipu3kS](https://user-images.githubusercontent.com/39315068/182360308-72e7c5cf-572b-4378-b2c5-5b1cdb9f7e35.png)

All this media has been deleted from my server already, jellyseerr marks it as Available.

### Platform

desktop

### Device

Windows

### Operating System

Ubuntu

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Do you have available scan enabled on sonarr and radarr services? Because if so it will do that. Otherwise it shouldn't (I just tested)

**Comment by zeroquinc** [comment]
> Do you have available scan enabled on sonarr and radarr services? Because if so it will do that. Otherwise it shouldn't (I just tested)

Scan is enabled on both Sonarr and Radarr since the setup. I just double-checked and they are still enabled. I also tried disabling and re-enabling them but after a Radarr and Sonarr scan the media is still marked as available.

**Comment by Fallenbagel** [comment]
You could create a new instance, this time disable scan on sonarr and radarr and it won't mark anything as available. Or you can manually remove data for each one after the other (not ideal). The reason why they are marked as available is because you had scan from both services turned on when you set it up

**Comment by Martin1134** [comment]
I'm having the same problems, the above steps didn't solved them.

**Comment by Fallenbagel** [comment]
> I'm having the same problems, the above steps didn't solved them. 

Could you come over to discord so its easier to troubleshoot?

**Comment by thedudeabides79** [comment]
Did this ever make it over to discord. Went and searched but could not find it. Having the same issue on unraid server build.

**Comment by Fallenbagel** [comment]
> Did this ever make it over to discord. Went and searched but could not find it. Having the same issue on unraid server build.

It did. But I recommend to make a new support thread on discord and we can follow the troubleshooting steps. I think I already know your issue so

**Comment by Fallenbagel** [comment]
> I'm on version 2.0.1 and this issue is still affecting me. I've done a full manual scan and jellyseerr still thinks the movie is available in jellyfin.
> 
> I was able to delete it by going into the cog on the right hand side of the screen and 'manage  movie' and delete it that way.

That's usually due to a misconfiguration. You'll have to jump onto discord to troubleshoot this.
