### ISSUE TITLE
Cannot reset jellyseerr?

### ISSUE THREAD

**Issue by realitymolder** [Fallenbagel/jellyseerr#196]
### Description

Hey,
it seems like I cannot log in anymore, so I wanted to reset my container, but I cannot seem to get in the configuration screen even though I removed the docker container completely, changed its name, forced recreated it.
Nothing helps. 
In the logs, it says: 

`2022-08-06T00:30:00.075Z [warn][Jellyfin Sync]: No admin configured. Jellyfin sync skipped.`

Thanks

### Version

1.1.1

### Steps to Reproduce

1. Go to jellyseerr Web UI
2. Try to log in.
3. Login will fail, it seems like users aren't configured / imported.
4. Expecting to see the first setup wizard - cannot get it to work.

### Logs

```shell
2022-08-06T00:30:00.075Z [warn][Jellyfin Sync]: No admin configured. Jellyfin sync skipped.
```

### Platform

desktop

### Device

Macbook Pro

### Operating System

Mac

### Browser

FireFox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You need to delete the config folder that you mapped. Where did you map the config folder to?

**Comment by realitymolder** [comment]
> 

You are completly right, I cannot be sure now, because it was in the middle of the night. But I assume that my docker-compose file config pointer pointed on the old folder. 
When I deleted everything, and redeployed everything again from nothing. It did work! 
Thanks.
