### ISSUE TITLE
Very Slow Loading

### ISSUE THREAD

**Issue by eximo84** [Fallenbagel/jellyseerr#198]
### Description

Full load of the home page after login takes around 3 minutes to load all of the images and requests.

Home page just sits there with the placeholder icons flashing away, eventually after 3 minutes everything loads.  This used to happen with Overseerr too but i always assumed it was because it was accessing it via an external URL rather than the internal URL.  However on Jellyseerr i am accessing via the internal IP address.

This happens on any browser and i dont believe its my internet or networking being slow.  Other containers do not take long to load content.

### Version

1.1.1

### Steps to Reproduce

1. Login
2. wait....

### Platform

desktop

### Device

Windows 11 Desktop

### Operating System

Windows 11

### Browser

Firefox, Edge

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Does this occur on a fresh install? Is there anything in the logs?

**Comment by rowanfuchs** [comment]
I have the same issues and it shows no errors other than a few 429 (Too many requests) on TMDB in the browsers console. It would be awesome to be able to select metadata providers, I wouldn't mind some extra serversided caching on images either.

**Comment by Fallenbagel** [comment]
>TMDB added pretty strict rate limiting recently
>we re-enabled the local image caching option recently in the develop branch to combat this. Since we last had this option its been improved significantly and fixes the problem with TMDB rate limits 

^ That was Overseerr. So it seems that its TMDB rate limit issue thats making it slow. We have merged upstream into our dev branch (after a few caveats and tweaks) it should be on the dev branch and hopefully this should fix the issue.

**Comment by Fallenbagel** [comment]
#216 might solve this issue. TMDB rate limit issue has been fixed as well as they added a local image caching feature (you can turn it on in settings). This should increase the loading speeds significantly

**Comment by rowanfuchs** [comment]
Awesome, thats fast! I will test it this weekend as I broke my full environment 😅 and need to set everything up again.

**Comment by Fallenbagel** [comment]
> @Fallenbagel i pulled latest dev branch but jellyseerr refused to start, is this fix in the latest dev version pushed earlier today?
> 
> I'm happy to wait for it to be on the stable branch.

Theres been a little issue with dev branch due to a small merge error. We are fixing it rn (I'm on mobile and at uni so taking a while)

**Comment by Fallenbagel** [comment]
Update: fixed. The develop image is now building c:

**Comment by rowanfuchs** [comment]
Can confirm, amazing load times and no more errors. Thank you!
