### ISSUE TITLE
[Feature Request] Add per-user tag

### ISSUE THREAD

**Issue by ftc2** [Fallenbagel/jellyseerr#201]
### Description

when managing/reviewing media in sonarr and radarr, i think it would be useful to be able to see who requested a series or movie.

also, i think this is among the most useful metadata that jellyseerr generates, so it would be nice to retain it for the future. consider loss of jellyseerr db, migrating to some hypothetical new request app, or an admin simply no longer using jellyseerr.

this has already been suggested upstream, but they don't want to implement it for reasons unknown.

https://github.com/sct/overseerr/issues/1964

### Desired Behavior

set a tag in sonarr/radarr with the jellyseerr user's username when requesting. for safety and flexibility, it would be desirable to add a prefix.
e.g. when user `james` requests movie, set the tag `user-james` (or `jellyseerr-james` or something) in radarr when it's approved in jellyseerr.

it couldn't hurt to make the prefix configurable by admins, but it's not important.

it would also be very nice to have a sub-feature to go back and set user tags on previous requests in jellyseerr. this would help existing jellyseerr admins when this feature first becomes available.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by dephcon** [comment]
@ftc2 thanks for porting my request over, I was hoping this new team would be more open to it.

**Comment by brommeltje** [comment]
Would like this very much, so i can do some post-processing based on user tags

**Comment by jack-mil** [comment]
This would be a great feature, and would further allow individual webhook notifications per user, setting download clients unique to user, etc. Basically anything that sonarr/radarr allows using flags for

**Comment by Fallenbagel** [comment]
This is already completed in the development branch
