### ISSUE TITLE
Stutter while scrolling on Firefox Browser

### ISSUE THREAD

**Issue by realitymolder** [Fallenbagel/jellyseerr#202]
### Description

While using jellyseerr on the web with Firefox, scrolling and moving between UI elements is very slow as if its "too heavy" 

Using Webkit based browsers (ie: Chromium / Safari) is working well.

### Version

1.1.1

### Steps to Reproduce

1. Open Firefox
2. Go to jellyseerr web UI (I'm using docker to run the app)
3. You should see the problem right away - scroll down in the main page

### Platform

desktop

### Device

Macbook pro

### Operating System

MacOS 13

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ftc2** [comment]
i never even noticed it until now, but in my testing, scrolling does seem noticeably less snappy in firefox than chrome.

**Comment by Fallenbagel** [comment]
Ah. So same issue as overseerr too. I just noticed (lmfao I just thought it was bc my server was potato).

I recently read two comments on overseerr discord as well regarding similar issue

> Does anyone use Firefox with overseerr? It's really slow for me
> using a chrome based browser on the same machine for the same site and the slowness goes away. It's mostly with scrolling


Another feedback was: 
> if some requests a lot of requests it generally slows down

Worth looking into. Do you have a lot of requests as well?

**Comment by realitymolder** [comment]
> Ah. So same issue as overseerr too. I just noticed (lmfao I just thought it was bc my server was potato).
> 
> I recently read two comments on overseerr discord as well regarding similar issue
> 
> > Does anyone use Firefox with overseerr? It's really slow for me
> > using a chrome based browser on the same machine for the same site and the slowness goes away. It's mostly with scrolling
> 
> Another feedback was:
> 
> > if some requests a lot of requests it generally slows down
> 
> Worth looking into. Do you have a lot of requests as well?

Interesting, not much ATM. Only 4 and they are already "approved". 
Quite sure it's because of all the other pictures as well. (not exclusive to the request section.)
A screenshot is attached below. 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/26459151/184846626-cfa795e7-1be2-4392-a684-1706d358f6f5.png">

**Comment by Fallenbagel** [comment]
@realitymolder Another thing from Overseerr discord by an overseerr dev. Turns out its firefox v103 issue as v102 does not have that stutter

> Try with v102
https://ftp.mozilla.org/pub/firefox/releases/102.0/

**Comment by Fallenbagel** [comment]
I j

> @realitymolder Another thing from Overseerr discord by an overseerr dev. Turns out its firefox v103 issue as v102.1.0esr does not have that stutter
> 
> > Try with v102
> > https://ftp.mozilla.org/pub/firefox/releases/102.0/
> 
> and it was replied with
> 
> > using the 102.1.0esr version fixes the scrolling issue
> 
> so maybe try on https://ftp.mozilla.org/pub/firefox/releases/102.1.0esr/

I just tested on v102.1.0esr and it indeed does not stutter. (I am on that now)

**Comment by realitymolder** [comment]
> > > using the 102.1.0esr version fixes the scrolling issue
> > 
> > 
> > so maybe try on https://ftp.mozilla.org/pub/firefox/releases/102.1.0esr/
> 
> I just tested on v102.1.0esr and it indeed does not stutter. (I am on that now)

How can we let Firefox know about this bug? Is that in a specific package that we can put a finger on ?

**Comment by Fallenbagel** [comment]
> How can we let Firefox know about this bug? Is that in a specific package that we can put a finger on ?

I am not sure. There should be a way to report bugs, maybe check their website?
As for the specific package, all I know (and can confirm) is that that v102.1.0esr has no issue however the latest one as in the 103 does have the issue present.

**Comment by realitymolder** [comment]
I Opened an issue in Bugzilla, lets see what happens now haha

**Comment by Fallenbagel** [comment]
> I've opened an issue in Bugzilla, let's see what happens now haha


I heard that the issue has been fixed in Firefox nightlies so hopefully very soon it will be fixed for stable 🥳

**Comment by Fallenbagel** [comment]
I just tested this with the latest firefox `104.0.2` and it seems to have been fixed c:

**Comment by realitymolder** [comment]
> I just tested this with the latest firefox `104.0.2` and it seems to have been fixed c:

that was a very fast fix tbh
