### ISSUE TITLE
Non-admin/owner account cannot request 4K content.

### ISSUE THREAD

**Issue by cpfowler** [Fallenbagel/jellyseerr#203]
### Description

New user accounts, whether jellyfin, local, or both don't have the ability to request anything in 4K.

### Version

1.1.1

### Steps to Reproduce

1. Create new user, doesn't matter if local, or if from Jellyfin import.
2. Give them permissions for 4K, and auto approve 4K.
3. New user cannot request 4K.

### Screenshots

I have both Sonarr and Radarr setup appropriately. 1 docker container for Sonarr, 1 for Radarr. Both default, and 4K default profiles point to the same container for each.
![1](https://user-images.githubusercontent.com/77090074/184785508-9ec6942d-1a4e-46a8-9e76-8b5d65abfb09.png)

Permissions for the new user
![2](https://user-images.githubusercontent.com/77090074/184785583-3b539387-22aa-45da-bb24-1eaffbbcb40d.png)

Proof the owner account can request 4K
![3](https://user-images.githubusercontent.com/77090074/184785638-cfb8afd5-03ab-48c3-a82c-9ded3e0de3aa.png)

Yet the new user cannot request 4K
![4](https://user-images.githubusercontent.com/77090074/184785724-99dadd76-bcad-44b2-b5fc-7ca861b98329.png)

Proof the request from new user syncs to Radarr as my 720/1080 default profile
![5](https://user-images.githubusercontent.com/77090074/184785846-105093cf-8597-4127-9c32-13ecf5d18be2.png)

### Logs

```shell
Only 2 relevant logs:
2022-08-16T02:16:06.619Z [info][Notifications]: Sending notification(s) for MEDIA_AUTO_APPROVED{"subject":"Day Shift (2022)"}

2022-08-16T02:16:06.621Z [info][Media Request]: Sent request to Radarr{"mediaId":33,"requestId":9}
```

### Platform

desktop

### Device

Desktop PC

### Operating System

Windows 10 & 11

### Browser

Firefox and Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you show me where you pressed to request again?
I just tested this and the request 4k is in the drop down,

![image](https://user-images.githubusercontent.com/98979876/184844980-30355593-99a5-4888-8d53-a0be200d5014.png)

**Comment by cpfowler** [comment]
Well this is embarrassing... I Swear I spent 10+ minutes looking around for where regular accounts can request 4K, including that drop down and couldn't find anything mentioning 4K.

Now that you point it out, sure enough, it's right there in front of me, glaringly, and mocking me. :smiling_face_with_tear:
