### ISSUE TITLE
Jellyseerr stuck when testing connection to Radarr server

### ISSUE THREAD

**Issue by BadCactus634** [Fallenbagel/jellyseerr#205]
### Description

Hi! So I just installed Jellyseerr and setup the link with Jellyfin, that's working fine.
Only problem is when i try to add a Radarr server, I compiled everything correctly in the form but when i click "test" it just keep loading forever...

I already tried restarting the container and resetting the config (by deleting the dir mounted in docker and let Jellyseerr recreate it). Also tried with "localhost" (not accepted) and 127.0.0.1 (connection refused).
I am on Ubuntu 20.04, latest version of Docker, Jellyseerr 1.1.1 (it say "stable" in the bottom left corner but "beta" in settings...).

I searched on the Internet but nobody seems to have this problem...

Log only shows:
[Radarr] Failed to retrieve profiles: connect ETIMEDOUT 192.168.1.3:7878

Maybe has something to do with Docker network? But it's working fine for Jellyfin.

### Version

1.1.1

### Steps to Reproduce

1. Install Jellyseer on Docker (Portainer)
2. Try to add a Radarr server in initial setup

### Screenshots

![image](https://user-images.githubusercontent.com/68558172/185678065-c3ce0a25-28fe-4478-a014-fc61d7a51010.png)
![image](https://user-images.githubusercontent.com/68558172/185678059-7a392583-e225-4b59-b864-d4688854fe9f.png)

### Logs

```shell
2022-08-19T17:52:34.800Z [error][Radarr]: [Radarr] Failed to retrieve profiles: connect ETIMEDOUT 192.168.1.3:7878
```

### Platform

desktop

### Device

Laptop

### Operating System

Windows 10

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This could be docker networking issue. Could you hop on over to our discord so I could help you figure it out?

**Comment by Fallenbagel** [comment]
> Sure, I'm Stefano#7721 do you need me to create a new post in support?

yes
