### ISSUE TITLE
Change default port

### ISSUE THREAD

**Issue by Monirzadeh** [Fallenbagel/jellyseerr#208]
### Description

By default, jellyseerr run on port `5055` I want to change that to other port like `80`.
It is good if we can change that in settings or at least with env variable

### Desired Behavior

Add option to change from setting menu (like sonarr or radarr) or env variable

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
If you're running on docker, it can be changed by mapping the port
```
  ports:
    - 80:5055
```
Where the first port is your host bind.

If you're running natively this can be achieved by having an environment file that can be referenced in the service as follows:
```
[Service]
EnvironmentFile=/etc/conf.d/jellyseerr.conf
```
And in the `/etc/conf.d/jellyseerr.conf` file you add
```
PORT=80
```
