### ISSUE TITLE
Emby playback error

### ISSUE THREAD

**Issue by yang0026** [Fallenbagel/jellyseerr#210]
### Description

I setup with a Emby server, and when I click "Play on Jellyfin", the URL will direct to http://myip.com:8096/web/index.html#!/details?id=xxxx&context=home&serverId=xxxxxx，and show nothing，the correct Emby media link should be http://myip.com:8096/web/index.html#!/item?id=xxxx&context=home&serverId=xxxxxx , the "details" should be "item".

### Version

1.1.1

### Steps to Reproduce

1. Setup jellyfin server by using emby server ip and user;
2. select a video in the emby library；
3. click "Play on Jellyfin"
4. no detail of the video show up

### Platform

desktop

### Device

PC

### Operating System

Windows11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Did you add the emby env variable because this has been fixed #71 
If you get detail that means the emby env variable is missing.
