### ISSUE TITLE
Add Slovenian translation

### ISSUE THREAD

**Issue by dyxen** [Fallenbagel/jellyseerr#213]
### Description

Hello,
please add Slovenian language to translation on Webplate.
If you need any additional info please respond.
Have a nice day,
DyXen

### Desired Behavior

Hello,
please add Slovenian language to translation on Webplate.
If you need any additional info please respond.
Have a nice day,
DyXen

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Was slovenian language added upstream? 🤔

**Comment by jonpas** [comment]
See https://github.com/sct/overseerr/issues/3155.

I think this issue can be closed as translations happen upstream in overseerr.
