### ISSUE TITLE
Constant emails

### ISSUE THREAD

**Issue by dmike3** [Fallenbagel/jellyseerr#215]
### Description

I keep getting emails that a show is available. It’s stuck in some type of loop and emails me over and over every couple hours.

### Version

1.1.1

### Steps to Reproduce

No idea

### Platform

desktop

### Device

Apple

### Operating System

All OS

### Browser

All browsers

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Related to this issue #176
