### ISSUE TITLE
slightly corrupt jellyfin link when clicking on request

### ISSUE THREAD

**Issue by Ceredril** [Fallenbagel/jellyseerr#220]
### Description

<img width="672" alt="jellyseer" src="https://user-images.githubusercontent.com/63151691/189501852-5d5f4932-4a5b-4223-abd0-d0dcfb3b74ba.PNG">
When clicking on the green "Available" here it opens up the jellyfin entry of this movie/episode.
This is quite practical, however the link that is opened is in the following format:
[...]:8096//web/index.html#!/details?id=[...]
instead of
[...]:8096/web/index.html#!/details?id=[...]

there is one "/" too many.

### Version

1.1.1

### Steps to Reproduce

Go to Requests and click on an entry marked as "Available"

### Platform

desktop

### Device

irrelevant

### Operating System

irrelevant

### Browser

irrelevant

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Amcro** [comment]
Yup, i have exact same problem with profile picture getting pulled from jellyfin, looking at the sqlite database shows double // in the exact same spot, right after port number. I wanted to open ticket but as it seems it's the same issue so i'm just going to add comment on this one.

**Comment by Ceredril** [comment]
Thx for the temporary (or for me permanent) fix!

**Comment by Fallenbagel** [comment]
For the permanent fix, you can stop the container, go to the config folder and you should see the settings.json file, open it and remove the trailing slash
