### ISSUE TITLE
Add an option to have discord notification display or not display requested by.

### ISSUE THREAD

**Issue by lexxanite** [Fallenbagel/jellyseerr#221]
### Description

I would like the discord notifications to not display the requested by jellyfin account name on the announcement. I feel there should be an option to check if you want usernames visible in the announcement.

### Desired Behavior

I want the Discord tag to not have the Requested By section.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You could achieve this by using the webhook notification instead of the discord one. You can template it to not have the requested by displayed

**Comment by butts136** [comment]
I agree with Lexxanite, You should add a check box to hide the (requested by : )

**Comment by Fallenbagel** [comment]
> I agree with Lexxanite, You should add a check box to hide the (requested by : )

[#238 (comment)](https://github.com/Fallenbagel/jellyseerr/issues/238#issuecomment-1277034838) You can use this template on the webhook notification (and customize however you want, the current template will not show requested by)

**Comment by Pukabyte** [comment]
What if you are already using the webhook. this should be added in the discord feature

**Comment by fallenbagel** [comment]
> What if you are already using the webhook. 

For the record, I'm only replying to the above quoted question. There is a PR opened for multiple webhook:
#1608

That said I will re-open this issue as a feature request but will keep it tagged as `awaiting triage`.

**Comment by someRandomDude-a** [comment]
I achieved this by patching the discord.js file inside the container with a mount to remove all PII from notifications which was a big requirement for my userbase
@lexxanite  if urgent, you can use this method for seerr 3.2.0
```yaml
    volumes:
      - ./config:/app/config
      - ./patch/discord-websocket/discord.js:/app/dist/lib/notifications/agents/discord.js
```
[discord.js](https://github.com/user-attachments/files/28479253/discord.js)

This can be implemented fairly easily with an option / setting.


> You could achieve this by using the webhook notification instead of the discord one. You can template it to not have the requested by displayed

This is not a good solution, the template sections to null out fields for missing values does not work with discord, the discord notification client has different formats for different notifications that is not repeatable with the templates from custom webhook integrations.
