### ISSUE TITLE
Jellyseerr crashes on Raspberry pi 4

### ISSUE THREAD

**Issue by zeskeertwee** [Fallenbagel/jellyseerr#223]
### Description

I attempted to install jellyseerr on a raspberry pi 4b, and it crashed immediately.

### Version

The latest docker version (digest sha256:558927b7caaf42c4940bc21f1aa46bc3d6dc1730e4b1539b701ed6961d6b2c7d) (the develop docker version also crashes with the same error)

### Steps to Reproduce

1. Use the `docker-compose.yml` from https://hub.docker.com/r/fallenbagel/jellyseerr
2. run `sudo docker-compose up`
3. it pulls the image and crashes

### Logs

```shell
pi@[REDACTED]:~/jellyseerr $ sudo docker-compose up
Creating network "jellyseerr_default" with the default driver
Pulling jellyseerr (fallenbagel/jellyseerr:latest)...
latest: Pulling from fallenbagel/jellyseerr
57fb4b5f1a47: Pull complete
d1393c274244: Pull complete
1af5ea6e06a0: Pull complete
ccde71dd47a8: Pull complete
4178c73c1d34: Pull complete
68a8f3ca0c92: Pull complete
a4f7e167d14d: Pull complete
Digest: sha256:558927b7caaf42c4940bc21f1aa46bc3d6dc1730e4b1539b701ed6961d6b2c7d
Status: Downloaded newer image for fallenbagel/jellyseerr:latest
Creating jellyseerr ... done
Attaching to jellyseerr
jellyseerr    | 
jellyseerr    | 
jellyseerr    | #
jellyseerr    | # Fatal error in , line 0
jellyseerr    | # unreachable code
jellyseerr    | #
jellyseerr    | #
jellyseerr    | #
jellyseerr    | #FailureMessage Object: 0xbeaa85fc
jellyseerr exited with code 133
```

### Platform

desktop

### Device

Raspberry pi 4b 8gb

### Operating System

Raspbian GNU/Linux 10 (buster) armv7l

### Browser

Not relevant

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you try what this person block quoted?

https://github.com/jesec/flood/issues/390#issuecomment-1186491973

I havent been able to reproduce this on my rpi

**Comment by zeskeertwee** [comment]
Thanks! That fixed the issue, and it's working perfectly now!
