### ISSUE TITLE
Log format corrections

### ISSUE THREAD

**Issue by nickcj931** [Fallenbagel/jellyseerr#224]
### Description

In an attempt to parse my logs with failed authentication events, I have noticed inconsistency with how logs spit out various messages based on the type of authentication failure. Which is inconsistent. You also get different tags come through for selected filter option, for example selecting Warning also gets you Error messages 

Inconsistency label examples
1. If you attempt to login with your Jellyseerr created user credentials you get Severity="WARN"; Label="API"; Message="Failed sign-in attempt using invalid Overseerr password"
2. If you attempt to login with Emby credentials you get Severity="INFO"; Label="AUTH";Message="Failed login attempt from user with incorrect Jellyfin credentials"

It would be good if you could look for Authentication issues under the same tag to pickup any possible malicious activity much easier.

### Version

1.1.1

### Steps to Reproduce

1. Go to Settings
2. Logs
3. Select between different filters
4. Observe filtered out tags making it into the view and also different tags when login fail attempts are made

### Screenshots

![Screenshot 2022-09-15 at 13 29 17](https://user-images.githubusercontent.com/17556895/190404571-f0d4823e-67f1-444c-a697-761976b30b8f.png)

### Logs

```shell
2022-09-15T12:28:43.801Z [warn][API]: Failed sign-in attempt using invalid Overseerr password{"email":"<EMAIL REMOVED>","ip":"::ffff:<IP ADDRESS REMOVED>"}

2022-09-15T12:28:31.647Z [info][Auth]: Failed login attempt from user with incorrect Jellyfin credentials{"account":{"email":"<EMAIL REMOVED>","ip":"::ffff:<IP ADDRESS REMOVED>","password":"__REDACTED__"}}
```

### Platform

desktop

### Device

Server

### Operating System

Unraid

### Browser

Chrome, Safari, Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Is it the same on `develop` tag too?

**Comment by nickcj931** [comment]
Yep just done a pull on the develop tag and its exactly the same result
![Screenshot 2022-09-26 at 09 12 58](https://user-images.githubusercontent.com/17556895/192226562-047a2896-d315-4f9c-8fb3-fd7362c4bb1b.png)
