### ISSUE TITLE
can you add a non docker version

### ISSUE THREAD

**Issue by Pickymarker** [Fallenbagel/jellyseerr#226]
### Description

can you add a non docker version

### Version

can you add a non docker version

### Steps to Reproduce

can you add a non docker version

### Screenshots

can you add a non docker version

### Logs

```shell
can you add a non docker version
```

### Platform

desktop

### Device

can you add a non docker version

### Operating System

can you add a non docker version

### Browser

can you add a non docker version

### Additional Context

can you add a non docker version

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
A non docker version is already supported.
