### ISSUE TITLE
new user add email addr need save twice

### ISSUE THREAD

**Issue by anschein** [Fallenbagel/jellyseerr#227]
### Description

import emby account,and edit there email,when first time click save button,lost input email and back to user name,but after input the email addr again,the save button works

### Version

1.1.1

### Steps to Reproduce

As Description

### Platform

desktop

### Device

desktop pc

### Operating System

win11

### Browser

chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by serverless83** [comment]
This bug is still present in 1.6.0 version.

**Comment by noybman** [comment]
Still an issue today in 1.8.1.
I decided to "import users", then manually went through each one and hit "save", now users can get it right on their first try (perhaps).  It seemed to work for me a few times so far.

this makes me think something needs to be written to the database on import and it is not written until saved at least once?

**Comment by gauthier-th** [comment]
Fixed in #760.
