### ISSUE TITLE
[Feature Request] Support multiple Discord webhooks

### ISSUE THREAD

**Issue by nickspacemonkey** [Fallenbagel/jellyseerr#236]
### Description

If possible, I would like to be able to notify 2 or more Discord servers using the webhook integration please.

### Desired Behavior

Maybe a button to add additional webhook URLs could be done. The same information just needs to be sent to multiple webhooks, although more granular control could allow a user to separate 'issues' notifications into their own channel as an example.

Many thanks for your work.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sypion** [comment]
Not sure why this was closed. Would love this addition to separate issues reported on a separate channel from requests.

**Comment by Fallenbagel** [comment]
> Not sure why this was closed. Would love this addition to separate issues reported on a separate channel from requests.

I'm not sure either but as for the seperate issue thing you could technically utilise the webhook function to just send the issues thingy to a different channel

**Comment by FredHaa** [comment]
I would also like this feature.

Meanwhile, do you have a template to use for the JSON payload in order to integrate it with discord?

**Comment by Fallenbagel** [comment]
> I would also like this feature.
> 
> Meanwhile, do you have a template to use for the JSON payload in order to integrate it with discord?

It's the default discord webhook template (many resources online)
For example: https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html

**Comment by FredHaa** [comment]
Thank you

However, I realize that this solution is not as dynamic as I would like. Is there any chance of the original requested feature being made? I.e. being able to enable multiple agents/specify different webhook URLs per message type?

Maybe if I open a new issue (and then not close it myself like the OP in this issue)?
