### ISSUE TITLE
Webhook test message fails when sending to discord.

### ISSUE THREAD

**Issue by lexxanite** [Fallenbagel/jellyseerr#238]
### Description

Cannot send test messages to discord that are empty, per the logs.

### Version

1.2.0

### Steps to Reproduce

1. Go to Settings
2. Go to notifications
3. Go to webhook
4. Create a discord webhook
5. click test webhook
6. Fails with provided error.

### Logs

```shell
2022-10-13T01:39:30.595Z [error][Notifications]: Error sending webhook notification{"errorMessage":"Request failed with status code 400","response":{"code":50006,"message":"Cannot send an empty message"},"subject":"Test Notification","type":"TEST_NOTIFICATION"}
```

### Platform

desktop

### Device

Desktop

### Operating System

Windows 10

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you show me how youre setting it up? I just tested and it seems to be working with no issues

**Comment by lexxanite** [comment]
![FireShot Capture 086 - Notifications - Settings - Jellyseerr](https://user-images.githubusercontent.com/73835921/195502516-3143a30f-4eb0-41cc-8c89-5e5e30d27c25.png)


{
    "notification_type": "{{notification_type}}",
    "event": "{{event}}",
    "subject": "{{subject}}",
    "message": "{{message}}",
    "image": "{{image}}",
    "{{media}}": {
        "media_type": "{{media_type}}",
        "tmdbId": "{{media_tmdbid}}",
        "tvdbId": "{{media_tvdbid}}",
        "status": "{{media_status}}",
        "status4k": "{{media_status4k}}"
    },
    "{{request}}": {
        "request_id": "{{request_id}}"
    },
    "{{issue}}": {
        "issue_id": "{{issue_id}}",
        "issue_type": "{{issue_type}}",
        "issue_status": "{{issue_status}}",
        "reportedBy_email": "{{reportedBy_email}}",
        "reportedBy_username": "{{reportedBy_username}}",
        "reportedBy_avatar": "{{reportedBy_avatar}}"
    },
    "{{comment}}": {
        "comment_message": "{{comment_message}}",
        "commentedBy_email": "{{commentedBy_email}}",
        "commentedBy_username": "{{commentedBy_username}}",
        "commentedBy_avatar": "{{commentedBy_avatar}}"
    },
    "{{extra}}": []
}

**Comment by Fallenbagel** [comment]
Why not the discord notification thing?

**Comment by lexxanite** [comment]
https://github.com/Fallenbagel/jellyseerr/issues/221#issuecomment-1243022317

**Comment by Fallenbagel** [comment]
What about the authorization header? I dont think its needed for discord

**Comment by lexxanite** [comment]
I have removed the rest of the webhook URL in order to keep it secret. The authorization header makes no difference on the success.

**Comment by Fallenbagel** [comment]
WAIT I think i know whats happening. Your template has all variables defined but no message

**Comment by Fallenbagel** [comment]
@lexxanite Try this template

{
    "avatar_url": "https://github.com/Fallenbagel/jellyseerr/blob/develop/public/os_logo_square.png?raw=true",
    "username": "Jellyseerr",
    "embeds": [
        {
            "color": 1127128,
            "title": "{{notification_type}}",
            "description":"{{subject}}\n\n{{message}}\n\nStatus: {{media_status}}\n\nRequest Id: {{request_id}}",
            "thumbnail": {
                "url": "{{image}}"
              },
            "footer": {
                "text": "Link https://jellyseerrurl/{{media_type}}/{{media_tmdbid}}",
                "icon_url": "https://github.com/Fallenbagel/jellyseerr/blob/develop/public/os_logo_square.png?raw=true"
            }
        }
    ]
}

Remember to change the `jellyseerrurl` part

Also this link might help you, its a guide on how to create discord templates
https://birdie0.github.io/discord-webhooks-guide/index.html

**Comment by lexxanite** [comment]
I have fully tested and confirmed this works as expected with the template provided.
