### ISSUE TITLE
Slightly OT: Custom CSS Theme for Jellyfin?

### ISSUE THREAD

**Issue by devenator** [Fallenbagel/jellyseerr#243]
### Description

I love the look of jellyseerr. It would be great if someone could make a CSS for the Custom CSS code field in Jellyfin to match the look with jellyseerr.

### Desired Behavior

The whole look would be very nice, but i'm looking especially for the zooming effect on the posters-cards and the purple-graded effect on the selected menu / buttons...

### Additional Context

I have zero understanding how nodejs actually works, but  if this is easily possible, it woud be even greater, if a yarn run build would create a css-file on jellyseerr, that just could be @import url 'ed in jellyfin!

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
There is overseerr theme for jellyfin at themepark.
https://docs.theme-park.dev/themes/jellyfin/

So what you need to do is use this line in custom css field
```
@import url("https://theme-park.dev/css/base/jellyfin/overseerr.css");
```

**Comment by devenator** [comment]
That's awesome, exactly what i was looking for, i already use a lot of theme-park-css for *rr, but i didnt see that they also have an overseer for jellyfin! Thanks a lot :+1:
