### ISSUE TITLE
Repeating Request notifications

### ISSUE THREAD

**Issue by Suzaru** [Fallenbagel/jellyseerr#246]
### Description

For some reason some request notifications will be repeated every day at 1.30am and I don't know why.

### Version

1.2.1

### Steps to Reproduce

I am not 100% sure, doesn't happen all the time. Maybe if I interfere with the selection process?

### Screenshots

![image](https://user-images.githubusercontent.com/31924909/198054988-bdd4c21c-0344-41b5-baa0-a7d67d8adcc1.png)

### Platform

desktop

### Device

not applicable

### Operating System

not applicable

### Browser

not applicable

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sho-87** [comment]
Same as https://github.com/Fallenbagel/jellyseerr/issues/176 and https://github.com/Fallenbagel/jellyseerr/issues/215 I think

**Comment by Fallenbagel** [comment]
I'm hoping this gets resolved when individual episode requesting is implemented. I feel like when jellyseerr/overseerr detects an episode that's not in the jellyserrr/overseerr database (mostly special seasons) it triggers a repeated notification everytime. I'm not entirely sure

**Comment by GeoffreyCoulaud** [comment]
I also have this problem. It's kind of annoying, but I don't want to put pressure on the devs, it's a minor problem.
