### ISSUE TITLE
`Warning: data for page "/setup" is 181 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.`

### ISSUE THREAD

**Issue by sdfg2** [Fallenbagel/jellyseerr#249]
### Description

Logging in to jellyfin works, syncing libraries works, hitting the "Start Scan" button does nothing, and the "Continue" button doesn't become available.  Checking logs, looks like jellyseerr starts the full scan, but the page doesn't get updated.  Refreshing the page gives a node error about page size.

### Version

1.2.1-1

### Steps to Reproduce

Install from AUR using the patch included in the AUR page.
Go to jellyseer
Enter jellyfin login details
Sync libraries
Press 'Start Scan' button, see nothing seems to happen
Refresh page, see error in log

### Logs

```shell
Oct 29 21:23:11 heracles node[3970755]: Warning: data for page "/setup" is 181 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
Oct 29 21:23:11 heracles node[3970755]: See more info here: https://nextjs.org/docs/messages/large-page-data
```

### Platform

desktop

### Device

Desktop

### Operating System

Arch

### Browser

All that I've tried.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The warning doesn't matter. Its sth else. Could you open a support thread on discord easier to communicate and narrow down

**Comment by sdfg2** [comment]
I don't use discord.

**Comment by Fallenbagel** [comment]
> I don't use discord.

Okay so  the sync libraries, could you show me a screenshot?

**Comment by sdfg2** [comment]
Nope, because now I'm getting a 401 when trying to put in my login details to get to that stage again, and there's no explanation in the logs as to what's going on.

**Comment by Fallenbagel** [comment]
> Nope, because now I'm getting a 401 when trying to put in my login details to get to that stage again, and there's no explanation in the logs as to what's going on.

Could you delete the contents inside the config folder?

**Comment by Fallenbagel** [comment]
> Yup.  Still getting 401.

Do you have devices limited on jellyfin?

**Comment by sdfg2** [comment]
No, but you made me think of the sessions.  I deleted the existing Jellyseerr session in Jellyfin and could log in again.  I realise it's an edge case, but might want to handle that a bit more elegantly :-)

![image](https://user-images.githubusercontent.com/5736478/199064980-a7e4f7d1-4886-4876-a8e9-abf76f072400.png)

That's after hitting the scan button.

**Comment by Fallenbagel** [comment]
> ![image](https://user-images.githubusercontent.com/5736478/199064980-a7e4f7d1-4886-4876-a8e9-abf76f072400.png)
> 
> That's after hitting the scan button.

you didnt turn on the libraries. maybe because of the dark reader? or sth the color is black but you see those thingies? you need to press them to turn on those libraries. When turned on they are in purple color
![image](https://user-images.githubusercontent.com/98979876/199070980-ed1b34a8-54a7-4cd8-b098-6a362e0e600c.png)

**Comment by sdfg2** [comment]
Thanks.
