### ISSUE TITLE
Play on Plex when using Emby (Requests)

### ISSUE THREAD

**Issue by KSPSlice** [Fallenbagel/jellyseerr#254]
### Description

In Requests, when hovering over with the mouse over the Available Status, Play On Plex shows. I have an Emby install. The movie itself shows correctly as Play on Emby.
![2022-11-08](https://user-images.githubusercontent.com/89319681/200630984-5805c83b-1910-4b7b-a149-80097ed6d203.png)

### Version

1.2.1

### Steps to Reproduce

Go to Requests or Requests under the Discover tab. Under the Status Available hover with the mouse. Shows Play on Plex for an Emby install.

### Screenshots

![2022-11-08](https://user-images.githubusercontent.com/89319681/200631430-074bbb59-f992-40eb-b7ad-4f339c9cbf07.png)

### Platform

desktop

### Device

Desktop PC

### Operating System

Windows 10

### Browser

Edge, Chrome

### Additional Context

Jellyseerr installed via Docker on a Synology NAS. First time posting, so hope I didn't miss anything.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Yeah it's one of the strings that were added recently that we forgot to replace

**Comment by Krafting** [comment]
Same issue here but using Jellyfin, not Emby! :+1:
