### ISSUE TITLE
Only first library retrieved from Jellyfin

### ISSUE THREAD

**Issue by KiwiLostInMelb** [Fallenbagel/jellyseerr#255]
### Description

When doing a sync of libraries from Jellyfin only the first library is show/available.  TV, Doco's, etc are not retrieved/synced or listed.

### Version

 1.2.1

### Steps to Reproduce

settings->jellyfin->sync libraries

### Platform

desktop

### Device

Chrome on linux

### Operating System

Linux

### Browser

Chrome

### Additional Context

No errors in logs.  In fact the logs are pretty sparse even on debug mode.
Installation is from fallenbagel/jellyseerr:latest
Docker container Network is running host (not bridge)
Jellyfin is on a separate box (not localhost)
Jellyfin version 10.8.7
Jellyfin added as http internal url and it does have a subpath (/jellyfin)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Do you have automatic grouping enabled?
What type of libraries are the ones that are not synced and the ones that got synced?

**Comment by jfldsf** [comment]
I think i might have the same issue but they didn't describe it very well (lmk if different and i should make a new issue). I'm not sure if it has something to do with it being the first library or what it is. when I add a movie everything works as it should, but when i add tv show it never moves to "available." it goes from processing to having no status as shown here: 
![image](https://user-images.githubusercontent.com/32817688/201461395-361fc946-298d-4c7a-9e6d-4f9c9d4250fd.png)
even though it is in Jellyfin. Manually running both full scan and recent scan does nothing for it to recognize as available. please let me know what other info i can send, and thanks for your active development <3

**Comment by Fallenbagel** [comment]
What happens when you press sync libraries?

**Comment by jfldsf** [comment]
sorry i don't think I had the same issue, but it does nothing, both of them appeared in there. it took until the sonarr scan for the series to show up as partially available

**Comment by KiwiLostInMelb** [comment]
Sync libraries does nothing - if I delete the first library from the config file then it will only find the first library again.
The first library is a movies folder.  The others are 3x TV folders and 2x movies folders (all others not discovered).

>> Do you have automatic grouping enabled?
Yes.  I dont have auto grouping on the library that actually synced though.  The ones that didnt sync have grouping enabled.

Ok, so I turned off auto grouping and all the libraries sync now. Is this a known limitation?  I didnt see it in the instructions but may have missed it.  

Can it be fixed so grouping can work?

Thanks heaps for looking into this one!

**Comment by Fallenbagel** [comment]
> Ok, so I turned off auto grouping and all the libraries sync now. Is this a known limitation?  I didnt see it in the instructions but may have missed it.  

Yes it's a known limitation as of now. I should probably add it into the readme as its the most common issue most new users are facing

> Can it be fixed so grouping can work?

Will have to look into it really. Wondering if jellyfin api allows it or not. Definitely worth a shot

**Comment by Fallenbagel** [comment]
> sorry i don't think I had the same issue, but it does nothing, both of them appeared in there. it took until the sonarr scan for the series to show up as partially available

Could you create a new issue with the details and we could go over what's happening?
