### ISSUE TITLE
Radarr integration does not work. Add logs

### ISSUE THREAD

**Issue by schklom** [Fallenbagel/jellyseerr#258]
### Description

I cannot connect to my Radarr, logs about it are non-existent, all I know is `Failed to connect to Radarr`.

### Version

c1424634fb070503e4c0d0e4f6bf1c1f57bb32be

### Steps to Reproduce

1. Add a Radarr instance from a Docker container
2. Add Radarr API key
3. Test
4. Fail

### Screenshots

`Failed to connect to Radarr`

### Logs

There are no relevant logs

### Platform

desktop

### Device

Server

### Operating System

Debian 11

### Browser

Firefox

### Additional Context

Radarr 4.2.4.6635 (Docker image by linuxserver.io) on the same machine, in the same Docker network.

Jellyseerr can talk to the Radarr container:
```sh
docker exec -it jellyseerr wget http://radarr:7878
```
creates `index.html` in the `jellyseerr` container with the login webpage.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

Edit: Added additional context

**Comment by Fallenbagel** [comment]
Which version is radarr? How are you connecting to it? Same machine? Are they in the same docker network?

**Comment by schklom** [comment]
Radarr 4.2.4.6635 (Docker image by linuxserver.io) on the same machine, in the same Docker network.

Jellyseerr can talk to the Radarr container:
```sh
wget http://radarr:7878
```
creates `index.html` with the login webpage.

**Comment by Fallenbagel** [comment]
> Radarr 4.2.4.6635 (Docker image by linuxserver.io) on the same machine, in the same Docker network.
> 
> Jellyseerr can talk to the Radarr container:
> ```sh
> docker exec -it jellyseerr wget http://radarr:7878
> ```
> creates `index.html` with the login webpage.

Hmm could you provide me a screenshot of the service page from jellyseerr?

**Comment by schklom** [comment]
The container name of `radarr` is actually `vpn` (I used `radarr` before for clarity), but what I wrote before stands: it can be reached by `jellyseerr`, they are on the same Docker network, on the same machine, and `jellyseerr` can download the login page with `wget`.

![Screenshot_20221119_192729](https://user-images.githubusercontent.com/23263086/202866221-60439f57-fca5-410c-a7fe-40d21a29092c.png)

**Comment by Fallenbagel** [comment]
> The container name of `radarr` is actually `vpn` (I used `radarr` before for clarity), but what I wrote before stands: it can be reached by `jellyseerr`, they are on the same Docker network, on the same machine, and `jellyseerr` can download the login page with `wget`.

Could you try with the machine ip, see it that works or not 🤔

**Comment by schklom** [comment]
> Could you try with the machine ip, see it that works or not

No luck :/
Gotify does not work either, even when called with a Webhook. When triggering a request, my reverse-proxy never sees a request.

No requests are received either when I put Radarr behind a reverse-proxy. This is really strange, considering that it used to work in May when I first used it.

**Comment by schklom** [comment]
@Fallenbagel I recreated the Jellyseerr container from scratch, and the integrations with Gotify, Radarr, etc are working now. I will keep that version and delete the previous one.

I have no idea what happened, maybe you introduced a breaking change? Anyway, I don't care anymore, it is working :)

Sorry for the bother and thanks, I appreciate devs who are there to help! :+1:

**Comment by Fallenbagel** [comment]
> I have no idea what happened, maybe you introduced a breaking change? 

Unlikely because I've been using the same version since I started on alpha 🤔 and i don't recall seeing a big change in that part of the logic through any of the upstream commits.

We may never know what went wrong but glad you got it working now! 🥳
