### ISSUE TITLE
Media not marked as available despite existing on server and displayed "Play on Jellyfin" button.

### ISSUE THREAD

**Issue by cichy45** [Fallenbagel/jellyseerr#260]
### Description

Hello Jellyseerr Team. 

I have just setup Jellyseerr via docker and all went smooth. However I spotted one issue. After manually requesting full library scan, some media that I own are displayed as "Available" with "Play on Jellyfin" button and without the button to request them. 

Some media however are not displayed as available, despite existing on server. Jellyseerr displays "Play on Jellyfin" button and it works correctly however there is also button to request the title. 
Search result:
![image](https://user-images.githubusercontent.com/86913474/204142203-c1b38931-2967-4225-9bc4-ca16bf2b7e8b.png)
Play/request button:
![image](https://user-images.githubusercontent.com/86913474/204142246-6b2b8fbd-2090-4389-be8a-9832cbd61d02.png)

I can mark the movie/series as available but I would need to check for all my media how it is displayed on Jellyseerr.

### Version

1.2.1

### Steps to Reproduce

1. Connect Jellyseerr with Jellyfin
2. Do full manual library scan.
3. Check if some movies/series are not reported as available but can be played & requested at the same time.

### Logs

```shell
2022-11-27T15:05:00.707Z [debug][Jellyfin Sync]: Updating existing title: Elfen Lied
2022-11-27T15:00:00.782Z [debug][Jellyfin Sync]: Updating existing title: Elfen Lied
2022-11-27T14:55:00.354Z [debug][Jellyfin Sync]: Updating existing title: Elfen Lied
```

### Platform

desktop

### Device

Windows PC

### Operating System

Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you see if you turn on sonarr/radarr scan in services and running that scan it works or not?

**Comment by cichy45** [comment]
@Fallenbagel I will do that, I just have to install Sonarr first.

**Comment by rykzon** [comment]
I just had that issue aswell with just my 4k Sonarr instance. I noticed my service connection didn't have "enable Scan" set for sonarr4k which fixed it after running a sonarr scan. So show availability in the jellyseerr GUI seems to be linked to sonarr/radarr scans?

**Comment by Fallenbagel** [comment]
> I just had that issue aswell with just my 4k Sonarr instance. I noticed my service connection didn't have "enable Scan" set for sonarr4k which fixed it after running a sonarr scan. So show availability in the jellyseerr GUI seems to be linked to sonarr/radarr scans?

No its linked to jellyfin. It will also show availability with *arr. The reason why it wasn't showing availability with jellyfin is because of missing ids in your metadata that was produced by the jellyfin

**Comment by thorkseng** [comment]
Hello all,

I am having the same issue now (with the last version). I am running sonarr/radarr/jellyfin/jellyseerr.
I request the series, download it, but it does not appears correctly as downloaded on the jellyseer. 
I begin to happens around week ago with the series, but I didn't happen me in the last few months.

For example: Mandalorian, The man in the high castle, attack on titan, but for example "Foundation" was downloaded weeks ago, is correctly set as "Partially Available":
![image](https://user-images.githubusercontent.com/37229415/224477807-438e4400-db75-4c35-b9ff-d94beec889e0.png)

Checking in the logs of the jellyseerr I found that it knows that the series are there:
![image](https://user-images.githubusercontent.com/37229415/224477874-61739f52-c499-47a8-a9b0-ddd06cbc3fae.png)

Let me know anything where to look into, or provide more logs.

Thanks in advance.

**Comment by thorkseng** [comment]
Updated on my case: I checked that the sonarr and radarr was disable the scan. 
I enabled it, and now are in the "Recently added" tab the series, but it does not know that are available on jellyfin and there is no the typical link to "plan on jellyfin". I am checking the logs on jellyfin and jellyseerr to undesrtand why it does not getting that data. In the case of Mandalorian it works few months ago with the old seasons, but now it's not working with the new one.

**Comment by Fallenbagel** [comment]
> Updated on my case: I checked that the sonarr and radarr was disable the scan. 
> I enabled it, and now are in the "Recently added" tab the series, but it does not know that are available on jellyfin and there is no the typical link to "plan on jellyfin". I am checking the logs on jellyfin and jellyseerr to undesrtand why it does not getting that data. In the case of Mandalorian it works few months ago with the old seasons, but now it's not working with the new one.

Sounds like a tmdb id missing issue. Try moving the affected stuff out of directory, and delete any nfos or anything and move back and replace metadata

**Comment by thorkseng** [comment]
I was checking on the jellyfin and the metadata is there. Also, I don't have any nfo on the same folders.
Every Show is in a independent folder, with an strict order {Serie name - YEAR}/{name - SXXEXX - Title}. And I don't see any nfo on the folders of the shows.

I am not sure how to do of the cleaning of the metadata on jellyfin, any advice? On my way, I went to jellyfin > series > refresh metada > refresh all metada. It finished correctly, refreshing all the metadata on jellyfin database, but I force library sync in jellyseer and it seems not working.

Thanks in advance.

**Comment by Fallenbagel** [comment]
From my testings it works when you move the stuff out of the library folder, let jellyfin delete the media then move back in

**Comment by thorkseng** [comment]
Let me know if I did it correctly, it doesn't work this steps:
1. I move the folder of "The mandalorian" to /tmp/The Mandalorian".
2. I go to jellyfin and enable scan library. The show disappear from the library.
3. I go the jellyseer and sync libraries, scan libraries and (not necessary I think) I run all the jobs for syncing.
4. I move to the show from /tmp to the shows data folder again.
5. In jellyfin I sync the library, wait for it: the show again appears correctly.
6. In jellyseerr I sync the libraries, (I did the same that step 3).

I miss something? I did not see any special in the logs, errors or something like that. Also, I got the push notification that there are new episodes from the show that I moved out and move in.

 I am not sure if could be a bug (because this happens only in the new requests, but not in the last month requests) or a missing configuration from mi side :)

Thanks a lot for your patience.

**Comment by thorkseng** [comment]
Also, I will add some information of the stack:
- Jellyfin in docker of linuxserver.io (running as user). Stable. 1.8.9.
- Jellyseerr in docker. Stable release. 1.4.1.
- Sonarr in docker from linuxserver.io, version 3.0.10.1566
- Radarr in docker from linuxserver.io, version 4.3.2.6857

In the same stack I also have qbittorent, prowlarr and swag. And I use watchtower to update the images.

**Comment by Fallenbagel** [comment]
Did you clear series from jellyseerr itself? What's the issue exactly? (Also might not be a bug since I'm not able to recreate it and a lot of others too)

**Comment by thorkseng** [comment]
I am sorry, but I don't know how to clear the series from jellyseer?

The issue that I am having is that the button "play on jellyfin" does not appears on this series. The three are downloaded on this month with the new release, all the previous ones has the button that link directly with jellyfin. The mandalorian has the button, but I deleted the old seasons and when it begins to download the season three has the same issue, next screenshot to check (I have the two episodes but it doesn't show the button that link directly with jellyfin:
![image](https://user-images.githubusercontent.com/37229415/224506794-23a0ab38-05dc-44c0-949f-a3aea750267e.png)

**Comment by thorkseng** [comment]
It works! I found the clear button on the left button, and resync all the libraries and the series now has the direct link to jellyfinl
It's ok, but, I don't understand why it happens only with the new series. At least it working fine 👍 

Thanks a million!

**Comment by Fallenbagel** [comment]
> It's ok, but, I don't understand why it happens only with the new series. At least it working fine 👍 

Like I said earlier, what happened was the tmdbID was missing in your jellyfin metadata. That's why jellyseerr was unable to find it as jellyseerr uses tmdb as a database and matches with the id given by jellyfin with jellyseerrs own database.

The reason why it still showed as partially available was because it matched with sonarr sync. But due to the missing tmdb id, it didn't match with jellyfin sync. Once you refreshed the metadata it fixed and grabbed the tmdb ID so jellyseerr was able to match

**Comment by thorkseng** [comment]
Thanks a lot for the explanation. Also, if it happens in the future and is any way to get a detailed logs to know what is happening I will be happy to share with you.

Thanks a lot!

**Comment by Fallenbagel** [comment]
> Thanks a lot for the explanation. Also, if it happens in the future and is any way to get a detailed logs to know what is happening I will be happy to share with you.

As long as you have the logs in debug level, just run a jellyfin full scan(on jellyseerr) and the logs should show a tmdb id error which would be helpful to narrow down the issue c:

**Comment by thorkseng** [comment]
Sorry to ask this, but how I setup the logs in debug mode? I checked in the tab of logs and there is no errors. I don't find anything in the documentation/readme of the github repository.

Also, I tried to download a film, and it works perfectly (it sync and show the button), so I think someone was incorrect with this three series/films that were missing, but it seems don't happen anymore.

Really appreciate all your effort on great piece of software :)

**Comment by Fallenbagel** [comment]
> Sorry to ask this, but how I setup the logs in debug mode? I checked in the tab of logs and there is no errors. I don't find anything in the documentation/readme of the github repository.

It's the `DEBUG_LEVEL` in dockercompose environment c:

**Comment by thorkseng** [comment]
> > Sorry to ask this, but how I setup the logs in debug mode? I checked in the tab of logs and there is no errors. I don't find anything in the documentation/readme of the github repository.
> 
> It's the `LOG_LEVEL` in dockercompose environment c:

Ok, next time it happens I will set the log_level to debug and read the logs.

Thanks a million!

**Comment by Fallenbagel** [comment]
I am going to close this as I assume its working since there has been no further clarification.
