### ISSUE TITLE
"Retry" in Requests screen does nothing

### ISSUE THREAD

**Issue by teun95** [Fallenbagel/jellyseerr#261]
### Description

When a different user has requested an item, but the request failed, the admin or a user with permission to manage requests can _Retry_ or _Delete Request_

Choosing _Retry_ does nothing, it also doesn't show up in the log. Same case in Android Firefox and Desktop Firefox. Deleting the request and adding it again leads to a succesful request. 

### Version

1.2.1

### Steps to Reproduce

1. Create request under conditions that make it fail
2. Navigate to to the Requests management interface
3. Click the purple retry button

### Screenshots

![image](https://user-images.githubusercontent.com/37039643/204897483-fdfe096b-799b-4572-ae1f-2969eed6b7f4.png)

### Platform

desktop

### Device

Desktop PC (client)

### Operating System

Windows 10

### Browser

Firefox 1067.0 (64-bit)

### Additional Context

```
user@user:~$ docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
user@user:~$ docker compose version
Docker Compose version v2.12.2
```

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Is this still an issue?
