### ISSUE TITLE
Remove mandatory email for jellyseer admin account

### ISSUE THREAD

**Issue by IVIbox** [Fallenbagel/jellyseerr#265]
### Description

Possiblity of removing email in favor of only user name for jellyseer admin account. It serves no real purpose other than user name. I tried to see if there's a reset password option when selecting log in with jellyseerr account but there isn't. So not sure whats the point, besides always prefer less info if needed even for open source internal services

### Desired Behavior

Removal of email requirements or at least the choice between only username, email or both.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
It's essential for smtp too. You can also put I anything you want in there really (there is no validation)

**Comment by Fallenbagel** [comment]
> I do have 1 other feature request, should i submit ilon this thread or open a new one?

Open new one so it's easier to track c:

**Comment by beechfuzz** [comment]
I agree with this -- remove the email address requirement.  If SMTP options are enabled, then users without email addresses simply won't receive emails.

Better yet, add a field called "username" and allow us to login with that instead.  Logging in with an email address simply makes no sense, and you're placing the burden on the users to come up with work-arounds.

**Comment by Fallenbagel** [comment]
> Better yet, add a field called "username" and allow us to login with that instead.  Logging in with an email address simply makes no sense, and you're placing the burden on the users to come up with work-arounds.

Thing is, there is no validation for it. And local login utilises that. You can write bogus in it and it will still accept. And upstream is very adamant in keeping it because it could break somethings 🤔
