### ISSUE TITLE
Search IMDB

### ISSUE THREAD

**Issue by Zeusy123** [Fallenbagel/jellyseerr#267]
### Description

Would it be possible to ad ability to search imdb?

### Desired Behavior

When searching for movie title it also search imdb as many movies not on TMDB, but are on IMDB

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Unfortunately imdb does not have an open api to scrape from so im not sure how viable this would be 🤔
