### ISSUE TITLE
Yarn Start throw a sqlite3 issue

### ISSUE THREAD

**Issue by nephaste** [Fallenbagel/jellyseerr#268]
### Description

Trying to compile in a /opt/JellySeerr Prefix with NodeJS 16.18.1

but on stat it throw an error with sqlite3

/opt/JellySeer/jellyseerr/node_modules/typeorm/driver/sqlite/SqliteDriver.js:130
            throw new DriverPackageNotInstalledError_1.DriverPackageNotInstalledError("SQLite", "sqlite3");
            ^

DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save

sqlite3 is well installed ...

![image](https://user-images.githubusercontent.com/3392684/206858573-08b5def4-fd76-47dc-b182-ff2feff08eaa.png)

### Version

git master

### Steps to Reproduce

follwoing step in install tutorial

installed yarn 1.2.19 as well into my prefix

![image](https://user-images.githubusercontent.com/3392684/206858407-53e85c2e-55aa-45e5-9cfc-a26346ac3218.png)

Yarn install

![image](https://user-images.githubusercontent.com/3392684/206858449-5d7df9c8-9a63-4af5-917a-212089784c2d.png)

yarn run build

![image](https://user-images.githubusercontent.com/3392684/206858503-ba12dbc2-6612-478b-b1a6-5d11eb1c3b8d.png)
![image](https://user-images.githubusercontent.com/3392684/206858556-d1b8a517-f975-4c86-9823-17faeb6bea96.png)

starting on my dev environment (and on target as wel) jump into this error

![image](https://user-images.githubusercontent.com/3392684/206858604-ac0fbe07-b31d-48be-9cbb-76cfbf8ad8ab.png)

### Logs

```shell
dont know how to find it
```

### Platform

desktop

### Device

none

### Operating System

Linux Ubuntu 

### Browser

none

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by nephaste** [comment]
already tried to installe " npm install sqlite3 --save" but has no impact error remain the same

**Comment by Fallenbagel** [comment]
Try on nodejs version LTS

**Comment by nephaste** [comment]
Hi Thanks... got same problem with Overseerr .. 
problem is libc on target system is 2.21 and latest bianry prodived by NodeJS are not compatble with this old libc...
I will give a try with version 17 (latest working) or build a static version for nodeJS 18

**Comment by nephaste** [comment]
seems i am unlucky NodeJs17 and NodeJS18 LTS throw the same error

![image](https://user-images.githubusercontent.com/3392684/206905232-d112ed40-e429-48d0-9951-8962bfd30ca6.png)

**Comment by nephaste** [comment]
and got an error installing sqlite3 now

![image](https://user-images.githubusercontent.com/3392684/206905364-2ce2128e-2005-4213-9ba1-1361dbb42a95.png)

**Comment by Fallenbagel** [comment]
> and got an error installing sqlite3 now
> 
> ![image](https://user-images.githubusercontent.com/3392684/206905364-2ce2128e-2005-4213-9ba1-1361dbb42a95.png)

Could you try `yarn install sqlite3 --save`

**Comment by nephaste** [comment]
seems command is yarn add sqlite3 --save (also tried without --save) same issue

![image](https://user-images.githubusercontent.com/3392684/206917467-7b3c490c-813b-4c72-8e7c-1804d923afa4.png)

![image](https://user-images.githubusercontent.com/3392684/206917492-09d80d92-92c3-46d7-b710-a820bc1a931d.png)

**Comment by Fallenbagel** [comment]
Try adding the it to global w the `-g` arg

**Comment by nephaste** [comment]
will try tomorrow... also found this

https://github.com/TryGhost/node-sqlite3/wiki/Binaries

will give a try if -g do not work

**Comment by nephaste** [comment]
![image](https://user-images.githubusercontent.com/3392684/207113394-e1fefb20-0d84-4f8b-859b-d5b38e09fe09.png)

but

![image](https://user-images.githubusercontent.com/3392684/207113553-ab9d7334-499f-411d-b1b7-afe51569dca7.png)

it is getting me mad

**Comment by Fallenbagel** [comment]
https://stackoverflow.com/questions/40461439/error-installing-sqlite3-in-node-js

^ Try one of these. There seems to be an issue with your node_modules folder. Have you tried deleting and re-running a yarn install?
Also for a hassle-free usage I recommend docker (and in the near future we will hopefully release snaps, just need it snaps to be configured)

**Comment by nephaste** [comment]
installing typeorm 0.2.5 ..error changed

![image](https://user-images.githubusercontent.com/3392684/207353380-1af1ad9b-1650-4b6f-aa7f-98be180f26e8.png)

**Comment by Fallenbagel** [comment]
> did everything, built several times... also used the nodejs 16.7.1 (used in docker)

Did you try nodejs 18

Also, which os is this? I have tried on debian, ubuntu, arch(use for test builds), nixos (running as my production) and alpine (the one used in docker)

**Comment by nephaste** [comment]
I must run on trusty 1404 ... due to libc restriction

i am trying to move on dev branch to see (was on main)

still got this typeorm warning

![image](https://user-images.githubusercontent.com/3392684/207366538-d6264cec-7ff6-4b6c-805a-e0e1dc631e3c.png)

**Comment by Fallenbagel** [comment]
Those warnings are not significant. You can safely ignore them.

Also I just tested on Ubuntu 22.04.1 LTS
![image](https://user-images.githubusercontent.com/98979876/207367069-7ad1243d-e14c-48f4-a79c-aee7658d9586.png)

**Comment by nephaste** [comment]
still no luck .. typeorm makin mess even on dev branch

![image](https://user-images.githubusercontent.com/3392684/207368580-8c30c171-fc15-4f17-8b69-d355c047a776.png)

**Comment by Fallenbagel** [comment]
> still no luck .. typeorm makin mess even on dev branch
> 
> ![image](https://user-images.githubusercontent.com/3392684/207368580-8c30c171-fc15-4f17-8b69-d355c047a776.png)
> 

Would snap builds work for you? We gonna release snap builds soon

**Comment by nephaste** [comment]
tried ubuntu 2204 same script... seems to work (thats crazy) ... will see if cross toolchain worked exporting on NAS target

![image](https://user-images.githubusercontent.com/3392684/207375794-c0dc31c9-2ecc-45bb-b9f5-96ca76fec95f.png)

**Comment by nephaste** [comment]
On target, it goes back with same previous error  ... somethin i am missing, not logical

![image](https://user-images.githubusercontent.com/3392684/207383476-cb48edb6-291f-4259-ab8b-b6803cb3581b.png)

**Comment by Fallenbagel** [comment]
> On target, it goes back with same previous error  ... somethin i am missing, not logical
> 
> ![image](https://user-images.githubusercontent.com/3392684/207383476-cb48edb6-291f-4259-ab8b-b6803cb3581b.png)
> 

Seems to be related to ubuntu 14.04. The only way I could think of is dockerised or snap builds

**Comment by nephaste** [comment]
this is my host target (Qnap NAS) not ubuntu 1404, exported compilation in the package

i exported the CC , CXX, etc... for a cross compilation with my toolchain in my script build , but it doesnt take effect ...

export CXX=${HOST}-g++   
export LD=${HOST}-ld                   
export AS=${HOST}-as                   
export AR=${HOST}-ar                   
export CC=${HOST}-gcc 

do you know if i can crossompile with Yarn (npm) i dont find infromation on this ?

**Comment by Fallenbagel** [comment]
> do you know if i can crossompile with Yarn (npm) i dont find infromation on this ?

I found this but its to cross-compile to arm. Might be able to adapt?
https://chrislea.com/2018/08/20/cross-compiling-node-js-for-arm-on-ubuntu/

**Comment by nephaste** [comment]
thanks, but seems to cross compile nodejs it self and a nodejs application with his modules...
will check if i can use my MUSL framwork to build it under an Alpine OS

**Comment by nephaste** [comment]
Finally able to start with Alpine ELF but crash ... I am definitively unlucky

![image](https://user-images.githubusercontent.com/3392684/208685416-791cb714-79be-45bb-9baa-07b5718c3e20.png)

**Comment by Fallenbagel** [comment]
> Finally able to start with Alpine ELF but crash ... I am definitively unlucky
> 
> ![image](https://user-images.githubusercontent.com/3392684/208685416-791cb714-79be-45bb-9baa-07b5718c3e20.png)

Which node version is this?

**Comment by nephaste** [comment]
Hi Finally, fixed this issue by cross compiling correctly sqlite3

basically here are instruction done, where ${HOST} is my toolchain 

export npm_config_build_from_source=true

export CC=${HOST}-cc
export CXX=${HOST}-g++


CYPRESS_INSTALL_BINARY=0 CC=${HOST}-cc CXX=${HOST}-g++ npm_config_build_from_source=true npm_config_build_from_source=sqlite3 ../bin/yarn install --frozen-lockfile --network-timeout 1000000  ;
CC=${HOST}-cc CXX=${HOST}-g++ npm_config_build_from_source=true npm_config_build_from_source=sqlite3 ../bin/yarn run build ;
