### ISSUE TITLE
Anime search does only find anime by japanese title

### ISSUE THREAD

**Issue by gianklug** [Fallenbagel/jellyseerr#279]
### Description

If I for example search for "One Piece", I don't find the actual anime. When searching for the original title "ワンピース", the anime actually shows and is also titled "One Piece" in the UI. 

This is suboptimal for end users as they don't know they have to search for the original title and assume it's just not available.

### Version

1.2.1

### Steps to Reproduce

1. Search for anime in english title
2. Notice it isn't there
3. Search for original japanese title
4. Tada, it's there

### Screenshots

![image](https://user-images.githubusercontent.com/51193103/208321737-f0b2a313-dd76-49b2-878d-50d2c781468c.png)
![image](https://user-images.githubusercontent.com/51193103/208321746-aba3ffa3-d33f-41ed-90a5-ed55bdd8f2c2.png)

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
![Screenshot_20221219_044121_Chrome Dev](https://user-images.githubusercontent.com/98979876/208325632-f33bf160-5b98-414a-bec0-de16b3309dc6.jpg)

It is there.

**Comment by emailkanji** [comment]
I think you missed it because the title image was different than what you expected. One piece is an option on your search for "one piece". It's the first option on the second row.

**Comment by gianklug** [comment]
afaik one piece wasn't the only issue and there were some that I simply could not find. I'll search for another example.

**Comment by Fallenbagel** [comment]
> afaik one piece wasn't the only issue and there were some that I simply could not find. I'll search for another example.

Could you provide another example? Because so far everything I searched is found. And if you can't find its probably because its in English name and not romanji. 

Jellyseerr/overseerr uses tmdb so the title depends on what it is named in tmdb.

**Comment by Fallenbagel** [comment]
I will be closing this issue as no further information was provided and since then there has been a lot of fixes in regards to how the search functionality works.
