### ISSUE TITLE
Emby support

### ISSUE THREAD

**Issue by dbroome1978** [Fallenbagel/jellyseerr#28]
Would it be possible to add Emby support or has the user management portions veered to far away?

**Comment by Fallenbagel** [comment]
I'm not entirely familiar with emby, or emby's implementation of api or whether it'd work with emby the way jellyfin works, as in jellyfin's case jellyseerr logs into jellyfin as if it's a client device.

**Comment by Fallenbagel** [comment]
> Would it be possible to add Emby support or has the user management portions veered to far away?

Emby is supported! Emby works with the current implementation of jellyseerr, just use the emby ip address instead of jellyfin when setting up c:
