### ISSUE TITLE
Unable to sign in with Nginx reverse proxy in place

### ISSUE THREAD

**Issue by MartijnLangohr** [Fallenbagel/jellyseerr#281]
### Description

When accessing Jellyseerr though my Nginx reverse proxy, I'm unable to sign in. After filling in my credentials and clicking 'Sign in', it just stays on the login page and doesn't seem to go any further. 
I've set up my Nginx reverse proxy config as described in [this comment](https://github.com/sct/overseerr/issues/274#issuecomment-1279709298), I've only replaced all /overseerr paths with /jellyseerr.

My credentials are fine as I'm able to sign in when accessing Jellyseerr without the reverse proxy in place.

### Version

1.2.1

### Steps to Reproduce

1. Access Jellyseerr over reverse proxy (using the Application URL)
2. Filling in my Jellyfin credentials
3. Clicking 'sign in'

### Platform

desktop

### Device

none

### Operating System

Ubuntu 20.04

### Browser

Edge Chromium

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
If you have discord could you look through this?
Just today someone set up subfolder for jellyseerr 

https://discord.com/channels/952656177924300932/1054270739437588480

**Comment by MartijnLangohr** [comment]
I have Discord but the link you shared is not working for me:
![image](https://user-images.githubusercontent.com/46994663/208979049-90df01ad-9eb5-4090-b53d-daaf2d068657.png)

**Comment by Fallenbagel** [comment]
> I have Discord but the link you shared is not working for me:

Could you check the #support thread pinned one?

**Comment by MartijnLangohr** [comment]
Yep found the thread, thanks! Got the reverse proxy working :)
I can't get profile pictures to work tho. I saw OP in Discord had that problem as well but setting the external Jellyfin URL and logging out and back in isn't working for me.. Keep getting 404 errors on the profile picture. Any idea what's causing this?

**Comment by Fallenbagel** [comment]
> Yep found the thread, thanks! Got the reverse proxy working :)
> I can't get profile pictures to work tho. I saw OP in Discord had that problem as well but setting the external Jellyfin URL and logging out and back in isn't working for me.. Keep getting 404 errors on the profile picture. Any idea what's causing this?

Could you right click on the avatar and press inspect and check the link? What link it uses

**Comment by MartijnLangohr** [comment]
> > Yep found the thread, thanks! Got the reverse proxy working :)
> > I can't get profile pictures to work tho. I saw OP in Discord had that problem as well but setting the external Jellyfin URL and logging out and back in isn't working for me.. Keep getting 404 errors on the profile picture. Any idea what's causing this?
> 
> Could you right click on the avatar and press inspect and check the link? What link it uses

It's trying to do a GET request on  `https://my.proxy.server.com/os_logo_square.png`, not sure if that's expected or not.

**Comment by Fallenbagel** [comment]
> It's trying to do a GET request on  `https://my.proxy.server.com/os_logo_square.png`, not sure if that's expected or not. 

Not the network request. Could you check the avatar png link. Also send me a screenshot how the avatar looks like

**Comment by MartijnLangohr** [comment]
> > It's trying to do a GET request on  `https://my.proxy.server.com/os_logo_square.png`, not sure if that's expected or not.
> 
> Not the network request. Could you check the avatar png link. Also send me a screenshot how the avatar looks like

It uses the same link as in the network request: `https://my.proxy.server.com/os_logo_square.png`. 
Screenshot of the avatar:

![image](https://user-images.githubusercontent.com/46994663/209474423-3cc3069a-b72a-4e38-9408-34b9fb4c1967.png)

**Comment by Fallenbagel** [comment]
> It uses the same link as in the network request: `https://my.proxy.server.com/os_logo_square.png`. 
> Screenshot of the avatar:
> 
> ![image](https://user-images.githubusercontent.com/46994663/209474423-3cc3069a-b72a-4e38-9408-34b9fb4c1967.png)

Hmm that's strange behaviour. Thats not related to jellyfin either since `os_logo_square.png` is the jellyseerr logo that is the default for accounts without any jellyfin avatars.

How are you running this? Natively or through container? Either that image is missing from your build or your reverse proxy is not proxying the image. 

Does the avatar appear when you access locally?

**Comment by MartijnLangohr** [comment]
> How are you running this? Natively or through container? Either that image is missing from your build or your reverse proxy is not proxying the image.
> 
> Does the avatar appear when you access locally? And also do you have an avatar set in jellyfin itself?
> 
As you already assumed, my reverse proxy wasn't proxying the image. Adding `sub_filter '/os_logo_' '/$app/os_logo_';` to the sites config did the trick and the avatars are working fine now. 

I noticed that there was a sub_filter for the site logo so that does get proxied, but the avatar did not as it doesn't start with 'logo_'.

**Comment by RogueGhost93** [comment]
I made a discord account to get access to the thread mentioned in this issue but it didnt work out, cant access it on discord.
Any chance someone can post the solution here? 
Im constantly getting error as incorrect password on jellyfin even though its not incorrect, it is probably because of traefik but i cant seem to resolve it. Thanks

**Comment by Fallenbagel** [comment]
> I made a discord account to get access to the thread mentioned in this issue but it didnt work out, cant access it on discord.
> Any chance someone can post the solution here? 
> Im constantly getting error as incorrect password on jellyfin even though its not incorrect, it is probably because of traefik but i cant seem to resolve it. Thanks 

Are you the one who posted a support thread on discord recently about traefik but using subdomains? If not hop onto discord and ill help out and show you the thread. 

This issue is specifically for subfolder not subdomain (if you're the one who created about traefik subdomain)

**Comment by Fallenbagel** [comment]
> Yes that is me. I managed to get access again but only temporarily and the reason could be because i temporarily switched from traefik to direct access thrlugh http://jellyfin:8096, now i cant log in again. I had access on three different browsers at the same time and lost it at the same time, firefox, chromium, vanadium(android) and they are all gone so i dont think it is related to cookies or browser cache...
> Still works if i bypass traefik and change the hostname to http://jellyfin:8096....

Wait you can't access jellyfin over browser?

**Comment by RogueGhost93** [comment]
> 

I can access jellyfin just fine... The poblem is i cant access it from jellyseerr through browser usin my domain name, if im using http://jellyfin:8096 it works just fine, if using jellyfin.domain.com then it hangs forever and logs show incorrect password. Setting for reverse proxy in jellyseerr is checked.

**Comment by Fallenbagel** [comment]
> > 
> 
> I can access jellyfin just fine... The poblem is i cant access it from jellyseerr through browser usin my domain name, if im using http://jellyfin:8096 it works just fine, if using jellyfin.domain.com then it hangs forever and logs show incorrect password. Setting for reverse proxy in jellyseerr is checked.

Why use jellyfin.domain.com? If same machine for api connections do http

**Comment by RogueGhost93** [comment]
Yes that is one of the possible solutions, however, every other app can use the traefik link except jellyseerr. It is much more conveniet to use same approach in all apps imo. Also if using reverse proxy
- ports:
   - 5055:5055
section can be removed in all containers respectively, i havent tried yet but i do believe that if that section is removed you actually can not access any of your containers through their local port, the only possible access is through traefik, im not 99.99% on this, still new to traefik etc but so far from what ive seen anyone using traefik just removes ports section completely. Mines are still present as im making a lot of changes atm so its easir to have local ports accessable for debugging like in this jellyseerr example, but in my final setup the goal is to have access only through traefik and have services open to some friends(public).

If there is no solution to this it is fine, i will make it work in some roundabout way, however this way of connecting jellyseerr to jellyfin should be working.
