### ISSUE TITLE
[Feature Request] Show Download Progression When Media is Processing

### ISSUE THREAD

**Issue by callbacked** [Fallenbagel/jellyseerr#286]
### Description

Hello, it has been great so far using Jellyseer, my friends love it! I just had an idea for a feature request.

In the requests tab, for any media that is being processed there should be a way to see download progression.

Since you can see the download progression in Radarr/Sonarr under activity > queue, maybe that could be used for integration in jellyseer?

For instance see the api docs for Radarr about [QueueDetails](https://radarr.video/docs/api/#/QueueDetails/get_api_v3_queue_details).

Scrolling towards the end under the media type you see this:

````
......
"size": 0,
    "title": "string",
    "sizeleft": 0,
    "timeleft": {
      "ticks": 0,
      "days": 0,
      "hours": 0,
      "milliseconds": 0,
      "minutes": 0,
      "seconds": 0,
      "totalDays": 0,
      "totalHours": 0,
      "totalMilliseconds": 0,
      "totalMinutes": 0,
      "totalSeconds": 0
    },
    "estimatedCompletionTime": "2023-01-02T14:14:47.114Z",
    "status": "string",
    "trackedDownloadStatus": "ok",
    "trackedDownloadState": "downloading",
    "statusMessages": [
      {
        "title": "string",
        "messages": [
          "string"
        ]
      }
.....
````
Perhaps something could be made of this to replace the spinning wheel next to "Processing" in the requests tab.

 Thank you for reading this, I am grateful for your efforts in making our lives easier in terms of managing requests!

**Comment by Fallenbagel** [comment]
This is already a feature though.
Currently you can see the download progress if you press the settings of an already processing item as shown below

![direct.png](https://user-images.githubusercontent.com/98979876/210237072-65db06c6-743d-470f-a91e-10ca862e943d.png)

**Comment by callbacked** [comment]
I am a fool, my apologies!

**Comment by ahhmino** [comment]
I know this is a closed issue, but can I get clarification on where this download status is? I'm checking the settings panel of an item during download, but I don't see this progress bar

**Comment by Fallenbagel** [comment]
You need to enable scan on the *arr services. Then only will you see the progress. Because the progress is synced from the *arr

**Comment by ipkpjersi** [comment]
I have enable scan already enabled, I'm on the latest Jellyseerr Stable 2.5.2, and yet I don't see progress:
![](https://i.imgur.com/MblOOvf.png)

Not sure what I'm doing wrong.

**Comment by fallenbagel** [comment]
> I have enable scan already enabled for Radarr, I'm on the latest Jellyseerr Stable 2.5.2, and yet I don't see progress:
> ![](https://i.imgur.com/MblOOvf.png)
> 
> Not sure what I'm doing wrong.

Hover over the badge or press the cog wheel on a media that has activity in radarr activity tab. If you're still not sure please hop onto discord for support and I can help out.
