### ISSUE TITLE
Discover language doesn't work properly

### ISSUE THREAD

**Issue by jdewoody71** [Fallenbagel/jellyseerr#293]
### Description

When setting Discover Language to English, it still shows series & films from other languages

### Version

1.3.0

### Steps to Reproduce

Settings | General | Discover Language | English. 

### Screenshots

![Screenshot from 2023-01-05 07-40-33](https://user-images.githubusercontent.com/31523590/210793356-61148e25-043a-4b57-8a64-ee22861f1743.png)
![Screenshot from 2023-01-05 07-41-15](https://user-images.githubusercontent.com/31523590/210793544-01ee37b4-f1f6-4804-9344-ed8543fbb179.png)
![Screenshot from 2023-01-05 07-41-46](https://user-images.githubusercontent.com/31523590/210793706-3a47fd84-a6bb-48fc-9617-e6b198b742fa.png)

### Platform

desktop

### Device

Any

### Operating System

Any

### Browser

Any

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by jdewoody71** [comment]
Checking in to see if this is getting any traction. Thanks.

**Comment by Fallenbagel** [comment]
Wb if you set discover country

**Comment by jdewoody71** [comment]
It is already set as well
![image](https://github.com/Fallenbagel/jellyseerr/assets/31523590/01b8222e-997f-470a-a7c4-d86b61eb7c4d)

**Comment by mjtbrady** [comment]
I too am seeing this.  With Discovery Language set to English I get search results for what looks like any language.

To qualify this a bit more:
- When I first login, everything displayed on the "home screen" looks to be in English.  
- When selecting Movies or Series from the navigation bar on the left everything displayed on those screens also look to be in English.
- When entering text into the search bar, the Search Results are not all English.  They seem to be in any language.

I am running Jellyseerr 1.5.0 on Docker CE (on OpenMediaVault 6).

**Comment by Fallenbagel** [comment]
That setting does exactly what it's said "discover language" as in change the language for the discover page not search. That's why

**Comment by mjtbrady** [comment]
Thanks for the explanation. I obviously did not understand that there was a distinction between Discovery and Search.

Obvious next question.  How then do I filter on the language when doing a search?

**Comment by Fallenbagel** [comment]
> Obvious next question. How then do I filter on the language when doing a search?

Filters on search is pretty limited as of now. In a way not there even because the only "filters" are like adding year `Batman:2022` or `imdb:xxxxx` or `tmdb:xxxxx`

**Comment by mjtbrady** [comment]
Ok.  Thanks for your help.

**Comment by developerwill** [comment]
Are we ever going to have this feature? For both Discover and Search.
