### ISSUE TITLE
Does not allow Jellyfin login without password

### ISSUE THREAD

**Issue by russelg** [Fallenbagel/jellyseerr#31]
#### Description

My Jellyfin account does not have a password, neither the UI for setup or the API allow me to provide an empty password.
Furthermore, `http://jellyfin:8096/` is not a valid URL according to the setup.

#### Version

develop (:latest on docker)

#### Expected Behavior

I should be able to sign in to Jellyfin without a password. And the above URL should be valid.

#### Device

- **Platform:** Desktop
- **Device:** Macbook Pro
- **OS:** macOS
- **Browser:** Firefox 98.0.1

**Comment by Fallenbagel** [comment]
> Furthermore, `http://jellyfin:8096/` is not a valid URL according to the setup.

For the URL, jellyseerr would not be able to resolve the DNS, therefore change that to `http://localhost:8096` or `http://<ip address>:8096`

> My Jellyfin account does not have a password, neither the UI for setup or the API allow me to provide an empty password.

I have not tested without password but I will check to see if I can implement it. The current way it accesses your jellyfin, it requires a password as the field in the database cannot parse empty space (I'll look into this, however, for the time being the only workaround is to use a simple password)

**Comment by russelg** [comment]
> For the URL, jellyseerr would not be able to resolve the DNS, therefore change that to `http://localhost:8096` or `http://<ip address>:8096`

Yep, I used the host IP to allow the setup to progress, but my point is that should not be necessary. The setup can resolve my Sonarr and Radarr at `http://sonarr:8989` and `http://radarr:7878` respectively, so I see no reason why `http://jellyfin:8096` could not resolve as well...

**Comment by Fallenbagel** [comment]
> The setup can resolve my Sonarr and Radarr at `http://sonarr:8989` and `http://radarr:7878` respectively, so I see no reason why `http://jellyfin:8096` could not resolve as well...

It's the way the api was implemented. I'll see if I can figure it out dw (once we finish migrating the database which could give a big performance boost). 

Also glad you were able to progress with the setup!
