### ISSUE TITLE
Emby series is showing series Discover rather than current library

### ISSUE THREAD

**Issue by alexisspencer** [Fallenbagel/jellyseerr#317]
### Description

When i am setup for Emby, and I click on "series", its showing series to discover rather than current series library contents.
Movies works ok though

### Version

1.4.0

### Steps to Reproduce

1. Setup for Emby
2. Go to "Series" on the left hand side

### Platform

desktop

### Device

Surface Pro 3

### Operating System

Ubuntu Desktop 22.04

### Browser

Opera

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
That is the expected behavior. The newly added series/movies tab is a each media type specific discover page with advanced filtering (if you select filter)
