### ISSUE TITLE
Admin checkbox to disable "Recently Added" on Discover page

### ISSUE THREAD

**Issue by Kuuchuu** [Fallenbagel/jellyseerr#320]
### Description

I would love ability to disable the "Recently Added" section on the Discover page. I don't mind users seeing content that is available when they come across it in Jellyseerr, but sometimes I don't want to advertise all the weird shiz that gets added. Until there is a way to block users from seeing content that they shouldn't have access to (Parental Controls, for example), a way to disable "Recently Added" would help my situation.

### Desired Behavior

A checkbox on the admin settings page for the "Recently Added" section would be sufficient, in my opinion. Or maybe (or in addition to the admin settings toggle) a button on the "Manage Series" page to hide availability or hide from "Recently Added".

### Additional Context

Mock-up of checkbox for "Recently Added" next to "Hide Available Media"
![image](https://user-images.githubusercontent.com/20036947/215955033-5e60fea6-fdbe-48c0-9b0c-eb150818b860.png)

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is already a feature. You can either disable visibility of recently added using the new customise discover page (this will affect you the admin too)
![image](https://user-images.githubusercontent.com/98979876/215962564-66680b11-9e1b-4ec5-b9e3-5c04a2ee6801.png)

or if you just dont want your users to see recently added then
![image](https://user-images.githubusercontent.com/98979876/215962652-5b4974d5-72af-413a-b19c-43b6c6439527.png)
Disable that in `settings > Users` for new users and in Users page select all users and press `bulk edit` and remove `view recently added` permission.

**Comment by Kuuchuu** [comment]
Oof, thank you @Fallenbagel. Sorry I missed that, I appreciate your help & work on this project!
