### ISSUE TITLE
Warning message about volume not being configured properly

### ISSUE THREAD

**Issue by wioo** [Fallenbagel/jellyseerr#324]
### Description

This warning message appears on jellyseerr first run. Its there for whole setup stage. 

There is no problem with the volume. All files are there after setup and restarts. I can see the files in /lib/docker/volumes...  and there is empty DOCKER file which causes this warning I presume.

The message is gone after setup.

### Version

1.4.1

### Steps to Reproduce

Create new container with docker volume.

### Platform

desktop

### Device

PC

### Operating System

Linux

### Browser

Qutebrower

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
As long as you have the volumes setup correctly then you should be fine. Its just a warning that appears when using docker volumes that comes from upstream

**Comment by wioo** [comment]
Oh, I see. Thank you.
