### ISSUE TITLE
Port cant be changed on custom docker network

### ISSUE THREAD

**Issue by samdnz** [Fallenbagel/jellyseerr#326]
### Description

To change the running port when using aa custom docker network you cant use the --port argument to docker. Thus leaving no way to change the port in this situation

### Version

9 days agov1.4.1 Latest Current

### Steps to Reproduce

run on docker with a custom network

### Platform

desktop

### Device

n/a

### Operating System

docker on linux

### Browser

n/a

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samdnz** [comment]
Actually you do honor the PORT env var

**Comment by samdnz** [comment]
-e PORT=80 on your docker run will work

**Comment by Fallenbagel** [comment]
> -e PORT=80 on your docker run will work

Yes

**Comment by samdnz** [comment]
Might be worth adding that to the docker guide?

**Comment by Fallenbagel** [comment]
> Might be worth adding that to the docker guide?

True. I'll do that tonight
