### ISSUE TITLE
Telegram notification multiple users

### ISSUE THREAD

**Issue by HHUBSS** [Fallenbagel/jellyseerr#327]
### Description

I would like to request for Telegram notification to send it to multiple users. For example, add multiple users using comma in "ChatID" field.

### Desired Behavior

Telegram notification to send to multiple users. Currently it is limited to only 1 user. I want to be able to send  notification who ever requested the movie to send it to their chatID.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Youre looking at the wrong notification place. The chatid in `settings > notifications` is for you, the admin. There you put the bot token too. As for users, their notifications are handled in their profile settings > notifications whwre they add in their chatid.

**Comment by HHUBSS** [comment]
Sorry but there is no Telegram to configure in the user's profile settings. Can you teach me how, please?

![image](https://user-images.githubusercontent.com/89816305/217723660-4b7b072e-9ce6-474a-9316-d2cebad8f312.png)

**Comment by Fallenbagel** [comment]
> Sorry but there is no Telegram to configure in the user's profile settings. Did I miss something? Can you teach me how, please?
> 
> ![image](https://user-images.githubusercontent.com/89816305/217723660-4b7b072e-9ce6-474a-9316-d2cebad8f312.png)
> 

Did you enable telegram notifications in `settings > notifications > telegram` first? You'll need to enable, add your chatid, your bot token and enable the notification types you want and save. Then only would the users' telegram notification option turn up

**Comment by HHUBSS** [comment]
Yes it is enable already. However, when I check again the settings, I didn't notice that I need to input the bots username so that the telegram will be shown in users notification. 

![image](https://user-images.githubusercontent.com/89816305/217773200-6c1318d6-340e-406b-803b-bb76624972a3.png)

**Comment by Fallenbagel** [comment]
> Yes it is enable already. However, when I check again the settings, I didn't notice that I need to input the bots username so that the telegram will be shown in users notification. 
> 
> ![image](https://user-images.githubusercontent.com/89816305/217773200-6c1318d6-340e-406b-803b-bb76624972a3.png)
> 

Yeah like I mentioned before, you need to fill the admin parts out before user's notifs will unlock
