### ISSUE TITLE
Unable to update docker image from 1.3.0

### ISSUE THREAD

**Issue by Abraka** [Fallenbagel/jellyseerr#328]
### Description

Unable to update docker image from 1.3.0:

#docker pull fallenbagel/jellyseerr:latest
Trying to pull repository docker.io/fallenbagel/jellyseerr ... 
manifest for docker.io/fallenbagel/jellyseerr:latest not found

### Version

1.3.0

### Steps to Reproduce

#docker pull fallenbagel/jellyseerr:latest
Trying to pull repository docker.io/fallenbagel/jellyseerr ... 
manifest for docker.io/fallenbagel/jellyseerr:latest not found

### Platform

desktop

### Device

PC

### Operating System

linux

### Browser

chromium

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Are you able to pull from any other docker repo?

**Comment by Abraka** [comment]
# docker pull docker.io/linuxserver/radarr
Using default tag: latest
Trying to pull repository docker.io/linuxserver/radarr ... 
latest: Pulling from docker.io/linuxserver/radarr
b8d225448c24: Already exists 
665a26860e09: Already exists 
069b15fc6d38: Already exists 
d34339113334: Already exists 
4cbbbf1047e7: Extracting [=========================================>         ] 57.93 MB/69.82 MB
8d2e065dc8c7: Download complete

**Comment by Fallenbagel** [comment]
![Screenshot_20230210_231410_Termux](https://user-images.githubusercontent.com/98979876/218166228-26b88651-1a96-436f-bcef-6ec043a963ef.jpg)


I mentioned
> Because that sounds like a docker configuration problem

Because I had a similar problem with mine when there was a misconfiguration. I had do a `docker system reset`. Beware tho this will remove all your containers and volumes and networks. So if you got any map them to the Host machine if you plan on doing this

**Comment by Abraka** [comment]
Well, its looks like develop branch is working. So I will close this here and lets see what next update after 2-3 months do.

**Comment by Fallenbagel** [comment]
> Well, its looks like develop branch is working. So I will close this here and lets see what next update after 2-3 months do.

You could also try without the `:latest` tag see if it works for stable. Or you can append the version number too
