### ISSUE TITLE
Add support for adding to sonarr with "season folders" enabled

### ISSUE THREAD

**Issue by corylowry12** [Fallenbagel/jellyseerr#329]
### Description

When adding a series via Jellyseer, it should give the option to add with "series folder" already enabled

### Desired Behavior

Title/Description

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
![Screenshot_20230213_063533_Chrome Dev](https://user-images.githubusercontent.com/98979876/218351651-59665c70-7b29-4bfd-8740-ebde1cb9b120.jpg)

Uh wdym?

**Comment by corylowry12** [comment]
My apologies, I just hadn't seen that option.
