### ISSUE TITLE
Plex logon during setup doesn't do anything

### ISSUE THREAD

**Issue by jazzgott** [Fallenbagel/jellyseerr#33]
#### Description

As in the title. I have successfully logged on to plex, but that did not push the setup forward.

#### Version

develop-

#### Steps to Reproduce

1. fresh install
2. open UI
3. setup starts, log on with plex
4. that's it, nothing happens.

#### Expected Behavior

I was expecting to be logged on using plex creds.

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- Windows 11 PC
- Firefox and Edge

**Comment by jazzgott** [comment]
> Which docker image tag were you using?

latest

**Comment by Fallenbagel** [comment]
This has been fixed in `develop` tag.
