### ISSUE TITLE
[Feature Request] Play media on Jellyfin Media Player

### ISSUE THREAD

**Issue by Tusker1922** [Fallenbagel/jellyseerr#331]
### Description

I prefer using the Jellyfin Media Player but find it inconvenient when clicking on 'Play on Jellyfin' automatically opens the Web-GUI.

### Desired Behavior

A new option could be added on the drop-down menu, where the user could choose to play media on the Jellyfin Media Player rather than the current Web-GUI default.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I'm not sure if this is possible, however, I'll try to take a look

**Comment by gauthier-th** [comment]
Using custom URL protocol to open the Jellyfin Media Player is not possible.
