### ISSUE TITLE
Failed to process Jellyfin item

### ISSUE THREAD

**Issue by Virtuo1** [Fallenbagel/jellyseerr#342]
### Description

This is happening to specifically two shows out of my library. There is no noticeable error when viewing the page of respective show, other than the fact that I feel like it is slowing down the whole application.

### Version

1.4.1

### Steps to Reproduce

I'm not sure how it came to be in the first place but it happens everytime the 'Jellyfin Recently Added Scan' task runs.

### Logs

```shell
2023-03-07T20:00:09.382Z [error][Jellyfin Sync]: Failed to process Jellyfin item. Id: 33d91d84fbafeae3909f24c3d0dcc9ed{"errorMessage":"Invalid auth token","jellyfinitem":{"AirDays":[],"BackdropImageTags":["ff961c1f403db101064685a7df3bd91a"],"ChannelId":null,"ChildCount":40,"CommunityRating":8.169,"EndDate":"2014-03-31T00:00:00.0000000Z","Id":"33d91d84fbafeae3909f24c3d0dcc9ed","ImageBlurHashes":{"Backdrop":{"ff961c1f403db101064685a7df3bd91a":"W~Jt;jodbdxubcof~os.bdt6f,oz--s.WsjsofogxUoIa~fiazt7"},"Primary":{"ec2c6e9d557820de046efd5584206c6a":"d:KB{zxuo#xu%~t7ofkC0gRkW9R*W-WBWBWU%IoeWFjs"}},"ImageTags":{"Logo":"a6728d10a10665df0214acdd75e01d66","Primary":"ec2c6e9d557820de046efd5584206c6a"},"IsFolder":true,"LocationType":"FileSystem","Name":"How I Met Your Mother","OfficialRating":"TV-14","PremiereDate":"2005-09-19T00:00:00.0000000Z","ProductionYear":2005,"RunTimeTicks":13200000000,"ServerId":"25af6c6dd7f94327a186ba0cfc4e9e96","Status":"Ended","Type":"Series","UserData":{"IsFavorite":false,"Key":"75760","PlayCount":0,"PlaybackPositionTicks":0,"Played":false,"UnplayedItemCount":207}}}
```

### Platform

desktop

### Device

Dell Computer

### Operating System

Ubuntu 20.04.5 LTS (Docker)

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
It says invalid auth token. You can refresh your auth token by logging out and back in again

**Comment by Fallenbagel** [comment]
> I get this all the time also.
> 
> ![image](https://user-images.githubusercontent.com/16105140/226362304-7e6b3639-d917-4494-a030-d5e8535d8270.png)
> 

Could you check the details of that to see if it's invalid auth token or tmdbID missing. Because they're two different issues. Both are fixable so dw it's just a misconfiguration

**Comment by Dubwize** [comment]
It's a mix of both.

`2023-03-20T14:23:42.046Z [error][Jellyfin Sync]: Failed to process Jellyfin item. Id: 0afbf5ce34a1822a1e490af228aa31d8{"errorMessage":"[TMDB] Failed to get TV show using the external TVDB ID: No show returned from API for ID 279821","jellyfinitem":{"AirDays":[],"BackdropImageTags":["2ee415ef97b16f8f361a982fe4e5e952"],"ChannelId":null,"Id":"0afbf5ce34a1822a1e490af228aa31d8","ImageBlurHashes":{"Backdrop":{"2ee415ef97b16f8f361a982fe4e5e952":"WJIyLVtLE1xdGYoa}[bq9@S%kpWS^7+uELb_r?Sb^7RiV=t8I;Ri"},"Banner":{"38807e6c17f0bdbebd108d40ec325285":"HMA,tfM{4nx]Wnt7WBIUoy_4M{D$xuj[t8j]M{fj"},"Primary":{"17aa6ad4544472ce81090295026d56c5":"d36auA?H4:EO~q-oM|Ip4n%M-;RPRkWYt7xt~qD%D%x]"}},"ImageTags":{"Banner":"38807e6c17f0bdbebd108d40ec325285","Primary":"17aa6ad4544472ce81090295026d56c5"},"IsFolder":true,"LocationType":"FileSystem","Name":"Who Needs Ibiza? The Great British Holiday","PremiereDate":"2014-03-12T00:00:00.0000000Z","ProductionYear":2014,"RunTimeTicks":0,"ServerId":"8d443b3e1658478d82c4ef79e45341ec","Status":"Continuing","Type":"Series","UserData":{"IsFavorite":false,"Key":"279821","PlayCount":0,"PlaybackPositionTicks":0,"Played":false,"UnplayedItemCount":2}}}`

`2023-03-20T14:23:34.162Z [error][Jellyfin Sync]: Failed to process Jellyfin item. Id: 6fae7a27178e7ef3551009689267b871{"errorMessage":"Invalid auth token","jellyfinitem":{"AirDays":[],"BackdropImageTags":["19882da3be0eb6cfbdb2024c89d25c6e","f9dcbc2f38c0d16b6f2788327823d4b7"],"ChannelId":null,"Id":"6fae7a27178e7ef3551009689267b871","ImageBlurHashes":{"Art":{"a683b78546d23c9dc81d896120f8a658":"NEC$x.rc9Zi|OTbb1Gn+whspnPS1%KSKIXbYN0ox"},"Backdrop":{"19882da3be0eb6cfbdb2024c89d25c6e":"W67K*Wo}s;tQIVt7?]aeIpjZRQxtD+V@M{M|t6WBrrkVnPWVozM|","f9dcbc2f38c0d16b6f2788327823d4b7":"W6ATp0}t-;-=E3-;l.AXPATdIpRjKk-Vicoz#,VY%3-:IBNdNuEL"},"Banner":{"b65e3e91411b8c4e9e91a8d932212454":"HnEyrJR*M|?aWAa{s:ofWB~pRjRQ-pWBkBoeayWB"},"Logo":{"1919b3271a5dc0f3ffbad7bf01e8c743":"OVCPU?ofRkayayoeR*IVj@oLj@j[ayj[0MWCofj[azWCoe"},"Primary":{"0516543e65dd4e73d08da4a13cdf4497":"dJC=oF^5KjpHB.Naw0spK5XmkCbv[DxGI:R+1cJTw0i{"},"Thumb":{"f24d5f1e97330f4ce925a0cfaaae28b4":"NZHxfnRQE2t6xZRk%Kafoeofj[oe0Mt6%LRkfPWC"}},"ImageTags":{"Art":"a683b78546d23c9dc81d896120f8a658","Banner":"b65e3e91411b8c4e9e91a8d932212454","Logo":"1919b3271a5dc0f3ffbad7bf01e8c743","Primary":"0516543e65dd4e73d08da4a13cdf4497","Thumb":"f24d5f1e97330f4ce925a0cfaaae28b4"},"IsFolder":true,"LocationType":"FileSystem","Name":"The Walking Dead","OfficialRating":"TV-MA","PremiereDate":"2010-10-31T00:00:00.0000000Z","ProductionYear":2010,"ServerId":"8d443b3e1658478d82c4ef79e45341ec","Type":"Series","UserData":{"IsFavorite":false,"Key":"153021","PlayCount":0,"PlaybackPositionTicks":0,"Played":false,"UnplayedItemCount":179}}}`

**Comment by Fallenbagel** [comment]
First to fix the tmdb ID error, you need to refresh and replace all your metadata. Some of your stuff is missing tmdbid which is used by jellyseerr to sync. Best way is to append the `[tvdbid-xxxxx]` for series folder and `[imdbid-ttxxxxx]` or `[tmdbid-xxxxx]` for movies file (you can use *arr stack for this. Ping me if you need the complete naming scheme I use). Then after doing a refresh and replace metadata, then running jellyfin full scan on jellyseerr should fix tmdbid error.

As for auth error, one thing you could try is logging out and logging back in again

**Comment by Dubwize** [comment]
These have all been scraped by Radarr and Sonarr,  so the TMDB info is only wrong, if one of them has failed at scraping it correctly.

That said,  I've double checked a bunch, and the TMDB info is correct.  So this isn't a scarping, *arr or a jellyfin issue.
ie:
![image](https://user-images.githubusercontent.com/16105140/226478853-720c3576-21b7-467f-9af9-73a3dd8aafd4.png)
![image](https://user-images.githubusercontent.com/16105140/226478797-be1e6a69-bbd3-446d-8561-a383b717e84b.png)

**Comment by Fallenbagel** [comment]
Not TVDB id. Yours is still missing the tmdbID. *arr generations sometimes do not include the tmdbID (i have noticed this). if you want to test on one, move obiwan kenobi series out of the library folder of jellyfin, and then move it back in after adding the tvdbid number to the series folder. Then run a replace metadata. Im pretty sure the tmdbid number will be added. What you highlighted is tvdbid

**Comment by Dubwize** [comment]
Interesting.  You mean actually have the TMDB ID in the folder name itself?

**Comment by Fallenbagel** [comment]
> Interesting. You mean actually have the TMDB ID in the folder name itself?

No. TVDBid but that should be enough to add the tmdbid by jellyfin

**Comment by Dubwize** [comment]
None of my media has that, and there's no way I'm going to go back in and add that to ever folder and rescan my 100TB of media into jellyfin.   Since I can see both TMDB, and TVDB already existing everywhere in the metadata, nfo, etc, etc.   I'll just leave Jellyseerr broken, It requests fine so at least it does the main job.

**Comment by Fallenbagel** [comment]
> None of my media has that, and there's no way I'm going to go back in and add that to ever folder and rescan my 100TB of media into jellyfin. Since I can see both TMDB, and TVDB already existing everywhere in the metadata, nfo, etc, etc. I'll just leave Jellyseerr broken, It requests fine so at least it does the main job.

You can let sonarr/radarr rename but yes I see your concern. You could give it a try on one small series tho if you're curious. I can guarantee it would work
