### ISSUE TITLE
Timezone is not used to show the correct information.

### ISSUE THREAD

**Issue by thorkseng** [Fallenbagel/jellyseerr#344]
### Description

When a show has a new chapter in the future (for example, at 22pm EST time) but that is the past in the present (for example GMT time), the system Jellyseerr shows that the show has aired, but not real, thinking that it was on the same day for the wrong timezone.

For example, last chapter of next show is aired on 12th of March US time (future), but in Europe it shows that it has done 22 hours ago (past):
![image](https://user-images.githubusercontent.com/37229415/224577462-b191b286-cc42-4dd9-9356-a4fb2f44dc97.png)

Checking the sonarr information it has done the change of the timezone (the show will aired in some hours, on 13th march at 1am :
![image](https://user-images.githubusercontent.com/37229415/224577518-6dd36b2d-c841-4f77-97eb-d735d9a797e8.png)

The time of when the chapter will be aired should match with the information of sonarr/radarr but at the same time it should match the information of the timezone to adjust the timezone correctly.

### Version

1.4.1

### Steps to Reproduce

Any series with aired on US time and living in Europe.

### Platform

desktop

### Device

Any

### Operating System

Any

### Browser

Any

### Additional Context

I used last version, and I added the TZ to the container:
![image](https://user-images.githubusercontent.com/37229415/224577629-84f6007b-3f30-4ad2-ae51-8d2875e7a7b7.png)

![image](https://user-images.githubusercontent.com/37229415/224578190-aac1e092-5df5-4fbc-9278-cc3f2f32866f.png)

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The time is taken from tmdb. Sonarr uses tvd. Jellyseerr just takes the data from tmdb

**Comment by thorkseng** [comment]
You are right, in the tmdb shows 12th March. Maybe could be a possibility/alternative to get the data from the Sonarr api? It seems very more accurate than tvd.

Thanks in advance.

**Comment by thorkseng** [comment]
> I'm not sure if they even offers the time through sonarr api (might be mistaken never checked) 🤔
It would be great if sonarr exposes that information in the API.

> But that would also break anyone who uses jellyseerr for the sole purpose of just using it with radarr or so
The ideal would be that shows be checked on sonarr and films on radarr, right?

**Comment by Fallenbagel** [comment]
> The ideal would be that shows be checked on sonarr and films on radarr, right?


What I meant was what if someone runs jellyseer but doesn't use sonarr and only radarr. If they were to accidentally open a series, wouldn't the time be booked. A fallback to tmdb could be used yeah but you get my point 🤔
