### ISSUE TITLE
French develp version status broken 

### ISSUE THREAD

**Issue by GeoffreyCoulaud** [Fallenbagel/jellyseerr#355]
### Description

The version status badge in the bottom left of the desktop UI of Jellyseer is broken in french.

In weblate, the english string is `Overseer Develop` which is translated to  `Développement d'Overseer`. This works because in french `de ` is replaced by `d'` when followed by a vowel.  
In the case of Jellyseer, the string is `Développemeent d'Jellyseer` which should be `Développemeent de Jellyseer`.

I'm not sure how this should be handled.

### Version

fd460df2439df154307d089ebb8206688f1b7b26

### Steps to Reproduce

1. Install the right version
2. Set locale to french
3. Go to Jellyseer's home page

### Screenshots

![Capture d’écran du 2023-03-24 20-12-03-obfuscated](https://user-images.githubusercontent.com/20744730/227618676-851a9a52-17e3-4987-964f-81e188fc06f8.png)

### Platform

desktop

### Device

MSI Delta 15

### Operating System

Manjaro Linux Gnome Unstable

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You'll need to correct in this [line](https://github.com/Fallenbagel/jellyseerr/blob/fd460df2439df154307d089ebb8206688f1b7b26/src/i18n/locale/fr.json#L128).
You can open a PR request and I'll accept c:
