### ISSUE TITLE
incorrect header check

### ISSUE THREAD

**Issue by 11harveyj** [Fallenbagel/jellyseerr#359]
### Description

Seem to be having issues communciating with Emby, I keep getting the following errors in the logs:

`Something went wrong while getting libraries from the Jellyfin server: incorrect header check`

I've restarted both Emby and Jellyseerr no end of times with no luck.

Authentication also does not work at all (apart from local auth, although weirdly it can still import users)

### Version

1.4.1

### Steps to Reproduce

Not sure, for me I have Jellyseerr hosted on an external network with an IPSec connection back to the site which hosts the Emby server. For some reason this has suddenly stopped working (no config changes etc.)

### Platform

desktop

### Device

All devices

### Operating System

All devices

### Browser

All devices

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you exec into the container and see if `curl -L https://embydomain.com` resolves

**Comment by 11harveyj** [comment]
Output as below, as curl isn't installed in the docker container by the looks of it, I also did a ping

/ # curl -L https://e.media.system32.uk
sh: curl: not found
/ # ping e.media.system32.uk
PING e.media.system32.uk (162.55.86.85): 56 data bytes
64 bytes from 162.55.86.85: seq=0 ttl=63 time=0.304 ms
^C
--- e.media.system32.uk ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.304/0.304/0.304 ms
/ # ping 192.168.1.246
PING 192.168.1.246 (192.168.1.246): 56 data bytes
64 bytes from 192.168.1.246: seq=0 ttl=61 time=81.394 ms
^C
--- 192.168.1.246 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 81.394/81.394/81.394 ms

**Comment by Fallenbagel** [comment]
Ping will work but thats not what we want.
Could you exec into container and then run
`apk update && apk add curl` then run it?

**Comment by 11harveyj** [comment]
Ahhh, thats it, forgot alpine isn't `apt` lol. Here we go, seems externally its complaining about a certificate, although the cert isn't self-signed and is valid.

```
/app # curl -L https://e.media.system32.uk
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
/app # curl -L http://192.168.1.246
curl: (7) Failed to connect to 192.168.1.246 port 80 after 30 ms: Connection refused
/app # curl -L http://192.168.1.246:8097
﻿<!DOCTYPE html>
<html data-appversion="4.8.0.21" data-culture="en-GB" lang="en" class="preload">
<head>

    <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="preload" href="modules/fonts/material-icons/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmP_3.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="manifest" href="manifest.json">
    <meta name="description" content="Emby Server">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">

    <meta http-equiv="X-UA-Compatibility" content="IE=Edge">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Emby">
    <meta name="robots" content="noindex, nofollow, noarchive">
    <meta property="og:title" content="Emby">
    <meta property="og:site_name" content="Emby">
    <meta property="og:url" content="https://emby.media">
    <meta property="og:description" content="Energize your media.">
    <meta property="og:type" content="article">
    <meta property="fb:app_id" content="1618309211750238">
    <meta name="apple-itunes-app" content="app-id=992180193">
    <link rel="apple-touch-icon" href="images/icon-192x192.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/icon-72x72.png">
    <link rel="apple-touch-icon" sizes="144x144" href="images/icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="images/icon-152x152.png">
    <link rel="apple-touch-icon" sizes="192x192" href="images/icon-192x192.png">
    <link rel="apple-touch-icon" sizes="384x384" href="images/icon-384x384.png">
    <link rel="apple-touch-icon" sizes="512x512" href="images/icon-512x512.png">
    <link rel="apple-touch-startup-image" href="images/splash.png">
    <link rel="shortcut icon" href="favicon.ico">
    <meta name="msapplication-TileImage" content="images/icon-144x144.png">
    <meta name="msapplication-TileColor" content="#333333">
    <meta name="theme-color" content="#43A047">

    <title>resmediaserver</title>

    <style>
        .preload {
            background-color: #000;
        }

        .app-splash {
            background-image: url(modules/themes/logowhite.png);
            background-position: center top;
            background-repeat: no-repeat;
            background-size: contain;
            position: fixed;
            top: 30%;
            left: 30%;
            right: 30%;
            height: 20%;
            contain: strict;
            content-visibility: auto;
        }

        .hide {
            display: none !important;
        }

        @media (orientation: landscape) {

            .app-splash {
                left: 37.5%;
                right: 37.5%;
            }
        }
    </style>

</head>
<body class="mainAnimatedPages skinBody">
    <div class="backdropContainer"></div>
    <div class="backgroundContainer"></div>
    <div class="mainDrawer hide focuscontainer-y padded-bottom-page" is="emby-scroller" data-horizontal="false" data-centerfocus="true" data-navcommands="card" data-bindheader="false" data-skipfocuswhenvisible="true">
        <div class="scrollSlider mainDrawerScrollSlider"></div>
    </div>
    <div class="skinHeader focuscontainer-x focuscontainer-up headroom flex align-items-center flex-grow headerTop">
        <div class="headerLeft headerSection">
        </div>
        <div class="headerMiddle headerSection sectionTabs">
        </div>
        <div class="headerRight headerSection focuscontainer-right">
        </div>
    </div>

    <div class="app-splash"></div>
    <script src="apploader.js?v=4.8.0.21" defer></script>
</body>
</html>/app # 
```

I'm pretty certain I have the internal IP set in the config.

**Comment by Fallenbagel** [comment]
Internal ip is working right? Could you check `settings.json` and see if it's so. If it is, simply try to log out and log back in to refresh user token

**Comment by 11harveyj** [comment]
This is the Jellyfin section of the settings.json file

```
"jellyfin": {
  "name": "",
  "hostname": "http://192.168.1.246:8097",
  "externalHostname": "",
  "libraries": [],
  "serverId": "<REDACTED>"
 },
```

Logging out and logging back in again doesn't seem to resolve either.

**Comment by Fallenbagel** [comment]
> Logging out and logging back in again doesn't seem to resolve either.

One other thing I can think of is, backup the current config folder fully and delete the original so jellyseerr is reset. Setup new one to see if same issue occurs or not

**Comment by 11harveyj** [comment]
Ok, so closing this down now. I'm not sure what was going on but its been working ok since (despite me not actually resetting Jellyseerr / starting a fresh).
