### ISSUE TITLE
[Feature Request] Anime profile support for Movies.

### ISSUE THREAD

**Issue by Middlepepper** [Fallenbagel/jellyseerr#360]
### Description

Can you provide support for anime profiles with Radarr? 

Currently there is no option to allow for an "Anime" Profile in the Radarr Server screen. The Main as is just so it select a seperate library or profile if the ANIME_KEYWORD_ID = 210024 is found on themoviedb

### Desired Behavior

Having the following options enable for Radarr instance and apply if ANIME_KEYWORD_ID = 210024 is detected on themoviedb for a requested movie.

Anime Quality Profile
Anime Root Folder
Anime Language Profile
Anime Tags

### Additional Context

This might be related to issue #195 but I think the callout here is slightly different.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I currently have a webhook script that can do this.
https://github.com/Fallenbagel/seerr-route
For the meantime you could try that

**Comment by Middlepepper** [comment]
Well I was not expecting that quick of a reply. Thank you! I'll give this a try So if I spin this up on say python /path/to/Seerr-Route.main.py  &  it'll just run in the background and flip any request per the "rootFolder" set for the values?

**Comment by Fallenbagel** [comment]
> Well I was not expecting that quick of a reply. Thank you! I'll give this a try So if I spin this up on say python /path/to/Seerr-Route.main.py  &  it'll just run in the background and flip any request per the "rootFolder" set for the values?

As long as you set the api keys and the jellyseerr url and the rootfolder paths yes. (Sorry I have not had time to modularise and keep the config in a seperate file with an easier to configure manner )

To test you could try requesting from a user that doesn't have advanced request permissions and watch as it changes rootfolder c:

**Comment by Middlepepper** [comment]
Perfect that should work just fine for me for the moment, I'll pay around with it on a test user like you suggested.

**Comment by luckycold** [comment]
Would support for different quality profiles be possible too? I see no workaround for this use case. I use Trash Guides and one of the aspects to it is that there's a specific profile for Anime. I don't think your script does this, unfortunately.

**Comment by Fallenbagel** [comment]
> Would support for different quality profiles be possible too? I see no workaround for this use case. I use Trash Guides and one of the aspects to it is that there's a specific profile for Anime. I don't think your script does this, unfortunately.

That script is supposed to be an example. The api endpoints of jellyseerr is what the script uses and it can be modified to do exactly that too. I could make a seperate branch that changes quality profiles too later this weekend

**Comment by luckycold** [comment]
>   That script is supposed to be an example. The api endpoints of jellyseerr is what the script uses and it can be modified to do exactly that too. I could make a seperate branch that changes quality profiles too later this weekend

I'll go ahead and try my hand at modifying it. This is my first time doing this kind of thing. So, I'll give an update this weekend if I couldn't figure it out.

**Comment by luckycold** [comment]
I just tried to edit it and I'm running into issues with the Docker file. It seems when I try to run it after building, it's telling me 
``` 
Traceback (most recent call last):
  File "//./main.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named "dotenv" 
```
If I had to guess, I think it has something to do with the build command in docker is deprecated now. I don't know much about docker development, unfortunately. Just managing them. Due to my limited knowledge on this, I'm going to give up on the Docker side of this. Going to try to run it raw on my raspberry pi and see how that goes.

**Comment by luckycold** [comment]
Weird... I'm getting the same error running it raw.

**Comment by luckycold** [comment]
I ran into to many issues for this. I'm out of my depth on this since I can't even get it to run at all, let alone getting it to work for my purposes.

**Comment by Fallenbagel** [comment]
Duplicate #232

**Comment by nado** [comment]
While trying to automate it on my side, I discovered radarr/sonarr support "Custom Script" for a long time, if anyone needs it here is the script I made for movies (almost identical for series).
Sonarr has "Anime" in its genres but not radarr, hence the use of OriginalLanguage coupled with the Genre Animation to identify animes.

My tags are applied by the sonarr/radarr Autotagging system so I dont modify them with this script.

```bash
#!/bin/bash

OnMovieAdded() {
    local baseurl="http://localhost:7878/api/v3"
    local apikey="xx"

    if [[ "$radarr_movie_genres" =~ "Documentary" ]]; then
        if [[ ! "$radarr_movie_path" == "/data/share/videos/documentaries" ]]; then
            curl -i -s -X 'PUT' "$baseurl/movie/editor" \
                -H "X-Api-Key: $apikey" \
                -H 'accept: application/json' \
                -H 'Content-Type: application/json' \
                -d "{\"movieIds\": [ $radarr_movie_id ], \"rootFolderPath\": \"/data/share/videos/documentaries\", \"moveFiles\": true}"
        fi
    elif [[ "$radarr_movie_genres" =~ "Animation" ]]; then
        case "$radarr_movie_originallanguage" in
            jpn | zho | chi | kor)
                curl -i -s -X 'PUT' "$baseurl/movie/editor" \
                    -H "X-Api-Key: $apikey" \
                    -H 'accept: application/json' \
                    -H 'Content-Type: application/json' \
                    -d "{\"movieIds\": [ $radarr_movie_id ], \"qualityProfileId\": 10}"
                ;;
        esac
    fi

}

case $radarr_eventtype in
    Test)
        ;;
    MovieAdded)
        OnMovieAdded
        ;;
    *)
        echo "Unhandled event type: $radarr_eventtype"
        ;;
esac
```

**Comment by Middlepepper** [comment]
Thank you for sharing that script, this helps me slimdown my docker compose and is easily expanded.
