### ISSUE TITLE
[Feature Request] Clear request status when media is not found in library

### ISSUE THREAD

**Issue by Suzaru** [Fallenbagel/jellyseerr#362]
### Description

If it is not too much trouble I wanted to ask if you can add an option to activate the following behaviour:

Sometimes a request gets added, the media will be added into the library but deleted after a short period of time. If I am not mistaken the status of the request stays on "available" no matter if the media was deleted or not. That leads to confusion of users when they see "Media X is available." but they can't find it in Jellyfin, since it got deleted. Would be super nice if there was an option like that.

### Desired Behavior

On a full library scan, clear the request status if the media is not found in the library.

### Additional Context

Thank you for all your work, I've been a fan since day one. Greatly appreciate it! <3

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The code for this is already available in development branch and even works too (just temporarily disabled as it bugs out with jellyfin/emby. Works with plex)

**Comment by Fallenbagel** [comment]
> Duplicate of  #84 

Thanks! Will be closing this as duplicate
