### ISSUE TITLE
[Feature Request] Add multi Root folder in one Sonarr/Radarr server

### ISSUE THREAD

**Issue by MohammedSaudAlsahli** [Fallenbagel/jellyseerr#365]
### Description

In Jellyseerr I have only one root folder for each radarr/sonarr destination server

### Desired Behavior

In my way to organize movies and shows, I use media folder and sub folder for movies and other sub folder for tv show etc. I want one destination server with two or more root folders

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Do you mean one root folder for sonarr and radarr?

**Comment by MohammedSaudAlsahli** [comment]
No, I mean multiple root folders for sonarr or radarr, example for one sonarr server: root1 - /Media/TV Shows, root2 - /Media/Anime, root3 - /Media/Cartoons. Current Jellyseerr need to create 3 destination servers.

**Comment by Fallenbagel** [comment]
> No, I mean multiple root folders for sonarr or radarr, example for one sonarr server: root1 - /Media/TV Shows, root2 - /Media/Anime, root3 - /Media/Cartoons. Current Jellyseerr need to create 3 destination servers.

You dont need 3 destination servers you can change the rootfolder when requesting if you have advanced request permission. As for anime there's an anime specific configuration so even if you don't have advanced request permission you can have both anime and TV shows in same sonarr. To add cartoons you'll have to have the advanced request permission so you can change rootfoldee when requesting or you can use something like a webhook to redirect it automatically like [seerr-route](https://github.com/Fallenbagel/seerr-route)
