### ISSUE TITLE
[Feature Request] Provide Github container registry as docker container registry

### ISSUE THREAD

**Issue by cbirkenbeul** [Fallenbagel/jellyseerr#370]
### Description

Hi,
due to many docker things in the last weeks and the rate limit it would be nice, if you provide the docker image via the ghcr als github packages. 
Just to have an option to pull the container from. 
Thanks.

### Desired Behavior

Have a docker hub alternative

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I have been planning to do so too
