### ISSUE TITLE
can't login behind NPM proxy

### ISSUE THREAD

**Issue by ptichalouf** [Fallenbagel/jellyseerr#372]
### Description

hello everyone, with the exactly same config has overseerr i have on NPM https://ask.XXXXXX.XXX

now with jellyseerr i can't login with jellyfin or jellyseerr on any account. 

Log is empty someone could help me ? 

### Version

latest

### Steps to Reproduce

install jellyseerr exactly like overseerr on NPM and login doesn't work

### Platform

desktop

### Device

macbook pro m1

### Operating System

macos

### Browser

chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you checkthe network tab of dev tools to see what happens when you try to login

**Comment by NaturallyAsh** [comment]
Did you try enabling proxy support in Settings? https://docs.overseerr.dev/using-overseerr/settings#enable-proxy-support

**Comment by Fallenbagel** [comment]
I will be closing this issue as I have not heard back from you. Feel free to re-open although this is more of a configuration issue and we carry out support tickets in our discord rather than here
