### ISSUE TITLE
access jellyfin locally

### ISSUE THREAD

**Issue by cellulosa** [Fallenbagel/jellyseerr#373]
### Description

During the initiation setup, jellyseerr demands a domain hostname rather than an IP and port.

### Desired Behavior

Be able to enter localhost:8096 during the setup, when both (jellyseerr and jellyfin) are running on the same machine.

### Additional Context

This is terrific software, lots of love for bringing it to us! <3

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is already possible? Hostname doesn't necessarily mean your domain. You can type
http://127.0.0.1:8096
