### ISSUE TITLE
Can't login & login site not working probably

### ISSUE THREAD

**Issue by PakuDrag** [Fallenbagel/jellyseerr#376]
### Description

Trying to open jellyseer on my tv (Samsung smart tv, Tizen Os) via internet browser(Tizen browser)

### Version

1.5

### Steps to Reproduce

1.Use a tizen os tv
2. Open internet browser
3. Write username and password
4. Click sign in 

### Screenshots

![jellyseer](https://user-images.githubusercontent.com/70688269/235374408-d230d81d-6728-401c-9766-20c744e0ec0a.jpg)

### Logs

```shell
No log input for this matter
```

### Platform

desktop

### Device

Samsung TV

### Operating System

Tizen Os

### Browser

Tizen Browser

### Additional Context

Other devices work fine. The site stays the same in the screenshot when clicked sign in button

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could be that the tizenOS browser is way too old version of chromium. I also have a tizenOS which version of tizen is this? So I can test too

**Comment by PakuDrag** [comment]
Sorry for the late response. The version is : 2.1.3.0721073

**Comment by PakuDrag** [comment]
Solved by updating OS

**Comment by quaternion7** [comment]
I have the same problem, but the OS Software updates says its on the latest version (2.1.3.072...) :/
Also i notice it adds the username and password as GET parameters, so maybe its because the browser really doesnt support the compiled javascript.
So, no alternatives for my tizen tv?

**Comment by PakuDrag** [comment]
> 

Yeah I guess the old browser doesn't support it. As far as I know there is no alternative but try to call the Samsung support and try to get them to update it (if they even can).
