### ISSUE TITLE
Volume mapping and Timezone erros when using podman

### ISSUE THREAD

**Issue by caioolivv** [Fallenbagel/jellyseerr#378]
### Description

I'm trying to deploy Jellyseerr with podman with the following command:

```
podman run -d \
  --label "io.containers.autoupdate=registry" \
  --name=jellyseer \
  -e LOG_LEVEL=debug \ 
  -e TZ=America/Sao_Paulo \ 
  -p 8009:5055/tcp  \
  -v /path/to/jellyseer:/config:Z \
  --restart always \
  docker.io/fallenbagel/jellyseerr:latest
```

 Jellyseerr seems to not be able to write to the folder (even if I chmod 777) and logs are always shown on GMT time, instead of GMT-3.

### Version

1.5.0

### Steps to Reproduce

Run:

```
podman run -d \
  --label "io.containers.autoupdate=registry" \
  --name=jellyseer \
  -e LOG_LEVEL=debug \ 
  -e TZ=America/Sao_Paulo \ 
  -p 8009:5055/tcp  \
  -v /path/to/jellyseer:/config:Z \
  --restart always \
  docker.io/fallenbagel/jellyseerr:latest
```

### Platform

desktop

### Device

Intel Jasper Lake Mini PC

### Operating System

Fedora Server 37

### Browser

Any

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
What folder are you mapping for `/path/to/config/`

**Comment by caioolivv** [comment]
> What folder are you mapping for `/path/to/config/`

`~/containers/jellyseer`

**Comment by caioolivv** [comment]
I should say that this doesn't necessarily stop Jellyseerr from working, but I can't seem to find a way to configure jail2ban to act on Jellyseerr, as I can't read the logs and if I could, the logs would be in a different time zone.

**Comment by Fallenbagel** [comment]
> > What folder are you mapping for `/path/to/config/`
> 
> `~/containers/jellyseer`

Maybe because you're mapping it to the home directory and you're not necessarily running the container as your user. Try mapping to another place like opt or mnt or so. Or add `user` to the podman commands to specify user

**Comment by caioolivv** [comment]
Tried mounting to /mnt/jellyseerr and runinng with my user with:

```
sudo podman run -d \
  --label "io.containers.autoupdate=registry" \
  --name=jellyseerr \
  -e LOG_LEVEL=debug \
  -e TZ=America/Sao_Paulo \
  -p 8009:5055/tcp \
  -v /mnt/jellyseerr:/config:Z \
  --restart always \
  docker.io/fallenbagel/jellyseerr:latest
```

and

```
podman run -d \
  --label "io.containers.autoupdate=registry" \
  --name=jellyseerr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e LOG_LEVEL=debug \
  -e TZ=America/Sao_Paulo \
  -p 8009:5055/tcp \
  -v /home/caiooliveira/containers/jellyseerr:/config:Z \
  --restart always \
  docker.io/fallenbagel/jellyseerr:latest
```

Neither worked.

**Comment by caioolivv** [comment]
Also tried

```
podman run \
  -d \
  --label "io.containers.autoupdate=registry" \
  --name=jellyseerr \
  --userns=keep-id \
  -e LOG_LEVEL=debug \
  -e TZ=America/Sao_Paulo \
  -p 8009:5055/tcp \
  -v /home/caiooliveira/containers/jellyseerr:/config:Z \
  --restart always \
  docker.io/fallenbagel/jellyseerr:latest
```

but that kills podman somehow?

**Comment by caioolivv** [comment]
Also tried

```
podman run \
  -d \
  --label "io.containers.autoupdate=registry" \
  --name=jellyseerr \
  --userns=keep-id \
  -e LOG_LEVEL=debug \
  -e TZ=America/Sao_Paulo \
  -p 8009:5055/tcp \
  -v ~/containers/jellyseerr:/config:Z \
  --restart always \
  docker.io/fallenbagel/jellyseerr:latest
```

but that kills podman somehow?

**Comment by caioolivv** [comment]
Volume mapping was using `-v ~/containers/jellyseerr:/config:Z` instead of `-v ~/containers/jellyseerr:/app/config:Z`. I still have the timezone wrong on the logs though. Any idea how to solve that?

**Comment by caioolivv** [comment]
Seems to be how overseerr is [setup](https://github.com/sct/overseerr/issues/1387). Closing the issue

**Comment by Fallenbagel** [comment]
Just fyi, 
```
podman run -d \
  --label "io.containers.autoupdate=registry" \
  --name=jellyseerr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e LOG_LEVEL=debug \
  -e TZ=America/Sao_Paulo \
  -p 8009:5055/tcp \
  -v /home/caiooliveira/containers/jellyseerr:/config:Z \
  --restart always \
  docker.io/fallenbagel/jellyseerr:latest
  ```
  This only works on linuxserver images and images with passable user UID and GUID. Otherwise you need to use:
  ```
podman run -d \
  --label "io.containers.autoupdate=registry" \
  --name=jellyseerr \
  --user=1000:1000
  -e LOG_LEVEL=debug \
  -e TZ=America/Sao_Paulo \
  -p 8009:5055/tcp \
  -v /home/caiooliveira/containers/jellyseerr:/config:Z \
  --restart always \
  docker.io/fallenbagel/jellyseerr:latest
  ```
