### ISSUE TITLE
Option series type (Sonarr v4 bug Anime)

### ISSUE THREAD

**Issue by pixelroll** [Fallenbagel/jellyseerr#379]
### Description

Currently on V4 of sonarr if the option series type is in anime, the search is done episode by episode only, so no season pack which are however majority once the anime finished. So, most of the dated anime are not available in full...

### Desired Behavior

It would be nice to be able to set the "series type" option to be used by default

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Added in [feat: Add default seriesTypes for anime](https://github.com/Fallenbagel/jellyseerr/commit/f6286359cfd2ed93fc692aa2efda37310e02c11c)
