### ISSUE TITLE
Latest docker tag has no layers

### ISSUE THREAD

**Issue by samdnz** [Fallenbagel/jellyseerr#382]
### Description

https://hub.docker.com/layers/fallenbagel/jellyseerr/latest/images/sha256-71f18efd7ec4106e5111a0bdf0f836817838195c717bdf225946d9a31ec05e89?context=explore

probably just need to tag and push again

### Version

1.5.0

### Steps to Reproduce

go to https://hub.docker.com/layers/fallenbagel/jellyseerr/latest/images/sha256-71f18efd7ec4106e5111a0bdf0f836817838195c717bdf225946d9a31ec05e89?context=explore

or use  docker update witgh the latest tag

### Platform

desktop

### Device

n/a

### Operating System

docker on linux

### Browser

n/a

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
![Screenshot_20230507_163929_Firefox Beta.jpg](https://user-images.githubusercontent.com/98979876/236675241-c346d09e-17c0-41ef-bcfc-40a25cf1e77b.jpg)


Uh what do you mean?

**Comment by Fallenbagel** [comment]
I will be closing this issue as there are no follow ups. Feel free to reopen
