### ISSUE TITLE
 the default Series Type used is Anime, and you can't choose freely

### ISSUE THREAD

**Issue by PN62323424** [Fallenbagel/jellyseerr#383]
### Description

If you add anime now, the default Series Type used is Anime, and you can't choose freely. But sonarr can't search by anime, because it will search each episode separately, and hundreds of episodes will be blocked by BT station quickly, so I can only use standard to download season, and then change it to anime manually to catch up with the drama.

Can you change the Series Type to anime or standard, so that you can search for season?

### Desired Behavior

----

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Sonarr v4?

**Comment by PN62323424** [comment]
> Sonarr v4?

Yes, if I remember correctly, sonarr v3 is also unable to choose between anime or standard. But since anime generally has hundreds of episodes, once anime is selected, it will result in hundreds or thousands of searches, which in turn will make the BT site inaccessible for a short time

**Comment by PN62323424** [comment]
> > > Sonarr v4?
> > 
> > 
> > Yes, if I remember correctly, sonarr v3 is also not able to select anime or criteria. But since anime usually has hundreds of episodes, once anime is selected, sonarr will search each episode one by one, which will result in hundreds or thousands of searches, thus making some BT sites inaccessible for a while. If the choice of standard or anime mode is allowed, the user can choose for himself whether to download the season pack or the episodes
> 
> I use sonarr v3 exclusively and mine finds season packs. Someone else reported that they changed how anime category works in sonarr v4.

Thank you for your answer.

sonarr v4 does work better in many ways, but it also retains standard and anime, so it would be helpful if jellyseerr could allow users to select Series Type, i.e. standard or anime. Because there are some finished anime, it is possible to use standard to search for season packs, so that the number of searches is less likely to be blocked by BT stations.

**Comment by Fallenbagel** [comment]
> As far as I know, there are still quite a few release groups on some anime sites like nyaa that take absolute set numbering

Yeah but generally it's generally mostly seasoned nowadays. Esp new anime and stuff from my experience. And Sonarr V3 is working great so I'm not sure why they changed it completely for v4 is what I meant

**Comment by PN62323424** [comment]
> > As far as I know, there are still quite a few release groups on some anime sites like nyaa that take absolute set numbering
> 
> Yeah but generally it's generally mostly seasoned nowadays. Esp new anime and stuff from my experience. And Sonarr V3 is working great so I'm not sure why they changed it completely for v4 is what I meant

I think I may have found the reason for this thing, some BT stations will limit the number of searches in anime mode, most of the sites I currently own do not have too much impact even if they generate hundreds of searches, just the individual site limits.

If this is the case, you can modify the standard or anime the only benefit is to use the standard to search the number of searches a little less, new anime can be used in this way, old anime due to the inconsistency of the season and tvdb, standard under the hard to use.

The above is for your reference, thank you very much for your help.

**Comment by Fallenbagel** [comment]
Fixed in [feat: Add default seriesTypes for anime](https://github.com/Fallenbagel/jellyseerr/commit/f6286359cfd2ed93fc692aa2efda37310e02c11c)
