### ISSUE TITLE
~25 requests to jellyfin every 5 minutes?

### ISSUE THREAD

**Issue by Emporea** [Fallenbagel/jellyseerr#387]
### Description

Pihole on the local network revealed about 25 dns queries to jellyfin every 5 minutes. I traced this back to jellyseerr. Why so many?

This results in ~ 7200 queries per day from jellyseerr alone.

Let me know if I can help with any logs.

### Version

1.5.0

### Steps to Reproduce

Setup docker container with jellyfin and jellyseer and connect them.
let it run.

### Screenshots

![Screenshot 2023-05-19 at 00-42-18 Pi-hole - pihole](https://github.com/Fallenbagel/jellyseerr/assets/21969523/8893c5a5-aae4-4816-8ee5-eae1b62cdfbe)

Pi-hole data from several days. Jellyfin domain receives abnormal requests

### Platform

desktop

### Device

/

### Operating System

/

### Browser

/

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Theres a jellyfin recently added sync job that runs every 5 minutes. That is why. If you want you can increase the cron timing of it to an hour to lessen the dns queries tho its just gonna leave you with a 1hm hour delay on syncing.

**Comment by Fallenbagel** [comment]
I will be closing this issue as there are no follow ups. Feel free to reopen

**Comment by Fallenbagel** [comment]
> I followed your suggestion and changed it to an hour. The question still remains: why it has to access the url so often per cron job execution. Isnt it possible to access it only once per jellyfin sync job?

Because every 5 minutes it's doing a scan of the library for any recently added media. There's two sync jobs. The fully one runs every 24 hours. Recently added sync job every 5 minutes. All of these api requests need to request jellyfin api endpoint to talk to it?

**Comment by michelsup** [comment]
I face the same issue, I get hundreds of thousands of DNS request per day, it's insane. I'm sure there should be a possibility to cache the answer for a few minutes.

**Comment by Fallenbagel** [comment]
It's because of the way jellyfin user token works. You have to first call jellyfin, get the user access token, then call again using the access token to see if admin user before running library scan and stuff. If docker add the hosts with the ip so it resolves within the docker or filter out the jellyfin domain.

**Comment by michelsup** [comment]
Thank you very much @Fallenbagel , I didn't thought about setting the IP within docker. Well done.
