### ISSUE TITLE
Invalid User

### ISSUE THREAD

**Issue by jakanaka** [Fallenbagel/jellyseerr#389]
### Description

If emby users are deleted from emby, user can not login to jellyserr as expected. But user is also kept in the user list of jellyserr. It should auto delete a user if deleted from emby or give an option

### Version

1.5.0 docker

### Steps to Reproduce

1. create a test user in emby with username & password `test` for example
2. login in jellyseerr with username & password `test` for example
3. delete user `test` from emby
4. unable to login to jellyseerr but user exists in the userlist

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate #90
