### ISSUE TITLE
Debian Install; no file named install for yarn to use. 

### ISSUE THREAD

**Issue by Normanras** [Fallenbagel/jellyseerr#391]
### Description

After following the two `git` commands in the install under "[Linux](https://github.com/Fallenbagel/jellyseerr#linux)", here's what's been cloned from git and following the steps in the docs:

```
user@jellyfin:~/jellyseer# ls
CHANGELOG.md        LICENSE          cypress.config.ts          next.config.js     renovate.json        tailwind.config.js
CODE_OF_CONDUCT.md  README.md        docker-compose.yml         overseerr-api.yml  server               tsconfig.json
CONTRIBUTING.md     babel.config.js  docs                       package.json       snap                 yarn.lock
Dockerfile          config           merged-prettier-plugin.js  postcss.config.js  src
Dockerfile.local    cypress          next-env.d.ts              public             stylelint.config.js
user@jellyfin:~/jellyseerr# yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```
In addition, here are the versions of `yarn` and `node`.
```
user@jellyfin:~/jellyseerr# yarn --version
0.32+git
user@jellyfin:~/jellyseerr# node --version
v20.2.0
user@jellyfin:~/jellyseerr# 
```

### Version

None, yet

### Steps to Reproduce

Follow the steps for [Linux install steps](https://github.com/Fallenbagel/jellyseerr#linux). Here they are for easy access: 

Linux
Pre-requisites:

Nodejs (atleast LTS version)
Yarn
Git
```
git clone https://github.com/Fallenbagel/jellyseerr.git && cd jellyseerr
git checkout main #if you want to run stable instead of develop
yarn install
```

It is at yarn install where the steps fail. 

### Screenshots

See CLI output above.

### Platform

desktop

### Device

Proxmox VM

### Operating System

Debian

### Browser

n/a

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
That's because the yarn that the apt package provides is not the same yarn as the node yarn (its some cmdlet or sth). Do this:

`apt purge yarn`

Then make sure you have the correct version of nodejs and then:

`npm install -g yarn`

**Comment by Badrelddin** [comment]
It's works!! 

do  `apt purge  cmdtest` 

and then  `npm install -g yarn`

**Comment by Normanras** [comment]
Oh man! I had a tab open with an unsent comment to @Fallenbagel suggestion! That 100% worked. So sorry for the delay!

**Comment by Fallenbagel** [comment]
Oh wait I just realised the other commenter wasn't the author of this issue. Sorry for pre-closing the issue I thought it was you @Normanras

**Comment by Normanras** [comment]
No worries at all, @Fallenbagel ! You're good - I'm glad it worked for them too :)
