### ISSUE TITLE
Bizarre error: Entitymediaerror

### ISSUE THREAD

**Issue by Yankees4life** [Fallenbagel/jellyseerr#416]
### Description

Not too sure whats happening here. Updated to the latest develop version and I get this when I yarn install, build and start

```
yarn run v1.22.19
warning ..\..\..\package.json: No license field
$ NODE_ENV=production node dist/index.js
2023-06-26T03:42:16.278Z [info]: Starting Overseerr version develop-local
warn  - You have enabled experimental features (scrollRestoration, largePageDataBytes) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

2023-06-26T03:42:21.731Z [info][Notifications]: Registered notification agents
2023-06-26T03:42:21.759Z [error]: EntityMetadataNotFoundError: No metadata for "User" was found.
    at DataSource.getMetadata (C:\Users\Jean\Documents\Projects\jellyseerr\node_modules\typeorm\data-source\DataSource.js:295:19)
    at get metadata [as metadata] (C:\Users\Jean\Documents\Projects\jellyseerr\node_modules\typeorm\repository\Repository.js:15:40)
    at Repository.count (C:\Users\Jean\Documents\Projects\jellyseerr\node_modules\typeorm\repository\Repository.js:160:40)
    at C:\Users\Jean\Documents\Projects\jellyseerr\dist\index.js:112:45
Note: This command was run via npm module 'win-node-env'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Version

Development

### Steps to Reproduce

1. yarn install
2. yarn run build
3. yarn start

### Platform

desktop

### Device

Windows Laptop

### Operating System

Windows 10

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Your package.json is probably corrupted and thats why node modules are not being installed

**Comment by Yankees4life** [comment]
> Your package.json is probably corrupted and thats why node modules are not being installed
> 
> You're supposed to run install the node modules and build before running it. Also better to stick to main branch than develop

I guess I'll switch to the main to see if that works. Damn shame as develop versions has been working for a while now but yeah

**Comment by Fallenbagel** [comment]
> I guess I'll switch to the main to see if that works. Damn shame as develop versions has been working for a while now but yeah

No its nor specific to develop version. Your package json file is messed up. (Context: I have and am still running develop version)

**Comment by Yankees4life** [comment]
Issue seemed to sort it out self out after a clean install and I switched to the stable initially and then I switched to the develop and did a yarn start. Weird. I guess the package.json on the develop version is messed up

**Comment by Fallenbagel** [comment]
> Issue seemed to sort it out self out after a clean install and I switched to the stable initially and then I switched to the develop and did a yarn start. Weird. I guess the package.json on the develop version is messed up

The package.json on develop version is not messed up. I am running it currently. That clone that you did might have had a messed up one

**Comment by Yankees4life** [comment]
> > Issue seemed to sort it out self out after a clean install and I switched to the stable initially and then I switched to the develop and did a yarn start. Weird. I guess the package.json on the develop version is messed up
> 
> The package.json on develop version is not messed up. I am running it currently. That clone that you did might have had a messed up one

Well....that's bizarre but it's working now so...I'll close this one out.

**Comment by FrankJeager** [comment]
I've done a clean install from develop and I have this error at start...

**Comment by Fallenbagel** [comment]
> I've done a clean install from develop and I have this error at start...

You shouldn't be running develop but try removing package.json and git pulling

**Comment by FrankJeager** [comment]
Same error with a git pulling.

I switched to 1.5.0 and everything is fine.

I wanted to use develop for the nodemailer 6.9.1 cause nodemailer 6.8.0 stopped working...
But with 1.5.0 and a nodemailer updated to 6.9.4 it is working again.

**Comment by Fallenbagel** [comment]
> Same error with a git pulling.
> 
> I switched to 1.5.0 and everything is fine.
> 
> I wanted to use develop for the nodemailer 6.9.1 cause nodemailer 6.8.0 stopped working...
> But with 1.5.0 and a nodemailer updated to 6.9.4 it is working again.

I am on develop and I don't seem to be getting this issue tho

**Comment by FrankJeager** [comment]
Did you use NODE_ENV=production ?
The datasourceoptions are different between production and development environnement.
Before writting a message here I tried to play with the datasource.ts to see what I could do. But nothing I did solved the issue...

**Comment by Fallenbagel** [comment]
> Did you use NODE_ENV=production ?
> The datasourceoptions are different between production and development environnement.
> Before writting a message here I tried to play with the datasource.ts to see what I could do. But nothing I did solved the issue...

Nope all I did was git pull, yarn install & yarn build and yarn start. Didn't change anything
