### ISSUE TITLE
Discover Language not applying

### ISSUE THREAD

**Issue by cinderblockgames** [Fallenbagel/jellyseerr#417]
### Description

I changed my Discover Language in settings to English, but I'm still seeing items that have different original languages (e.g., Mavka/Ukrainian).

### Version

1.5.0

### Steps to Reproduce

Go to settings. Change Original Language. Check home page. 

### Platform

smartphone

### Device

Samsung S22 5G

### Operating System

Android

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Restart jellyseerr. Maybe clear browser cache too. Its just tmdb cache. Leave it applied for a while and it should only show english
