### ISSUE TITLE
[Feature Request] Possibility to specify Sonarr/Radarr root folder per user

### ISSUE THREAD

**Issue by v3DJG6GL** [Fallenbagel/jellyseerr#419]
### Description

I'd love to specify different root folders for different users.
Example:
Sonarr is configured with following root folders:
`/media/user1`
`/media/user2`
`/media/user3`

With Jellyfin, user1 has access to their personal library which is located at `/media/user1`.
The same goes for Jellyfin accounts user2 -> `/media/user2` and user3 -> `/media/user3`

Using Jellyseerr, there is indeed the possibility to grant users the permission `Advanced Requests` so they can manually choose the root folder where they want to have their downloaded content.

But sometimes - especially if those root folders are meant to be user-specific personal Jellyfin libraries - an option to specify one specific root folder would be very nice.
Because even if the users are aware that they have to change this value - eventually they might forget about it.

### Desired Behavior

One possibility to achieve that:
Add a possibility under _Settings_ -> _Services_ -> _Edit Radar/Sonarr_ -> _Root Folder_ to optionally add different root folders linked to one/several Jellyseerr users.

Another place where such an option could be integrated is, of course, _Settings_ -> _Users_, where a submenu could be added with the option to link Sonarr/Radarr root folders to one/several Jellyseerr users.

The same goes for _Users_ -> _user1_ -> _View Profile_ -> _Permissions_

I don't know how hard it is to implement such an option but one similar idea is probably #197

Thanks for all your hard work! 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by feerlessleadr** [comment]
Probably not happening, given the lack of movement on my request from almost 2 years ago:

https://github.com/Fallenbagel/jellyseerr/issues/171

**Comment by Fallenbagel** [comment]
Duplicate #419

**Comment by v3DJG6GL** [comment]
> Duplicate #419

This is #419
But seeing PR #757, it seems we are not far away from this request :)

**Comment by Fallenbagel** [comment]
> > Duplicate #419
> 
> This is #419
> But seeing PR #757, it seems we are not far away from this request :)

Oh 
I wrote the wrong issue number 😅
