### ISSUE TITLE
Forgot password button on the login page point to internal address

### ISSUE THREAD

**Issue by gauth-fr** [Fallenbagel/jellyseerr#424]
### Description

The Forgot password button on the login page point to internal address (hostname) and not the the external hostname.

### Version

1.5.0

### Steps to Reproduce

1. have the hostname set to an internal address ie 192.168.0.10:8096
2. have the external hostname set to another one ie jellyseer.domain.com
3. Go to the login page and click to the forgot password link
4. It will direct to the internal hostname

### Platform

desktop

### Device

laptop

### Operating System

windows 11

### Browser

firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate of #199 and #212
