### ISSUE TITLE
[Feature Request] Readme.md - clearer server installation prerequisites

### ISSUE THREAD

**Issue by pm3003** [Fallenbagel/jellyseerr#428]
### Description

The installation method from Github is accurate, but  the prerequisites could be clearer.
I'm not familiar with yarn and have limited JS experience. The following information would have spared me a few hours of googling before I managed to install jellyseer:
- necessary RAM or Swapspace
- necessary free disk space
- Yarn version
- an example of a node version
- clearer instructions for where to store the systemd service file: people who know systemd usually already understand how to do this, but for people without this knowledge the information provided is not enough.

In my case, for an install from a clean LXC container in Proxmox with Ubuntu 22.04:
- 2GB RAM necessary (or yarn install would fail)
- more than 4 GB available memory necessary (or package fetching and caching fails)
- export NODE_OPTIONS=--max_old_space_size=4096 (or yarn install fails with "Javascript Heap out of memory)
- yarn v3 (v1 wouldn't work, install fails) - a global yarn install

These values are the result of a bit of googling, trial and failure. I lack the competence to evaluate the relevance of the above, but I think it could be useful to share the info. Feel free to close if irrelevant.

### Desired Behavior

Installations instructions for installing on Linux should enable an installation from scratch with clear prerequisites.

**Comment by Lucas-Haux** [comment]
Agreed, this needs to be added!
