### ISSUE TITLE
Can't connect to Emby from 4.7.12

### ISSUE THREAD

**Issue by Shurelol** [Fallenbagel/jellyseerr#431]
### Description

Can't connect to Emby from 4.7.12
4.7.11 Ok
4.7.12 not Ok
4.7.13 not Ok
4.8.0.39 not Ok

Emby had fixed a security hole in 4.7.12
https://github.com/MediaBrowser/Emby.Releases/releases/tag/4.7.12.0

Maybe it causes this problem

### Version

1.5.0

### Steps to Reproduce

Use emby version higher than 4.7.11

### Platform

desktop

### Device

computer

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Emby version doesn't seem to be the issue.

![image-21.png](https://github.com/Fallenbagel/jellyseerr/assets/98979876/5adb7027-8d5a-4527-bb7b-7c7d36277a98)

![image-28.png](https://github.com/Fallenbagel/jellyseerr/assets/98979876/0fadac87-bf64-4a49-aa8d-d7decba2d42a)

This is from our discord. A user is running 4.7.13.0 I.e latest version

**Comment by Shurelol** [comment]
in my situation
emby is running on windows
jellyseerr is running on windows docker (same computer, network mode: bridge)

jellyseerr said The username or password is incorrect.
emby said The account is already verified in Activity

so weird

**Comment by Fallenbagel** [comment]
> in my situation
> emby is running on windows
> jellyseerr is running on windows docker (same computer, network mode: bridge)
> 
> jellyseerr said The username or password is incorrect.
> emby said The account is already verified in Activity
> 
> so weird

Try running jellyseerr in host mode without the ports defined

**Comment by Fallenbagel** [comment]
Could you try this. open cmd and try `curl -L http://embyurl:8096`. My guess is either the container cant reach emby or another reason is config path is mapped wrong so permission issue.

**Comment by ericlokz** [comment]
I have the same failure.emby Version is [4.7.13.0].
![微信截图_20230721165513](https://github.com/Fallenbagel/jellyseerr/assets/30315596/295695fd-a552-45d8-9b66-26fb9f273dcb)
![微信截图_20230721165542](https://github.com/Fallenbagel/jellyseerr/assets/30315596/60858e26-ce3f-4b4d-b508-2400066698bc)

**Comment by Fallenbagel** [comment]
> > Could you try this. open cmd and try `curl -L http://embyurl:8096`. My guess is either the container cant reach emby or another reason is config path is mapped wrong so permission issue.
> ![img](https://github.com/Fallenbagel/jellyseerr/assets/112518475/7900fcc5-2a44-4dc5-9995-b0234c4b289f)
> Like this? 
> I'd say it's only happened since my windows emby was upgraded to 4.7.12 or 4.7.13, before that my jellyseerr was running fine.
> 

Not like that. From within jellyseerr containe

**Comment by Fallenbagel** [comment]
> I have the same failure.emby Version is [4.7.13.0].
> ![微信截图_20230721165513](https://github.com/Fallenbagel/jellyseerr/assets/30315596/295695fd-a552-45d8-9b66-26fb9f273dcb)
> ![微信截图_20230721165542](https://github.com/Fallenbagel/jellyseerr/assets/30315596/60858e26-ce3f-4b4d-b508-2400066698bc)
> 

Your issue is different. Your logs show that your whole container can't reach outside network. See github api failing too

**Comment by ericlokz** [comment]
> > I have the same failure.emby Version is [4.7.13.0].
> > ![微信截图_20230721165513](https://user-images.githubusercontent.com/30315596/255127436-295695fd-a552-45d8-9b66-26fb9f273dcb.png)
> > ![微信截图_20230721165542](https://user-images.githubusercontent.com/30315596/255127454-60858e26-ce3f-4b4d-b508-2400066698bc.png)
> 
> Your issue is different. Your logs show that your whole container can't reach outside network. See github api failing too

But when I connect to emby in docker, it can be connected. The one that cannot be connected is winserver

**Comment by Fallenbagel** [comment]
> But when I connect to emby in docker, it can be connected. The one that cannot be connected is winserver
wdym?

**Comment by Shurelol** [comment]
IN JELLYSEERR
![image](https://github.com/Fallenbagel/jellyseerr/assets/16237201/c5ebd007-f344-4aa1-8217-6ce5b0bc2776)

BUT IN EMBY
![image](https://github.com/Fallenbagel/jellyseerr/assets/16237201/2466d1a4-86f2-4eb8-8ca0-3d2d8518272a)

curl is ok
![image](https://github.com/Fallenbagel/jellyseerr/assets/16237201/b88e11db-2588-4206-8839-3973f17a3a60)

**Comment by Fallenbagel** [comment]
> IN JELLYSEERR
> ![image](https://github.com/Fallenbagel/jellyseerr/assets/16237201/c5ebd007-f344-4aa1-8217-6ce5b0bc2776)
> 
> BUT IN EMBY
> ![image](https://github.com/Fallenbagel/jellyseerr/assets/16237201/dc45c663-bc3b-4cb4-8b90-52d16a96f380)
> 
> curl is ok
> ![image](https://github.com/Fallenbagel/jellyseerr/assets/16237201/b88e11db-2588-4206-8839-3973f17a3a60)
> 
> 

How did you setup jellyseerr

**Comment by Shurelol** [comment]
`version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Shanghai
            - JELLYFIN_TYPE=emby
            - HTTPS_PROXY=http://192.168.0.115:7890
       ports:
            - "50555:5055"
       volumes:
            - D:/docker_config/jellyseerr:/app/config
       restart: unless-stopped
       network_mode: bridge`

**Comment by Shurelol** [comment]
if using network_mode: host, jellyseerr can;t be visited

**Comment by Shurelol** [comment]
> Try adding all http, https, HTTP, HTTPS, noproxy variables

already tried, same result
jellyseerr said The username or password is incorrect.
emby said The account is already verified in Activity

**Comment by Fallenbagel** [comment]
When you tried `network_mode=host` did you keep the port? You should remove the port and try 🤔

I cant seem to reproduce that since I'm able to set the proxies. Another thing you could try is, bring up jellyseerr normally without the environment variables, then exec into the container and try `export http_proxy=http://example:1234`

And lastly the thing you could try is running redsocks (used to do this) to apply proxy in another container and running jellyseerr network through that container where redsocks will divert all traffic through the proxy. I think I might still have my previous config files (currently I run my proxy as a tproxy on my rpi using nftables so I don't use these methods anymore as tproxy will proxy the entire home network)

**Comment by Shurelol** [comment]
> When you tried `network_mode=host` did you keep the port? You should remove the port and try 🤔
> 
> I cant seem to reproduce that since I'm able to set the proxies. Another thing you could try is, bring up jellyseerr normally without the environment variables, then exec into the container and try `export http_proxy=http://example:1234`
> 
> And lastly the thing you could try is running redsocks (used to do this) to apply proxy in another container and running jellyseerr network through that container where redsocks will divert all traffic through the proxy. I think I might still have my previous config files (currently I run my proxy[v2ray/xray w dokodemo-door]as a tproxy on my rpi using nftables so I don't use these methods anymore as tproxy will proxy the entire home network)

host network not available in windows docker
https://github.com/docker/roadmap/issues/238

and more log 
in emby
![image](https://github.com/Fallenbagel/jellyseerr/assets/16237201/32fbad5e-c0cb-435e-ab9c-b7266f113b2b)

in jellyseerr
2023-07-25T15:48:02.466Z [info][Auth]: Failed login attempt from user with incorrect Jellyfin credentials {"account":{"ip":"::ffff:172.17.0.1","email":"shure","password":"__REDACTED__"}}

**Comment by Shurelol** [comment]
I tried to deploy emby and jellyseerr in different computer

emby: 192.168.0.115:8096
jellyseerr: 192.168.0.107:5055

everything works fine

**Comment by Shurelol** [comment]
1.6.0 solved this problem
