### ISSUE TITLE
Discover Region setting not saving if set to "All Regions"

### ISSUE THREAD

**Issue by GeorgeGedox** [Fallenbagel/jellyseerr#433]
### Description

Just change region in the settings, it will save, refresh and select "All Regions" and try to save. If the page is refreshed the previous region will still be selected.

### Version

1.5.0

### Steps to Reproduce

1. Go to Settings -> Discover Region
2. Change region to something else than default and save
3. Refresh page, try changing region again to "All Regions" and save
4. Refresh page, previous region will still be selected

### Platform

desktop

### Device

Desktop

### Operating System

Windows 10

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is a known bug. Workaround is to stop jellyseerr go to config folder open settings.json and change from there from for example `"de"` to `""`

**Comment by GeorgeGedox** [comment]
If this is a known issue is anyone actively working on it? If not I can open a PR

**Comment by Fallenbagel** [comment]
Should be fixed with: 28a2c50495d0ce531da7f8c442bd488a54b1e84c
