### ISSUE TITLE
Requests are automatically approved by user even though auto-approve not enabled.

### ISSUE THREAD

**Issue by WoxWik** [Fallenbagel/jellyseerr#443]
### Description

The only setting I have enabled for the particular user is: 

Grant permission to submit requests for non-4K media.
- Grant permission to submit requests for non-4K movies.
- Grant permission to submit requests for non-4K series.

However, when they make requests they are automatically approved

### Version

1.5.0

### Steps to Reproduce

User clicks request for particular series, or movie

### Platform

desktop

### Device

macbook

### Operating System

macos

### Browser

safari

### Additional Context

The only non-standard feature I have enabled is telegram notifications but I dont think these auto-approve requests 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you hop onto discord. So its easier to troubleshoot?

**Comment by Fallenbagel** [comment]
Is this still an issue? I will be closing this as we are currently on 1.8.1 and I have not been able to reproduce. However, feel free to reopen if it is
