### ISSUE TITLE
Error checking user access: This user does not exist on the main Plex account's shared list

### ISSUE THREAD

**Issue by xabufr** [Fallenbagel/jellyseerr#448]
### Description

Same as in overseerr: https://github.com/sct/overseerr/issues/3550

### Version

1.6.0

### Steps to Reproduce

Try to import new Plex user, no user found even when there are new ones

### Logs

```shell
Error checking user access: This user does not exist on the main Plex account's shared list
```

### Platform

desktop

### Device

Desktop

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by GilGedje** [comment]
Same here

**Comment by Fallenbagel** [comment]
Could you try the develop tag?

**Comment by xabufr** [comment]
@Fallenbagel indeed, I tried with the develop branch and it works well, do you know when you'll release it?
Thanks!

**Comment by Fallenbagel** [comment]
@xabufr the fix was merged from upstream 9 days ago

**Comment by atvking** [comment]
Any eta on a new release with this fix implemented? I have several users now who I would like to grant access to to make requests. Should I just temporarily create local accounts for all of them? Thanks!
