### ISSUE TITLE
Plugin for Emby/Jellyfin

### ISSUE THREAD

**Issue by Uuugh** [Fallenbagel/jellyseerr#451]
### Description

Jellyseerr has a fantastic and intuitive interface, but it is separate from the Emby/Jellyfin interface and is only accessible via the web interface.

### Desired Behavior

Provide a plugin for Emby/Jellyfin to enable access to the Jellyseerr interface/website via Emby/Jellyfin accross media devices (TV, phone, Roku, etc).

An alternative would be to create plugins for Roku, Amazon, etc; but this would take much more maintenance. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Jellyfin/emby plugins cannot modify the ui so this is not possible
