### ISSUE TITLE
Importing users from plex doesn’t work

### ISSUE THREAD

**Issue by GilGedje** [Fallenbagel/jellyseerr#453]
### Description

importing new users from plex shows no new users, yet the affected users cant access using plex cred and are not shown in the users table

### Version

1.6.0

### Steps to Reproduce

1. Share plex library with a new user in the plex webpage
2. Connect to jellyserr site
3. Go to settings, then users and try to import new users
4. Pay attention as no user cab be imported yet the user is not in the user list

### Logs

```shell
Error checking user access: This user does not exist on the main Plex account's shared list
```

### Platform

smartphone

### Device

Iphone 12

### Operating System

IOS 16.6

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate #448
