### ISSUE TITLE
Back button on PWA not working properly (browser history loop)

### ISSUE THREAD

**Issue by ioqy** [Fallenbagel/jellyseerr#461]
### Description

Opening the "Manage Movie" or "Manage Series" panel of an item in the status "Requested" and then closing it, makes the browser go into a loop when hitting the back button. This also happens on the normal (non PWA) web page, but is not that much of a problem because you have the back button of the browser. In the PWA there is no back button of the browser (at least on iOS) but only the back button of the Jellyseerr UI.

This only happens when clicking the purple "Requested" button, but not when clicking the cogwheel.

### Version

1.6.0

### Steps to Reproduce

1. Open any item with the state "Requested"
2. Click on the purple "Requested" button to open the "Manage" panel.
3. Close the "Manage" panel
4. Hit the back button
5. The "Manage" panel opens again

### Platform

smartphone

### Device

iPhone XS

### Operating System

iOS 16.6

### Browser

Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This has been fixed in recent versions. Feel free to re-open if you still face the same issue
