### ISSUE TITLE
Series fetching info from TMDB and not TVDB

### ISSUE THREAD

**Issue by NekoPavel** [Fallenbagel/jellyseerr#465]
### Description

All media currently prefers to fetch metadata from TMDB.
This causes issues as Sonarr uses TVDB and you get season discrepancies.

### Version

1.6.0

### Steps to Reproduce

1. Search for Jujutsu Kaisen
2. Observe that it shows up as a single season
3. Search it up on TVDB
4. Observe that it is split into several seasons

1. Request Jujutsu Kaisen 
2. Check Sonarr
3. Only the first season out of two is requested 

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/19249984/5ebe437e-862b-41e6-8179-50bff831cae8)

![image](https://github.com/Fallenbagel/jellyseerr/assets/19249984/4ab5a50e-e174-4470-b2e8-879348aa1605)

### Logs

```shell
Do not think this is relevant, but can provide if necessery
```

### Platform

desktop

### Device

Any

### Operating System

Docker on Ubuntu

### Browser

Any

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Series is fetching from tmdb because tvdb api is not free

**Comment by NekoPavel** [comment]
Did some searching, and it seems like [Sonarr](https://wiki.servarr.com/sonarr/faq#how-sonarr-handles-scene-numbering-issues) uses [TheXEM](https://thexem.info/) which is a community driven database. Any chance of using that?

**Comment by Fallenbagel** [comment]
Dont they use [skyhook](https://wiki.servarr.com/sonarr/faq#tvdb-is-updated-why-isnt-sonarr)
