### ISSUE TITLE
Movies in collections not being detected

### ISSUE THREAD

**Issue by colfin22** [Fallenbagel/jellyseerr#473]
I have 3 libraries, TV shows, Movies and Collections but no movies that are in collections are being marked as available. Should Collections be a library item at all? It's not very clear. I've removed Collections to see what the results are after a scan

_Originally posted by @colfin22 in https://github.com/Fallenbagel/jellyseerr/discussions/472_

**Comment by Fallenbagel** [comment]
Please follow the issue template

**Comment by colfin22** [comment]
Sorry, I created the issue from discussion I don't think it offered the template.

I'm running a new scan and will upload my results to a new issue, closing this issue
