### ISSUE TITLE
[BUG] Media don't automatically fill as " available "

### ISSUE THREAD

**Issue by volrod64** [Fallenbagel/jellyseerr#475]
### Description

Hello,
The new update is DOPE. The fact that the user can see how long the download is taking is perfect.
But i have an issue with it. I'm using docker compose, transmission and jellyseer, and I have an issue where even when the movie is downloaded at 100%, it's written " processing " and I have to manually put the movie as " available " 

You can ask me about anything of my configuration or to test anything, i'm down for it.

Thanks for the awesome program !

### Version

1.6.0

### Steps to Reproduce

Download anything
Look at the download task
Go at 100% then just say " processing " even if the media is properly downloaded on Transmission

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/94232342/9bdb6ad7-0d1a-43fa-a3b7-027306254623)
![image](https://github.com/Fallenbagel/jellyseerr/assets/94232342/dcc01e3d-338f-4a8c-a9d0-a34731a12ed5)
![image](https://github.com/Fallenbagel/jellyseerr/assets/94232342/67dfdde8-fec0-49a2-a526-5c08702451e0)

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Theres a problem with your configuration that's why. Could you hop onto discord so we can follow through?I'll update here after

**Comment by volrod64** [comment]
https://discord.com/channels/952656177924300932/1150497243460288593/1150497243460288593
done

**Comment by Fallenbagel** [comment]
Closing this as this was mainly an *arr misconfiguration
