### ISSUE TITLE
[Request] Backup and Restore

### ISSUE THREAD

**Issue by hbednar** [Fallenbagel/jellyseerr#484]
### Description

Unless I have missed something, at the moment there seems to be no way to backup a snap pack installed jellyseerr and no backup documentation for either snap or docker.

### Desired Behavior

Could jellyseerr implement an automated backup and a manual restore function like sonarr and radarr have .
where all configs and db are copied and added to an archive in a backup folder every few days.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
> > Backing up docker is as easy as just copy pasting the config folder.
> 
> Will this include things like jellyseerr user and setings and Sonarr and Radarr settings.
> 
> > As for snap package, we don't officially support it but it'd be the same thing just copy paste the config folder
> 
> Which directory do you mean.

All the settings are in the config folder.

For the snap config folder, it's wherever snap stores it. I'm not sure either I'll update here after I find out in a while

**Comment by Fallenbagel** [comment]
> Which directory do you mean.

I think it is `/root/snap/overseerr/common`

**Comment by hbednar** [comment]
Thanks, i will test that out.

**Comment by hbednar** [comment]
@Fallenbagel 
I tested both docker and snap by backing up the db directory and settings file and it worked with out any issues.
It may be worth adding some documentation on this otherwise it's working.

**Comment by Fallenbagel** [comment]
> @Fallenbagel 
> I tested both docker and snap by backing up the db directory and settings file and it worked with out any issues.
> It may be worth adding some documentation on this otherwise it's working.

Where was the snap config folders again? Did I quote the right path? (I don't use snap so not really sure myself)

**Comment by Fallenbagel** [comment]
> @Fallenbagel 
> I tested both docker and snap by backing up the db directory and settings file and it worked with out any issues.
> It may be worth adding some documentation on this otherwise it's working.

Where was the snap config folders again? Did I quote the right path? (I don't use snap so not really sure)

**Comment by hbednar** [comment]
Your suggestion was right, i tried `/root/snap/jellyseerr/common` and it worked after i started the service again.

**Comment by fdw** [comment]
I'd like to re-open the request, because the `config` folder also contains a `cache` and `logs` - both of which I'm not really interested in restoring.

**Comment by gauthier-th** [comment]
> I'd like to re-open the request, because the `config` folder also contains a `cache` and `logs` - both of which I'm not really interested in restoring.

Then don't copy these files? You can just copy the `config/db` folder and the `config/settings.json` file

**Comment by gauthier-th** [comment]
We are currently working on a docs website for Jellyseerr, it will be added there.

**Comment by Fallenbagel** [comment]
> We are currently working on a docs website for Jellyseerr, it will be added there.

#848. Once that's in we will have docs 😄
