### ISSUE TITLE
[Feature Request] Allow Users to Remove Shows

### ISSUE THREAD

**Issue by theianspence** [Fallenbagel/jellyseerr#487]
### Description

Administrators are able to remove movies/shows from Radarr/Sonarr, which deletes the files from the server. 

### Desired Behavior

It would be super handy if users could have permission to delete media that they requested. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by xabufr** [comment]
duplicate of #393 ?

**Comment by Fallenbagel** [comment]
> duplicate of #393 ?

Yes. Thanks for pointing it out!
