### ISSUE TITLE
Delete request after requesting user watches the content

### ISSUE THREAD

**Issue by CurringtonCloud** [Fallenbagel/jellyseerr#488]
### Description

Delete request after requesting user watches the content. Currently requests stay even after availible and the requesting user watches the content. I have only tested in Jellyfin and not Plex but its not happening for now.

### Desired Behavior

Once the requsting user watches the content in Jellyfin the request is fufilled and shoud be dropped from request list. No changes to the files just remove the request automatically.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
That would break things. That request count is used for many other things like quota and stuff and automatic removal is not how request management softwares work

**Comment by CurringtonCloud** [comment]
Understood, maybe a status change when the user or a user watches it. Would like to know if what is been requested is being watched. It would help with clean up in low storage space times. For users without endless storage. Since Jellyfin knows what has been watched hopefully it can be pulled from the system.

**Comment by gauthier-th** [comment]
Automatically deleting media is not the purpose of Jellyseerr. Its purpose is to manage requests.
You could use something like https://github.com/Schaka/janitorr to delete your media.
