### ISSUE TITLE
Library sync fails if jellyfin initial user is LDAP

### ISSUE THREAD

**Issue by linedpaper** [Fallenbagel/jellyseerr#489]
### Description

403 unauthorized error and unable to make an initial sync of libraries when using my LDAP admin.  When I setup using the local admin account  the libraries sycned with no issue.

### Version

    1.7.0

### Steps to Reproduce

1. Setup Jellyfin with LDAP
2. Setup new Jellyseerr instance and configure using an LDAP admin account.

### Platform

desktop

### Device

docker

### Operating System

docker

### Browser

firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Sulframus** [comment]
Having the same issue, however I can't sync libraries even when trying to use a local account.

**Comment by Fallenbagel** [comment]
> Having the same issue, however I can't sync libraries even when trying to use a local account.

What's the error you get when you try to sync libraries with local account? Make sure local account is admin, and also make sure automstic grouping is disabled

**Comment by Sulframus** [comment]
> > Having the same issue, however I can't sync libraries even when trying to use a local account.
> 
> What's the error you get when you try to sync libraries with local account? Make sure local account is admin, and also make sure automstic grouping is disabled

In the browser console I can see "GET https://sub.domain.tld/api/v1/auth/me 401 (Unauthorized)

![image](https://github.com/Fallenbagel/jellyseerr/assets/50105122/3c473161-4713-406e-ab40-170eae94380a)
"
And also a POST of the above

And that is prior to signing in as well. This is happening for both local and LDAP account now. Yesterday, I was at least able to sign in.

**Comment by Fallenbagel** [comment]
What about the app logs?

**Comment by Sulframus** [comment]
So just enabled debug logs, but the only thing that comes in is about scheduled jobs.

**Comment by Fallenbagel** [comment]
> So just enabled debug logs, but the only thing that comes in is about scheduled jobs.

When you attempt to login there's no log?

**Comment by Sulframus** [comment]
Correct. 
![image](https://github.com/Fallenbagel/jellyseerr/assets/50105122/1d4b01b5-6140-47b5-aa71-13c4f135ddca)

**Comment by Fallenbagel** [comment]
@linedpaper #524 should fix it! :smile:
