### ISSUE TITLE
Hide Items

### ISSUE THREAD

**Issue by spyhuntergenral** [Fallenbagel/jellyseerr#490]
### Description

A per user option to "hide" unrequested media would be pretty cool.
or an admin level option to globally hide certain media.

### Desired Behavior

i.e adding a button to hide/blacklist something from the discover page so that it is no longer shown. 

(I'm thinking specifically of shows/movies that don't already exist, and will never be wanted)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ricerodriguez** [comment]
I would really like to see this feature as well. Radarr's blocklist doesn't seem to work to well as a replacement in the meantime.

**Comment by JoaquinOlivero** [comment]
Hello! I would like to be assigned this issue.

**Comment by Fallenbagel** [comment]
> Hello! I would like to be assigned this issue.

You can go ahead and PR c:
I'll review asap

**Comment by nado** [comment]
Do I understand correctly that this is an admin managed blacklist for all users?
Do you plan on adding a per-user blacklist, would you prefer that I create another issue to track this feature request?

**Comment by Fallenbagel** [comment]
> Do I understand correctly that this is an admin managed blacklist for all users?
> Do you plan on adding a per-user blacklist, would you prefer that I create another issue to track this feature request?

It's not just admin. It's whoever has the permission. You can give them the permission

**Comment by nado** [comment]
> > Do I understand correctly that this is an admin managed blacklist for all users?
> > Do you plan on adding a per-user blacklist, would you prefer that I create another issue to track this feature request?
> 
> It's not just admin. It's whoever has the permission. You can give them the permission

Sure, but is it a common list for all users or can it be per-user (i.e., some users dont care about some type of shows while others wish to see them and won’t want the same blocklist)

**Comment by gauthier-th** [comment]
> > > Do I understand correctly that this is an admin managed blacklist for all users?
> > > Do you plan on adding a per-user blacklist, would you prefer that I create another issue to track this feature request?
> > 
> > 
> > It's not just admin. It's whoever has the permission. You can give them the permission
> 
> Sure, but is it a common list for all users or can it be per-user (i.e., some users dont care about some type of shows while others wish to see them and won’t want the same blocklist)

This is the same list for everybody.
