### ISSUE TITLE
Forward Proxy option

### ISSUE THREAD

**Issue by spyhuntergenral** [Fallenbagel/jellyseerr#491]
### Description

Currently all outbound internet requests follow the default network path, 

### Desired Behavior

Add the ability to set proxy options in the GUI settings

i.e external web requests to "api.themoviedb.org" would get proxied via a network proxy (http/https or socks5)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
If on docker you can set the proxy through the environment (although some people had issues with it, from my testings http/https/socks5) worked pretty well

**Comment by Fallenbagel** [comment]
That's not how you set it

```
environment:
     HTTPS_PROXY=http://192.168.100.1:8000
```

Should be an = sign

**Comment by Fallenbagel** [comment]
> What?? that's just yaml syntax?

Yeah but this is the environment block. In this block its an equal sign. Maybe you might want to read the [docs](https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-environment-attribute)

Or check this https://github.com/Fallenbagel/jellyseerr/issues/343#issuecomment-1738877516
