### ISSUE TITLE
jellyfinUserIds is not iterable from API

### ISSUE THREAD

**Issue by bilyboy785** [Fallenbagel/jellyseerr#492]
### Description

When trying to sync Jellyfin users with Jellyseerr from API i've got : 

```
jellyfinUserIds is not iterable
```

### Version

1.7.0

### Steps to Reproduce

```
curl -X POST 'https://JELLYSEERR_HOST/api/v1/user/import-from-jellyfin' -H 'accept: application/json' -H 'X-Api-Key: XXXXXX'
```

### Platform

desktop

### Device

Macbook Pro M1 Pro

### Operating System

macOS

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Because you're not passing in the jellyUserIds in the body. Body expects jellyfinUserIds to be present:
```
curl -X 'POST' \
  'http://localhost:5055/api/v1/user/import-from-jellyfin' \
  -H 'accept: application/json' \
  -H 'X-Api-Key: xxxxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "jellyfinIds": [
    "string"
  ]
}'
```

**Comment by bilyboy785** [comment]
Thank's ! Is there any way to import all new jellyfin users ?

**Comment by Fallenbagel** [comment]
> Thank's ! Is there any way to import all new jellyfin users ? 

Through the web ui you can easily import all jellyfin users yeah. But any reason why you're importing all users? You don't need to import all users as new users can sign in on their own if you have jellyfin login enabled

**Comment by bilyboy785** [comment]
Ohhhh i missed that ! A user that is not imported can login if the jellyfin login is enable ???

**Comment by Fallenbagel** [comment]
> Ohhhh i missed that ! A user that is not imported can login if the jellyfin login is enable ???

Yes. That's what's the `enable new jellyfin sign-in` option does
