### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by Bondou** [Fallenbagel/jellyseerr#496]
### Description

Hello,

I have a connection problem with Jellyfin. When I try to log in, every user, including the admin, gives me an error message. I tried creating a new user on Jellyfin with the username “test” and the password “test,” but those credentials don’t work either. Can you help me with this issue?
This issue is new; I could connect before, and now it's impossible, even though I haven't changed anything in my configuration.

### Version

I can’t see cuz I can’t log

### Steps to Reproduce

1. Create a new profile in Jellyfin 
2. Log in with this profile in jellyseerr
3. Error message : Something went wrong while trying to sign in.

### Platform

desktop

### Device

Asus rog 

### Operating System

Windows

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by leomrch** [comment]
Hello, same issue, i can't log in my Jellyseerr account i have a 401 error (Unauthorized) and my friends have same problem too...

**Comment by Fallenbagel** [comment]
@leomrch just to confirm, is your issue solved?
@Bondou what about you?

(cant remember if you hopped onto discord or not since this issue wasnt updated afterwards)

**Comment by leomrch** [comment]
Hello, sorry for the late response but i solved the problem by uninstalling and install Jellyseerr again

**Comment by shaneholloman** [comment]
same issue

**Comment by Fallenbagel** [comment]
> same issue

Hop onto discord. With more information
