### ISSUE TITLE
Simply request episodes of a series

### ISSUE THREAD

**Issue by danzirokx** [Fallenbagel/jellyseerr#500]
### Description

A user wanted to ask me for the continuation of the first season of an anime, but they couldn't because the season had already been added (but partially since the rest of season 1 was released later).

### Desired Behavior

It would be really great to have the ability to request episodes one by one. Because a season can be released in two parts, but since it's still the first season, it appears as partially available, and we can no longer request the continuation. 

Thank you very much for your work

### Additional Context

ombi request  :

![image](https://github.com/Fallenbagel/jellyseerr/assets/78000711/8779ff41-9996-4fbe-8ec0-74ed99e7859c)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ojmaster** [comment]
adding onto this, it would be really nice to see what episodes of a season are available instead of just seeing Partially Available.

**Comment by Fallenbagel** [comment]
Duplicate #264
