### ISSUE TITLE
Add ability to request just the pilot (first) episode of a series

### ISSUE THREAD

**Issue by zacps** [Fallenbagel/jellyseerr#502]
### Description

Sometimes I want to try out a series by watching just the first episode, currently I need to request the whole first season to do this.

### Desired Behavior

As title

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by tippfehlr** [comment]
Duplicate of #264. See https://github.com/Fallenbagel/jellyseerr/issues/592#issuecomment-1847836482 why this might take a while.

**Comment by Fallenbagel** [comment]
Thank you @tippfehlr 
Closing this because duplicate
