### ISSUE TITLE
Add more networks

### ISSUE THREAD

**Issue by bdovaz** [Fallenbagel/jellyseerr#503]
### Description

Why don't they match the ones in TMDB?

https://github.com/Fallenbagel/jellyseerr/blob/bd65f940e365d7acd5d820a70b901b1663d5ca17/src/components/Discover/NetworkSlider/index.tsx#L15

Is there any reason that I don't understand? If we go for example to [this page](https://www.themoviedb.org/tv) we will see that there are about 50 networks.

### Desired Behavior

I would like to have relevant networks from my country.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You literally can create a new slider using the pencil icon and select tmdb network and add any networks....
