### ISSUE TITLE
[Feature Request] watch history + third-party viewing history synchronization

### ISSUE THREAD

**Issue by jim608** [Fallenbagel/jellyseerr#508]
### Description

I would like to request a new feature in jellyseerr that would allow users to query their Jellyfin watch history and sync it to third-party websites such as anilist.co or myanimelist.net

This feature would be useful for users who want to keep track of their watch history across multiple platforms. It would also be helpful for users who want to share their watch history with others.

I believe that this new feature would be a valuable addition to Jellyseerr. It would be a useful tool for users who want to keep track of their watch history and share it with others.

Thank you for your time and consideration.

### Desired Behavior

* **Querying watch history:** Users should be able to query their Jellyfin watch history to see a list of all the media they have watched.
* **Syncing watch history:** User watch history are automatically synced to websites such as anilist.co or myanimelist.net

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The syncing to third party websites part should really be done on jellyfin. And there are even now countless plugins that does it to anilist and MAL
