### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by GrabbenD** [Fallenbagel/jellyseerr#509]
### Description

I'm trying to create a user friendly flow for my parents and friends which allows non tech-savvy users to simply browse & discover movies/series then download and stream at highest possible quality from **one single app**.

The vast majority of whom stream directly from a TV use a Android based system (like NVIDIA Shield, Android TV, Chromecast, Firestick, Plasma Bigscreen/Anbox, ..) which itself uses Playstore Apps. **This implies that they have to first navigate to a web browser with a fiddly TV controller, type in a long server address and then do the deed in Jellyseerr which then redirects to another app. Such process isn't as seamless as just opening one app and having everything in one place (to minimize confusion with older people and avoid quality problems due video/audio codecs).**

### Desired Behavior

One idea how this could work is to integrate Jellyseerr directly into Jellyfin's start page. This way no new app would have to be created and it would be possible to utilize all codecs from Jellyfin's browser & mobile apps.

### Additional Context

Any ideas/solutions to this problem are highly welcomed!

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Unfortunately the behavior described:
> One idea how this could work is to integrate Jellyseerr directly into Jellyfin's start page. This way no new app would have to be created and it would be possible to utilize all codecs from Jellyfin's browser & mobile apps.

would not be possible. Jellyseerr can be linked and added to jellyfin using [custom menu links](https://jellyfin.org/docs/general/clients/web-config/#custom-menu-links). In addition, Jellyseerr is a PWA so you can install onto your mobile like any other native app (this also unlocks some cool features like web push notifications [native-like notifications]) and PWA is supported on desktops, macs, android, and iphones (iOS 16+).

**Comment by GrabbenD** [comment]
> would not be possible. Jellyseerr can be linked and added to jellyfin using [custom menu links](https://jellyfin.org/docs/general/clients/web-config/#custom-menu-links).

Nice find, thanks for sharing.
Having Jellyseerr as the front page would be the holy grail.. I tried asking this question in various forums and there's a lot of interest but sadly no real solutions.

On the other hand, there's one project which does this: [Reiverr](https://github.com/aleksilassila/reiverr) but sadly there's no TV/android app yet and some basic features like subtitles are still being worked on (but the lack of developers makes the progress slow)

> In addition, Jellyseerr is a PWA so you can install onto your mobile

The problem are mainly android TVs/Nvidia Shield/.. since they don't support PWA :/
I don't have enough knowledge to know if tweaking Jellyfin app to make a different startpage is even feasible.
Another idea that comes to mind is using Kodi for client/app (with a custom theme to show Jellyserr instead) and Jelly as backend

Wish there was a official way of integrating Jelly and Jellyseerr into one beast 🙁

**Comment by GrabbenD** [comment]
> would not be possible. Jellyseerr can be linked and added to jellyfin using [custom menu links](https://jellyfin.org/docs/general/clients/web-config/#custom-menu-links).

Just a update:
Android TV clients can't actually see Web Links from the suggested workaround.

With Plex there's a baked in 'Discovery' page but I'd much rather use Jellyfin and Jellyseerr if there's a way to combine them into one app

**Comment by Fallenbagel** [comment]
> Just a update:
> Android TV clients can't actually see Web Links from the suggested workaround.
> 
> With Plex there's a baked in 'Discovery' page but I'd much rather use Jellyfin and Jellyseerr if there's a way to combine them into one app

That's because androidTV does not use the Web link. You still cannot combine jellyseerr and jellyfin unless you create a custom app. 

**Jellyseerr is in no way affiliated with jellyfin to be able to combine them.**

**Comment by GrabbenD** [comment]
I know, I'm fishing for more ideas or similar projects!

In the meantime, here's a feature request to display custom menu links in Jellyfin's native clients which would make it possible to have everything contained to one app. For future readers, consider dropping a upvote to make it more visible :) 

https://features.jellyfin.org/posts/2435/custom-menu-links-in-jellyfins-native-apps-using-e-g-webview

**Comment by GrabbenD** [comment]
Here's a update for future readers.

Jellyfin Server has a `--webdir` option which allows you to serve a different webroot other than the default [Jellyfin Web](https://github.com/jellyfin/jellyfin-web) interface. One way would be to tweak Jellyfin Web to display a iFrame of Jellyseerr which would make it visible in the website, Android (mobile) app and Desktop client _(but you have to enable web version in settings)_. Currently only exception is Android TV which is completely native (and I'm not sure what's the status of iOS clients).

I'm still fishing for a better solution 🙂

**Comment by thorbolo** [comment]
@GrabbenD how is fishing going along? Any Updates on this topic?😃

**Comment by GrabbenD** [comment]
@thorbolo Instead of building a native app from scratch (as discussed here), it's much simpler to just add support for D-pad navigation and display Jellyseerr as a WebView from pretty much anywhere:

https://github.com/Fallenbagel/jellyseerr/issues/601#issuecomment-2092917457

**Comment by DinleyH** [comment]
Ah this has been something I have wanted to do for ages, I gave up in the end. Would be very cool to have both of them in one place. Its no big deal having 2 seperate apps for me but some non-techy users who use my jellyfin server would certainly love it.

**Comment by DinleyH** [comment]
> [@thorbolo](https://github.com/thorbolo) Instead of building a native app from scratch (as discussed here), it's much simpler to just add support for D-pad navigation and display Jellyseerr using a WebView from pretty much anywhere:
> 
> [#601 (comment)](https://github.com/fallenbagel/jellyseerr/issues/601#issuecomment-2092917457)

I definitely like the idea of using d-pad navigation for jellyseer on tv's. 

Also on the idea of having jellyseer and jellyfin functionality in a single application, I noticed in the jellyfin api docs there is an endpoint for creating a direct streaming link for a media item. Currently the "play on jellyfin" button on the media items info page on jellyseer is just a link to the media item on jellyfin, but if this endpoint is used:
https://api.jellyfin.org/#tag/Videos/operation/GetVideoStream

You could create a stream link for the item and use that as a media source for the clients built in media player. With some navigation tweaks this would make it possible to request and watch media all in one application. I've been looking into this recently but I only have a basic understanding of jellyseers code.

**Comment by mattish91** [comment]
I may or may not add to this, but i just found an app called "seertv" on google playstore for my android tv device, it loads up jellyseer/overseer from a "local user" account. Might be worth looking at, unfortunatley i couldn't find any github link.

I did how ever find this: https://devmesh.ca/seerrtv

Im going to test it out some. 

Seams to forward all the requests to jellyseer correctly too.

**Comment by gauthier-th** [comment]
I am working on an official Jellyseerr app. The alpha version for Android is done, and a beta version should be published soon. Next versions should include iOS, as well as TV devices.

**Comment by Divinelink** [comment]
Hi everyone, I'm not sure if this the correct place or if it's appropriate to self-promote, in the past months I've been working on a native android app for movies/tv-shows. I've integrated some Jellyseerr features into it, so you can handle authentication and request new media. Started building this because I wanted a faster way to request content for myself, and figured others might find it useful too. The app is open source if you want to check it out, contribute and of course leave some feedback, i'd greatly appreciate it! 

https://github.com/Divinelink/scenepeek-android

**Comment by mrmuiz** [comment]
> I may or may not add to this, but i just found an app called "seerrtv" on google playstore for my android tv device, it loads up jellyseer/overseer from a "local user" account. Might be worth looking at, unfortunatley i couldn't find any github link.
> 
> I did how ever find this: https://devmesh.ca/seerrtv
> 
> Im going to test it out some.
> 
> Seams to forward all the requests to jellyseerr correctly too.

This works perfect !!

**Comment by N-harzallah** [comment]
> > I may or may not add to this, but i just found an app called "seerrtv" on google playstore for my android tv device, it loads up jellyseer/overseer from a "local user" account. Might be worth looking at, unfortunatley i couldn't find any github link.
> > I did how ever find this: https://devmesh.ca/seerrtv
> > Im going to test it out some.
> > Seams to forward all the requests to jellyseerr correctly too.
> 
> This works perfect !! It has a Discord https://discord.gg/9qmuYvjJ

do you know how the app work ?? what are the use case of this api found inside the app ? 

https://seerrtv.devmesh.ca/api/config &  https://seerrtv.devmesh.ca/api/setupid

**Comment by mrmuiz** [comment]
> > > I may or may not add to this, but i just found an app called "seerrtv" on google playstore for my android tv device, it loads up jellyseer/overseer from a "local user" account. Might be worth looking at, unfortunatley i couldn't find any github link.
> > > I did how ever find this: https://devmesh.ca/seerrtv
> > > Im going to test it out some.
> > > Seams to forward all the requests to jellyseerr correctly too.
> > 
> > 
> > This works perfect !! It has a Discord https://discord.gg/9qmuYvjJ
> 
> do you know how the app work ?? what are the use case of this api found inside the app ?
> 
> https://seerrtv.devmesh.ca/api/config & https://seerrtv.devmesh.ca/api/setupid

You can ask him on Discord.

**Comment by LuciferUchiha** [comment]
> I am working on an official Jellyseerr app. The alpha version for Android is done, and a beta version should be published soon. Next versions should include iOS, as well as TV devices.
> Note: this SeerrTV app is not open source, and the developer doesn't seem to have planned to publish the source code.

Is there any more Information on this? Links?

**Comment by gauthier-th** [comment]
> > I am working on an official Jellyseerr app. The alpha version for Android is done, and a beta version should be published soon. Next versions should include iOS, as well as TV devices.
> > Note: this SeerrTV app is not open source, and the developer doesn't seem to have planned to publish the source code.
> 
> Is there any more Information on this? Links?

This is still a WIP. An alpha version is available here: https://github.com/jellyseerr/mobile-app

**Comment by GrabbenD** [comment]
@gauthier-th Great progress! Have you considered expanding this app to Android TV?

**Comment by DinleyH** [comment]
> I may or may not add to this, but i just found an app called "seerrtv" on google playstore for my android tv device, it loads up jellyseer/overseer from a "local user" account. Might be worth looking at, unfortunatley i couldn't find any github link.
> 
> I did how ever find this: https://devmesh.ca/seerrtv
> 
> Im going to test it out some.
> 
> Seams to forward all the requests to jellyseerr correctly too.

Ah this does look ideal, and you can install apks on firesticks if im not mistaken? Its a shame because as always samsung tizen tv's get left behind for these kinda things. I hate tizen and samsungs entire tv app system. It is relatively straight forward to install third party apps on samsung tvs in dev mode, and I can make an app that is full screen and goes to my jellyseer app, the lack of D navigation makes it impossible to use. In theory it sounds simple: add key navigation and integrate some sort of media player, but I tried and it turns out it was way harder than I thought at my skill level :')

**Comment by gauthier-th** [comment]
> > > > I am working on an official Jellyseerr app. The alpha version for Android is done, and a beta version should be published soon. Next versions should include iOS, as well as TV devices.
> > > > Note: this SeerrTV app is not open source, and the developer doesn't seem to have planned to publish the source code.
> > > 
> > > 
> > > Is there any more Information on this? Links?
> > 
> > 
> > This is still a WIP. An alpha version is available here: https://github.com/jellyseerr/mobile-app
> 
> Yo, when do you think you'll be able to release an Android TV version ?

Maybe in a few months? Maybe not. Can't promise anything, but I'll try

**Comment by MaitreGEEK** [comment]
Yay

**Comment by damientkyt** [comment]
> > > > > I am working on an official Jellyseerr app. The alpha version for Android is done, and a beta version should be published soon. Next versions should include iOS, as well as TV devices.
> > > > > Note: this SeerrTV app is not open source, and the developer doesn't seem to have planned to publish the source code.
> > > > 
> > > > 
> > > > Is there any more Information on this? Links?
> > > 
> > > 
> > > This is still a WIP. An alpha version is available here: https://github.com/jellyseerr/mobile-app
> > 
> > 
> > Yo, when do you think you'll be able to release an Android TV version ?
> 
> Maybe in a few months? Maybe not. Can't promise anything, but I'll try

I see that the page says ios supported but the release pages only has a apk/android one.

**Comment by gauthier-th** [comment]
> I see that the page says ios supported but the release pages only has a apk/android one.

Please see https://github.com/jellyseerr/mobile-app/issues/4
