### ISSUE TITLE
Use a single Jellyseerr for Plex and Jellyfin at the same time

### ISSUE THREAD

**Issue by kuesttman** [Fallenbagel/jellyseerr#511]
### Description

It would be interesting to be able to integrate Jellyfin and Plex at the same time, making it possible to synchronize the two servers at the same time, allow users to log in using Plex or Jellyfin, and display the availability link on Plex or Jellyfin with the link to access the content on the respective platforms.
I have a Plex server and a Jellyfin Server, so it would be interesting for me to use just one installation of Jellyseerr for both.

### Desired Behavior

Use a single Jellyseerr for Plex and Jellyfin at the same time

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by le0m** [comment]
From what i've read, Overseerr is decoupling its logic from Plex and they're already in contact with Jellyseerr devs to re-merge the two projects (i donnow if there's been more discussion behind closed doors).
See: https://github.com/sct/overseerr/pull/3015

**Comment by Fallenbagel** [comment]
Also duplicate #100
