### ISSUE TITLE
infinite loop and crash with "JavaScript heap out of memory"

### ISSUE THREAD

**Issue by remisharrock** [Fallenbagel/jellyseerr#513]
### Description

looks like I have an infinite loop and then a crash :

```
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.564Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.565Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":22,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.568Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":21,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.568Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":21,"mediaId":26}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.568Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":23,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.571Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":23,"mediaId":28}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.578Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.582Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":22,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.583Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":21,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.585Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":21,"mediaId":26}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.588Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":23,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.588Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":23,"mediaId":28}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.596Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":22,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.596Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.601Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":21,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.601Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":21,"mediaId":26}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.605Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":23,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.605Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":23,"mediaId":28}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.612Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":22,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.612Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.616Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":21,"mediaId":26}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.617Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":21,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.621Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":23,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.621Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":23,"mediaId":28}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.628Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":22,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.628Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.632Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":21,"mediaId":26}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.632Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":21,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.635Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":23,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.635Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":23,"mediaId":28}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.644Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":22,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.646Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.647Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":21,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.647Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":21,"mediaId":26}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.649Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":23,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.649Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":23,"mediaId":28}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.660Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":22,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.662Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.663Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":21,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.664Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":21,"mediaId":26}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.664Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":23,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.665Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":23,"mediaId":28}


Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.677Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.678Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":21,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.679Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":21,"mediaId":26}
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.680Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":23,"med>
Oct 28 17:41:52 jellyseerr yarn[612]: 2023-10-28T15:41:52.680Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":23,"mediaId":28}
Oct 28 17:41:53 jellyseerr yarn[612]: 2023-10-28T15:41:53.411Z [warn][Media Request]: Media became available before request was approved. Skipping approval notification {"requestId":22,"med>
Oct 28 17:41:53 jellyseerr yarn[612]: 2023-10-28T15:41:53.415Z [warn][Media Request]: Media already exists, marking request as APPROVED {"requestId":22,"mediaId":27}
Oct 28 17:41:54 jellyseerr yarn[612]: <--- Last few GCs --->
Oct 28 17:41:54 jellyseerr yarn[612]: [612:0x6805370]  7526177 ms: Scavenge 1007.1 (1039.9) -> 1000.3 (1039.9) MB, 2.0 / 0.0 ms  (average mu = 0.223, current mu = 0.029) task;
Oct 28 17:41:54 jellyseerr yarn[612]: [612:0x6805370]  7526191 ms: Scavenge 1006.6 (1039.9) -> 1000.4 (1040.2) MB, 2.0 / 0.0 ms  (average mu = 0.223, current mu = 0.029) task;
Oct 28 17:41:54 jellyseerr yarn[612]: [612:0x6805370]  7526905 ms: Mark-sweep 1007.0 (1040.2) -> 996.7 (1040.2) MB, 700.4 / 0.0 ms  (average mu = 0.317, current mu = 0.400) task; scavenge m>
Oct 28 17:41:54 jellyseerr yarn[612]: <--- JS stacktrace --->
Oct 28 17:41:54 jellyseerr yarn[612]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Oct 28 17:41:54 jellyseerr yarn[612]:  1: 0xb87bc0 node::Abort() [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]:  2: 0xa96834  [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]:  3: 0xd687f0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]:  4: 0xd68b97 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]:  5: 0xf462a5  [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]:  6: 0xf471a8 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]:  7: 0xf576b3  [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]:  8: 0xf58528 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/no>
Oct 28 17:41:54 jellyseerr yarn[612]:  9: 0xfc77e4 v8::internal::ScavengeJob::Task::RunInternal() [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 10: 0xe37f3b non-virtual thunk to v8::internal::CancelableTask::Run() [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 11: 0xbf20c4  [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 12: 0xbf552e node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 13: 0x166ad63  [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 14: 0x16805a4  [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 15: 0x166ba27 uv_run [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 16: 0xac7a6d node::SpinEventLoop(node::Environment*) [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 17: 0xbcc984 node::NodeMainInstance::Run() [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 18: 0xb42648 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 19: 0xb4610f node::Start(int, char**) [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[612]: 20: 0x7f9ac5f671ca  [/lib/x86_64-linux-gnu/libc.so.6]
Oct 28 17:41:54 jellyseerr yarn[612]: 21: 0x7f9ac5f67285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
Oct 28 17:41:54 jellyseerr yarn[612]: 22: 0xac3f4e _start [/usr/bin/node]
Oct 28 17:41:54 jellyseerr yarn[611]: Aborted
Oct 28 17:41:54 jellyseerr yarn[595]: error Command failed with exit code 134.
Oct 28 17:41:54 jellyseerr yarn[595]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Oct 28 17:41:54 jellyseerr systemd[1]: jellyseerr.service: Main process exited, code=exited, status=134/n/a
Oct 28 17:41:54 jellyseerr systemd[1]: jellyseerr.service: Failed with result 'exit-code'.
Oct 28 17:41:54 jellyseerr systemd[1]: jellyseerr.service: Consumed 26min 23.806s CPU time.
```

### Version

develop branch pulled the 28 of  october 2023 

### Steps to Reproduce

have an integration with radarr, prowlarr, qbittorrent 
I used the Jellyseerr LXC script to install jellyseer from https://tteck.github.io/Proxmox/

### Platform

desktop

### Device

server site

### Operating System

debian

### Browser

brave

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Don't use develop branch. Thats only for development. And sounds like something is being requested and approved nonstop. Your instance is broken.

**Comment by remisharrock** [comment]
I'm ok using develop branch I may help :) looks like this is reproductible when someone creates a request that have to be validated by the admin, and then, before the admin validates the request, the movie becomes available (thus the message "Media became available before request was approved") .
As soon I validated the request, there is no more infinite loop. For now I will keep it like that and I will try not te be in that situation again, so I have first validate the request then make the video available. 
I'm not sure what is making the request, I guess it's the jellyseer client itself ? Or is it radarr ? Why would radarr make a request... ?

**Comment by Fallenbagel** [comment]
I just did exactly that and I cant replicate it 😐

**Comment by remisharrock** [comment]
So I still can reproduce this error, I pulled the latest version from the develop branch. 
To replicate: 
1 have an installation with SONARR  ;
2  request for a tv show but do not approve the request
3 download manually the tv show and make it avaiable on sonarr and then jellyfin
4 next time jellyseer will do an update it will loop infinitely as described above. 
only way to stop it is to restart the service.

**Comment by Fallenbagel** [comment]
> So I still can reproduce this error, I pulled the latest version from the develop branch. 
> To replicate: 
> 1 have an installation with SONARR  ;
> 2  request for a tv show but do not approve the request
> 3 download manually the tv show and make it avaiable on sonarr and then jellyfin
> 4 next time jellyseer will do an update it will loop infinitely as described above. 
> only way to stop it is to restart the service. 
> 

I still can't reproduce this and I run the latest commit.

**Comment by JHart56474** [comment]
Just FYI I have just had this happen on Stable 1.8.1. Happy to provide any data if its helpful, I immediately say the spike in CPU and restarted the stack

**Comment by Fallenbagel** [comment]
@JHart56474 I still can't reproduce this and I have a fairly huge library. 

Which os? How do you have it installed? Which node version are you using?

**Comment by JHart56474** [comment]
@Fallenbagel  Sure, it's running on Oracle Linux 8, arm64 in Docker Compose version v2.21.0 with Docker version 24.0.6, build ed223bc, Node vers 18.18.2.  Ive saved logs from the event and I can easily recreate it by adding requested Media to my Jellyfin Server and then interacting with the request for that media, either clicking approve or by initiating a Recently Added Scan. However if I approve the request first, before adding the media, it does not happen. 

Sample of Logs : 
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.604Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.604Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.619Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.619Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.632Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.633Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.647Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.648Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.662Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.663Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.679Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.680Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.692Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.692Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.707Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.708Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.723Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.725Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.746Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.747Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.760Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.762Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.791Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.794Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.816Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.818Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.884Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.886Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.901Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.902Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.916Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.918Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.930Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.932Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.943Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.945Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.958Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.958Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.969Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.970Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media became available before request was approved. Skipping approval notification","requestId":6,"timestamp":"2024-05-19T22:25:16.981Z"}
{"label":"Media Request","level":"warn","mediaId":62,"message":"Media already exists, marking request as APPROVED","requestId":6,"timestamp":"2024-05-19T22:25:16.982Z"}


This repeats until its manually reset

**Comment by remisharrock** [comment]
Yes same here, consistently reproducible and having the error " became available before request was approved "
So you request for a film but do not accept the request, then you download and make the movie available (I'm using radar) and then the error occurs at next refresh (with the request still not accepted).
Maybe there is a state where when a request is not accepted and the movie becomes available, this error happens.

**Comment by JHart56474** [comment]
@gauthier-th  Its running on an Arm v8.2+ 64-bit CPU  in the Oracle Cloud with some additional info in the beginning of my last comment. Anything more, just let me know specifically

**Comment by remisharrock** [comment]
AMD Ryzen 5 3600 6-Core Processor 
inside an LXC managed by proxmox

**Comment by Fallenbagel** [comment]
Could one of you try adding this:
if using `yarn start`:
- into the `package.json` replace the start script with:
```json
"start": "NODE_OPTIONS='--max-old-space-size=4096' NODE=production node dist/index.js
```

if using the systemd service add the following environment variable:
```
Environment=NODE_OPTIONS=--max-old-space-size=4096
```

if docker:
```
-e NODE_OPTIONS=--max-old-space-size=4096
```

if docker compose:
```
environment:
     - NODE_OPTIONS=--max-old-space-size=4096
```

**Comment by gauthier-th** [comment]
@JHart56474 @remisharrock we updated Next.js as well as the Node.js version. It's not release yet but it's available with the `update-nextjs` branch or the `preview-nextjs-update` tag.
Could you please try it and check if it resolves your error?

**Comment by Fallenbagel** [comment]
And if possible use the node_options i provided

**Comment by gauthier-th** [comment]
Is this still an issue?

**Comment by Fallenbagel** [comment]
We will close this for now due to lack of update. The provided solution should in theory work by increasing the javascript heap size.

Feel free to re-open if you still have issues.

**Comment by Fallenbagel** [comment]
> same issue. jellyseerr loops infinitely between two requestId `Media already exists...` until memory limit of VM is reached and the complete VM freezes. I assigned the VM 10GB RAM and it is still freezes.

Sounds like your instance might be fucked. We did however fix a lifecycle issue recently so try latest.
