### ISSUE TITLE
Deleted Movies and shows on Jellyfin still show as available

### ISSUE THREAD

**Issue by xenoncolt** [Fallenbagel/jellyseerr#516]
### Description

So, the issue is that I accidentally deleted a few seasons of a show, and now I need them back. When I search for that show on Jellyseerr, it shows that it is available, but I can't find the show's seasons in my drive. This has also happened with movies. I also scan Jellyfin library from Jellyseerr There are some screenshots down below..

### Version

1.7.0

### Steps to Reproduce

---

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/81591350/edb20c6b-7c50-4875-87b8-da5a990b7bb5)
![image](https://github.com/Fallenbagel/jellyseerr/assets/81591350/6a7ab39d-9519-4d4c-a3f0-7830aaa5b8a1)

### Platform

desktop

### Device

Any

### Operating System

Linux

### Browser

Same of all browser

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate #84
