### ISSUE TITLE
Play on Jellyfin uses wrong link structure for Emby

### ISSUE THREAD

**Issue by bruor** [Fallenbagel/jellyseerr#517]
### Description

I'm using Emby, the "play on jellyfin" button doesn't send me to the right place.

It tries to send me to this URL: https://emby:8920/web/index.html#!/details?id=7842534&context=home&serverId=c78909e312474069aed420fbbc7f4cc0

But it should have sent me to this URL: https://emby:8920/web/index.html#!/item?id=7842534&serverId=c78909e312474069aed420fbbc7f4cc0

### Version

1.7.0

### Steps to Reproduce

1. Go to any available media file you can find in search
2. Click on the "Available" button or the "play on Jellyfin" button
3. Url will take you to a blank page on Emby.

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/454516/6241c2f2-b6da-4926-afe7-03c9a127adcf)
![image](https://github.com/Fallenbagel/jellyseerr/assets/454516/0df1b47b-7b2e-4423-be3f-70e20312a6d7)
![image](https://github.com/Fallenbagel/jellyseerr/assets/454516/22349944-85f5-4502-a36f-06c7d916530d)

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Because you didn't add the correct `JELLYFIN_TYPE=emby` environment variable.
