### ISSUE TITLE
Movie is launched in 4K instead of 1080p when both available

### ISSUE THREAD

**Issue by zer0ish** [Fallenbagel/jellyseerr#520]
### Description

Everything is in Unraid dockers with Emby as the media server.

When I have a movie both in 1080p(in my 1080p folder) and a 4K of the movie(in a 4K folder) as seen in SC2 Jellyseer opens emby website to the 4K version even though I selected the 1080p version in Jellyseer. 

Both the 1080p and the 4K have unique Item Id's in emby as seen in SC3

From SC1, if I click Available or Play on emby, the expected behavior would be to open the 1080p version.
If I click the 4K available or the Play 4K on Emby it should open the 4K version.

All my 4K are in their own folder and all my 1080 are in their own folder(SC2) so clicking on either should know where the correct movie is since Jellyseer has the path to that movie and Emby has a unique item id for each.

### Version

1.7.0

### Steps to Reproduce

Got to the movie

Click Available

and then

Go to movie

Click 4K available

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/29928635/d3f46383-cf37-4eff-b1f0-f3d5b79aa88d)
![image](https://github.com/Fallenbagel/jellyseerr/assets/29928635/76407458-3393-4714-88b5-b941c2425b1e)
![image](https://github.com/Fallenbagel/jellyseerr/assets/29928635/90300809-82b0-45ef-b81f-11102e11316e)

### Platform

desktop

### Device

Windows Browser

### Operating System

Window 10 for the clientside, Unraid docker for the server side

### Browser

Brave but happens on Edge, chrome and Firefox too

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by markschrik** [comment]
I have the same issue. Weird part is even users who do not have access to my 4K library, still can access it this way.

**Comment by markschrik** [comment]
@zer0ish Funny thing, I noticed on accident. Someone created an issue for a movie available in HD and 4K. On the issue screen, if I click Play on Emby, it forwards to the HD version. If I click on Play in 4K on Emby, it also forwards to the HD version. This is getting confusing. Do you have this too?

**Comment by zer0ish** [comment]
@markschrik I have my 4K movies library un-synced so users will go to the 1080p version. If they want the 4K ones, they can go to emby directly and select it from the 4K folder there instead of going through Jellyseer for 4K stuff.
At least until it's fixed.

**Comment by Fallenbagel** [comment]
> I have the same issue. Weird part is even users who do not have access to my 4K library, still can access it this way. 

This cannot be fixed until jellyfin api is fixed (I think it was in 10.9.0) because of how jellyfin just hides unrestricted libraries from the ui as opposed to the api

**Comment by Fallenbagel** [comment]
@zer0ish @markschrik could you try the develop tag to see if this issue exists?

You can clear the data of the affected media item from the cog wheel, then do a full scan to see if it properly assigns 4k id to 4k and 1080p to 1080p

**Comment by zer0ish** [comment]
> @zer0ish @markschrik could you try the develop tag to see if this issue exists?
> 
> You can clear the data of the affected media item from the cog wheel, then do a full scan to see if it properly assigns 4k id to 4k and 1080p to 1080p (ref. #805)

Sorry for the late reply to this. Been very busy with other projects.
Can you tell me if this will mess up my production setup for how it currently is?

Or should I create new dockers for Emby and Jellyseerr to test this?

**Comment by gauthier-th** [comment]
> Can you tell me if this will mess up my production setup for how it currently is?

The PR solving this issue is now released. You can update your production setup to the new version of Jellyseerr (1.9.2) and check if it works.

**Comment by zer0ish** [comment]
So I just deleted and reinstalled the Jellyseerr 1.9.2 docker in unraid.

Both HD and 4K show Available but when clicking Play on Emby, it defaults to the 4K. 
Even if I click the green Available button for the HD version it opens in 4K.

Clicking the 4K Available just opens the Manage Movie pop-out sidebar.
![image](https://github.com/user-attachments/assets/c7dbafcd-ad21-4b0f-8ce2-1ff7af77d8e9)


HD ID: 
![image](https://github.com/user-attachments/assets/85964270-24f1-444b-bb0b-ce7b08d84e66)

4K ID:
![image](https://github.com/user-attachments/assets/5e1fb262-96a9-4c5d-8192-8498262e87dd)


When clicking the down arrow on Play on Emby it only shows this, where as before, it would show play 4K on Emby.
![image](https://github.com/user-attachments/assets/c04044d2-9b84-4f94-a071-76da8510577c)

I manually re-ran all the Jobs in the settings one at a time too.
This is my Emby Libraries section showing both a toggled on now:
![image](https://github.com/user-attachments/assets/d079a9c7-dbee-4729-8286-3b0b54f93ab0)

**Comment by Fallenbagel** [comment]
> So I just deleted and reinstalled the Jellyseerr 1.9.2 docker in unraid.
> 
> Both HD and 4K show Available but when clicking Play on Emby, it defaults to the 4K. 
> Even if I click the green Available button for the HD version it opens in 4K.
> 
> Clicking the 4K Available just opens the Manage Movie pop-out sidebar.
> ![image](https://github.com/user-attachments/assets/c7dbafcd-ad21-4b0f-8ce2-1ff7af77d8e9)
> 
> 
> HD ID: 
> ![image](https://github.com/user-attachments/assets/85964270-24f1-444b-bb0b-ce7b08d84e66)
> 
> 4K ID:
> ![image](https://github.com/user-attachments/assets/5e1fb262-96a9-4c5d-8192-8498262e87dd)
> 
> 
> When clicking the down arrow on Play on Emby it only shows this, where as before, it would show play 4K on Emby.
> ![image](https://github.com/user-attachments/assets/c04044d2-9b84-4f94-a071-76da8510577c)
> ![image](https://github.com/user-attachments/assets/7187ae86-8dd6-4161-8689-420931b29eed)
> 
> 
> I manually re-ran all the Jobs in the settings one at a time too.
> This is my Emby Libraries section showing both a toggled on now:
> ![image](https://github.com/user-attachments/assets/d079a9c7-dbee-4729-8286-3b0b54f93ab0)
> 
> 

Do you mean when you hover over the 4k badge it goes to manage model? That's a bug then

**Comment by zer0ish** [comment]
Yes when clicking the green 4K Available it opens that manage panel as seen in the first screenshot.
So I guess the problem is still there for the initial reported issue?

**Comment by zer0ish** [comment]
Ok so after a day of letting it sit. The green Available and 4K Available is now opening the movie in Emby but both in HD instead of one in HD one in 4K. The issue with the 4K one going to Manage Movie panel is now fixed.

But both HD and 4K Available buttons go to the HD version instead of the 4K.
![image](https://github.com/user-attachments/assets/37184381-f3c6-4c50-b1ed-c18506d1814c)
![image](https://github.com/user-attachments/assets/ae45618e-0b8b-4d6a-a736-cda4dbfe249c)

The Play on Emby button goes to HD and the now returned Play 4K on Emby button also goes to the HD version.
![image](https://github.com/user-attachments/assets/f5ad0a0e-4be1-44bd-bb16-fe88fdc32ce5)

**Comment by gauthier-th** [comment]
> Ok so after a day of letting it sit.

I think this is because your new 4k item is not detected as “recently added” by Jellyfin, so it was detected when the “Jellyfin Full Library Scan” task was run (every 24 hours), instead of the “Jellyfin Recently Added Scan” task, which runs every 5 minutes.

> But both HD and 4K Available buttons go to the HD version instead of the 4K.

I think I found your issue, but I don't use Emby so I can't be sure.
Could you please go to the movie page, then go into your browser console (usually with `F12`), go in the `Network` tab, reload your

**Comment by zer0ish** [comment]
> > But both HD and 4K Available buttons go to the HD version instead of the 4K.
> 
> I think I found your issue, but I don't use Emby so I can't be sure. Could you please go to the movie page, then go into your browser console (usually with `F12`), go in the `Network` tab, reload the page, and send me the response of the request of `http://localhost:5055/api/v1/movie/475557`? It should be a JSON

Am I doing this from Jellyseerr Movies section, or from the movie itself, or in emby?

Can you give me a screenshot of what I'm looking for in the network tab of the console?
Sorry, I always get lost in the browser console.

**Comment by gauthier-th** [comment]
> Am I doing this from Jellyseerr Movies section, or from the movie itself, or in emby?

In the movie page itself: http://your.jellyseerr.com/movie/XXXXX

> Can you give me a screenshot of what I'm looking for in the network tab of the console?

![image](https://github.com/user-attachments/assets/067ccfc8-c178-4152-95fb-9d1f2450b6f3)

**Comment by zer0ish** [comment]
I just changed to Firefox since Brave was showing diff results, no JSON just scripts.
![image](https://github.com/user-attachments/assets/688f5fe2-c986-41b8-92c5-ba68f3d544ca)

**Comment by gauthier-th** [comment]
> I just changed to Firefox since Brave was showing diff results, no JSON just scripts. ![image](https://private-user-images.githubusercontent.com/29928635/376349872-688f5fe2-c986-41b8-92c5-ba68f3d544ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzIxNDYsIm5iZiI6MTcyODkzMTg0NiwicGF0aCI6Ii8yOTkyODYzNS8zNzYzNDk4NzItNjg4ZjVmZTItYzk4Ni00MWI4LTkyYzUtYmE2OGYzZDU0NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE4NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MzlhMGVkODg0OTE0MDM2YzA4ZjI1MmFmNGZhNGRlMzgzZGUyYzc1NzhhMzJiZGJjMDcyZWVmMTc2ZWY0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h1fxKkDUfsyNFz2PSZ7Td5rR8E6CALTmpWqPRy_UoYc)

Could you please expand and show me the `mediaInfo` property?

**Comment by zer0ish** [comment]
> > I just changed to Firefox since Brave was showing diff results, no JSON just scripts. ![image](https://private-user-images.githubusercontent.com/29928635/376349872-688f5fe2-c986-41b8-92c5-ba68f3d544ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzIxNDYsIm5iZiI6MTcyODkzMTg0NiwicGF0aCI6Ii8yOTkyODYzNS8zNzYzNDk4NzItNjg4ZjVmZTItYzk4Ni00MWI4LTkyYzUtYmE2OGYzZDU0NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE4NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MzlhMGVkODg0OTE0MDM2YzA4ZjI1MmFmNGZhNGRlMzgzZGUyYzc1NzhhMzJiZGJjMDcyZWVmMTc2ZWY0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h1fxKkDUfsyNFz2PSZ7Td5rR8E6CALTmpWqPRy_UoYc)
> 
> Could you please expand and show me the `mediaInfo` property?

Sorry for the delay, was Thanksgiving in Canada.
Here is what you asked for.
![image](https://github.com/user-attachments/assets/dc7aff21-d259-4fa9-a02a-6517dacec48b)
