### ISSUE TITLE
Apostrophe characters in the search query will lead to an error 500 

### ISSUE THREAD

**Issue by channouze** [Fallenbagel/jellyseerr#523]
### Description

Whenever the user searches for any content that has an apostrophe in its name, Jellyseerr will output an error code 500.

### Version

1.6.0

### Steps to Reproduce

1. Open Jellyseer web ui
2. Type any string character containing an apostrophe (') Alt+0027
3. Observe

### Logs

```shell
That error does not show up in logs
```

### Platform

desktop

### Device

Any

### Operating System

Debian Bookworm

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
![Screenshot_20231106_214556_Chrome.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/b8a93ec0-29fe-4532-be2b-044c969f2f4d)

Did you say you're on 1.6.0? Latest version is 1.7.0

**Comment by Fallenbagel** [comment]
Can you try development branch? Because thats what I'm on. I think thats why

**Comment by channouze** [comment]
Still the same issue unfortunately. This is very weird because backtick, backslashes, quotes in the search query don't generate any error.

**Comment by Fallenbagel** [comment]
> Still the same issue unfortunately. This is very weird because backtick, backslashes, quotes in the search query don't generate any error; where semicolon, exclamation mark do.

![Screenshot_20231108_200259_Chrome Dev.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/bd53685c-0cac-4fbe-b1b2-22cb63bc07aa)

I'm on development branch. I have just tested it on several devices even after installing new on test devices. It works. So probably your instance is having issues with tmdb or sth can you share logs?

**Comment by channouze** [comment]
Here's the redacted log
[overseerr-2023-11-08-redacted.log](https://github.com/Fallenbagel/jellyseerr/files/13299905/overseerr-2023-11-08-redacted.log)

**Comment by Fallenbagel** [comment]
Nothing out of the ordinary. How did you install jellyseerr? 

Can you provide me the chrome devtools console log when the error occurs and also in network tab look for an error.

And if docker is it possible to whip up a new fresh test container with the tag `:develop` with the block
```
dns:
    - 1.1.1.1
    - 1.0.0.1
```
added.

See if you face the same issue on that new container. Because I can't reproduce this on any device

**Comment by channouze** [comment]
I have a baremetal setup (no docker), on an OVH dedicated server hosted in canada
Jellyseerr is installed through a standard git pull

Here's the network log:

> _app-81985b2fadeaef37.js:1 [SW] Registration successful, scope is: https://jellyseerr.***.***/
> _app-81985b2fadeaef37.js:1 [SW] Registration successful, scope is: https://jellyseerr.***.***/
> _app-81985b2fadeaef37.js:1 
>         
>         
>        GET https://jellyseerr.***.***/api/v1/search?page=1&query=I%20don%27t 400 (Bad Request)
> (anonymous) @ _app-81985b2fadeaef37.js:1
> xhr @ _app-81985b2fadeaef37.js:1
> Se @ _app-81985b2fadeaef37.js:1
> request @ _app-81985b2fadeaef37.js:1
> P.forEach._e.<computed> @ _app-81985b2fadeaef37.js:1
> (anonymous) @ _app-81985b2fadeaef37.js:1
> fetcher @ _app-81985b2fadeaef37.js:1
> (anonymous) @ 90082-e04adc662dcdc2aa.js:1
> (anonymous) @ _app-81985b2fadeaef37.js:1
> (anonymous) @ _app-81985b2fadeaef37.js:1
> (anonymous) @ _app-81985b2fadeaef37.js:1
> ri @ framework-6a24ea55bfe2d3c0.js:1
> ki @ framework-6a24ea55bfe2d3c0.js:1
> bi @ framework-6a24ea55bfe2d3c0.js:1
> yi @ framework-6a24ea55bfe2d3c0.js:1
> (anonymous) @ framework-6a24ea55bfe2d3c0.js:1
> ws @ framework-6a24ea55bfe2d3c0.js:1
> ls @ framework-6a24ea55bfe2d3c0.js:1
> S @ framework-6a24ea55bfe2d3c0.js:1
> T @ framework-6a24ea55bfe2d3c0.js:1
> _app-81985b2fadeaef37.js:1 
>

**Comment by Fallenbagel** [comment]
Did you git pull after checking out to development branch? I am also running it like that on the latest commit.

**Comment by channouze** [comment]
I was indeed a few commits behind but still no luck :(

**Comment by Fallenbagel** [comment]
Could you try git cloning to another directory and yarn install and build and start so it's a fresh instance just to see if that works? I'm still unable to reproduce this at all

**Comment by channouze** [comment]
Node version was the culprit :| 
I had 20.x installed, downgraded it to 18 instead and the issue is now gone. Thanks for the support!
