### ISSUE TITLE
"View Collection" button cuts off text of long collection name in desktop view

### ISSUE THREAD

**Issue by cmbarba** [Fallenbagel/jellyseerr#566]
### Description

Media items that belong to a collection with a long name have the collection name cut off in the box with the "view" button to see the collection. For the particular collection show in the screenshot, the problem is not present on mobile since the button is wider, but this may not be the case for collections with even longer names.

### Version

1.7.0

### Steps to Reproduce

1. Go to page for media that is part of a collection with a long name
2. Observe "View" collection button

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/82081846/55601ffe-38ec-4a09-9940-5d75b82174c8)

### Platform

desktop

### Device

PC

### Operating System

Arch Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
https://github.com/sct/overseerr/pull/3696
