### ISSUE TITLE
Exposure of usernames via User ID Guessing in URL

### ISSUE THREAD

**Issue by 844Nick** [Fallenbagel/jellyseerr#569]
### Description

I recently discovered a potential security flaw that allows users to access other users' usernames by manipulating user IDs. When navigating to a profile URL such as https://jellyseerr.example.com/users/[UserID], changing the UserID parameter in the URL to an arbitrary number reveals the corresponding username of that user. This could lead to privacy issues particularly for Jellyseerr/Jellyfin users who use email addresses as usernames.
![image](https://github.com/Fallenbagel/jellyseerr/assets/29069410/b32df85b-4a95-47b4-b982-6824fdbe7ec3)

### Reproduce as end user

End user has only permissions to the request function:
![image](https://github.com/Fallenbagel/jellyseerr/assets/29069410/c70c06ee-0fcc-4237-a8b8-8d47a72e8d02)

**Steps**
1. Log in to Jellyseerr
2. Go to "Requests"
3. Click on the username at the "Modified" date
4. Change the UserID in the URL bar of the browser

To reproduce for testing just open the URL: https://jellyseerr. _yourdomain.com_ /users/2

### Desired Behavior

Protect the user pages for users and only allow access to admins.

### Additional Context

Version:
Stable 1.7.0

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Apparently that is the intended behavior https://github.com/sct/overseerr/pull/3695#issuecomment-1817827774

In your case, you can set a display name on those people using the emails. The display name will be what will appear for others
