### ISSUE TITLE
Requesting TV Show with Sonarr

### ISSUE THREAD

**Issue by h3kt0rx** [Fallenbagel/jellyseerr#573]
### Description

Requesting a TV Show that has the same name but different years with jellyseerr grabbed the wrong one for Sonarr. Solution might be to add year for TV show when adding to Sonarr from jellyseerr?

### Version

1.7.0

### Steps to Reproduce

1. Request "The Curse" (2022) from jellyseerr.
2. Check the imported TV Show in Sonarr.

### Platform

desktop

### Device

PC

### Operating System

Debian

### Browser

Brave

### Additional Context

Docker

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
It adds using the tvdbid. Not the show name. So what this means is if it grabbed the wrong one, then the tvdbid in the externalid thing in tmdb was wrong. Tmdb is an open source database and you can go and fix that yourself too

**Comment by h3kt0rx** [comment]
Thanks for the info!

**Comment by Fallenbagel** [comment]
I just checked. The external ID is correct on tmdb. And I just requested it on jellyseer and the correct one got added to sonarr.

**Comment by h3kt0rx** [comment]
Must be something with my configuration it seems, meh. Thanks 👍

**Comment by Fallenbagel** [comment]
> Must be something with my configuration it seems, meh. Thanks 👍

Could be that previously the external id on tmdb was wrong and thats what was cached on yours. Try again. Delete the curse from sonarr and request rhe curse 2022 from jellyseerr see which gets added
