### ISSUE TITLE
I want to get notifications over synologychat

### ISSUE THREAD

**Issue by horseytr** [Fallenbagel/jellyseerr#588]
### Description

In version 1.7.0, I tried and failed to get the jellyseerr notification by passing in the address from synologychat's webhook, which I set up in the notification-webhook

### Desired Behavior

For many reasons, I always use synologychat, and I like jellyseerr very much. I hope I can get notifications through synologychat.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I assume this issue was solved. If not feel free to reopen.
