### ISSUE TITLE
jellyseer behind and apache

### ISSUE THREAD

**Issue by dieg0nob** [Fallenbagel/jellyseerr#591]
### Description

I have not found a way to configure apache so that jellyseer works for example from https://mydomain.com/jellyseer
dont have baseurl path? 

### Desired Behavior

If it had baseurlpath maybe it would be easier to make it work with Apache
Please, if someone has made it work with Apache, please share the configuration

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is not where this should be asked. Please redirect this question preferably to discord. You could use gh discussion too but our discord is mainly used for support.

Gh issues are for issues, feature requests and bugs.
