### ISSUE TITLE
Letterboxd link

### ISSUE THREAD

**Issue by EliantenHolder** [Fallenbagel/jellyseerr#594]
### Description

I love the fact that jellyseerr gives a link to IMDB/Trakt and MovieDB when on a page for a specific movie, I would love to have a link to the movie on Letterboxd too. Since it's a great source of movie ratings and discussions. Radarr already has a link like this and it would be great if Jellyseerr had one too.

### Desired Behavior

On the page for a specific movie I would like a button with the Letterboxd logo next to the IMDB/Trakt/MovieDB logos that links to the Letterboxd page for the specific movie. 

### Additional Context

This is the PR for adding letterboxd to Radarr if that is helpful: https://github.com/Radarr/Radarr/pull/6300

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Actually that pr is very helpful!
Will look into this and if there's anyone who wants to contribute this is a good, easy fiest issue c:

**Comment by JamesRobb03** [comment]
Hey, I'd be interested in contributing to the repo and was thinking of picking this one up as a first issue. Let me know, thanks :)

**Comment by Fallenbagel** [comment]
> Hey, I'd be interested in contributing to the repo and was thinking of picking this one up as a first issue. Let me know, thanks :)

Ofcourse go right ahead c:
No need go ask for permission 😅
