### ISSUE TITLE
Filter for available media on Jellyfin

### ISSUE THREAD

**Issue by xansone** [Fallenbagel/jellyseerr#597]
### Description

Hey, recently i've changed disk for my server and im starting to upload to new movies without old ones saved in jellyseerr, but I cant check what Jellyseerr currently says is available in one click. 

### Desired Behavior

- Available media on Jellyfin (filter)
- Massive remove of availability data from jellyseer.

### Additional Context

The only thing I am missing is this feature, if I could filter media from my jellyfin and clean it up and make a scan, would be great :) 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Once the availability sync job gets merged it should clean up automatically when something is unavailbel

**Comment by xansone** [comment]
> Once the availability sync job gets merged it should clean up automatically when something is unavailbel

I tried but removed things are still shown up as available, I re-sync library and scanned it and they are still there, I would have to manually clean it up, Am I missing something?

**Comment by Fallenbagel** [comment]
yes. as I mentioned before:
> one the availability sync job gets merged

#522
