### ISSUE TITLE
Establish default (radarr/sonarr) services for particular users 

### ISSUE THREAD

**Issue by LucaDangeloS** [fallenbagel/jellyseerr#599]
### Description

It'd be nice to have the option to force users to use a particular service transparently. That way you could split the folders where media is downloaded for each user and create a division for user groups (provided the media added with jellyseerr is also hidden for other user groups is the recently added tab and you can download duplicate media for each different folder in radarr/sonarr). 

### Desired Behavior

Set the default service on a per-user basis, without the need to give them the permission to select the service used on a request. That media would then be downloaded using this service transparently.

### Additional Context

The different services could be same instances of radarr/sonarr but with different root folders or some other configuration tweak.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by jshaptic** [comment]
How is #945 implementing requested enhancement? It is still not possible to specify default service per user, I think this issue should be reopened.

If anyone will hit this limitation, the only workaround for now is to use app called [redirecterr](https://github.com/varthe/Redirecter)
