### ISSUE TITLE
Support Sonarr v4 Language profile

### ISSUE THREAD

**Issue by Khayoann2** [Fallenbagel/jellyseerr#602]
### Description

Sonarr will release v4.
After testing, one of the breaking change about Language profile will have a direct impact with sonarr integration in jellyseerr : 
- Language profiles have been replaced with Language support in Custom Formats, giving you more control on upgrading

### Desired Behavior

Capability to select the v4 of sonarr when we plug our sonarr to jellyseerr and replace language profile by language support 

### Additional Context

Ref : https://forums.sonarr.tv/t/sonarr-v4-beta/31078

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This will come after #207

**Comment by gauthier-th** [comment]
Language profiles are removed from v4. This is now handled by custom formats and quality profiles.
