### ISSUE TITLE
Project start error

### ISSUE THREAD

**Issue by DrewTheGiraffe** [Fallenbagel/jellyseerr#607]
### Description

After a successful build I get the following error in CMD : 
`C:\Users\user1\Downloads\jellyseerr-main\jellyseerr-main>yarn start
yarn run v1.22.21
$ NODE_ENV=production node dist/index.js
2024-01-01T05:02:10.857Z [info]: Starting Overseerr version 1.7.0
warn  - You have enabled experimental features (scrollRestoration, largePageDataBytes) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

2024-01-01T05:02:12.713Z [info][Notifications]: Registered notification agents
2024-01-01T05:02:12.714Z [error]: EntityMetadataNotFoundError: No metadata for "User" was found.
    at DataSource.getMetadata (C:\Users\user1\Downloads\jellyseerr-main\jellyseerr-main\node_modules\typeorm\data-source\DataSource.js:295:19)
    at get metadata [as metadata] (C:\Users\user1\Downloads\jellyseerr-main\jellyseerr-main\node_modules\typeorm\repository\Repository.js:15:40)
    at Repository.count (C:\Users\user1\Downloads\jellyseerr-main\jellyseerr-main\node_modules\typeorm\repository\Repository.js:160:40)
    at C:\Users\user1\Downloads\jellyseerr-main\jellyseerr-main\dist\index.js:112:45
Note: This command was run via npm module 'win-node-env'
error Command failed with exit code 1.`

I am using the following versions of nodejs: v18.19.0

### Version

main@latest

### Steps to Reproduce

To reproduce, run a fresh install on windows 10 x64 Professional and follow along, you will likely also receive the error. It seems to be getting tied up with the User type thinking its the name or something equivalent. I don't know much about Node so this could be way off. I was attempting to install a fresh clean setup of the main branch. if I should have been testing the dev branch let me know. I will likely switch to that now and see if it builds.

### Platform

desktop

### Device

Dell T3600

### Operating System

Windows 10 Pro

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by DrewTheGiraffe** [comment]
Alright I tried the Dev branch with the same result, after looking on StackOverflow it is something to do with the definition of User or lack there of. I'm sure you Node wizards can figure it out much faster then I can. Please let me know what I need to do haha, and happy new year.

[https://stackoverflow.com/questions/51562162/no-metadata-for-user-was-found-using-typeorm](url)

**Comment by Fallenbagel** [comment]
Please read the release notes. It explains how to fix this.

**Comment by Fallenbagel** [comment]
> Do you mind linking that in your response? I have looked around but only see instructions for Docker and Arch Linux. Thanks for the reply either way.

That's because you're looking at the readme. Not the release notes. https://github.com/Fallenbagel/jellyseerr/releases/tag/v1.7.0
