### ISSUE TITLE
AuthenticationScheme: "CustomAuthentication" was forbidden.

### ISSUE THREAD

**Issue by cmtonkinson** [Fallenbagel/jellyseerr#609]
### Description

(cross-reference to https://github.com/jellyfin/jellyfin/issues/10661#issuecomment-1874239633)

Using jellyseerr (docker) `latest` (1.7.0) with jellyfin (ppa) `10.8.13-1` I am blocked on step 2 of the setup wizard because no Libraries are loading. The jellyseerr log says

`
[Jellyfin API]: Something went wrong while getting libraries from the Jellyfin server: Requests failed with status code 403
`

while the jellyfin server log says

`
AuthenticationScheme: "CustomAuthentication" was forbidden."
`

According to the linked thread, I guess JF changed some datetime handling? Not sure on which side of the equation the problem lies though, so sorry in advance if this is a bad report.

### Version

1.7.0

### Steps to Reproduce

1. Install jellyfin using Ubuntu repository.
2. Create a local jellyfin user/pass.
3. Install jellyseerr latest using Docker.
4. Start the setup wizard.
5. Se that no libraries are populating on Step 2.

### Screenshots

Jellyfin version:
![Screenshot 2024-01-02 at 11 35 05 AM](https://github.com/Fallenbagel/jellyseerr/assets/281467/702cf3e3-03fd-45f2-bcc9-e4a07ce079de)

Jellyseerr version:
![Screenshot 2024-01-02 at 11 36 40 AM](https://github.com/Fallenbagel/jellyseerr/assets/281467/2f2eb938-cab6-411f-80d3-1edf7a4ecaba)

Restarting jellyseerr:
![Screenshot 2024-01-02 at 11 39 08 AM](https://github.com/Fallenbagel/jellyseerr/assets/281467/dc02c0ea-9de3-4ac0-b49c-398ecd568f0d)

And every time I push the "Sync Libraries" button found here:
![Screenshot 2024-01-02 at 11 41 04 AM](https://github.com/Fallenbagel/jellyseerr/assets/281467/05fded9b-fb9b-4509-bfac-75e48d28ef17)

I see these messages in the jellyseerr and jellyfin logs, respectively:
![Screenshot 2024-01-02 at 11 41 44 AM](https://github.com/Fallenbagel/jellyseerr/assets/281467/5b8fff55-78e0-4f06-b2ba-40435790c392)

![Screenshot 2024-01-02 at 11 42 02 AM](https://github.com/Fallenbagel/jellyseerr/assets/281467/7c666786-7759-4ae5-8005-6c706ee9b18f)

---
Interestingly, the image digests from docker hub don't match my system:
![Screenshot 2024-01-02 at 11 45 18 AM](https://github.com/Fallenbagel/jellyseerr/assets/281467/60d941d3-05ef-49f7-bba1-8350553568ea)

### Platform

desktop

### Device

browser

### Operating System

Ubuntu 22.04 / Linux 5.15.0-91-generic

### Browser

chrome/safari

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Did you use an admin account?

**Comment by cmtonkinson** [comment]
That worked, thank you! After logging in with admin user (which I hadn't tried) I imported Jellyfin users and then they are able to log in. Is this expected behavior? In settings I noticed that "Enable New Jellyfin Sign-In (Allow Jellyfin users to sign in without first being imported)" is enabled by default.

**Comment by Fallenbagel** [comment]
> That worked, thank you! After logging in with admin user (which I hadn't tried) I imported Jellyfin users and then they are able to log in. Is this expected behavior? In settings I noticed that "Enable New Jellyfin Sign-In (Allow Jellyfin users to sign in without first being imported)" is enabled by default.

You dont need to import jellyfin users they can login without being imported if that setting is enabled. BUT the admin user as in when you setup jellyseerr you would ofcourse need to set it up using an admin account

**Comment by TMUniversal** [comment]
I'm experiencing this issue as well. My Jellyfin instance does not have an apparent `admin` user, though.
I've tried creating a new user with management permission and access to all libraries, and entering those credentials, which has not resolved the issue.

Is there a way to determine this user, or any other solutions?

**Comment by Fallenbagel** [comment]
> I'm experiencing this issue as well. My Jellyfin instance does not have an apparent `admin` user, though.
> I've tried creating a new user with management permission and access to all libraries, and entering those credentials, which has not resolved the issue.
> 
> Is there a way to determine this user, or any other solutions?

An admin user is the user who has sever management permission in jellyfin. Jellyfin cannot exist without a single admin user.

Your issue might be different and sounds more like a troubleshooting one and we do our troubleshooting on discord. Is it possible to hop onto discord?

**Comment by TMUniversal** [comment]
> An admin user is the user who has sever management permission in jellyfin. Jellyfin cannot exist without a single admin user.

Thank you for clarifying, I do have an admin user, then.

> Your issue might be different and sounds more like a troubleshooting one and we do our troubleshooting on discord. Is it possible to hop onto discord?

Yes, I'd love to get this sorted out. I'll join your Jellyseerr server, and we'll take it from there.
