### ISSUE TITLE
Setup should detect if Jellyfin account isn't an admin

### ISSUE THREAD

**Issue by nicdumz** [Fallenbagel/jellyseerr#610]
### Description

It turns out that for jellyseerr to work, the user used for setup must be an admin in Jellyfin ("Allow this user to manage the server" permission should be true).

That is however not documented and quite hard to discover, leading to setup issues.

### Desired Behavior

The login flow could check for `.Policy.IsAdministrator` boolean property in the returned object after login (https://api.jellyfin.org/#tag/User/operation/AuthenticateUser), and could abort setup if the provided user is not an admin, returning a user-friendly error message in that case.

Additionally, consider if this requirement is worth documenting in https://github.com/Fallenbagel/jellyseerr#pre-requisite-important, thanks!

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by nicdumz** [comment]
(Note that you can check `Policy` objects via `Users/Public`, e.g. `curl http://jellyfin.your.local.domain/Users/Public | jq -r '{user: .[].Name, isAdmin: .[].Policy.IsAdministrator}'`, but this only returns the 'public' users, so this is a partial reply)

**Comment by Fallenbagel** [comment]
> (Note that you can check `Policy` objects via `Users/Public`, e.g. `curl http://jellyfin.your.local.domain/Users/Public | jq -r '{user: .[].Name, isAdmin: .[].Policy.IsAdministrator}'`, but this only returns the 'public' users, so this is a partial reply)

We  could check `/Users/{userId}`. It returns a `"Policy": { "IsAdministrator": true, ...}`

**Comment by nicdumz** [comment]
True but that GetUser endpoint requires authentication, so it sounds like
checking the User object returned during the initial login is just
equivalent.

**Comment by nicdumz** [comment]
Yep, it is the case. It is documented in the https://api.jellyfin.org/#tag/User/operation/AuthenticateUser response sample and I've tested that locally too.
