### ISSUE TITLE
Wrong translation for a button

### ISSUE THREAD

**Issue by LelouBil** [Fallenbagel/jellyseerr#617]
### Description

In users > settings there is a button at the top right to go to the user's profile.
In French, I seed "Voir le profile", there souldn't be an "e" at the end.

At first I wanted to make a PR to fix it, but apparently this string is "Afficher le profil" in the localization files ? So I'm not sure where what I'm seeing is located.

### Version

1.7.0

### Steps to Reproduce

1. Have Jellyseerr in French
2. Go to "users"
3. Edit a specific user
4. Look at the top right

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/13931833/f3b0a7cb-d5de-41c9-a3ab-3828efe99f6b)

### Platform

desktop

### Device

Windows Computer

### Operating System

Windows 10

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Don't make PRs. We have our dedicated jellyseerr [weblate](https://jellyseerr.borgcube.de) now

Also the reason is, its already fixed in develop that's why you're seeing it fixed

**Comment by Fallenbagel** [comment]
Is this still an issue on 1.8.1?

**Comment by LelouBil** [comment]
Nope it's fixed :)
