### ISSUE TITLE
Play on Jellyfin doesn't show sometimes

### ISSUE THREAD

**Issue by ModernOctave** [Fallenbagel/jellyseerr#629]
### Description

If a show is scanned as available in Sonarr before it is scanned in Jellyfin, the "Play on Jellyfin" button does not show.

Example:
![Screenshot from 2024-01-20 18-29-20](https://github.com/Fallenbagel/jellyseerr/assets/84833795/806f6c0d-05dc-4f16-a82e-67e0419fb2b6)

Clearing data, then scanning Jellyfin, waiting until complete and then scanning Sonarr solves the issue.
![Screenshot from 2024-01-20 18-28-37](https://github.com/Fallenbagel/jellyseerr/assets/84833795/6ef96edc-7d7d-4d99-984d-10593e5ffd51)

This happens for both partially and completely available series.

### Version

1.7.0

### Steps to Reproduce

1. Download a new series or clear data for an existing series.
2. Go to jobs and then manually initiate a Sonarr scan and wait till complete.
3. Now initiate a Jellyfin scan (Choose Full Library or Recently Added based on the recency of the series in question).
4. Go back to series page, "Play on Jellyfin" button won't be visible but series will be shown as "Available".

### Platform

desktop

### Device

Desktop

### Operating System

Debian 11

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is a configuration issue. Can you hop onto discord as we do support tickets there and I'll help you fix this.

**Comment by Enthouane** [comment]
Sorry to unearth a closed issue but i'm having the same issue and as i do not use discord i do not have access to your solution...
Can anyone give some clues about this configuration issue you're mentionning ? Thanks.

**Comment by Fallenbagel** [comment]
> Sorry to unearth a closed issue but i'm having the same issue and as i do not use discord i do not have access to your solution...
> Can anyone give some clues about this configuration issue you're mentionning ? Thanks.

Can you send me a picture of one of the affected series, through the file manager/terminal. Which shows all the episodes

**Comment by Enthouane** [comment]
The latest that had this problem is this one : 
![Sans titre](https://github.com/Fallenbagel/jellyseerr/assets/94701334/fe92378d-ab30-418d-a9dc-555aac7c1e03)

**Comment by Fallenbagel** [comment]
> The latest that had this problem is this one : 
> ![Sans titre](https://github.com/Fallenbagel/jellyseerr/assets/94701334/fe92378d-ab30-418d-a9dc-555aac7c1e03)
> 

Thats your issue.1.7.0 doesn't support flat structure (develop does). You need to move everything into a Season 01 folder. And make sure services > sonarr > season folder is checked so all new ones will have season folders.
