### ISSUE TITLE
Page not Found while pressing Play on Jellyfin

### ISSUE THREAD

**Issue by agus4402** [Fallenbagel/jellyseerr#634]
### Description

When i click on the Play on Jellyfin, it shows the 404 message

### Version

1.7.0

### Steps to Reproduce

1. Go to the detail page of your downloaded movie
2. Click on the Play on Jellyfin
3. Error is Shown

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/83419633/a2cc7a77-add8-444a-b169-5a6f75aab51c)
![image](https://github.com/Fallenbagel/jellyseerr/assets/83419633/a1acfe4b-3448-4ece-8768-4260bbfd2340)

### Platform

desktop

### Device

Intel Alder lake 100 minipc

### Operating System

Windows 11

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Please hop onto discord. We do support tickets there.
