### ISSUE TITLE
Deleted items still show as available

### ISSUE THREAD

**Issue by RedPine404** [Fallenbagel/jellyseerr#645]
### Description

Items that have been deleted from the system (outside of Jellyseerr) and are no longer present in Sonarr/Radarr and Jellyfin are still showing as available in Jellyseerr. Broken hyperlinks are also present in the Jellyseerr entry. Sonarr/Radarr scan nor Jellyfin scan appear to fix this issue without manually clearing the data for the item in Jellyseerr.

### Version

1.7.0

### Steps to Reproduce

1. Request item in Jellyseerr
2. Item is downloaded
3. Jellyseerr syncs with Sonarr/Radarr and Jellyfin and marks item available
4. Delete item from Sonarr/Radarr interface
5. Jellyseerr still shows the item as available after sync has been completed

### Platform

desktop

### Device

Desktop

### Operating System

Arch Linux

### Browser

Firefox 122.0

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate #84
