### ISSUE TITLE
Cannot change email for imported accounts

### ISSUE THREAD

**Issue by jakobzudrell** [Fallenbagel/jellyseerr#646]
### Description

The `Email` field for users imported from Jellyfin cannot be changed and always falls back to their username.

This prevents users from getting notifications about events.

### Version

1.7.0

### Steps to Reproduce

1. Go to Users
2. Press `Import Jellyfin Users`
3. Edit a user account & change email
4. `Save changes`
5. User email switches back to username

### Platform

desktop

### Device

MacBook Air M2 (2022)

### Operating System

macOS 14.3

### Browser

Firefox 122.0

### Additional Context

I don't think the platform details above are relevant for this issue since it seems server based.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Why was this issue closed? Did it work? 
(In my testings emails are changeable)

**Comment by jakobzudrell** [comment]
Strangely it worked right after I created the issue 😀

However it there still seems to be a small bug, which does not always accept the change.. Sometimes when I try to update the email it switches back to the default Jellyfin user right upon saving the changes.

If you want, we can reopen the ticket but since it worked for me afterwards I decided to close it.

**Comment by Fallenbagel** [comment]
Yeah, the first time you change your email, it requires a change twice. There's already an issue opened for it so it's good c:

**Comment by jakobzudrell** [comment]
Alright, sorry for the bother in that case :)
