### ISSUE TITLE
Metadata differences with Sonarr result in some episodes not getting fetched

### ISSUE THREAD

**Issue by kyleyee52** [Fallenbagel/jellyseerr#648]
### Description

For some series, Jellyseerr sees all of the episodes as a singular season. 
However, Sonarr on the other hand views the same series as having multiple seasons.
As far as I've seen, this occurs mainly with anime.

As a result of this, requesting "Season 1" using Jellyseerr results in Sonarr only downloading the 1st of many seasons for that show.

Examples of this I've seen so far include Dragon Ball GT and Jujutsu Kaisen.

### Version

1.7.0

### Steps to Reproduce

1. With Sonarr set up, request a show such as "Jujutsu Kaisen" on Jellyseerr (Season 1 which in Jellyseerr contains episodes from seasons 1 and 2, totaling 47 episodes)
2. See that Sonarr only is set to fetch episodes from Season 1 (totalling 24 episodes)

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Unfortunately, we are unable to proceed due to the inconsistent standards employed by tmdb and tvdb in distributing seasons. (Tvdb api is paid)
