### ISSUE TITLE
Jellyseerr is adding the wrong user to tagged requests in sonarr and radarr

### ISSUE THREAD

**Issue by douglasparker** [Fallenbagel/jellyseerr#652]
### Description

Jellyseerr seems to be adding the wrong user as a tag to requested media in radarr and sonarr.

The user is correct in Jellyseerr and when notifications are sent, however the tag for the media is another user.

My (default user) tags are fine. Users are created automatically when they first login to jellyseerr using their Emby accounts.

### Version

1.7.0

### Steps to Reproduce

1. Make sure the tag requests option is ticked for sonarr and radarr.
2. Add multiple users excluding the default admin user.
3. Request media using an account that has logged in via Emby (not the main account)
4. Login to sonarr or radarr and check the tag and see that it belongs to another user.

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/18235822/a9f6d65d-0e92-4330-8373-d595bedddea4)
![image](https://github.com/Fallenbagel/jellyseerr/assets/18235822/2583378b-8b17-41a0-9a61-4165c29c2962)

### Platform

desktop

### Device

Windows

### Operating System

Windows 11 Pro

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Can you try the develop tag?

**Comment by douglasparker** [comment]
> Can you try the develop tag?

Unfortunately, I can’t test the develop tag because I am using preview-postgres.

**Comment by Fallenbagel** [comment]
> > Can you try the develop tag?
> 
> Unfortunately, I can’t test the develop tag because I am using preview-postgres.

Ah then I cant help. This could be an issue with that tag

**Comment by douglasparker** [comment]
> > > Can you try the develop tag?
> > 
> > 
> > Unfortunately, I can’t test the develop tag because I am using preview-postgres.
> 
> Ah then I cant help. This could be an issue with that tag

Okay, let’s keep this issue open and I will test again after preview-postgres gets merged into develop.

**Comment by dr-carrot** [comment]
@douglasparker I can't seem to repro it from fresh installs of sonarr/radarr/jellyseerr. From my investigation, the code is checking for a tag with the prefix: `this.requestedBy.id + ' - '`. If an existing tag exists with the same id but the wrong user, jellyseerr won't correct it or make a new one. Try deleting the tag from sonarr/radarr. Did you migrate to postgres from sqlite?

**Comment by douglasparker** [comment]
> @douglasparker I can't seem to repro it from fresh installs of sonarr/radarr/jellyseerr. From my investigation, the code is checking for a tag with the prefix: `this.requestedBy.id + ' - '`. If an existing tag exists with the same id but the wrong user, jellyseerr won't correct it or make a new one. Try deleting the tag from sonarr/radarr or updating the name (would require running an update against the *arr db). Did you migrate to postgres from sqlite, or is it a fresh install?

This is a fresh install of Jellyseerr, but I am using the same instance of Sonarr and Radarr from when I was using this feature in Overseerr.

I will delete all the tags and hopefully that should clear it up!
