### ISSUE TITLE
Datepicker not displayed correctly

### ISSUE THREAD

**Issue by toskium** [Fallenbagel/jellyseerr#653]
### Description

The datepicker in From and To filters does not expand in width which leads to squished display of the calendar.
See screenshot.

### Version

1.7.0 stable

### Steps to Reproduce

1. Set a filter
2. Chose From or To date

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/15872792/b34d84d5-419d-4501-9d52-9f5add8069fd)

### Platform

desktop

### Device

Desktop PC

### Operating System

Windows 11

### Browser

Chrome Version 121.0.6167.185 (Official Build) (64-bit)

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate #515 and already fixed.
