### ISSUE TITLE
DNS Flooding to api.themoviedb.org

### ISSUE THREAD

**Issue by Seimann** [Fallenbagel/jellyseerr#657]
### Description

Why does Jellyseerr flood the DNS server with 12 requests every 4 seconds? (at any time of the day)
Look at this picture. 88.417 requests in ~one week!

![jelly](https://github.com/Fallenbagel/jellyseerr/assets/21348054/25da26fd-ac9c-4542-815d-1a08fac2a9d7)

All 88.417 entries are = api.themoviedb.org
That's really too much

### Version

1.7.0 Stabil

### Steps to Reproduce

Docker Installation on Unraid

### Platform

desktop

### Device

All

### Operating System

Unraid

### Browser

All

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate of #387

**Comment by Seimann** [comment]
> Duplicate of #387
> 
> Edit: as for the tmdb api, you're literally browsing and hitting the tmdb api for various different things. Either just ignore the tmdb api on adhuardhome/pihole or idk [what you want exactly]

no, that's too many hits to "ignore" them
that should be solved

**Comment by JPVenson** [comment]
@Seimann How would you solve this?
This is how the api is build and what you'r jellyseer instance is requesting / its how you use it.
What did you expect Jellyseer to work like? Imagine every bit of movie data? Ai? Magic?

**Comment by sevenrats** [comment]
the api uses a 24 second ttl. nothing jellyseerr can do about it.
```
------------
    QUESTIONS:
	api.themoviedb.org, type = A, class = IN
    ANSWERS:
    ->  api.themoviedb.org
	internet address = 18.245.96.44
	ttl = 24
    ->  api.themoviedb.org
	internet address = 18.245.96.97
	ttl = 24
    ->  api.themoviedb.org
	internet address = 18.245.96.110
	ttl = 24
    ->  api.themoviedb.org
	internet address = 18.245.96.52
	ttl = 24
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
```

**Comment by sevenrats** [comment]
@Seimann it took me this long to put together that 3 per second is more than 1 every 24 seconds. My guess is your DNS system is failing to honor the TTL properly.  Jellyseerr is not the appropriate place for the fix.
