### ISSUE TITLE
Add ability to specify custom headers when integrating services

### ISSUE THREAD

**Issue by BassMatt** [Fallenbagel/jellyseerr#660]
### Description

Hey all, I'm trying to setup a connection with my radarr/sonarr instance.

I am hosting jellyseerr on my LAN. However, both my radarr/sonarr are outside of my LAN. To establish a connection it seems I have to pass a [Basic Authentication ](https://wiki.servarr.com/radarr/faq#authentication-method) header as well as the API key. I'm able to do this using https://docs.lunasea.app/, and removing the basic auth header messes up the connection.

It also seems like this is a common issue with overseerr as well.
https://github.com/sct/overseerr/issues/3425

### Desired Behavior

When adding a new radarr/sonarr server, jellyseerr should add a field in the configuration settings to add Custom Headers to the request (e.g. Basic Auth headers).

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by BassMatt** [comment]
Apologies, got some more context.

My radarr/sonarr are hosted behind nginx, and it requires basic auth to forward the requests to the servarr instances - similar to the person from that other thread using cloudflare zero trust.

**Comment by Fallenbagel** [comment]
> Apologies, got some more context.
> 
> My radarr/sonarr are hosted behind nginx, and it requires basic auth to forward the requests to the servarr instances - similar to the person from that other thread using cloudflare zero trust.
> 
> I'll need to pass the headers regardless of the servarr instances using basic or form auth on their end to connect.

Oh. Is that a like some seedbox/service provider thing that they add a basic auth or manually added?

**Comment by Fallenbagel** [comment]
> Apologies, got some more context.
> 
> My radarr/sonarr are hosted behind nginx, and it requires basic auth to forward the requests to the servarr instances - similar to the person from that other thread using cloudflare zero trust.
> 
> I'll need to pass the headers regardless of the servarr instances using basic or form auth on their end to connect.

Oh. Is that a like some seedbox/service provider thing that they add a basic auth or manually added?

**Comment by BassMatt** [comment]
Yeah, exactly. For my case I'm using a seedbox provider that has the nginx proxy setup and I don't have control to change.

**Comment by linedpaper** [comment]
I have this same issue.  For me it's all hosted internally, but Jellyseerr lives on my DMZ and radarr/sonarr are internal.  I am unable to connect to them as they need header auth.

**Comment by Fallenbagel** [comment]
If you have a basic auth, I think it will work (for now as a workaround) using your url as:
`http://user:password@domain.com/`

**Comment by Fallenbagel** [comment]
So I will be closing this issue. Feel free to re-open if you can't get it to work
