### ISSUE TITLE
[on the fly change]  while the video is UNPACKING__ allow play... and dont wait to it to finish (for example what if you download a whole season?)

### ISSUE THREAD

**Issue by beansofhell** [Fallenbagel/jellyseerr#661]
### Description

![image](https://github.com/Fallenbagel/jellyseerr/assets/126506518/5409764f-3aa2-46c4-8c11-4d45a52bdc34)
[on the fly change]  while the video is UNPACKING__ allow play... and dont wait to it to finish (for example what if you download a whole season?)

### Desired Behavior

[on the fly change]  while the video is UNPACKING__ allow play... and dont wait to it to finish (for example what if you download a whole season?)

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Sorry? I don't understand the request. Jellyseerr does not play your media?
