### ISSUE TITLE
Extremely slow page load with custom docker network on unRAID

### ISSUE THREAD

**Issue by GlenNicholls** [Fallenbagel/jellyseerr#666]
### Description

When I use a custom docker network for the container `fallenbagel/jellyseerr:latest` on unRAID, the page loads are extremely slow. If I change to `Bridge` network, the web app response times are always fast. I observe this slowness on a custom docker network both through reverse proxy and locally via LAN access of `<IP>:<web GUI port>`.

I figured this was a caching issue, so I kept the custom network active for a week. What I noticed is that with a custom docker network, the dashboard would always take 30s or more to load images/titles and it would still be working on loading as I scrolled. I found myself waiting multiple minutes on numerous occasions for the page to properly load before the web app was usable. However, if I searched for something, the waiting restarted. When I changed back to `Bridge` network, load times are a few seconds for all the page data and I never feel like I'm waiting as the full page loads in that time and search results are loaded and ready as they should.

### Version

1.7.0

### Steps to Reproduce

1. Create custom docker network
2. set Jellyseerr custom network in unRAID to use the custom network
3. open web UI and experience the slowness

### Platform

desktop

### Device

browser

### Operating System

seems to be irrelevant

### Browser

Chrome, Safari, Firefox

### Additional Context

When I set `Network Type: Bridge` and add `&& docker network connect proxy jellyseerr` to advanced setting `Post Arguments:`, I experience the same slowness issues as when I only change the `Network Type: <custom docker network>`. For creating the docker network, I used the command `docker network create <network name>` from the unRAID shell.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by GlenNicholls** [comment]
FYI, this is the recommendation I followed to add a custom docker network while also using `Network Type: Bridge`: https://www.reddit.com/r/unRAID/comments/q2ojh5/using_multiple_docker_networks_in_unraid/

**Comment by Fallenbagel** [comment]
You need to add a dns block to your unraid template. That is set to 1.1.1.1
the issue is dns.

**Comment by GlenNicholls** [comment]
Perfect, that fixes it. Thanks for the tip!

**Comment by Fallenbagel** [comment]
> are you saying you need to set dns always to 1.1.1.1 or that we need to block 1.1.1.1? Why does my default dns not work? I tried updating to `--restart=unless-stopped --dns 1.1.1.1` and it still takes just as long. 

This issue is old. And not related. You need to hop onto discord to confirm whether this issue is the http library issue from v2.

This issue is for v1.
