### ISSUE TITLE
When media is Deleted, Play on Button still exists

### ISSUE THREAD

**Issue by Panda260** [Fallenbagel/jellyseerr#668]
### Description

PR #522 solved the issue where media was no longer marked as Available when deleted
But the "Play on" button still exists and is not removed even through the manual scan

### Version

develop 24.02.2024

### Steps to Reproduce

1. Request something
2. wait until it is availible
3. Deletet it (but don't remove it via jellyseerr)
4. Either wait for all scans to complete or scan manually
5. When the Availible tag is gone the Play on Button still exists

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/52088459/73c8bdd1-d97e-42f3-a781-19694c83056d)

### Logs

```shell
no errors in logs

2024-02-24T13:45:34.153Z [info][AvailabilitySync]: The non-4K movie [TMDB ID 866398] was not found in any Radarr and jellyfin instance. Status will be changed to unknown.
```

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I have narrowed down on this. It seems that the play on button is there only when the media exists on *arr. If that media is also deleted from *arr, then play on button goes away

**Comment by Panda260** [comment]
Hmm okey i Test IT and reply Back

**Comment by Fallenbagel** [comment]
Nevermind that wasnt the issue. Figured it out. It was my mistake i had the wrong type set for jellyfinMediaId(4k) so an empty value could only be set to `undefined` instead of `null` which is not accepted in the sqlite database, therefore, the media was not saved after making the jellyfinMediaId(4k) null when the media is removed.
