### ISSUE TITLE
Fix base URI detection

### ISSUE THREAD

**Issue by ReclinesMC** [Fallenbagel/jellyseerr#669]
### Description

My jellyseerr server is linked to example.com/jellyseerr. Whenever I try to search for anything it resets the domain to example.com/.
Because I am using a host, they do not allow for me to make it jellyseer.example.com, so both me and my users are stuck facing this problem

### Version

v1.7.0

### Steps to Reproduce

1. Have your jellyseerr on a url such as example.com/jellyseerr
2. Try searching for something
3. Cry as it redirects you to example.com

### Screenshots

![msedge-25-12-41-38-VireoXjjJjLZbpsbT83Hsehae](https://github.com/Fallenbagel/jellyseerr/assets/48137058/732d7af9-3947-45b6-a05f-db3b7ec8202d)

### Platform

desktop

### Device

Prebuilt

### Operating System

WIndows 11

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate #97
