### ISSUE TITLE
Non admin user request not being passed to radar/sonarr

### ISSUE THREAD

**Issue by FluffyClaws** [Fallenbagel/jellyseerr#673]
### Description

Non admin users request are not being passed neither to radarr nor sonarr. 

I have multiple profiles and for the admin users it offers to choose one, for non admin it does not. 

The issue persists if there’s only 1 profile in sonarr/radarr, but in this case some times it returns “404 cannot be found”

Same goes for locally created users. 

No issues with admin users. 

### Version

1.7.0

### Steps to Reproduce

1. Login as non admin user
2. Request a media
3. As an admin go to “request”
4. Click on status
5. Check if the “Open in Radarr/Sonarr” button is present 
6. If it is, check if the requested media has been passed to sonarr/radarr. 

### Screenshots

![IMG_2919](https://github.com/Fallenbagel/jellyseerr/assets/77744197/16030b9c-86f1-40d6-8292-c56efe2909af)
![IMG_2920](https://github.com/Fallenbagel/jellyseerr/assets/77744197/b4737a50-d558-49ab-899c-ba6cb49e22e3)

### Logs

```shell
2024-02-28T11:52:39.218Z [warn][Media Request]: There is no default Radarr server configured. Did you set any of your Radarr servers as default?{"mediaId":18,"requestId":26}
```

### Platform

desktop

### Device

N/A

### Operating System

Win10 with Docker Desktop

### Browser

All of them

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by FluffyClaws** [comment]
Setting up “advanced request” for non admin user fixed both of the issues. 

Thanks!

**Comment by Fallenbagel** [comment]
> Setting up “advanced request” for non admin user fixed both of the issues. 
> 
> Thanks!

Still not a fix if you don't enable `default server`. Make sure you do. Because giving advanced request is a very different thing than your actual issue
