### ISSUE TITLE
Add support for Telegram Topics

### ISSUE THREAD

**Issue by Flashky** [Fallenbagel/jellyseerr#674]
### Description

Currently it is only possible to send Telegram notifications to user chats and group chats. 
However, there is a third kind of group chat: [supergroups](https://core.telegram.org/api/channel#supergroups)

Supergroups allow having multiple channels (or topics) inside the same group.

Other *arr apps such as Sonarr, Radarr or Readarr support Telegram notifications for supergroups topics.

**Use case:**
I might have a group with multiple channels that might be used for different bots and people:
- A channel for Jellyseer requests notifications.
- A channel for for Radarr/Sonarr/Readarr notifications.
- A channel for health/status notifications.
- Other common channels for people to talk

**How are topic messages sent:**

Sending a notification to a supergroup is very similar to sending it to a group, using the [sendMessage](https://core.telegram.org/bots/api#sendmessage) endpoint, it just requires one additional field on the payload: 

- `message_thread_id`: Integer _(Optional)_ Unique identifier for the target message thread (topic) of the forum; for forum supergroups only

### Desired Behavior

In the Telegram notification setup section, I would like to have an additional optional field to set the Topic/Channel/Thread id (pick the desired name) just below the chat id field.

See Radarr/Sonarr Telegram notification setup as an example.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
sct/overseerr#3515

**Comment by D3LZ-D3LZ-D3LZ** [comment]
I would love to see this added too!

**Comment by bytebone** [comment]
I am also interested in this. While I'm not super experienced in this tech stack, I cannot imagine this to be super hard to pull off, especially with the (failed to merge) PR on overseer as a reference. So I might sit down on the weekend and attempt an implementation if there is no work being done on this already.

**Comment by Fallenbagel** [comment]
> I am also interested in this. While I'm not super experienced in this tech stack, I cannot imagine this to be super hard to pull off, especially with the (failed to merge) PR on overseer as a reference. So I might sit down on the weekend and attempt an implementation if there is no work being done on this already.

Feel free to open a pr whenever you can! 😊
