### ISSUE TITLE
Connect with both Emby and Plex at the same time.

### ISSUE THREAD

**Issue by MastaG** [Fallenbagel/jellyseerr#675]
### Description

I'm now running two instances on two different vhosts.
One for Emby and one for Plex.
Would be nice if I could run a single instance that supports logging in with both Emby and Plex accounts.

### Desired Behavior

Connect Jellyseerr with both Plex and Emby at the same time, so users of both services can login and request videos.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Duplicate #100
