### ISSUE TITLE
Option to show original titles

### ISSUE THREAD

**Issue by parasiteoflife** [Fallenbagel/jellyseerr#676]
### Description

When we perform a search, Jellyseer lists the entries with their localized title.

### Desired Behavior

Have an option to enable showing the original title in listings.

### Additional Context

Big part of my family is used to the original titles for movies because the localized ones are pretty bad or deviate too much from the original untranslated title. Because of this is confusing for us to search for the original title and be presented with the localized one which more often than not we don't recognize. We could change our language to, say English, but that would change all the text to English which we don't want, the interface is great in our preferred language, even the entry description is great localized, the only thing requested in this issue is the title.

Thank you!

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This seems to be an issue with tmdb api not falling back to English if a localisation is missing
