### ISSUE TITLE
Filter by Rotten Tomatoes Score

### ISSUE THREAD

**Issue by suborbital-melon** [Fallenbagel/jellyseerr#679]
### Description

I like being able to filter media by the TMDB score, however I don't find it's as useful as scores from Rotten Tomatoes. It would be great to also have this as an option to filter by. It would be nice to be able to filter by both Tomatometer and Audience Score (at the same time), like you can on the Rotten Tomatoes website.

### Desired Behavior

When on either the Movies or Series tab, I would like to be able to add a filter based on the Tomatometer and Audience Score from Rotten Tomatoes.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by atnetsolutions** [comment]
I'll add to this, instead of a new feature request...is there a plan to add additional recommendation sources? Rotten Tomatoes, IMDB etc...?

**Comment by gauthier-th** [comment]
> > I'll add to this, instead of a new feature request...is there a plan to add additional recommendation sources? Rotten Tomatoes, IMDB etc...?
> 
> No. Because none of which you mentioned has a publicly accessible api.

Closing this issue because of this.
