### ISSUE TITLE
[Bug] "Play in 4K" visible in Issues despite content not being 4K

### ISSUE THREAD

**Issue by OdinVex** [Fallenbagel/jellyseerr#681]
### Description

I've got an episode with an issue unrelated to video dimensions but the "Play in 4K on Jellyfin" button is still visible/usable when viewed from the Issues section of that episode. The regular content viewed does not have 4K content and only shows "Play on Jellyfin". Dimensions in this case are 1280x960.

### Version

1.7.0

### Steps to Reproduce

1. Create an issue for non-4K content (in this case 1280x960).
2. Viewed on right, "Play in 4K on Jellyfin".

### Logs

```shell
N/A
```

### Platform

desktop

### Device

Custom

### Operating System

Manjaro Linux x64

### Browser

LibreWolf (Firefox-fork)

### Additional Context

I do not have any 4K Radarr/Sonarr either. I don't differentiate.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I cannot replicate this. Check your services > sonarr/radarr do you have default 4k server checked?

**Comment by Fallenbagel** [comment]
Can you check develop tag. I still can't replicate this.

![Screenshot_20240310_102617_Chrome Dev.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/35433c81-b035-40f7-ada3-561bc6190657)

**Comment by Fallenbagel** [comment]
Your connection with jellyfin is messed up. That might be why.

As you can see from my screenshot it's a series. And it's develop tag. I think this is more of a configuration issue and I would suggest you hop onto discord so we can follow through.

**Comment by Fallenbagel** [comment]
> I don't Discord, I'll just wander through trying to figure out how it determines whether something is 4K or not.

First you need to fix your jellyfin connection. I would suggest checking if the container can reach. Or try a complete fresh test container.

**Comment by Fallenbagel** [comment]
I can't recreate it still. I have checked on new instances, new instances, new machines, non of it has 4k in it. This might be an issue from your jellyfin api too. Try a new instance with new jellyfin instance i guess.

**Comment by Fallenbagel** [comment]
> That is unreasonable, given the size of the database and the time it takes to scan (Jellyfin's threading and DB backend is utterly in need of a complete rewrite). How does Jellyseerr come to think of anything as 4K? I'd rather debug it from that end.

I'm talking about a test jellyfin instance with just 1 show...

**Comment by Fallenbagel** [comment]
> Any way I can see that process/information? It's 640x480, old NTSC stuff. Edit: Besides, why would it be correct on the Series page but not the Issues page? This just sounds like an Issues page bug.

It does sound like a bug yes. But if I can't recreate/face the same bug, I can't fix it 🤷‍♂️😔

Desktop view (previously i sent mobile view. Both are series):

![Screenshot_20240311_005444_Firefox Beta.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/6fb3cf53-1118-4bf3-b53a-9f8b1b4d7512)

**Comment by Fallenbagel** [comment]
> Any way I can see that process/information? It's 640x480, old NTSC stuff. Edit: Besides, why would it be correct on the Series page but not the Issues page? This just sounds like an Issues page bug.

It does sound like a bug yes. But if I can't recreate/face the same bug, I can't fix it 🤷‍♂️😔
If you figure it out, feel free to open a pr.

Desktop view (previously i sent mobile view. Both are series):

![Screenshot_20240311_005444_Firefox Beta.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/6fb3cf53-1118-4bf3-b53a-9f8b1b4d7512)

**Comment by Fallenbagel** [comment]
> That looks mobile in Desktop View, not an actual desktop browser (or one with a small resolution and css media-specific sizes kicking in).

Oh yes sorry I attached the wrong screenshot lol hold on

**Comment by Fallenbagel** [comment]
Admin, sonarr unconfigured:

![image-42.png](https://github.com/Fallenbagel/jellyseerr/assets/98979876/6d976511-83d0-4f79-9d27-aec4997caa7a)

Admin, sonarr configured:
![jellyseerr_issue.png](https://github.com/Fallenbagel/jellyseerr/assets/98979876/ce6a3e71-d4c9-4a8a-8e17-07532e57e211)

Admin, different browser, different instance, sonarr 4k configured but no 4k media:
![image-24.png](https://github.com/Fallenbagel/jellyseerr/assets/98979876/cc675c4d-175b-4e98-8d26-6f256009097e)

Admin, different browser, differenct instance, different locale:
![image-43.png](https://github.com/Fallenbagel/jellyseerr/assets/98979876/5b269a54-e829-4475-9c61-b7501b967c19)

User view, no 4k:
![IMG_20240311_011453_054.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/20a69371-e9f4-493d-803a-9c0c248e0706)

**Comment by Fallenbagel** [comment]
> Under both `media` and `season` `status4k` is set to `1` even though no content is 4K. Curious, could the `Add4kStatusFields` migration have caused something? Is 4K status altered by full scans?
> 
> Edit: `"status4k" integer NOT NULL DEFAULT (1)` You've assigned it true by default (`./server/migration/1610370640747-Add4kStatusFields.ts`)?

Could you link to the line and file? I'll have a look when I reach home

**Comment by Fallenbagel** [comment]
> > Admin, different browser, different instance, sonarr 4k configured but no 4k media
> 
> If no 4K media then why does it say 4K? Also, see the comment earlier I made on migrations. Curious why it defaults to 4k for migrations and why it doesn't correct it on full scan. Since migration is ran even on new installs that seems like a curious thing if the server's not scanning when it should. (It populates on new instances, that connection thing was a fluke...)

I meant. No 4k media in jellyfin. It's available in sonarr thays why

**Comment by Fallenbagel** [comment]
> Under both `media` and `season` `status4k` is set to `1` even though no content is 4K. Curious, could the `Add4kStatusFields` migration have caused something? Is 4K status altered by full scans?
> 
> Edit: `"status4k" integer NOT NULL DEFAULT (1)` You've assigned it true by default (`./server/migration/1610370640747-Add4kStatusFields.ts`)?

About this, it came from overseerr:
https://github.com/sct/overseerr/blob/develop/server%2Fmigration%2F1610370640747-Add4kStatusFields.ts#L8

**Comment by Fallenbagel** [comment]
> https://github.com/Fallenbagel/jellyseerr/blob/develop/server/migration/1610370640747-Add4kStatusFields.ts#L8
> https://github.com/Fallenbagel/jellyseerr/blob/develop/server/migration/1610370640747-Add4kStatusFields.ts#L21
> 
> The migration assumes content is 4K because there was never a status before to differentiate. This is ran on every single new instance. I have no idea when Jellyseerr determines a content is 4K or not (when, such as full scan? old content that is scanned again?)

Jellyseerr determines if its 4k or not during the scan. The logic for it is there on the scanner job file hold on

**Comment by Fallenbagel** [comment]
https://github.com/Fallenbagel/jellyseerr/blob/develop/server%2Flib%2Fscanners%2Fjellyfin%2Findex.ts#L261-L357

**Comment by Fallenbagel** [comment]
> > I meant. No 4k media in jellyfin. It's available in sonarr thats why
> 
> What does that have to do with the actual media available? It's supposed to be looking at Jellyfin, isn't it? Besides, my Sonarr doesn't have 4K at all.
>

No. You can have availability from both sonarr and jellyfin. Seperately. That's what the enable scan option does.

**Comment by Fallenbagel** [comment]
> I was just looking at the Sonarr one, the 4K logic is convoluted for sure. Line 85->139. For the Jellyfin scanner, wouldn't season logic for 4K start at 237 rather than 261?

Oh yes that's where. Sorry I'm on mobile rn. But yeah you get the gist. It's very convoluted on how we have to process jellyfin 4k media too. Despite jellyfin api having a `is4K` param in their get items api, that param isn't used anywhere (left out legacy code from emby) so we have to look at the resolutions to determine.

**Comment by Fallenbagel** [comment]
> I was just looking at the Sonarr one, the 4K logic is convoluted for sure. Line 85->139. For the Jellyfin scanner, wouldn't season logic for 4K start at 237 rather than 261?

Oh yes that's where. Sorry I'm on mobile rn. But yeah you get the gist. It's very convoluted on how we have to process jellyfin 4k media too. Despite jellyfin api having a `is4K` param in their get items api, that param isn't used anywhere (left out legacy code from emby) so we have to look at the resolutions to determine.

**Comment by Fallenbagel** [comment]
I'll have a look too in the weekends. Try to recreate your issue. If you wanna give it a go, from the top of my head I would do:

1. Check the api first see if the item that returns has 4k set.
2. Since it only seems to be messing up on issues page, maybe console log the item see what's up.

I'll also add a label to this issue so if there's someone else who can replicate this exact issue, they could look into it c:

**Comment by Fallenbagel** [comment]
> > Since it only seems to be messing up on issues page, maybe console log the item see what's up.
> 
> It only shows on the Issues page for Seasons (not Movies)....and yet the sqlite database shows "status4k=1" (for movies and seasons). I sometimes manually import content but it's never 4K. ¯\\_(ツ)_/¯
> 
> Edit: I stopped the Jellyseerr instance and manually set `status4k` to 0 in media and seasons, started it back up (verified db was correctly adjusted and such, it's fine). Still shows 4K for Season Issues.

Hmm. Well ill try to see if i can debug even though I can't recreate it 🤔

**Comment by Fallenbagel** [comment]
@OdinVex found the issue and fixed it c:

**Comment by Fallenbagel** [comment]
> Is there a summary regarding why it would easily happen to me but not for you? Unfamiliar with the project's internals.

I was able to recreate it on a completely new instance. Issue was the Id was being set regardless instead of conditionally. Movies was already setting it conditionally but [shows weren't](https://github.com/Fallenbagel/jellyseerr/commit/530be4272cce1b0d74d7f4156b8d794cda6ea03f#diff-799b112b3397343d66cfa5140349c7551e63de0bebbf9bf628b7de831f916691L464-R466).
