### ISSUE TITLE
jellyseerr running from develop branch dockerfile keeps asking to reload page.

### ISSUE THREAD

**Issue by mcnugit** [Fallenbagel/jellyseerr#687]
### Description

built the latest docker image from develop branch- now Jellyseerr keeps prompting all users to reload the page. No matter if they click the "reload" button in the prompt, or if they use the browser's reload function (with or without cache), the prompt keeps coming back.

No errors in console or in application log

### Version

develop

### Steps to Reproduce

build Jellyseerr docker image in develop
log in on any browser, any device, any user
click "reload" button in "application update" prompt or reload the page using the browser's "reload" function

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/5922770/4d75ee5d-b396-46da-bea2-16f431a97f65)

### Platform

desktop

### Device

any

### Operating System

fedora (docker host)

### Browser

any

### Additional Context

stopped and started jellyseerr container
cleared browser cache
tried from different device and with different users, same result

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You need to pass in specific commit tag argument `docker build --tag fallenbagel/jellyseerr:develop --build-arg COMMIT_TAG=xxxxxx .` where xxxx stands for the latest commit argument.

Just an fyi, the latest develop tag already exists as the tag `fallenbagel/jellyseerr:develop`.

**Comment by Fallenbagel** [comment]
You need to pass in specific commit tag argument `docker build --tag fallenbagel/jellyseerr:develop --build-arg COMMIT_TAG=xxxxxx .` where xxxx stands for the latest commit argument.

Just an fyi, the latest develop tag already exists as the tag `fallenbagel/jellyseerr:develop`.

**Comment by mcnugit** [comment]
Sure enough, thank you!
