### ISSUE TITLE
'Bad character' when refreshing page behind caddy reverse proxy

### ISSUE THREAD

**Issue by paladincorners** [Fallenbagel/jellyseerr#689]
### Description

My setup has jellyseerr running behind a caddy reverse proxy. When initially logging in to jellyseerr, everything works fine and I can use Jellyseerr. However, if the page is refreshed, or the 'Jellyseerr' logo is clicked, or simply the window is closed and a new window opened (where I go to jellyseerr again), a blank page is returned.

Jellyseerr logs return no errors. However, in caddy, I get the following (redacted) error:

`{"level":"error","ts":xxxxxxxxx,"logger":"http.log.error","msg":"template: /:22: bad character U+FFFD '�'","request":...

If I then delete the jellyseerr login cookie in my browser and refresh the page, login again, then everything works again. Everything also works if I go to jellyseerr.xxx.xxx/discover (without deleting the cookie first).

It is clearly some issue between caddy and jellyseerr, possibly even an issue within caddy itself rather than jellyseerr. Any suggestions on how to resolve this?

### Version

1.7.0

### Steps to Reproduce

1. Run jellyseerr behind caddy reverse proxy
2. Login to jellyseerr
3. Refresh page

### Platform

desktop

### Device

Mac

### Operating System

Mac

### Browser

Firefox & safari

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
It sounds like a caddy configuration issue. Can you hop on discord as we do our support there?

**Comment by Thidsa** [comment]
i dont have that problem

**Comment by paladincorners** [comment]
Hi thank you for the responses. After further testing, yes it is an issue with Caddy. The following lines of code were used to allow only specific IP addresses to access the site:

```
@blocked not remote_ip xxx.xxx.xxx.xxx/xx
templates
respond @blocked "[Message here]" 403
```

Commenting this out resolved the issue. I have not been able to determine what about this is causing the problem, but it is affecting other services too and therefore likely not a Jellyseerr issue.
