### ISSUE TITLE
On invite server URL copy button gives wrong URL 

### ISSUE THREAD

**Issue by remy33** [Fallenbagel/jellyseerr#690]
### Description

After inviting a user, on the Join & download screen server URL shown the right external URL as well as the Open Jellyfin button works just fine, but copy button copy the internal server IP in URL. 

### Version

3.5.1

### Steps to Reproduce

Create new invite
Redeem the invite
Create a user
See that server URL is right ( https://jellyseer.exmple.com )
Click on "copy" botton and paste it.
You can see the internal Jellyfin server IP (https://192.168.X.X:8096)

### Screenshots

[
![msedge_UIbmqu8XOH](https://github.com/Fallenbagel/jellyseerr/assets/16070787/d4c3c79b-edbd-44e4-acc4-a131ef616015)
](url)

### Platform

desktop

### Device

PC / POCO m3 pro

### Operating System

Windows 11 /  Android 11

### Browser

Edge / Chrome

### Additional Context

It should be easy to fix, probably just wrong URL? 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
That is wizarr. Not jellyseerr.
