### ISSUE TITLE
some "Studio" links do not work under Discover

### ISSUE THREAD

**Issue by ret1** [Fallenbagel/jellyseerr#692]
### Description

on the discover page, some links like Walt Disney Pictures (id:2) or Sony Pictures (id:34) give a HTTP 500 (Internal server error). in the overseerr.log, i can see the following mesage:

`2024-03-19T10:02:12.650Z [debug][API]: Something went wrong retrieving movies by studio {"errorMessage":"[TMDB] Failed to fetch movie studio: Request failed with status code 404","studioId":"2"}`

but it works on the TMDB webste itself. for example:
https://www.themoviedb.org/company/2/movie

maybe an issue woth the API?

### Version

1.7.0

### Steps to Reproduce

1. open website to jellyseerr instance
2. click "Discover"
3. click the "Walt Disney Pictures" or "Sony Pictures" logo 

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This has been fixed on the tmdb api side now
