### ISSUE TITLE
Notification for Request Stuck on "Requested"

### ISSUE THREAD

**Issue by JamesRy96** [Fallenbagel/jellyseerr#701]
### Description

I have a few users that like very specific older films. Some of these are not found on indexers due to lack of popularity. 

Some require and interactive search to finding a download manually then marking the request as available. It would be nice to know when I need to check these request and intervene. 

### Desired Behavior

Jellyserr task runs and checks for titles that have a release date before the current date. If the request date is more than x days old (Adding a value for X in settings) and still in the requested status sent a notification to admins or another notification option. 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I'm sorry. im a little confused. Even if you manually add something, jellyseerr would send notification once it's detected as available. If it doesn't, then there's a configuration issue

**Comment by JamesRy96** [comment]
I'm thinking of a notification for if the status doesn't change to processing after X amount of time. 

That way you could manually search in Radarr/Sonarr for a torrent if a suitable release wasn't found from the trackers.
