### ISSUE TITLE
User tag is not added on movies after the second one

### ISSUE THREAD

**Issue by marmata** [Fallenbagel/jellyseerr#705]
### Description

Hi all! This is the first time I'm using the feature to tag requests. I found an issue, the first movie added is all fine, the request is added to sonarr and the tag is created. Subsequent requests from the same user however try to recreate the tag, which ends up with the following error in Radarr:

```
[POST /api/v3/tag]: constraint failed
UNIQUE constraint failed: Tags.Label
code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
```
so the movie is not added at all, altough on Jellyseer side, there's no error and the movie shows normally as "Requested"

### Version

1.7.0

### Steps to Reproduce

1. Make sure under services "Tag requests" is enabled for radarr
2. Request a movie
3. Make sure the movie has been added and tagged correctly in radarr
4. Add another movie from the same user
5. Check if movie added and tagged, or if error in radarr

### Platform

desktop

### Device

Windows 10

### Operating System

Docker

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you hop onto discord? To troubleshoot this? As I cannot reproduce this

**Comment by Fallenbagel** [comment]
Could you hop onto discord? To troubleshoot this? As I cannot reproduce this

**Comment by marmata** [comment]
Oddly enough I can't reproduce myself. I've added other requests which have gone thru successfully. Will come back if it happens again with more details, thanks!
