### ISSUE TITLE
Jellyseerr forces full series search instead of just the selected season

### ISSUE THREAD

**Issue by Atakku** [Fallenbagel/jellyseerr#710]
### Description

When I try to request one more season to a partially available series jellyseerr seems to request sonarr to perform a full series search instead of just the new season(s) i requested, which can take quite a while with large shows, and lead to issues

### Version

1.7.0 (docker.io/drcarrot/jellyseerr-postgres)

### Steps to Reproduce

1. Request another season on partially available series
2. Watch as sonarr sends requests to indexers looking for S1, S2, S3, and finally S4

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you hop onto discord. This is a common configuration issue and we do troubleshooting there.

**Comment by gauthier-th** [comment]
Can this be closed?

**Comment by PCJones** [comment]
> Can this be closed?

No. It's still a problem

**Comment by Fallenbagel** [comment]
> > Can this be closed?
> 
> No. It's still a problem 

Can you detail how to reproduce this then? Because none of us can.

**Comment by PCJones** [comment]
> > > Can this be closed?
> > 
> > 
> > No. It's still a problem
> 
> Can you detail how to reproduce this then? Because none of us can.

The issue has been explained a bit more here:
https://github.com/Fallenbagel/jellyseerr/pull/711

You might need to set "Upgrade Until Custom Format Score" in your Sonarr quality profile to a really large number so that sonarr will (in theory) always look for upgrades and is never satisfied (as is recommended by TRaSH Guides). If you still can't reproduce it that way I will try to create a step by step guide with a clean sonarr instance to see what exactly are needed to reproduce this

**Comment by Fallenbagel** [comment]
> You might need to set "Upgrade Until Custom Format Score" in your Sonarr quality profile to a really large number so that sonarr will (in theory) always look for upgrades and is never satisfied (as is recommended by TRaSH Guides).

I already have that enabled. I just requested just season 2 of a series and i got just season 2 only

**Comment by PCJones** [comment]
Alright, I'll look into a step by step guide. It'll take a while as I'm currently on vacation

**Comment by gauthier-th** [comment]
I can reproduce this
