### ISSUE TITLE
Cannot set Discover Region to All Regions

### ISSUE THREAD

**Issue by JonHodgins** [Fallenbagel/jellyseerr#712]
### Description

Discover Region cannot be set to All Regions after it has been set to a specific region. 

### Version

1.7.0

### Steps to Reproduce

1. Go to Settings
2. Change "Discover Region" to anything except "All Regions"
3. Save
4. Change "Discover Region" to "All Regions"
5. Save
6. Refresh page (will have reverted to the previous region)

### Platform

desktop

### Device

desktop

### Operating System

Windows

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Workaround is to stop jellyseerr go to config folder open settings.json and change from there from for example "de" to ""

And restart.

This is already a fixed issue in develop.
