### ISSUE TITLE
Can not connect to Emby after update from 1.7.0 to 1.8.1

### ISSUE THREAD

**Issue by mjtbrady** [Fallenbagel/jellyseerr#722]
### Description

Running Jellyseerr and Emby on OpenMediaVault 7 with the OpenMediaVault Compose plugin.

Emby is in one compose file with host networking.  Jellyseerr in another compose file with bridged networking.  Both have been working well for some time and there have been several upgrades to both since the original install.

After updating Jellyseerr from 1.7.0 to 1.8.1 (1.8.0 does the same thing) today everything requiring a connection to Emby stopped working. Down grading to 1.7.0 with no other changes gets everything working again.

After much digging and going around in circles I found that changing "Settings -> Emby -> Internal URL" from a URL with the FQDN of the Emby server to a URL with the IP address of the Emby server gets everything working with 1.8.1.

I have included the log entries for a sync job failing on 1.8.1 with the FQDN still in place.

### Version

1.8.1

### Steps to Reproduce

1. Upgrade to 1.8.1.
2. Attempt to login with Emby user ID.

### Logs

```shell
2024-04-19T04:10:00.025Z [info][Jobs]: Starting scheduled job: Jellyfin Recently Added Scan
2024-04-19T04:10:00.025Z [info][Jellyfin Sync]: Jellyfin Sync Starting {"sessionId":"71d1726b-c18c-4bf3-8c95-02a5a70d1601"}
2024-04-19T04:10:00.028Z [info][Jellyfin Sync]: Beginning to process recently added for library: Concerts
2024-04-19T04:10:00.029Z [error][Jellyfin API]: Something went wrong while getting library content from the Jellyfin server: connect ECONNREFUSED ::1:8096
2024-04-19T04:10:00.030Z [error][Jellyfin Sync]: Sync interrupted {"errorMessage":"Invalid auth token"}
```

### Platform

desktop

### Device

Surface Pro

### Operating System

Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Can you hop onto discord. This looks like a config issue.

**Comment by M0NsTeRRR** [comment]
Hello @mjtbrady it appears that the FQDN you are using resolve to `::1` it's the loopback address like `127.0.0.1`. Can you tell me which FQDN you put in your configuration ?

**Comment by M0NsTeRRR** [comment]
Okay, I've looked into the issue, and it seems that Node 17 (from changelog) prefer IPv6 over IPv4 for DNS resolution. This behavior has changed since the latest version of Jellyseer.js, which was using version 16. Currently, we're using Node.js 18.

To force IPv4 resolution, you can add an environment variable to the Jellyfeer container: `NODE_OPTIONS='--dns-result-order=ipv4first'`

You could also fix your ipv6 setup to avoid this workaround (would be better).

**Comment by mjtbrady** [comment]
@M0NsTeRRR thanks for looking at this.  

The change with Node's behavior looks like it is the trigger for what I am seeing, but the underlying cause is that the FQDN for Emby absolutely should not be resolving to ::1.  I will look into that.

**Comment by mjtbrady** [comment]
Found it almost immediately.

The problem is that on the openmediavault host that is running Jellyseerr and Emby, there is an entry in the /etc/hosts file for ::1 with the FQDN.  There shouldn't be.  On openmediavault the /etc/hosts file is generated, so I believe that the root cause of this problem lies with openmediavault.

**Comment by M0NsTeRRR** [comment]
Your welcome, I got exactly the same issue regarding IPv6 so i've looked into it :)
Glad you found your DNS resolution issue :)

**Comment by j-seixas** [comment]
@mjtbrady did you remove the ipv6 entry in OMV /etc/hosts? Or how did you resolve this?
I dont seem to be able to make it work with the `NODE_OPTIONS='--dns-result-order=ipv4first'`. Do I add it as an env in the docker compose file?

**Comment by mjtbrady** [comment]
The problem is that when IPv6 is set to auto in the OMV GUI, an incorrect hosts file is generated.  You will see in the hosts file that the OMV FQDN and hostname resolves to ::1. Which is very wrong and is what is causing the error.  

I did not try setting NODE_OPTIONS.   I have configured IPv6 statically in the OMV GUI.  This results in a correctly generated host file.  You could try setting IPv6 to "none" and see if that generates a correct file if you don't have/want IPv6.

**Comment by j-seixas** [comment]
Hmm, but from day 1 I've ipv6 disabled in my network interfaces, so it's not fixed by changing that. I will probably open a ticket in omv foruns to check this

**Comment by votdev** [comment]
> Found it almost immediately.
> 
> The problem is that on the openmediavault host that is running Jellyseerr and Emby, there is an entry in the /etc/hosts file for ::1 with the FQDN. There shouldn't be. On openmediavault the /etc/hosts file is generated, so I believe that the root cause of this problem lies with openmediavault.

Hostname and FQDN are added with reason here to fix a SaltStack name resolution bug which otherwise causes the deployment of SaltStack states to take minutes instead of seconds.
