### ISSUE TITLE
Jellyseerr content link redirects to homepage. 

### ISSUE THREAD

**Issue by Sarin-jacob** [Fallenbagel/jellyseerr#723]
### Description

Whenever jellyseerr content link (eg baseurl/{mediatype}/id) is opened(android) from another app(gmail, telegram, ntfy) it gets redirected to login page then homepage. 

### Version

1.8.1

### Steps to Reproduce

Click on any link to jellyseerr notification from email app  on android

### Platform

smartphone

### Device

Android phone

### Operating System

Android 13

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This issue is related to reverse proxy (where the configuration wasn't setup right. On nginx proxy manager.)
