### ISSUE TITLE
Can't scroll past a certain point in "Upcoming Series"

### ISSUE THREAD

**Issue by ioqy** [Fallenbagel/jellyseerr#724]
### Description

When scrolling through "Upcoming Series" it get's stuck after the second "page" (I can see that it loads new items 2 times).

I can see in the network requests of the browser, that there are continuous requests with the same URL `http://jellyseerr/api/v1/discover/tv?page=1&firstAirDateGte=2024-04-19` at a rate of about 30 requests per second.

The same happens in different Browsers (Firefox and Chrome) and on different devices (Windows PC and iPhone)

"Upcoming Movies" works fine.

### Version

1.8.1

### Steps to Reproduce

1. Open "Upcoming Series" from the "Discover" start page
2. Scroll down

### Platform

desktop

### Device

Windows PC and iPhone

### Operating System

Windows 10 and iOS 17.4.1

### Browser

Firefox, Chrome and Safari

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
I can't reproduce this, is this still the case for you?
If yes, what Discovery Region and Discovery Languages are you using (in your settings)?

**Comment by ioqy** [comment]
Kind of. There are no more requests in the background but the page still ends after scrolling down two times, which totals to just 86 displayed TV shows.

I am using the discovery region United States and discovery language English and German. I also tried it with only English and All Languages but the result is the same.
