### ISSUE TITLE
Discover Language Not Filtering

### ISSUE THREAD

**Issue by randellhodges** [Fallenbagel/jellyseerr#733]
### Description

Region and language is set:
![image](https://github.com/Fallenbagel/jellyseerr/assets/7727467/63b669d6-18c6-4dbb-b5dd-2cc5b856fd0c)

Items that are not english are included:
![image](https://github.com/Fallenbagel/jellyseerr/assets/7727467/ef01867a-009e-4834-a424-c0b21943166f)
![image](https://github.com/Fallenbagel/jellyseerr/assets/7727467/fe87ef55-f4f3-4db9-b92c-6e91b43a89f7)

The original issue https://github.com/Fallenbagel/jellyseerr/issues/293 mentioned search, but this isn't search, as you can see discover is in the url (or did I misunderstand the original issue).

Not sure if this is a bug, or a feature request, but looking at the "original language" and being able to globally filter across earch/discover, etc, would be great.

Thanks for maintaining Jellyseerr. I've only discovered this app just yesterday and it is going to improve things for me tremendously.

Edit: It might just be "trending". I see it has filtering when I go to the movies section under discover.

### Version

1.8.1

### Steps to Reproduce

See screenshots for configuration

### Platform

desktop

### Device

browser

### Operating System

docker

### Browser

edge

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
Discovery Language should not filter the trending page but all other pages. It does not makes a lot of sense to filter the trend page as the filtered results would be irrelevant.
