### ISSUE TITLE
Update avatar path when changing ServerURL

### ISSUE THREAD

**Issue by MadaxDeLuXe** [Fallenbagel/jellyseerr#737]
### Description

- have jellyfin: jellyfin.example.com
- install jellyseerr and import users
- in DB: avatars will be: "https://jellyfin.example.com/Users/someUserId.........."
- change jellyfin server url to media.example.com

- all avatars have been broken: still "https://jellyfin.example.com/Users/..." in jellyseerr DB, needed to update the url manually

### Desired Behavior

Change avatar location in Jellyseerr DB if new jellyfin url != old jellyfin url

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Jellyseerr db does not save the avatar path.

It uses whatever you put in settings > jellyfin > externalHosthame. And directly requests the avatar. It does not cache.

You didn't update the externalHostname.

**Comment by MadaxDeLuXe** [comment]
Hey. Sorry for the late answer. I had seen ur anser - wasn't home & couldn't check. But I could have sworn I put the right adresses in. Local was set to the local IP of my reverse proxy and external to the FQDN. 

Well if it just reads it & puts it's there I guess it was on my end. It had been 2 long days and I was quite tired... However.. Maybe I f*ked something up with the split DNS setup I was working on, too. Changing those values manually was a quick fix.

**Comment by Fallenbagel** [comment]
> Hey. Sorry for the late answer. I had seen ur anser - wasn't home & couldn't check. But I could have sworn I put the right adresses in, of course! :D. Local was set to the local IP of my reverse proxy and external to the FQDN. 
> 
> Well if it just reads it & puts it's there I guess it was on my end. It had been 2 long days and I was quite tired... However.. Maybe I f*ked something up with the split DNS setup I was working on, too. Changing those values manually was a quick fix. But I'll keep it in mind now ! :P
> 
> Now everything is runnning nice as usual.
> 
> Thanks a lot, it's awesome!
> 

After setting the externalHostname, you have to restart for the effect to take change on the avatar urls. That probably was it
