### ISSUE TITLE
Emby Recently Added Scan

### ISSUE THREAD

**Issue by PH1L900D** [Fallenbagel/jellyseerr#739]
### Description

Emby recently added scan is not detecting recently added Movies (untested for TV Shows)

### Version

1.8.1

### Steps to Reproduce

1. Request movie in Jellyseerr
2. Wait for movie to be downloaded and added to Emby
3. Run recently added scan in Jellyseerr

### Platform

smartphone

### Device

Samsung Galaxy A52s

### Operating System

Android 14

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by pine-serpent** [comment]
also on 1.8.1 and experiencing the same issue.

**Comment by PH1L900D** [comment]
Now tested for TV Shows. Same issue

**Comment by Fallenbagel** [comment]
This is pretty sure a configuration issue.
Could you both hop onto discord? For troubleshooting. We don't do that here.

**Comment by PH1L900D** [comment]
Yep, see: https://discordapp.com/channels/952656177924300932/1235451310736674816

**Comment by PH1L900D** [comment]
Resolved by https://discord.com/channels/952656177924300932/1191760464359735448

**Comment by ChrisMoriarty** [comment]
Hey! Sorry to revive this, but is there an equivalent fix for Jellyfin instead of Emby?  I'm having the same problem, although the fix from discord: "emby dashboard > library > advanced library and change the date added to library scanned time" isnt the same on Jellyfin, and even after digging around I can't find a similar setting.

**Comment by Fallenbagel** [comment]
> Hey! Sorry to revive this, but is there an equivalent fix for Jellyfin instead of Emby?  I'm having the same problem, although the fix from discord: "emby dashboard > library > advanced library and change the date added to library scanned time" isnt the same on Jellyfin, and even after digging around I can't find a similar setting.  

Jellyfin > dashboard > library> display > date scanned
