### ISSUE TITLE
Jellyfin full library scan not working

### ISSUE THREAD

**Issue by Doug411** [Fallenbagel/jellyseerr#741]
### Description

If I execute a full library scan under jobs and cache.  I get the following error messages:

```
Something` went wrong while getting library content from the Jellyfin server: Request failed with status code 401
Sync interrupted
```
If I click on start scan under the Jellyfin (manual scan).  Nothing happens.

However, "recently added" scan works as expected.

The net result is that all my movies in Radarr show as 'available' in JellySeerr.  However, only those movies added from JellySeer, or recently added in Jellyfin have a 'Play on Jellyfin' button.   The majority of my library does not have the button.

FYI, I am logging into Jellyseer with my Jellyfin login, which is using LDAP authentication through Authentik.  Everything else works as expected.

### Version

1,8.1

### Steps to Reproduce

1. Go to Settings.  2. Go to Jobs and Cache.  3.  Click on Jellyfin full library scan run now.

### Platform

desktop

### Device

MS-01

### Operating System

Ubuntu 22.05/docker

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is a configuration issue. Please hop onto discord for further support queries. We do not carry out support here.

**Comment by pafade89** [comment]
@Fallenbagel 

Hello, I have the same problem. On the first start after installing Jellyseerr, it runs for a while and then suddenly an error occurs, and the sync no longer works.

`2024-06-05T06:30:00.052Z [error][Jellyfin API]: Something went wrong while getting library content from the Jellyfin server: Request failed with status code 401`

**Comment by Fallenbagel** [comment]
This probably is an expired auth token. A log out and log back in should fix this issue.
