### ISSUE TITLE
[Feature Request] Remove media once no users are requesting it anymore.

### ISSUE THREAD

**Issue by ShadowJonathan** [Fallenbagel/jellyseerr#743]
### Description

Currently, our family jellyfin is filling with stuff that my family wants to see, however, this is also takin up a lot of storage on the NAS.

I'd like to be able to say to them "Just remove the request on stuff you dont watch/have watched", so they can organise their own requests, following a quota I'll then add.

However, currently, when a request is removed, the media stays behind, unlinked to jellyseerr.

### Desired Behavior

When a user removes a request, and no other requests are present for that media by any other user, the media should be deleted.

This could possibly clash with outside media management, so a queue should be presented to the admin to process these requested deletes, something a-la https://github.com/Fallenbagel/jellyseerr/issues/488.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You can already delete media from jellyseerr...

**Comment by ShadowJonathan** [comment]
Yes, but i'd like to have it be automatic once the request that created some media is also then able to delete it automatically

**Comment by Fallenbagel** [comment]
> Yes, but i'd like to have it be automatic once the request that created some media is also then able to delete it automatically

Deleting requests should not delete the media. That would lead to accidental media loss and other complications, too. 

Original plan was to never let media to be deleted from jellyseerr as it could lead to such situations (since jellyseerr/overseerr is not a media management software), but due to constant requests that delete button was added. And that is now behind admin permission, too, for that purpose.

We now have a media availability sync job that currently two-way syncs, so the flow should be automatically deleting the media from either jellyfin (plugin), sonarr or radarr, and not jellyseerr.

**Comment by ShadowJonathan** [comment]
> Deleting requests should not delete the media. That would lead to accidental media loss and other complications, too.

yes, this is why im making the feature request; I want this to be configurable, and a admin queue to delete media from radarr and the likes.

**Comment by ShadowJonathan** [comment]
> However, we will not support automatic media deletion when requests are deleted.

Why not? This is a simple feature request: if all users have removed requests for a certain media -> add it to the delete queue for the administrator to remove.

**Comment by Fallenbagel** [comment]
> > However, we will not support automatic media deletion when requests are deleted.
> 
> Why not? This is a simple feature request: if all users have removed requests for a certain media -> add it to the delete queue for the administrator to remove.

I just explained why. Accidental media loss is something we try to prevent. Why overseerr rejected media removal as well. 

Simply put, out of scope. If you meant it like media removal request where admin has to approve, then that's different. But if you want automatic removal when requests are deleted (which is also not designed to be deleted. Only designed to be deleted when you remove the MEDIA not the other way around.)
