### ISSUE TITLE
Request ability to change profile pic.

### ISSUE THREAD

**Issue by devanteweary** [Fallenbagel/jellyseerr#747]
### Description

Basically just wanna be able to have myself and my users be able to go to their profiles and change the profile image.  

### Desired Behavior

Be able to go to Profile > Edit Settings > Click on Profile Image > Change it.
Oh and if Admin, be able to change any user's pic.

### Additional Context

This came about because one of my friends wants a Jellyseerr profile pic but can't add it.
Thank you!

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Profile pics are already change-able. The profile pics come from jellyfin/emby/gravatar.

**Comment by devanteweary** [comment]
> Profile pics are already change-able. The profile pics come from jellyfin/emby/gravatar.

I had a user who didn't have one in Jellyfin, then went in and changed it, but it never showed up in Jellyseerr. 

So I tested it out myself and changed it and it also didn't update. That was a couple of days ago. 

I'm thinking Jellyseerr might pull it in on the initial profile sync, but never again. 

Or am I wrong?

**Comment by Fallenbagel** [comment]
> > Profile pics are already change-able. The profile pics come from jellyfin/emby/gravatar.
> 
> I had a user who didn't have one in Jellyfin, then went in and added one, but it never showed up in Jellyseerr. 
> 
> So I tested it out myself and changed mine and it also didn't update in JS. That was a couple of days ago. 
> 
> I'm thinking Jellyseerr might pull it in on the initial profile sync, but never again. 
> 
> Or am I wrong? 

Yes. We don't pull any pictures. It's direct. You need to log out and log back in to update the profile pictures that are added in jellyfin.

**Comment by Fallenbagel** [comment]
> Yes that's wrong. That's not how it works. We don't pull or sync any profile pictures.\n\nIt displays the avatar directly. You need to log out and log back in to update the link to the profile pictures that are added in jellyfin.\n\nAlso make sure that the externalHostname is set correctly to your fqdn on settings > jellyseerr. That will be used for your profile picture.

For anyone stumbling on this issue and commenting on this issue in the future, this is how it worked <v2. Now it caches and proxies from jellyseerr and externalHostname does not matter but still log out and log in by that user "NOT RE-IMPORT" is required for the users avatar to update.

If you have any issues with the new avatarproxy, I suggest hopping on discord to first troubleshoot together before reporting. And if reporting please don't use this issue as this is only relevant to <v2.0.0. Not >v2.0.0.

(Commenting this as i saw a comment talking about not being able to reimport although that comment was deleted)
