### ISSUE TITLE
Genre filtering

### ISSUE THREAD

**Issue by adamef93** [Fallenbagel/jellyseerr#750]
### Description

It seems that stacking genres behaves as "and" rather than "or". Selecting the genres I'm interested in results in nothing found because it's searching for media categorized as action AND comedy AND sci-fi AND etc when I'm trying to filter out what I don't want to see

### Desired Behavior

Modify the genre filter in a way that multiple selections don't behave as an "and" operator. Or at least provide the option to change how combining genres works

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
That is the intended behavior of genre filter.
Genre filtering is done by the tmdb api. It works the exact way as the filters work on tmdb website:
https://www.themoviedb.org/tv/
https://www.themoviedb.org/movie/

We don't do any filtering logical on the client side.
