### ISSUE TITLE
Notification partially available

### ISSUE THREAD

**Issue by Sergiomg86** [Fallenbagel/jellyseerr#755]
### Description

I have seen that Telegram notifies only with complete series, it would be interesting that it notifies with the status "partially available" since some series come out week by week instead of complete seasons.

### Desired Behavior

A notification that says "series with no season completed" or "series available" and sends the same as the completed series notification.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
Duplicate #480
