### ISSUE TITLE
Cannot get through initial setup

### ISSUE THREAD

**Issue by Octelly** [Fallenbagel/jellyseerr#756]
### Description

When trying to sign in for the first time, the web interface shows a "Something went wrong while trying to sign in." and in Chromium DevTools all I can see is a 500 for `api/v1/auth/jellyfin`. `journactl -fu jellyseerr` does not yield any useful information. (see logs section)

I have tried nuking all off Jellyseerr's saved data that I could find several times already, including deleting all site cookies in my browser with no result. I've tried configuring it both through my reverse proxy and directly with no change. Using local IP/public URL for Jellyfin also didn't change anything.

I did get to the second step once, but was unable to replicate this.

### Version

[Nixpkgs for my system version reports version 1.7.0](https://search.nixos.org/packages?channel=23.11&show=jellyseerr)

### Steps to Reproduce

My server runs NixOS

```nix
services.jellyseerr.enable = true;
```

This runs the Jellyseerr executable through systemd, the exact service configuration used can be found [here](https://github.com/NixOS/nixpkgs/blob/6c0b7a92c30122196a761b440ac0d46d3d9954f1/nixos/modules/services/misc/jellyseerr.nix#L27-L55) (it is Nix code, but should be readable for anyone with systemd experience).

### Screenshots

![Screenshot_20240520_174714](https://github.com/Fallenbagel/jellyseerr/assets/29976879/2050831b-3e92-40da-9686-6fb5ee5f4dfe)

### Logs

```shell
May 20 17:26:49 (server name redacted) jellyseerr[348095]: 2024-05-20T15:26:49.746Z [info][Notifications]: Registered notification agents
May 20 17:26:49 (server name redacted) jellyseerr[348095]: 2024-05-20T15:26:49.866Z [info][Jobs]: Scheduled jobs loaded
May 20 17:26:50 (server name redacted) jellyseerr[348095]: 2024-05-20T15:26:50.436Z [info][Server]: Server ready on port 5055
May 20 17:27:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:27:00.020Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:28:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:28:00.021Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:29:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:29:00.021Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:30:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:30:00.023Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:30:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:30:00.039Z [info][Jobs]: Starting scheduled job: Jellyfin Recently Added Sync
May 20 17:30:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:30:00.042Z [info][Jellyfin Sync]: Jellyfin Sync Starting {"sessionId":"7879db48-f637-462d-b422-6885594c9074"}
May 20 17:30:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:30:00.086Z [info][Jellyfin Sync]: Recently Added Scan Complete
May 20 17:31:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:31:00.026Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:32:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:32:00.019Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:33:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:33:00.026Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:34:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:34:00.029Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:35:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:35:00.025Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:35:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:35:00.042Z [info][Jobs]: Starting scheduled job: Jellyfin Recently Added Sync
May 20 17:35:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:35:00.043Z [info][Jellyfin Sync]: Jellyfin Sync Starting {"sessionId":"695ba04b-e1c3-4b0c-b5d5-6fcaf08125d1"}
May 20 17:35:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:35:00.065Z [info][Jellyfin Sync]: Recently Added Scan Complete
May 20 17:36:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:36:00.024Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:37:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:37:00.014Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:38:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:38:00.024Z [debug][Jobs]: Starting scheduled job: Download Sync
May 20 17:39:00 (server name redacted) jellyseerr[348095]: 2024-05-20T15:39:00.025Z [debug][Jobs]: Starting scheduled job: Download Sync
```

### Platform

desktop

### Device

n/a

### Operating System

GNU/Linux based

### Browser

Brave (Chromium)

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Can you hop onto discord. We don't carry out troubleshooting on github issues.

(P.s I also use nixpkg)

**Comment by Octelly** [comment]
Didn't have time to go on Discord yet, but this issue is indeed still relevant.

**Comment by gauthier-th** [comment]
This looks like a configuration issue. If after checking the configuration this is still a problem, we can reopen the issue.

**Comment by Fallenbagel** [comment]
> Didn't have time to go on Discord yet, but this issue is indeed still relevant.

This is definitely a configuration problem. I am running nixos on all my servers and it is indeed working. We don't carry out support issues on github issues so as to keep github clean for bugs and feature requests and other issues

**Comment by Octelly** [comment]
Hey, I don't wanna argue, but this is quite literally just default settings.

All Jellyfin/Jellyseerr related lines in my main server's config (does not use a flake):
```nix
  services.jellyfin.enable = true;
  services.jellyseerr.enable = true;
```

Here are all the relevant virtualhost definitions in ``services.nginx.virtualHosts`` on my reverse proxy (also doesn't use a flake) - Jellyseerr is currently commented out as it's not working:

```nix
      # Jellyfin
      "[domain redacted]" = {
        forceSSL = true;
        useACMEHost = "[domain redacted]";
        locations."/" = {
          proxyPass = "http://${hosts.ocean-server}:8096";
          proxyWebsockets = true;
          recommendedProxySettings = true;
        };
      };

      ## Jellyseerr
      #"[domain redacted]" = {
      #  forceSSL = true;
      #  useACMEHost = "[domain redacted]";
      #  locations."/" = {
      #    proxyPass = "http://${hosts.ocean-server}:5055";
      #    proxyWebsockets = true;
      #    recommendedProxySettings = true;
      #  };
      #};
```

Both are on stable Nixpkgs.

**Comment by Fallenbagel** [comment]
> Hey, I don't wanna argue, but this is quite literally just default settings.
> 
> All Jellyfin/Jellyseerr related lines in my main server's config (does not use a flake):
> ```nix
>   services.jellyfin.enable = true;
>   services.jellyseerr.enable = true;
> ```
> 
> Here are all the relevant virtualhost definitions in ``services.nginx.virtualHosts`` on my reverse proxy (also doesn't use a flake) - Jellyseerr is currently commented out as it's not working:
> 
> ```nix
>       # Jellyfin
>       "[domain redacted]" = {
>         forceSSL = true;
>         useACMEHost = "[domain redacted]";
>         locations."/" = {
>           proxyPass = "http://${hosts.ocean-server}:8096";
>           proxyWebsockets = true;
>           recommendedProxySettings = true;
>         };
>       };
> 
>       ## Jellyseerr
>       #"[domain redacted]" = {
>       #  forceSSL = true;
>       #  useACMEHost = "[domain redacted]";
>       #  locations."/" = {
>       #    proxyPass = "http://${hosts.ocean-server}:5055";
>       #    proxyWebsockets = true;
>       #    recommendedProxySettings = true;
>       #  };
>       #};
> ```
> 
> Both are on stable Nixpkgs.

Not arguing. But there's a lot of troubleshooting steps I want to carry out and we don't carry out support here. Including `something went wrong` which can be explained by steps.

If you dont want to comply, i really cant help you. Because i am also running nix, on all my machines and i cant reproduce this so i am going to need your cooperation to figure out whats wrong in your instance.

A suggestion i could give then is, try overlaying it to use unstable nixpkg for jellyseerr only. It should be 1.8.1
