### ISSUE TITLE
Jellyseerr as an add-on for home assistant

### ISSUE THREAD

**Issue by languagemaniac** [Fallenbagel/jellyseerr#775]
### Description

Hi, I just installed home assistant for another purpose but saw that much of the software I use is available there in the form of an add-on, including radarr, sonarr, lidarr, prowlarr, Wireguard, adguard....

But looks like jellyseerr is not there. 

It's quite a simple way to install software, so here's my suggestion.

### Desired Behavior

for jellyseerr to be available as an add-on in home assistant add-on store.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
https://github.com/vaparr/ha-overseerr

https://github.com/hassio-addons/addon-overseerr

**Comment by languagemaniac** [comment]
> https://github.com/vaparr/ha-overseerr
> 
> https://github.com/hassio-addons/addon-overseerr

yeah I saw overseerr there but it only works for Plex. I am already using jellyseerr even though it's not available as an add-on, was just a suggestion so there are more ways to install jellyseerr.

**Comment by osh123** [comment]
https://github.com/alexbelgium/hassio-addons/tree/master/jellyseerr

**Comment by languagemaniac** [comment]
> https://github.com/alexbelgium/hassio-addons/tree/master/jellyseerr

Great! Thanks
