### ISSUE TITLE
jemalloc page size issue for arm64

### ISSUE THREAD

**Issue by nephaste** [Fallenbagel/jellyseerr#794]
### Description

building QPKG for Qnap NAS, while all work perfectily on x86_64, ARM64 has issue du jemmaloc page file size issue

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/f7593052-6e05-4faf-9102-6cc75954d6f9)

### Version

1.9.0

### Steps to Reproduce

NODEJS 20
git version

git clone https://github.com/Fallenbagel/jellyseerr.git && cd jellyseerr
git checkout main

cd jellyseerr

CYPRESS_INSTALL_BINARY=0 CC=${HOST}-cc CXX=${HOST}-g++ npm_config_build_from_source=true npm_config_build_from_source=sqlite3 ../bin/yarn install --frozen-lockfile --network-timeout 1000000  ;
CC=${HOST}-cc CXX=${HOST}-g++ npm_config_build_from_source=true npm_config_build_from_source=sqlite3 ../bin/yarn run build ;

### Platform

desktop

### Device

QNAP NAS 

### Operating System

Linux ARM64

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You're running out of memory during build. What's the ram?

**Comment by Fallenbagel** [comment]
Building on QPKG on QNAP is not officially supported. And this seems to be a nextjs issue (see https://github.com/ajnart/homarr/issues/598#issuecomment-1398079454)

And homarr's solution seems to be upgrading to nextjs 13. We are on 12. So until we can update to nextjs 13, there is nothing that can be done.

**Comment by nephaste** [comment]
Many users prefer nativ, than docker for many reasons... the myqnap.org repository proposed only undockerised QPKG, 
hope you will update nextjs soon ...

Thanks again,

**Comment by gauthier-th** [comment]
Updating Next.js is on our roadmap, so it might comes in a few days/weeks/months.

**Comment by gauthier-th** [comment]
@nephaste the Next.js update should be done. It's not release yet but it's available with the `update-nextjs` branch or the `preview-nextjs-update` tag.
Could you please try it and check if it resolves your error?

**Comment by nephaste** [comment]
Hi @gauthier-th , thanks a lot...

not sure what i did wrong but getting a sharp command not found with the branch

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/f9c011ac-069d-4430-8e06-52bf3a16e042)

**Comment by nephaste** [comment]
but seem he can build it via node-gyp

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/f26c8c6c-ea48-44d9-8b84-261cdb28fcdf)

and all is compiled finally

**Comment by Fallenbagel** [comment]
> Hi @gauthier-th , thanks a lot...
> 
> not sure what i did wrong but getting a sharp command not found with the branch
> 
> ![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/f9c011ac-069d-4430-8e06-52bf3a16e042)
> 

That is probably my fault. I added sharp as a dependency and im not sure if I set it up correctly

**Comment by gauthier-th** [comment]
> > Hi @gauthier-th , thanks a lot...
> > not sure what i did wrong but getting a sharp command not found with the branch
> > ![image](https://private-user-images.githubusercontent.com/3392684/342030571-f9c011ac-069d-4430-8e06-52bf3a16e042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzc0NjEsIm5iZiI6MTcxOTEzNzE2MSwicGF0aCI6Ii8zMzkyNjg0LzM0MjAzMDU3MS1mOWMwMTFhYy0wNjlkLTQ0MzAtOGUwNi01MmJmM2ExNmUwNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjNUMTAwNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTI2ZjFlOTkzYjAzMzg4ZWVmN2MyZGQ2ODJmOGQxYzRkM2MyNzdlODk2YjhjMDY3NDVlMTY1ZDllMjY1YmMwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IRqynaKQZDAtp1KEj347mFVQgcj0wHB7pkcWcfTnxCg)
> 
> That is probably my fault. I added sharp as a dependency and im not sure if I set it up correctly

It might be coming from us as well. When we build it for arm64 on our CI this error doesn't occurs though.
The CI is using Node.js v18.18 and Yarn v1.22.19.

What is your Yarn version? (`yarn --version`)

**Comment by gauthier-th** [comment]
I didn't saw it was already written in your screenshot sorry.
Could you try it with Node.js v18 instead of Node.js v20? We don't really support Node.js v20.

**Comment by nephaste** [comment]
Hi , it is already NodeJS v18 (cant remember the version exactly since it is also cross compiled for current libc)

yarn is installed to latest release as well (on each compilaton from source) just built the Qnap QPKG, and it seems to work as it is

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/5c2fbe6b-f2cc-4808-9f05-a570c2d8da25)

**Comment by nephaste** [comment]
![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/aa59d706-8cd2-45fa-a4e4-dc9f2e011198)

**Comment by gauthier-th** [comment]
In the end, did you manage to build it and run it without performing any extra action?

**Comment by nephaste** [comment]
Exactly... no action I tried to npm install -g  sharp in my nodejs directory and also into the jellyseerr directory but the error was still here, but job process continue seems to be build it with node-gyp on my understanding..

**Comment by Fallenbagel** [comment]
> Exactly... no action I tried to npm install -g  sharp in my nodejs directory and also into the jellyseerr directory but the error was still here, but job process continue seems to be build it with node-gyp on my understanding.. 

Could you try now? Remember to use nodejs 20 and pnpm 9

**Comment by nephaste** [comment]
something changed ? i installed pnpm 9.4.0 in my PATH but getting another error now

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/e82469a1-2e60-42d9-b091-d24abb520b69)

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/4d25de95-1a3a-4c8b-97fb-f51c1033939b)

**Comment by nephaste** [comment]
I added npm install -g next to my PATH, seems to compile now

**Comment by gauthier-th** [comment]
We did quite a lot of updates the last few days. Theses updates includes:
- Update to Next.js v14
- Update to Node.js v20
- Switch from Yarn to pnpm

This means you will have to install pnpm, and install your Node.js dependencies with pnpm instead of Yarn.
You can follow the build instructions in the [README](https://github.com/Fallenbagel/jellyseerr?tab=readme-ov-file#building-from-source-advanced) which has also been updated.

You shouldn't need to install global packages with npm (actually you should remove theses).

Could you please test it on develop without any extra flags or workarounds?

**Comment by nephaste** [comment]
Will give a try actually compilation is taking ages : 

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/d0327179-112d-4ce4-81f5-6830ccd0d119)

i need build from source some nodejs module (like sqlite3 because the provided binaries are using an upper libc than the NAS)

**Comment by Fallenbagel** [comment]
> I added npm install -g next to my PATH, seems to compile now
> 
> ![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/a30669a2-18da-47b6-a338-177b92ab2cba)
> 

Just a heads up. Look at your build command. You're doing` ../bin/yarn`

**Comment by nephaste** [comment]
yes just saw your message... tried pnpm but seems still need install next

and not sure what belong the sqlite3 error message

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/442c82a6-08a6-4098-9a14-f3a3a994521a)

**Comment by Fallenbagel** [comment]
> yes just saw your message... tried pnpm but seems still need install next
> 
> and not sure what belong the sqlite3 error message
> 
> ![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/442c82a6-08a6-4098-9a14-f3a3a994521a)
> 

You're still running the wrong package.json
It's still yarn building.

Could you hop onto discord? We'll guide you through this

**Comment by nephaste** [comment]
Should i use main branch (like on the README )

the current branch i am using now

git clone https://github.com/Fallenbagel/jellyseerr.git && cd jellyseerr
git checkout main

or going back to on update-nextjs branch

**Comment by Fallenbagel** [comment]
> Should i use main branch (like on the README )
> 
> the current branch i am using now
> 
> git clone https://github.com/Fallenbagel/jellyseerr.git && cd jellyseerr
> git checkout main
> 
> or going back to on update-nextjs branch

That's your issue.
You should be on develop.
Then run `pnpm install --frozen-lockfile`
Then `pnpm build`

**Comment by nephaste** [comment]
seems to work, but falling into an error i need check my flags and why he does not find some headers

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/534fb3bd-fdd1-43b8-985f-003fc247ae2f)

**Comment by nephaste** [comment]
mmmmmm look like i must ugrpade m libvips version  😢 

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/9bd4ad07-8ef6-41dd-a102-48c402516588)

**Comment by nephaste** [comment]
updated libvips but still falling in another strange issue ... not sure what is the problem

![image](https://github.com/Fallenbagel/jellyseerr/assets/3392684/d8445d60-d8f8-43a8-ae02-ee9ed9af39cf)
