### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by sntpPro** [Fallenbagel/jellyseerr#795]
### Description

During the login process using an EMBY account, the interface returned a 401 error. Switching back to version 1.8.1 is normal

### Version

v1.9.0

### Steps to Reproduce

![image](https://github.com/Fallenbagel/jellyseerr/assets/37789059/6c2c3b78-00d6-4d26-9816-6819e95fdceb)

### Platform

desktop

### Device

Windows

### Operating System

Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
#793

**Comment by Fallenbagel** [comment]
Actually could you hop onto discord to confirm if this is related to #793 to go through some troubleshooting steps?

We carry out support there.

**Comment by Fallenbagel** [comment]
It's not related to #793
