### ISSUE TITLE
Set partially requested Series to 'Available' when download completes

### ISSUE THREAD

**Issue by POD319** [Fallenbagel/jellyseerr#800]
### Description

When you request a partial series, ie -- only Season 1 of a 4 Season show -- when the download completes, it does not change from 'Requested'. This makes it hard to know when your request is actually complete. The Series will never set to 'Available' unless the entire Series is downloaded.

### Desired Behavior

Jellyseerr should mark partial series requests as 'available' when the request has downloaded.
Requested should only be shown when a series is not yet downloaded as according to the request, and not the entirety of the series.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
It should add a badge as partially available. If it's not changing from requested, then it's an improperly configured jellyseerr, and I have explained this on discord as well.

![Screenshot_20240607_113137_Chrome Dev.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/8947ed5e-46fb-4a48-ad5b-26878c4781be)
