### ISSUE TITLE
Login breaks without email set

### ISSUE THREAD

**Issue by maam27** [Fallenbagel/jellyseerr#803]
### Description

The user is unable to login to jellyseerr with their jellyfin account if the email has been removed from the account page.

### Version

1.9.0

### Steps to Reproduce

1. Go to profile
2. Click edit settings
3. empty the email field
4. logout
5. attempt to login using jellyfin

### Platform

desktop

### Device

pc

### Operating System

windows 10

### Browser

chrome

### Additional Context

Setting the email is forced during the setup process of jellyfin, this oculd explain why the login breaks if it suddenly isn't set. For clarity the email should not be able to be unset, or not be mandatory during the setup.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The intended behavior is email shouldn't be removed. Email is a must (even if it's just nonesense). Thank you for reporting that it can be set as empty (that's not intended)
