### ISSUE TITLE
wrong productioncountries value translation

### ISSUE THREAD

**Issue by theggs** [Fallenbagel/jellyseerr#826]
### Description

In production countries field, value `中国香港特别行政区` is transformed to `香港`, which should keep the oriainal value `中国香港特别行政区`

### Version

1.9.2

### Steps to Reproduce

1. Set display language to `简体中文`
2. search and go to detail page of movie 'Shaolin Soccer'
3. check the value of 出品国家(production countries)

### Screenshots

When viewing the details of movie '[Shaolin Soccer](https://www.themoviedb.org/movie/11770?language=en-US)' in language Chinese, we can see the production country is filled with `香港` 。
<img width="350" alt="image" src="https://github.com/Fallenbagel/jellyseerr/assets/11958242/98099a16-60be-4ac6-96f4-d5fd86758715">

While the field in TMDB (https://www.themoviedb.org/movie/11770?language=zh-CN) it is `中国香港特别行政区`。
<img width="1081" alt="image" src="https://github.com/Fallenbagel/jellyseerr/assets/11958242/ce14de9b-f851-41bf-a1eb-2c846dfc57b6">

I can see in the browser, Jellyseerr's response of `/movie/{movie_id}` the locale value of the field is `中国香港特别行政区`.
<img width="610" alt="image" src="https://github.com/Fallenbagel/jellyseerr/assets/11958242/7d3cd220-463a-4bae-912a-3c600ac9ef4f"> 
I don't why it becomes `香港` as the final display of result.

It should be `中国香港特别行政区` - the same result of TMDB's information.

### Platform

desktop

### Device

Macbook Pro 16'

### Operating System

MacOS 14.5

### Browser

Chrome 125

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
We don't use the values from tmdb for the purpose of localisation. It's handled by [`@formatjs/react-intl`](https://www.npmjs.com/package/react-intl).

And this is their localised name for that production country.

Here is the code snippet:

https://github.com/Fallenbagel/jellyseerr/blob/develop/src%2Fcomponents%2FMovieDetails%2Findex.tsx#L769-L791

**Comment by theggs** [comment]
I see, it come from JS internal function Intl.DisplayNames..
The translation in fine if standalone. But it is not good to use this translation as 'countries'.

Is there a reason why we don't use the displayname returned by TMDB firstly?

**Comment by Fallenbagel** [comment]
> Is there a reason why we don't use the displayname returned by TMDB firstly?

Yes. Localisation

**Comment by Fallenbagel** [comment]
> The translation in fine if standalone. But it is not good to use this translation as 'countries'.

It is the translation done by that package. So you should raise an issue with them.

> Is there a reason why we don't use the displayname returned by TMDB firstly?

Yes. For localisation.

**Comment by theggs** [comment]
@Fallenbagel 
The displayname returned by TMDB is already localized. And it seems already considered the semantic in this situation. Can jellyseerr use it firstly?

**Comment by Fallenbagel** [comment]
> @Fallenbagel 
> The displayname returned by TMDB is already localized. And it seems already considered the semantic in this situation. Can jellyseerr use it firstly?
> 

Is it localised for other languages as well? We use it for proper localisation so all the countries have their localised name for every display language selected.

**Comment by theggs** [comment]
@Fallenbagel 
It is not a `Intl.displaynames` issue. React-Intl use JavaScript’s internal function , and the translation is ok in generaral speaking.

While it is not suitable if the context is 'production countries'. Let me give an example to make it easier to understand.
```
const regionNamesInEnglish = new Intl.DisplayNames(['en'], { type: 'region' });
console.log(regionNamesInEnglish.of('GU'));

> "Guam"
```

It is true that "GU" stand for "Guam". But it is not suitable to say it is a country.
Hong Kong is a special area. It is a special administrative region(SAR). It publishes movies as a standalone region. When in this context, it is called 'Hong Kong SAR, China' -- Just as how TMDB call it.

**Comment by gauthier-th** [comment]
Hi @theggs 
I tried to replicate your issue on the latest version (1.9.2) in three different display language: English, Chinese and French. Here is the results:

English:
![image](https://github.com/Fallenbagel/jellyseerr/assets/37781713/cae079df-8186-4169-93a2-d781d23ab0f2)

Chinese:
![image](https://github.com/Fallenbagel/jellyseerr/assets/37781713/0bc3a00e-5fc3-46d7-b633-e29332aa1c38)

French:
![image](https://github.com/Fallenbagel/jellyseerr/assets/37781713/c9f84e0b-43d6-4196-9ba5-df02a1e95c44)

I can't replicate your issue in these 3 languages, the production country is "Hong Kong SAR, China".

**Comment by Fallenbagel** [comment]
I just tested as well.

![Screenshot_20240624_180958_Firefox Beta.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/e1d4d96b-2848-448e-9758-75ff3000ab21)

![Screenshot_20240624_181231_Firefox Beta.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/e07297bc-d34a-456b-9281-ef8a6428f4b9)

**Comment by Fallenbagel** [comment]
Develop as well.

![Screenshot_20240624_181459_Firefox Beta.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/7cbef4f8-f3e2-427c-aff9-5367d7a5d4cb)

![Screenshot_20240624_181507_Firefox Beta.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/2a0b5579-76bc-414f-ae20-eca7c4367d28)

**Comment by theggs** [comment]
That's quite strange.
@gauthier-th @Fallenbagel What OS and browser did you gus used?

**Comment by Fallenbagel** [comment]
> That's quite strange.
> @gauthier-th @Fallenbagel What OS and browser did you gus used?

I'm using docker + firefox

**Comment by gauthier-th** [comment]
> > That's quite strange.
> > @gauthier-th @Fallenbagel What OS and browser did you gus used?
> 
> I'm using docker + firefox

Same thing for me, Docker and Firefox

**Comment by theggs** [comment]
I can get a good result in MacOS + firefox 
<img width="448" alt="image" src="https://github.com/Fallenbagel/jellyseerr/assets/11958242/2ffffd1b-47c7-4e50-a3bf-ce9db34dc76b">

It seems a browser used javascript issue. It get different results in different browsers.
`Intl.DisplayNames` has a input para `style`, which is `long` by default. 

firefox: `style=long` -> 'Hong Kong SAR China'
firefox: `style=short` -> 'Hong Kong'

chrome: `style=long` -> 'Hong Kong'
chrome: `style=short` -> 'Hong Kong'

safari: `style=long` -> 'Hong Kong'
firefox: `style=short` -> 'Hong Kong'

**Comment by gauthier-th** [comment]
> I can get a good result in MacOS + firefox <img alt="image" width="448" src="https://private-user-images.githubusercontent.com/11958242/342352665-2ffffd1b-47c7-4e50-a3bf-ce9db34dc76b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzYwNzAsIm5iZiI6MTcxOTIzNTc3MCwicGF0aCI6Ii8xMTk1ODI0Mi8zNDIzNTI2NjUtMmZmZmZkMWItNDdjNy00ZTUwLWEzYmYtY2U5ZGIzNGRjNzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEzMjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZTI2MjJlMTllYWFiZWZhMWNlYWVlYmU4OTY5N2I0YmRjZmYxMjlmNTU0ODI4NzRjY2EwYTFkYmUzZTYzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IJPisUgymx7DQGnWCcnPgcNdBg_0plqE5IXvkaCVtdU">
> 
> It seems a browser used javascript issue. It get different results in different browsers. `Intl.DisplayNames` has a input para `style`, which is `long` by default.
> 
> firefox: `style=long` -> 'Hong Kong SAR China' firefox: `style=short` -> 'Hong Kong'
> 
> chrome: `style=long` -> 'Hong Kong' chrome: `style=short` -> 'Hong Kong'
> 
> safari: `style=long` -> 'Hong Kong' safari: `style=short` -> 'Hong Kong'

Good to know. Unfortunately, this means we can't really do anything about it.

**Comment by theggs** [comment]
yes, and can't expect the brower js engine will fix it quickly.
Let me will see what I can do for it when I have time.
