### ISSUE TITLE
Filter the result of TMDB Rating Descending by rating number

### ISSUE THREAD

**Issue by theggs** [Fallenbagel/jellyseerr#827]
### Description

For now, the feature sort film by`TMDB Rating Descending` is meaningless. Because a huge number of films that has 100/100 rating but only one person rated will fill up the screen.

### Desired Behavior

Add feature of filtering the result by rating by rate number. For example, only list movies more than 10 perple rated.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You can already do that?
![Screenshot_20240621_214634_Chrome Dev.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/28506b86-72b1-4db9-b917-3f07a2ac7d9e)

Set the user vote count and rating accordingly?

**Comment by theggs** [comment]
Thanks. It seems I missed it before.
