### ISSUE TITLE
the project in weblate is locked because of ssh key issue

### ISSUE THREAD

**Issue by theggs** [Fallenbagel/jellyseerr#828]
### Description

the project in weblate is locked because of ssh key issue. So no update of translation can be impleted.

### Version

current

### Steps to Reproduce

1. go to https://jellyseerr.borgcube.de/projects/jellyseerr/jellyseerr-frontend/#alerts
2. find the alert message
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/app/data/ssh/id_ed25519' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/app/data/ssh/id_ed25519": bad permissions
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 (128)
```

### Platform

desktop

### Device

No divice used

### Operating System

No OS used

### Browser

No browser used

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This should be fixed now. Thank you for reporting!
