### ISSUE TITLE
Can't log in with running jellyfin credentials

### ISSUE THREAD

**Issue by sane120** [Fallenbagel/jellyseerr#830]
### Description

As the title says, unable to log in using jellyfin credentials/ip

tried in edge and chrome

### Version

1.9.2

### Steps to Reproduce

open webUI
try to log in with jellyfin

### Logs

```shell
> {"message":"cookie 'connect.sid' required","errors":[{"path":"/api/v1/auth/me","message":"cookie 'connect.sid' required"}]}
```

### Platform

desktop

### Device

PC

### Operating System

Win11

### Browser

Chrome, Edge

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
We do not carry out support tickets in github. Please hop onto our discord and raise a support thread there.
