### ISSUE TITLE
[FATAL tini (7)] exec pnpm failed: No such file or directory

### ISSUE THREAD

**Issue by hcbille** [Fallenbagel/jellyseerr#834]
### Description

[FATAL tini (7)] exec pnpm failed: No such file or directory

### Version

Latest develop

### Steps to Reproduce

Crashes on startup

### Logs

```shell
[FATAL tini (7)] exec pnpm failed: No such file or directory
```

### Platform

desktop

### Device

-

### Operating System

-

### Browser

-

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Yes we are aware. A fix should be deployed in a second :)
