### ISSUE TITLE
Error 500 on the logs page.

### ISSUE THREAD

**Issue by WillGe** [Fallenbagel/jellyseerr#85]
#### Description
Hi! Absolutely love the project! Just something I stumbled upon when using the docker on unraid 6.9.2

When you go in settings > logs, you are greeted with a 500

#### Version

1.0.2 stable 

#### Steps to Reproduce

Head into the logs page.

#### Expected Behavior

Please provide a clear and concise description of what you expected to happen.

#### Screenshots

If applicable, please provide screenshots depicting the problem.

#### Device

- **Platform:** Unraid 6.9.2
- **Device:** Macbook Pro
- **OS:** MacOS
- **Browser:** Chrome

#### Additional Context

You can find the error in the docker logs. There seems to be a mismatch in the naming of the log file. The page itself is looking for /logs/jellyseerr.log but when they are laid out, they are actually created as Jellyseerr.log 
The naming convention for Overseerr was to not use any capitalization for the log files.

https://github.com/Fallenbagel/jellyseerr/blob/57cc48a699a595bb06cb98595fceca5202788031/server/logger.ts

**Comment by Fallenbagel** [comment]
For now you coukd use `develop` tag. We will soon be merging that with main branch and this issue will not be present there
