### ISSUE TITLE
Scrollbar Look.

### ISSUE THREAD

**Issue by XDark187** [Fallenbagel/jellyseerr#856]
### Description

The default thick white scrollbar is not matching with the modern UI of jellyseerr, it would be nice if it was thin and matched the colors of the UI.
![image](https://github.com/Fallenbagel/jellyseerr/assets/39034192/9a511fbd-a613-4b1e-9920-76174cce8449)

### Desired Behavior

it can be easily changed to something like this:
![image](https://github.com/Fallenbagel/jellyseerr/assets/39034192/152239f9-03a3-495c-be00-4b991ad698f9)

### Additional Context

For anyone who uses darkreader extension you can add the following CSS to make the scrollbar as shown above:

```
* {
  scrollbar-width: thin;
  scrollbar-color: #4b5563 #1f2937;
}

*:hover {
  scrollbar-color: #6b7280 #1f2937;
}
```

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
Could you create a PR for this?
