### ISSUE TITLE
Error 500 when opening page for Schitt's Creek

### ISSUE THREAD

**Issue by Metal-Snake** [Fallenbagel/jellyseerr#859]
### Description

When trying to open the page for "Schitt's Creek" I get a error 500 and get redirected to the start page.

### Version

1.9.2 Stable

### Steps to Reproduce

1. Search for "Schitt"
2. Click on the cover for "Schitt's Creek"
3. Get error 500

### Logs

In the logs this shows up when I try to open that page:

```shell
[debug][API]: Something went wrong retrieving series {"errorMessage":"Cannot read properties of undefined (reading 'map')","tvId":"61662"}
```

### Platform

desktop

### Device

Docker

### Operating System

Synology

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
![Screenshot_20240706_012346_Chrome Dev.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/53c90dff-d7bf-451d-802a-c9b50556e10f)

Unfortunately I cannot recreate this

**Comment by Fallenbagel** [comment]
Could you try clearing your tmdb cache

**Comment by Metal-Snake** [comment]
Seeing your screenshot I set my Jellyseer language to english and now it shows. 
I set the language back to german (deutsch) and I get the error again.
Could you try with language set to german?

**Comment by Fallenbagel** [comment]
> Seeing your screenshot I set my Jellyseer language to english and now it shows. 
> I set the language back to german (deutsch) and I get the error again.
> Could you try with language set to german?

![Screenshot_20240706_024046_Chrome Dev.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/05e15895-dbe9-4d54-b8de-01d3aa129bdb)

**Comment by Metal-Snake** [comment]
Trying to clean the cache, but there doesn't seem to be one?
<img width="1624" alt="Bildschirmfoto 2024-07-05 um 23 43 40" src="https://github.com/Fallenbagel/jellyseerr/assets/898220/30486cbb-55d2-45c0-b857-f7c802dc3001">

**Comment by Fallenbagel** [comment]
> Trying to clean the cache, but there doesn't seem to be one?
> <img width="1624" alt="Bildschirmfoto 2024-07-05 um 23 43 40" src="https://github.com/Fallenbagel/jellyseerr/assets/898220/30486cbb-55d2-45c0-b857-f7c802dc3001">
> 

Set the image caching on and let it be there for a while and it will work. It's a bug in the stable that is now fixed I believe

**Comment by Metal-Snake** [comment]
wow now the cache is shown and I was able to clear it, and now the page loads just fine. Thanks!

**Comment by Fallenbagel** [comment]
> wow now the cache is shown and I was able to clear it, and now the page loads just fine. Thanks!

Glad you got it working! 🥳
