### ISSUE TITLE
Inaccurate estimated download times

### ISSUE THREAD

**Issue by Nabstar3** [Fallenbagel/jellyseerr#865]
### Description

Currently, Jellyseer displays estimated download times for requested titles that often differ significantly from what the actual downloader states. This discrepancy can lead to confusion and frustration among users who rely on accurate timing information to plan their downloads effectively.

### Desired Behavior

We would like Jellyseer to either synchronize its estimated download time calculations with those provided by the downloader itself or implement a more accurate algorithm for estimating wait times. This would ensure that users receive consistent and reliable information regarding when their requested titles will be available for download.

### Additional Context

Currently, when a user requests a title for download through Jellyseer, the estimated download time displayed can be significantly different from what the downloader actually indicates. This issue persists across multiple instances and does not seem to improve with different network conditions or download priorities.

Here is an example of the issue:

Jellyseer estimates a download time of 24 hours for a requested title.
The downloader interface indicates a remaining download time of 6 hours

<img width="1058" alt="Screenshot 2024-07-07 045208" src="https://github.com/Fallenbagel/jellyseerr/assets/47038774/f9ab8172-5c60-4024-80a8-64f831828f38">

![Screenshot 2024-07-07 045438](https://github.com/Fallenbagel/jellyseerr/assets/47038774/f5570d48-b59f-47b9-8eb7-bd0b46530b4d)
.
Such discrepancies not only confuse users but also hinder their ability to effectively manage their downloads. We suggest exploring options to improve synchronization between Jellyseer's estimated times and those provided by the downloader, or enhancing the algorithm used to calculate these estimates.

Improving this feature would greatly enhance user experience by providing more accurate and reliable information, thereby reducing frustration and improving overall satisfaction with Jellyseer's download management capabilities.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The estimated time doesn't come from the downloaded but from sonarr/radarr. These tools sync every two minutes with the actual client. There's nothing we can do about this. We don't connect to download clients and don't plan to do so.

**Comment by Fallenbagel** [comment]
The estimated time doesn't come from the downloader but from sonarr/radarr. These tools sync every two minutes with the actual client. And we sync to them.

There's nothing we can do about this. We don't connect to download clients.

**Comment by Fallenbagel** [comment]
@Nabstar3 #866 should provide a way to refresh the timings once implemented. You can follow that issue for the development progress c:

**Comment by gauthier-th** [comment]
> ### Description
> 
> Currently, Jellyseer displays estimated download times for requested titles that often differ significantly from what the actual downloader states. This discrepancy can lead to confusion and frustration among users who rely on accurate timing information to plan their downloads effectively.
> ### Desired Behavior
> 
> We would like Jellyseer to either synchronize its estimated download time calculations with those provided by the downloader itself or implement a more accurate algorithm for estimating wait times. This would ensure that users receive consistent and reliable information regarding when their requested titles will be available for download.
> ### Additional Context
> 
> Currently, when a user requests a title for download through Jellyseer, the estimated download time displayed can be significantly different from what the downloader actually indicates. This issue persists across multiple instances and does not seem to improve with different network conditions or download priorities.
> 
> Here is an example of the issue:
> 
> Jellyseer estimates a download time of 24 hours for a requested title. The downloader interface indicates a remaining download time of 6 hours
> <img alt="Screenshot 2024-07-07 045208" width="1058" src="https://private-user-images.githubusercontent.com/47038774/346322874-f9ab8172-5c60-4024-80a8-64f831828f38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzODgzMzIsIm5iZiI6MTcyMDM4ODAzMiwicGF0aCI6Ii80NzAzODc3NC8zNDYzMjI4NzQtZjlhYjgxNzItNWM2MC00MDI0LTgwYTgtNjRmODMxODI4ZjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDIxMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwY2MzOWEzMzk0NTQxN2U0MjFhM2NlNmZjMDYwZjI3ZTI1YzUzNDlkNTZjOWVlNjRhMDYwYjgyYWQyZjQ2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Il043iB8C8u_6XhZhSaJ2CE_obCSSHayj07P1yQon_w">
> 
> ![Screenshot 2024-07-07 045438](https://private-user-images.githubusercontent.com/47038774/346322875-f5570d48-b59f-47b9-8eb7-bd0b46530b4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzODgzMzIsIm5iZiI6MTcyMDM4ODAzMiwicGF0aCI6Ii80NzAzODc3NC8zNDYzMjI4NzUtZjU1NzBkNDgtYjU5Zi00N2I5LThlYjctYmQwYjQ2NTMwYjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDIxMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZTc3OWM0YTY5Nzg4ZDg2OWUxZjg0MGMxODQ2YzcyYzg3NDQ4OThhNjM0NjcwZWEyNmE0ZmEyMDQ2ZGY4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KLL3cHrB0ESR-YKDoBVMRW_GiWKM6AJ2myVHvxfE6K8) . Such discrepancies not only confuse users but also hinder their ability to effectively manage their downloads. We suggest exploring options to improve synchronization between Jellyseer's estimated times and those provided by the downloader, or enhancing the algorithm used to calculate these estimates.
> 
> Improving this feature would greatly enhance user experience by providing more accurate and reliable information, thereby reducing frustration and improving overall satisfaction with Jellyseer's download management capabilities.
> ### Code of Conduct
> 
>     * [x]  I agree to follow Jellyseerr's Code of Conduct

Just curious, did you use ChatGPT to write this?

**Comment by Nabstar3** [comment]
> Just curious, did you use ChatGPT to write this? I mean wtf is this:

LOL, yeah I did generate this issue with ChatGPT. The description and behavior were alright in my opinion and I didn't extend my review to the additional context.

**Comment by Fallenbagel** [comment]
> 
> > Just curious, did you use ChatGPT to write this? I mean wtf is this:
> 
> LOL, yeah I did generate this issue with ChatGPT. The description and behavior were alright in my opinion and I didn't extend my review to the additional context. 
> 

There is no "algorithm" or so. We don't calculate the estimated values. Which is why it made no sense
