### ISSUE TITLE
Issue with Docker extra_hosts Configuration Not Working as Expected

### ISSUE THREAD

**Issue by JordiKing10** [Fallenbagel/jellyseerr#867]
Hello everyone,

I am encountering an issue with Docker where the extra_hosts configuration, which used to work perfectly, is no longer functioning as expected. Below is a detailed description of my setup and the problem I am facing.

**Configuration:
Docker Compose File (docker-compose.yml):**

`version: "3.8"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Madrid
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr_config:/app/config
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
    extra_hosts:
      - "jorditomas.es:192.168.1.240"
`
**Problem**

Previously, I was able to use the extra_hosts directive to resolve internal domain names to specific IP addresses within my Docker containers. However, this functionality seems to have stopped working. Here is an example of my setup for extra_hosts:

`extra_hosts:
  - "jorditomas.es:192.168.1.240"`

Despite this configuration, my services are no longer able to resolve jorditomas.es to 192.168.1.240 as expected. This is causing various connectivity issues between my containers.

In the 1.9.1 version it works perfectly.

### Version

1.9.2

### Steps to Reproduce

1. Verified that the extra_hosts entries are correctly specified in the docker-compose.yml file.
2. Restarted Docker and the individual containers multiple times.
3. Confirmed that the /etc/hosts file within the containers contains the correct entries.

### Logs

```shell
2024-07-08T20:05:09.932Z [debug][Jellyfin API]: Failed to authenticate with headers: Hostname/IP does not match certificate's altnames: IP: 192.168.1.240 is not in the cert's list:  {"ip":"192.168.1.200"}
2024-07-08T20:05:09.939Z [warn][Auth]: Failed login attempt from user with incorrect Jellyfin credentials {"account":{"ip":"::ffff:192.168.1.200","email":"jordi","password":"__REDACTED__"}}
```

### Platform

desktop

### Device

Docker server

### Operating System

Ubuntu

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
Hi, could you please test if this still occurs on the `develop` branch?

**Comment by JordiKing10** [comment]
No, I still have the same problem. I didnt know if its a docker update or something

**Comment by Fallenbagel** [comment]
Could you downgrade to 1.9.1 and see if it works.

From the logs it looks like it's an issue with the entries listed in the SSL CERT SAN field

**Comment by gauthier-th** [comment]
Closed due to inactivity. Feel free to re-open if needed.
