### ISSUE TITLE
Allow resetting requests when radarr/sonarr switch to unmonitored

### ISSUE THREAD

**Issue by michelchalfoun** [Fallenbagel/jellyseerr#869]
### Description

When using the media cleaner plugin for jellyfin, I can removed movie/series files when they haven't been watched in a while. On radarr/sonarr, I can set a setting to unmonitor a movie/series when the files are deleted on disk. This way, the movie/series doesn't need to be searched for right after it has been deleted. All of this is great, but when the movie becomes unmonitored, there isn't a way to re-request it on jellyseer which still shows the request as completed and wants to redirect me to the movie on jellyfin (which has been deleted)

### Desired Behavior

The desired behavior would be that once a movie/series is unmonitored on radarr/sonarr, the user should be allowed to request the movie again.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Media availability sync job will remove media that has been deleted from jellyfin
