### ISSUE TITLE
[Bug] No Email Field which fails Email notification

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Fallenbagel/jellyseerr#87]
#### Description

There is no email field in the user setting. So emails won't send.

#### Version

What version of Overseerr are you running? develop

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Set up email notifications
2. Test email
3. Fails

#### Expected Behavior

Send email

#### Screenshots

If applicable, please provide screenshots depicting the problem.

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** [e.g., desktop, smartphone, tablet]
- **Device:** [e.g., iPhone X, Surface Pro, Samsung Galaxy Tab]
- **OS:** [e.g., iOS 8.1, Windows 10, Android 11]
- **Browser:** [e.g., Chrome, Safari, Edge, Firefox]

#### Additional Context

Please provide any additional information that may be relevant or helpful.

**Comment by Fallenbagel** [comment]
Hi yes. The email notifications is currently disabled on the develop branch. This is because we removed the feature where entering an email was required by every user when logging into jellyseerr

**Comment by Fallenbagel** [comment]
Hi. @Cookie-Monster-Coder So there is a workaround to get email notifications working in the current version until an alternative method is introduced. 

### Pre-requisites (**_Required_**)
- Make sure your admin account's email was not replaced (as in do not use the import jellyfin button). If it was, you will have to recreate jellyseerr.
- Also this workaround requires you to know the password (atleast temporarily) of the jellyfin user

### Steps to follow
1. Delete the users that you want the email notifications to be sent to.
2. Go to `http://localhost:5055/api-docs/#/auth/post_auth_jellyfin` (the option that says "sign in using jellyfin username and password")
3. Press try it now
4. in the request body, add the following (remember to replace username with the user's username and password and email too.)
```json
{
  "username": "jellyfinusername",
  "password": "jellyfinpassword",
  "email": "emailaddressoftheuser"
}
```
5. Press execute and it should log in the user with their email (now you can set up SMTP server how you normally would)
