### ISSUE TITLE
Cannot filter on Streaming Services anymore

### ISSUE THREAD

**Issue by LazeX7** [Fallenbagel/jellyseerr#870]
### Description

When I open Filters the option to filter with Streaming Services is gone.
The text is still there, but you can only select a country.

A few days ago this was still possible.

![image](https://github.com/Fallenbagel/jellyseerr/assets/14087562/cadeb322-7793-4270-aa8f-9b32b0cfb782)

### Version

v1.9.2

### Steps to Reproduce

Login to Jellyseer.
Go to series or movies
Click on Filters

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/14087562/6e7447b4-64b2-4c69-a555-a71ced2fccea)

### Platform

desktop

### Device

Desktop

### Operating System

Windows 11

### Browser

Chrome

### Additional Context

Runs on VM in proxmox as a LXC container with Debian

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is an issue with the tmdb api. Nothing we can do about it.

https://www.themoviedb.org/talk/668e2e545a8415d4a132ca33

**Comment by LazeX7** [comment]
> This is an issue with the tmdb api. Nothing we can do about it.
> 
> https://www.themoviedb.org/talk/668e2e545a8415d4a132ca33

I see. Thank you for the quick reply. They to fixed it then.

**Comment by TheRedCyclops** [comment]
this seems to have been solved
