### ISSUE TITLE
Request to use alternative for TMDB.

### ISSUE THREAD

**Issue by lightningquick** [Fallenbagel/jellyseerr#873]
### Description

I think the dependency on one meta provider is not a good move. There should be multiple Meta-data providers. 
My ISP doesnt accept TMDB connections. And it is by far the most popular in my state. And this would mean, many users, or potential users will struggle to use Jellyseerr. 

### Desired Behavior

Therefore, I request you to have the option to choose between TMDB and any other provider. 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
There are no other proper FOSS metadata providers.

You can use a proxy. A lot of people who has tmdb blocked serve jellyseerr through a proxy.
