### ISSUE TITLE
Allow more requests for media if any Sonarr/Radarr instance doesn't have the media

### ISSUE THREAD

**Issue by CronixZero** [Fallenbagel/jellyseerr#874]
### Description

We differentiate between Anime in the localized language and Anime in their original language with subtitles. For this we use 2 Sonarr Instances. It would be great if users could request from those 2 instances (Original, Localized) even though the other might already contain the requested media. I think this could be useful for seperate 4K Instances as well.

### Desired Behavior

More than one request for a movie or show should be allowed if more than one Sonarr/Radarr instance is setup. The amount of requests should match the amount of instances. Additionally instances should be disabled in the instance selection after a request to that instance has been sent.

Perhaps it would be useful to add a configuration for this in the Setting if users do not desire this behaviour. 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You can already request in seperare 4k instances seperately...

You setup 2 instances. One as default server. One as 4k default server. 

And then now there would be two request buttons. And even if you request 1080p once, you can still request 4k and vice versa.

**Comment by CronixZero** [comment]
Oh, I didn't know that because I never used that functionality before! Thank you for your fast reply. I don't think that it solves the original problem with multiple non-4k instances but rather provides a workaround though. Do you think that there could be a way to maybe make it more generic besides the 4k/non-4k use case?

**Comment by Fallenbagel** [comment]
> Oh, I didn't know that because I never used that functionality before! Thank you for your fast reply. I don't think that it solves the original problem with multiple non-4k instances but rather provides a workaround though. Do you think that there could be a way to maybe make it more generic besides the 4k/non-4k use case? 

Currently we only allow 1080p/4k seperate requests (do note that it is not tied to the quality level. You can have any configuration you need)

**Comment by CronixZero** [comment]
Thank you, I think that #232 would be an ideal fix for this, so I'll close this Issue
