### ISSUE TITLE
Application Exception

### ISSUE THREAD

**Issue by MegaShinySnivy** [Fallenbagel/jellyseerr#878]
### Description

On attempting to load Jellyseerr, I get an exception that prevents the webapp from loading.

```
TypeError: r.warnings is undefined
    NextJS 10
framework-6a24ea55bfe2d3c0.js:1:71888
    NextJS 11
TypeError: r.warnings is undefined
    NextJS 10
main-a0d77ee65511e9c3.js:1:7915
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred main-a0d77ee65511e9c3.js:1:7932
TypeError: r.warnings is undefined
    NextJS 10
framework-6a24ea55bfe2d3c0.js:1:71888
TypeError: r.warnings is undefined
    NextJS 10
main-a0d77ee65511e9c3.js:1:7915
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred main-a0d77ee65511e9c3.js:1:7932
    NextJS 13
MouseEvent.mozInputSource is deprecated. Use PointerEvent.pointerType instead. 17100-f53437216927e03c.js:1:21060

```

### Version

1.9.2

### Steps to Reproduce

Start v1.9.2
Attempt to access it

### Platform

desktop

### Device

Desktop on Firefox

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
How did you install

**Comment by MegaShinySnivy** [comment]
I'm using the official docker container on Kubernetes. Here's my helmfile.

https://github.com/MegaShinySnivy/Scaling-Snakes/blob/main/kubernetes/apps/default/jellyseerr/app/helmrelease.yaml

**Comment by gauthier-th** [comment]
Could this be related to #875?

**Comment by MegaShinySnivy** [comment]
Possibly... I notice when bypassing my reverse proxy, NGINX, it doesn't error. Is it possible there could be some sort of interference?

**Comment by gauthier-th** [comment]
The author of the PR I mentioned earlier was also using k8s with some kind of reverse proxy, so yes it may be linked.
Could you test the `preview-fix-users-warning` tag to see if it fixes your issue?

**Comment by MegaShinySnivy** [comment]
Doing that gives me... Something else entirely! Skips the login screen (even in a private tab) and leads to an "Oops!" screen with an option to return home that does jack all.

**Comment by Fallenbagel** [comment]
> Doing that gives me... Something else entirely! Skips the login screen (even in a private tab) and leads to an "Oops!" screen with an option to return home that does jack all. 

You mentioned without reverse proxy it works. Then that sound like a configuration issue with reverse proxy. Are you using subdomain or subfolder?

Can you show me your nginx configuration?

**Comment by MegaShinySnivy** [comment]
Subdomain. Config information is at https://github.com/MegaShinySnivy/Scaling-Snakes/blob/main/kubernetes/apps/default/jellyseerr/app/helmrelease.yaml and https://github.com/MegaShinySnivy/Scaling-Snakes/blob/main/kubernetes/apps/networking/nginx/external/helmrelease.yaml

**Comment by M0NsTeRRR** [comment]
I use jellyseerr in a kubernetes environment without issues (traefik). Have you tried to disable some nginx settings you have to see which cause this issue ?

**Comment by MegaShinySnivy** [comment]
I'm not sure what I would disable, all of these are pretty standard

**Comment by MegaShinySnivy** [comment]
It was my custom error pages. What errors does jellyseerr rely on to function?

**Comment by gauthier-th** [comment]
How do your error pages work?
Jellyseerr needs all the content of the responses that the API sends back to the front-end.

**Comment by MegaShinySnivy** [comment]
https://kubernetes.github.io/ingress-nginx/user-guide/custom-errors/ Check here, TLDR if the application behind NGINX returns an error, NGINX overwrites it and sends the user to its own custom error page instead.

**Comment by gauthier-th** [comment]
Jellyseerr does not send a full HTML page with some http code for each page. It's a PWA, meaning that all the content of the website (HTML, CSS, JS) is loaded at the first visit and then put in the browser cache. When you go to another page, it just load the necessary content from the API (like a JSON with the movies info) and the front-end website parse and display this content. If there is some error, the API will send back some content (in JSON) anyway, with details on the server-side error so the website can display this error.
If you mess up with the content returned by the API when there is an error, the Jellyseerr app will probably not be able to parse the error details and crash.
(it's normal behavior for the API to return error codes)

**Comment by gauthier-th** [comment]
I'm closing this because I don't think it's a Jellyseerr error.

**Comment by stevewm** [comment]
I hit this too, but it looks like nobody posted a solution. 

For anyone else who ends up here you can fix this by annotating your jellyseerr ingress with `nginx.ingress.kubernetes.io/custom-http-errors: "599"`. Credit to @MegaShinySnivy for the fix.
