### ISSUE TITLE
Stuck on the settings page

### ISSUE THREAD

**Issue by ssersh** [Fallenbagel/jellyseerr#88]
![Screenshot(18)](https://user-images.githubusercontent.com/96318267/167342474-6b65b108-00be-45c8-b033-755d18f9e06d.png)
#### Description

I got stuck on the settings page (Configure Media Server), entered the data from jellyfin and at the second step does not let me go further. The continue button is disabled. No Jellyfin Libraries.

#### Version

Docker on unraid, version of jellyseerr latest and develop.

**Comment by Fallenbagel** [comment]
Did you press sync libraries?
Also make sure automatically group content is turned off

**Comment by ssersh** [comment]
Yes, I did. But nothing happens. Automatically group content is turned off.

**Comment by Fallenbagel** [comment]
Can you show me the logs when you press sync libraries?

**Comment by ssersh** [comment]
jellyseerr log?

**Comment by ssersh** [comment]
[Jellyseerr.log](https://github.com/Fallenbagel/jellyseerr/files/8647205/Jellyseerr.log)
[Jellyseerr-2022-05-08.log](https://github.com/Fallenbagel/jellyseerr/files/8647206/Jellyseerr-2022-05-08.log)

**Comment by Fallenbagel** [comment]
Could you try using the `develop` tag and connecting to it using the internal address?

**Comment by ssersh** [comment]
Develop tag and internal address and no luck.
[overseerr.log](https://github.com/Fallenbagel/jellyseerr/files/8675559/overseerr.log)
[overseerr-2022-05-12.log](https://github.com/Fallenbagel/jellyseerr/files/8675561/overseerr-2022-05-12.log)

**Comment by TheBlackJ3sus** [comment]
I had this same issue yesterday.
I think you can reproduce like this:

- Fresh install
- Get to configure media screen
- Restart docker container without finishing setup

You'll get stuck on this screen. Only solution was to delete config dir and start fresh but finish setup completely.

**Comment by Fallenbagel** [comment]
Yeah maybe try deleting the whole config folder and container and remaking it fresh just like how @TheBlackJ3sus said.

I've had a very few users have the same problem but was resolved with a quick complete fresh install. Do make sure your config folder has the right permissions.

**Comment by insomnia417** [comment]
I have the same question...

**Comment by Fallenbagel** [comment]
> I have the same question...
> okay, fresh install and re chmod ,then it's OK now!

It was a permission issue right? 🤔

**Comment by insomnia417** [comment]
> > I have the same question...
> > okay, fresh install and re chmod ,then it's OK now!
> 
> It was a permission issue right? 🤔

YES,it is !

**Comment by ssersh** [comment]
Changing permissions doesn't help me.

**Comment by Fallenbagel** [comment]
What is the type of libraries you have? Are they set as "other"? Or "shows" and "movies"?
