### ISSUE TITLE
[Feature request] “issues” feature 

### ISSUE THREAD

**Issue by Derever** [Fallenbagel/jellyseerr#89]
#### Description

After switching from Omi to Jellyseerr I was really impressed! But I also realised there is no “issues” feature to report issues with existing media. This would be a very helpful feature.

Overseerr implemented such a feature in v1.28.0 (https://github.com/sct/overseerr/releases/tag/v1.28.0). So hopefully this makes the whole implementation process a lot easier.

#### Desired Behavior

Being able to report issues with existing media trough Jellyseerr.

#### Additional Context

-

**Comment by Fallenbagel** [comment]
Issues feature is present in the `develop` tag. We will merge develop branch with latest very soon. For now please use `develop` tag for the latest features of overseerr

**Comment by Fallenbagel** [comment]
Issues feature is present in the `develop` tag. We will merge develop branch with latest very soon. For now please use `develop` tag for the latest features of overseerr
