### ISSUE TITLE
Jellyseeerr doesn't seem to connect

### ISSUE THREAD

**Issue by kubilayverboom** [Fallenbagel/jellyseerr#895]
### Description

m running Jellyfin and Jellyseerr in Docker containers on the same Proxmox host.

However, I'm unable to log in to Jellyfin and encountering the following error:
 
![afbeelding](https://github.com/user-attachments/assets/f9be83bc-b356-475d-bff2-1bb4382b78bf)
 
 
Jellyseerr logs provide limited information, but the server is correctly added in the settings.json file.

### Version

1.9.2

### Steps to Reproduce

1. Go the url of Jellyseerr
2. Login with Jellyfin
3. Fill in credentials and login

### Platform

desktop

### Device

Docker

### Operating System

Ubuntu Server 22.04

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is a configuration issue. Please hop onto discord. We don't carry out support here.
