### ISSUE TITLE
[ Feature Request ] - PWA - Progressive webapp

### ISSUE THREAD

**Issue by Its4Nik** [Fallenbagel/jellyseerr#897]
### Description

I often use Jellyseerr on my phone and it would be quite nice to also be able to use it as progressive web app.

Microsoft got a really short and pretty explanatory explanation on how to achive this:
https://learn.microsoft.com/en-us/windows/android/pwa

### Desired Behavior

Use Jellyseerr as progressive web app (PWA) on android, as an APK download from the GitHub or even GooglePlay or other third party websites.

### Additional Context

https://learn.microsoft.com/en-us/windows/android/pwa

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Jellyseerr is already a pwa..

It's been a pwa since day 0.

![Screenshot_20240726_191618_One UI Home.jpg](https://github.com/user-attachments/assets/da9b4b17-d7e1-45bd-be38-d41ca680ee2d)

**Comment by Its4Nik** [comment]
> Jellyseerr is already a pwa..
> 
> It's been a pwa since day 0.
> 
> We even have web push support because it's a pwa. Pwa is not an apk. How you install a pwa is access your site using https and you should see an install button. For example chrome Android will show an install button on the address bar.
> 
> https://github.com/Fallenbagel/jellyseerr/blob/develop/public%2Fsite.webmanifest
> 
> ![Screenshot_20240726_191618_One UI Home.jpg](https://github.com/user-attachments/assets/da9b4b17-d7e1-45bd-be38-d41ca680ee2d)
> 
> 

Ok weird cause in my browser it doesnt get shown... do i need https connectivity?

**Comment by Fallenbagel** [comment]
> > Jellyseerr is already a pwa..
> > 
> > It's been a pwa since day 0.
> > 
> > We even have web push support because it's a pwa. Pwa is not an apk. How you install a pwa is access your site using https and you should see an install button. For example chrome Android will show an install button on the address bar.
> > 
> > https://github.com/Fallenbagel/jellyseerr/blob/develop/public%2Fsite.webmanifest
> > 
> > ![Screenshot_20240726_191618_One UI Home.jpg](https://github.com/user-attachments/assets/da9b4b17-d7e1-45bd-be38-d41ca680ee2d)
> > 
> > 
> 
> Ok weird cause in my browser it doesnt get shown... do i need https connectivity?

Yes that is a requirement for pwa.

**Comment by Its4Nik** [comment]
> > > Jellyseerr is already a pwa..
> > > 
> > > It's been a pwa since day 0.
> > > 
> > > We even have web push support because it's a pwa. Pwa is not an apk. How you install a pwa is access your site using https and you should see an install button. For example chrome Android will show an install button on the address bar.
> > > 
> > > https://github.com/Fallenbagel/jellyseerr/blob/develop/public%2Fsite.webmanifest
> > > 
> > > ![Screenshot_20240726_191618_One UI Home.jpg](https://github.com/user-attachments/assets/da9b4b17-d7e1-45bd-be38-d41ca680ee2d)
> > > 
> > > 
> > 
> > Ok weird cause in my browser it doesnt get shown... do i need https connectivity?
> 
> Yes that is a requirement for pwa. 

Oh okay then i am stupid, i am sorry for wasting your time
