### ISSUE TITLE
Forgot Password URL always adds "/"

### ISSUE THREAD

**Issue by Snowius** [Fallenbagel/jellyseerr#901]
### Description

I had my Internal URL/External URL as https://jellyfin.myServer.xyz/ and the forgot password URL redirected to https://jellyfin.myServer.xyz//web/index.html#!/forgotpassword.html

Problem is the "//" here. URL won't lead anywhere.

Not that big of a deal and probably a quick fix, but just signaling it.

### Version

1.9.2

### Steps to Reproduce

1. Go to Settings > Jellyfin > Scroll down to "Jellyfin Settings"
2. Put URL such as "https://jellyfin.myServer.xyz/" in External/Internal URL
3. Save changes
4. Try to hit the password reset on the login page. It won't lead anywhere.

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
You shouldn't add a trailing slash when you write the forget password url.
