### ISSUE TITLE
More root path besides normal and anime

### ISSUE THREAD

**Issue by Envie77** [Fallenbagel/jellyseerr#909]
### Description

At the Moment only normal tv shows, movies and anime shows get the right root path. For anime movies or documantarys for example you have to do it manually. 

### Desired Behavior

It would be nice if jellyseer could Auto path documantary for example to the right root path

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
#757 should implement this. This PR will be reworked but a setting to apply different options depending on certain conditions will be implemented.
