### ISSUE TITLE
Jellyseerr doesn't retain config

### ISSUE THREAD

**Issue by riccbos** [Fallenbagel/jellyseerr#91]
#### Description

I set up my instance of Jellyseer and all was working until I restarted the Docker container. After that I'm prompted with the "setup" screen that asks me to insert my Jellyfin info. I checked in the volume containing the config file and there is the right file (the one with all my information), only Jellyseerr seems not to be able to read it.

#### Version

Version 1.02

#### Steps to Reproduce

1. Setup Jellyseerr
2. Run `docker-compose restart jellyseerr`

#### Expected Behavior

I expect to open the web interface and find all the data I set up earlier

#### Additional Context

Here is my `docker-compose` file:

`version: '3.7'
services:

  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       network_mode: "bridge"
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Rome
       ports:
            - 5055:5055
       volumes:
            - /home/username/media/jellyseerr/config:/app/config`

**Comment by Fallenbagel** [comment]
That is probably because permission issue. Jellyseerr is unable to write the configs to the folder that is mapped so it is unable to retain the config

**Comment by riccbos** [comment]
I don't think that's the problem because if I open the file `settings.json` inside the config folder, I can see that Jellyseerr wrote into it before. The `config` folder belongs to `root` and has rw permission.

Thanks for the advice btw.

**Comment by Fallenbagel** [comment]
Is there anything in the logs?
Also to test could you try mapping the config folder to a docker volume? You can do this by

`docker create volume config`

And in docker-compose
`- config:/config`

**Comment by riccbos** [comment]
I did that, but now when I open the webpage I get this warning : `The /app/config volume mount was not configured properly. All data will be cleared when the container is stopped or restarted.`
This doesn't appear when I create the container with the `docker-compose` file that I posted above

**Comment by riccbos** [comment]
Ok, I have no idea why, but reloading the original `docker-compose` file now works fine. I have not changed anything yet now if I restart the container it retains the config.

**Comment by Fallenbagel** [comment]
> I did that, but now when I open the webpage I get this warning : `The /app/config volume mount was not configured properly. All data will be cleared when the container is stopped or restarted.`
> This doesn't appear when I create the container with the `docker-compose` file that I posted above

For future reference, though that appears as long as the volume is retained in your device the configs would remain. I use volumes for when testing though I do not recommend that to run as production

Anyways, glad you solved it!

**Comment by riccbos** [comment]
Thank you for your help. The project is amazing btw
