### ISSUE TITLE
Different quality profiles dor different users

### ISSUE THREAD

**Issue by RyuunosukeDS3** [Fallenbagel/jellyseerr#921]
### Description

I want specific users to have their quality profile set for 1080p and some to have a 4k quality profile. This should be as simple as saving in DB for each user a specific quality profile.

### Desired Behavior

When changing users permissions give them the option to use a default quality profile that differs from user to user

### Additional Context

I run everything on a RPI, which is good enough for direct play but it is a nogo for transcode. I want to make this available to my family but most of em don't have 4k compatible devices and don't have enough understanding to select their own quality profile. So it would be ideal so i can set one for each one of them.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
#757 should implement this. This PR will be reworked but this is something that will be implemented.
