### ISSUE TITLE
Cannot log out of Jellyseerr

### ISSUE THREAD

**Issue by Querzion** [Fallenbagel/jellyseerr#922]
### Description

I can't log out. When I try nothing happens. I have no idea what's going on, it started yesterday, and I thought it might just be a fluke or something else, but I have stopped and started the docker in unRAID multiple times and it still won't log me out, and on top of that it always starts with me logged in. 

### Version

1.9.2 Stable

### Steps to Reproduce

I don't remember, I have been fixing with Requestrr, and other notifications and a lot of things, I can't name which one it was that might have created the issue. I'm logged in on my main account, logged out and logged in to the other one's without a problem yesterday, but later in the evening I couldn't log out at all, and now it won't respond on the action and gives off problems regarding the settings I'm trying to save. 

### Platform

desktop

### Device

AM5 Platform

### Operating System

Unraid 7.0.0 Beta 2

### Browser

Brave Browser

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Please hop onto discord. We don't carry out support/troubleshooting here. Github issues is used mainly to track bugs and feature requests.
