### ISSUE TITLE
Show description only visible in thumbnail

### ISSUE THREAD

**Issue by MrMcDaddy** [Fallenbagel/jellyseerr#925]
### Description

Sometimes when looking for a new show to watch, Jellyseer only shows me the first 5 lines of the show's description in the thumbnail.
That's alright, no issue so far.

But when I then click the show to get more info, Jellyseerr states that there is no description available. Hence, the show page gives me LESS information than the thumbnail, which is a bit weird.

I could understand if there is no description available in general, but the description I can see in the thumbnail had to come from somewhere.

I want to point out that this does only happen with some shows, not all of them, but always the same ones. So there is probably some difference in the sourcing for the thumbnail's and the actual page's description.
If that's the case, a fallback logic which picks the thumbnail's source in case the page's source has no content would be very much appreciated!

### Version

1.9.2

### Steps to Reproduce

1. Search for a show, e.g. "A good day to be a dog"
2. Check the thumbnail and see the first 5 lines of the show's description
3. Click the thumbnail, head to the show page and find "No description available"

### Screenshots

Thumbnail:
![Screenshot_20240811_221421_Chrome](https://github.com/user-attachments/assets/d1622d33-af79-487b-a8f2-eb538e50cafd)
Description page:
![Screenshot_20240811_221443_Chrome](https://github.com/user-attachments/assets/7068d084-d75a-417d-9305-ccd6c1930efe)

### Platform

smartphone

### Device

Samsung S23 Ultra, Samsung Flip 4

### Operating System

Android 14

### Browser

Chrome

### Additional Context

Shows I've seen this behavior on:
- A good day to be a dog
- As beautiful as you
- The vanished elephant
- Piers Morgan Uncensored
- Detective Maniam

I mostly clicking through the recommendations and picked those out showing this behavior.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
This is a TMDB issue occuring when there is no description in the specified language.
When using the search endpoint, TMDB fallback to english if there is no description available in the specified language.
When using the item endpoint, TMDB doesn't fallback to english, hence the absence of a description.

I don't think there is much we can do on our side.

**Comment by gauthier-th** [comment]
> I assume falling back to the search endpoint in case no description is available and caching this somewhere is no option?
Not really, it would be an overload just for this specific use case.
But maybe we could do the request in the specified language, and then do a second request in English if the description is missing? @Fallenbagel wdyt?

You can also go on TMDB and contribute to add the translated description.

**Comment by Fallenbagel** [comment]
> > I assume falling back to the search endpoint in case no description is available and caching this somewhere is no option?
> 
> Not really, it would be an overload just for this specific use case.
> But maybe we could do the request in the specified language, and then do a second request in English if the description is missing? @Fallenbagel wdyt?
> 

We could do that. Tmdb is supposed to fallback to en but it seems it only works on specific endpoints (a bug apparently afaik) but for the time being we could manually fallback i guess? 🤔

**Comment by gauthier-th** [comment]
> Tmdb is supposed to fallback to en but it seems it only works on specific endpoints (a bug apparently afaik) but for the time being we could manually fallback i guess? 🤔

Yep I think we should do it. Not having any description on a media is kinda critical.

@MrMcDaddy could you please check that all fields other than the description are filled in correctly?
