### ISSUE TITLE
Language issue (Swedish)

### ISSUE THREAD

**Issue by mattish91** [Fallenbagel/jellyseerr#930]
### Description

One of my user just noticed that it says "Play on PLEX" when holding over the "partially availiable" button that redirects to my Jellyfin instance. Just wanted to let you know. 

If i can help translate in some way ill gladly help. 

### Version

1.9.2

### Steps to Reproduce

1. Get some content requested.
2. Let the content get availiable.
3. Go to the content availiable.
4. Hover the mouse over "Partially availiable" button.
5. Get result. (Atleast for Swedish)

### Screenshots

![image](https://github.com/user-attachments/assets/8a114102-f3f5-4943-b5ed-6f83b1421c83)

### Logs

```shell
Not needed.
```

### Platform

desktop

### Device

ANY

### Operating System

ANY

### Browser

ANY

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
https://github.com/fallenbagel/jellyseerr/blob/develop/CONTRIBUTING.md#translation

**Comment by Fallenbagel** [comment]
https://jellyseerr.borgcube.de/translate/jellyseerr/jellyseerr-frontend/sv/?q=Play&sort_by=-priority%2Cposition&offset=2

It's already translated

**Comment by Fallenbagel** [comment]
Merged in #934
