### ISSUE TITLE
Pull ETA from Sonarr/Radarr or Download Client

### ISSUE THREAD

**Issue by kylehandy123** [Fallenbagel/jellyseerr#935]
### Description

Hi,
I'd like to ask for a feature to be added that the ETA until the movie/show is downloaded gets displayed alongside "Requested" in Jellyseerr. I have users asking me what the ETA is for requested items, and I feel that having the ETA displayed in Jellyseerr would save server admins a bit of a headache and allow users to have an idea when their requested media will be available.

### Desired Behavior

ETA from either Sonarr/Radarr or the Download client displayed in Jellyseerr on the requested media.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
We already display the downloading status and the ETA from sonarr/radarr when something is being grabbed.

`enable scan` enables this feature.
