### ISSUE TITLE
Support for Tizen OS

### ISSUE THREAD

**Issue by msrodrigobr** [Fallenbagel/jellyseerr#941]
### Description

I am a jellyfin user, and as I owner of a samsung tv that uses tizen OS, I had to manually install Jellyfin on my TV. As we have a jellyfin client that runs on Tizen OS, I would like to know if its feasible to have the same client for Tizen OS. 

### Desired Behavior

Have Jellyfin App on Tizen OS

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Jellyseerr is a web app. You can just access jellyseerr in tizen Web browser
