### ISSUE TITLE
Add more notification types for users

### ISSUE THREAD

**Issue by HamletDuFromage** [Fallenbagel/jellyseerr#942]
### Description

Users can only get notifications for their own requests by pushbullet or pushover. Admins, however, have an entire array of notification services to choose from 

### Desired Behavior

Be able to use more notification services for individual users (specifically telegram and webhook)

### Additional Context

Admin: 
![image](https://github.com/user-attachments/assets/b645d066-efd3-49cf-8ed1-431554c54e30)

User: 
![image](https://github.com/user-attachments/assets/6710608c-944b-4c04-a308-c055e1cf93a1)

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
No users get telegram, discord and stuff too.

They only appear when admin sets it up.

**Comment by HamletDuFromage** [comment]
Oh that's correct, I didn't specify the bot username. Sorry!
