### ISSUE TITLE
[Feature Request] Support Mixed Media Type Library

### ISSUE THREAD

**Issue by m3shat** [Fallenbagel/jellyseerr#95]
#### Description

Jellyfin and Emby allow for libraries containing movies and series at the same time (mixed content). Libraries of such type are not recognized and not selectable by jellyseer.

#### Desired Behavior

Jellyseer should recognize these libraries and process/import/scan them accordingly (best effort)

**Comment by Fallenbagel** [comment]
What do you mean by mixed content? Emby and jellyfin pointing to same media library? If so jellyseerr should recognise as long as you pick one of them when setting up 🤔

**Comment by m3shat** [comment]
I mean this content type when creating a library:
![image](https://user-images.githubusercontent.com/11942295/169411628-8c24c060-84d3-4f2f-bb3c-91413ba69810.png)

**Comment by Fallenbagel** [comment]
Ah. Is that also a library type in jellyfin? Because I use jellyfin and I have not seen that type.

For now the current way overseerr and jellyseerr is built is to only detect library types of `Movies` and `Shows`

**Comment by m3shat** [comment]
Even through discouraged, it is indeed an available type, see [jellyfin documentation](https://jellyfin.org/docs/general/server/libraries.html#content).
Would it be possible to "force" jellyseerr to import such a library or would that require significant changes to the database/data model?

**Comment by Fallenbagel** [comment]
> Even through discouraged, it is indeed an available type, see [jellyfin documentation](https://jellyfin.org/docs/general/server/libraries.html#content). 

![image](https://user-images.githubusercontent.com/98979876/169424873-3db84fb2-f1e8-43b7-82f1-769d5df4b6c8.png)
is it the other library type?

> Would it be possible to "force" jellyseerr to import such a library or would that require significant changes to the database/data model?

Unfortunately forcing is not possible and it would require the a rewrite of how jellyseerr imports jellyfin libraries as it currently only looks for `tv` and `show` just like how overseerr does for plex

**Comment by m3shat** [comment]
> > Even through discouraged, it is indeed an available type, see [jellyfin documentation](https://jellyfin.org/docs/general/server/libraries.html#content).
> 
> ![image](https://user-images.githubusercontent.com/98979876/169424873-3db84fb2-f1e8-43b7-82f1-769d5df4b6c8.png) is it the other library type?

Yes

Additional Context:
I use this library type to have Anime Series and Anime Movies in one library

**Comment by Fallenbagel** [comment]
> Additional Context: I use this library type to have Anime Series and Anime Movies in one library

Oh. There was some other user who did the same thing, though it was just Anime Series so they just changed it to `Shows`.

**Comment by michaelkrieger** [comment]
I use this library type for documentaries and stand-up comedy, as I've found it best for these media types.  The 'Other' media type (formerly called Mixed Media) allows one to search both TheTVDB and TMDB and TVMaze and IMDB and other comparable things which can create more complete views for those kinds of content types.  The Movies data type does not allow scraping TV sources.  Comedy specials and Documentaries may have a source on movies or TV depending on the original source.

**Comment by Kuuchuu** [comment]
I would also love to see this feature built in. For me the content type is listed as "Mixed Movies and Shows" in the library creation screen
![image](https://user-images.githubusercontent.com/20036947/200629090-b449d31a-7d80-457d-9ebf-2460f951a81c.png)
and "Other" after it is created
![image](https://user-images.githubusercontent.com/20036947/200629262-40f13a90-d28d-4f0a-9209-4e23769e8e04.png)

Thanks for your work on this project, I appreciate it!
