### ISSUE TITLE
Broken link in readme (PR created)

### ISSUE THREAD

**Issue by Glich440** [Fallenbagel/jellyseerr#957]
### Description

The link to the documentation in the README.md file is broken, I have already submmited a PR that fixes it #956  

### Version

N/A

### Steps to Reproduce

1. Go to the readme
2. access the link to the docs
3. See that it leads to a 404

### Platform

desktop

### Device

All

### Operating System

All

### Browser

All

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
This link is not broken. I just tested it on Firefox (Windows & Linux), Edge (Windows) and Chrome (Windows & Linux), and it worked on every browsers.
Please provide more details on how to reproduce this (i.e. a video capture or info about your device) if you want to re-open the issue.

**Comment by Glich440** [comment]
I finally found why you couldn't reproduce the issue, the page only lands on a 404 if javascript is disabled, removing the backslash does make it load a bit faster and allow viewing without js.
