### ISSUE TITLE
users require e-mail adress even though "Require user email" is disabled

### ISSUE THREAD

**Issue by Wurzelmann** [Fallenbagel/jellyseerr#963]
### Description

I imported my users directly from Jellyfin via the **Users** menu, which worked perfectly, but every user has their username automatically filled as e-mail address in their user settings. I do not know if this has been like this since importing (more than a year ago), but I cannot delete those user names from the e-mail field without jellyseerr complaining

**Email required** even though the setting **Require user email** (Settings->Notifications->Email) is disabled and not checked.

My only options at this point are:

1. replace all those usernames in the e-mail field with actual e-mail addresses
2. ignore it (which seems to lead to problems when logging users in from new devices, since jellyseerr expects them to use an e-mail address, which they do not have with their account, and never needed before)

### Version

1.9.2

### Steps to Reproduce

1. import Jellyfin users via Users -> Import Jellyfin Users
2. klick **Edit** on a user without e-mail address
3. notice how jellyseer automatically copied their **Display Name** to the **Email** field
4. try to clear the **Email** field
5. jellyseerr complains with "Email required"

### Screenshots

![Screenshot_2024-09-07_16-42-46_jellyseer_require_user_mail_disabled](https://github.com/user-attachments/assets/c625b916-bd85-4d7f-b63d-7bc5f12d2858)
![Screenshot_2024-09-07_16-41-13_jellyseer_email_required](https://github.com/user-attachments/assets/17f53191-effb-409b-ac2d-e1937a4ecfdf)

### Platform

desktop

### Device

Desktop, laptops

### Operating System

Debian 12.7, Windows 10

### Browser

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The require email button is not for that. The email field in the profile has to be something. The reason why their usernames get copied is because of that. That is whats used for local logins. That field cannot be empty

**Comment by Wurzelmann** [comment]
Okay, so the copied username is a placeholder for the login then if it's a Jellyfin and not a local user, if I understood that correctly?

**Comment by Fallenbagel** [comment]
> Okay, so the copied username is a placeholder for the login then if it's a Jellyfin and not a local user, if I understood that correctly? 

Each user has two login types. Authentication through jellyfin and jellyseerr. Jellyfin authentication is handled by jellyfin. Jellyseerr login form has jellyseerr handling the authentication using the email & password. The problem we face when it comesnto jellyfin is, none or the users have an email as jellyfin doesn't use it. So we use usernames as emails. Now the issue comes when you want to use smtp, ofc these usernames aren't actually emails right? That's what the require emails button is for.

**Comment by Fallenbagel** [comment]
Just closing the issue as this issue is not really relevant anymore as described above ^

**Comment by Wurzelmann** [comment]
Ah, I see, thank you for explaining this. I just wanted to close it, thank you.
