### ISSUE TITLE
Jellyfin user profile picture when using a reverse proxy

### ISSUE THREAD

**Issue by NoZiL** [Fallenbagel/jellyseerr#964]
### Description

When a Jellyfin external URL is set, the web interface should get the profile picture from the value instead of the internal URL.

### Version

1.9.2

### Steps to Reproduce

1. Go to `/settings/jellyfin`
2. Set External URL
3. Right clic and inspect on the current user dropdown at top right
4. Check the src attribute
Src attribute should be the Exernal URL set

### Platform

desktop

### Device

web

### Operating System

web

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
I can't reproduce this.
I have a different internal and external URL for Jellyfin, but Jellyseerr uses the correct external URL for Jellyfin avatars.

**Comment by Fallenbagel** [comment]
It already does this. It uses the external url. You will need to relogin for it to change.
