### ISSUE TITLE
Add a content tag blacklist

### ISSUE THREAD

**Issue by Starkiller4011** [Fallenbagel/jellyseerr#970]
### Description

I understand that the blocking of adult material from TMDb has some issues but is there any reason why we can't have a content tag blacklist on the jellyseerr side? The ability to pull tags and filter based on them already exists, would be nice to have the ability to apply a universal tag blacklist in the settings so that we can keep anything that is tagged with certain tags from making it to any level in the app would be nice. Just a small example of the kinds of tags that I personally have come across while looking for kids movies, and the reason I am the only one who is able to use jellyseerr as a result; bondage, porno, erotic movie, lesbian, sexual violence, sadomasochism, sexual torture, etc. 

### Desired Behavior

Manually managed blacklist in the settings for content tags to make sure content with those tags are filtered out of the app entirely.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
#632
