### ISSUE TITLE
Sort and Filter Buttons Stay On Top

### ISSUE THREAD

**Issue by hieuhho** [Fallenbagel/jellyseerr#976]
### Description

Currently the sort button and the filter button in the the discovery movies/series tab and are out of frame when you scroll down.

### Desired Behavior

The sort and filter buttons should stay at the top, similar to the search box 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
This is the intended behavior.
