### ISSUE TITLE
This command was run via npm module 'win-node-env'

### ISSUE THREAD

**Issue by bulletproof2k** [Fallenbagel/jellyseerr#977]
### Description

Error at startup

### Version

Latest

### Steps to Reproduce

yarn start

### Screenshots

![Снимок экрана 2024-09-23 084423](https://github.com/user-attachments/assets/bb98c817-f7d8-4aab-9c33-61f8b02f76d9)

### Platform

desktop

### Device

iPhone

### Operating System

Windows 11 Pro

### Browser

Yandex Browser

### Additional Context

Recently, I started getting this error at startup, updated all packages, but this did not help solve the problem.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
This is a configuration issue. Your settings.json (located in the config folder) seems to be incorrectly formatted.
[Check the documentation](https://docs.jellyseerr.dev/getting-started/buildfromsource?versions=latest) for more information.
We don' carry support on GitHub. Please hope onto Discord if you want more help.

**Comment by bulletproof2k** [comment]
> @bulletproof2k That is the expected behavior. If you look at the release notes you can see how to fix that: [`v1.9.2` (release)](https://github.com/Fallenbagel/jellyseerr/releases/tag/v1.9.2)
> 
> Basically you need to downgrade the typeorm package before build

You can close the issue solved.
