### ISSUE TITLE
[Feature Request] Remove 'Jellyfin' References if Running Emby Environment Variable

### ISSUE THREAD

**Issue by msmcpeake** [Fallenbagel/jellyseerr#98]
### Description

I would like to see if when the JELLYFIN_TYPE=emby environment variable is set, references inside the webapp would say Emby instead of Jellyfin.

### Desired Behavior

References such as the login page and the "Play on Jellyfin" button on media pages would say Emby instead.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I have been working on this. Hopefully can implement this soon.
Currently only it chooses between plex and jellyfin depending on the mediaServerType.
Thanks for the request though, keeps me reminded c:

**Comment by msmcpeake** [comment]
Thanks for the response.  Awesome work, been waiting for integration since Overseerr dropped.
