### ISSUE TITLE
detailed request process

### ISSUE THREAD

**Issue by yohanb** [Fallenbagel/jellyseerr#982]
### Description

Hi!
First off, huge thanks for everyone's contributions in this repo 👏.
I was thinking that it would make sense to have a more detailed view of the request process in the UI.  I find it's difficult to know why a request isn't going through.  I need to dig into Radarr and figure out why it's not downloading; unavailable language, no matching quality profile, etc.
Would this be something of interest?  How would you see the information displayed on the UI?
I can give it a try by contributing a PR 😬

### Desired Behavior

Have a UI section for request details or simply add more statuses to the movies/series.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
Yep, how would you do that?
In Radarr, there is no such way of displaying why a movie is missing, it just shows the status as "Missing".
The only thing i can think of is to implement the "Interactive Search" dialog inside Jellyseerr, with the score and rejection beside each item. And that's not really the purpose of Jellyseerr to manage media files like Radarr does.

**Comment by yohanb** [comment]
> Yep, how would you do that? In Radarr, there is no such way of displaying why a movie is missing, it just shows the status as "Missing". The only thing i can think of is to implement the "Interactive Search" dialog inside Jellyseerr, with the score and rejection beside each item. And that's not really the purpose of Jellyseerr to manage media files like Radarr does.

I haven't explored Radarr's api TBH so not sure exactly what's possible.
If the returned status is missing, can't we perform a search in the backend and determine why based on some pretty simple logic?

**Comment by gauthier-th** [comment]
> on some pretty simple logic

That would mean having to fetch all Radarr/Sonarr settings (indexers, download clients, custom formats, etc.) and re-implementing some logic from Radarr/Sonarr, just to display an information that may not be exact and already available on Radarr/Sonarr.
You could instead go on Radarr/Sonarr and filter the unavailable media to manage them here.

Honestly I don't think that's a good idea.
