### ISSUE TITLE
[Feature Request] Multiple Plex servers

### ISSUE THREAD

**Issue by adocampo** [Fallenbagel/jellyseerr#983]
### Description

Yes, I know this is not the first issue with the same subject, but after looking those issues, I think my request is quite different. 

I have just one Plex instance, but I have quite a few friends who also has their own Plex and we're inviting us each other. 

### Desired Behavior

I would like too know if something is on my Plex or in one of my friend's Plex. Perhaps a badge in a blue color, instead of green, so I can avoid to download that media, and when clicking on the Plex icon inside the details will be shown if me or any of my friends have that media.

I don't know if that is even doable, the good thing is overseer is just querying just one Plex.

What do you think?

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
It may be doable. But in my opinion this would add a lot of complexity into the codebase for what seems to be a really niche feature.
I don't think we'll implement this, sorry.

**Comment by adocampo** [comment]
Oh, what a pity... but I don't know why I finally ended in jellyseer.... I've followed the github link in overseerr and I see now I'm on a computer that it's another repo... 

I'm telling that because sharing the media libraries in jellyfin is not as straight forwards as in plex, and perhaps overseer devs doesn't see this feature a niche feature... I know there are a lot of people sharing their plex with friends, and Tautulli is a project to show the stats of your plex server, and it's really useful when your plex server is accessed by others...

**Comment by gauthier-th** [comment]
Well feel free to open this issue on the Overseerr GitHub then :)
Can I close this issue?

**Comment by adocampo** [comment]
Yes, I already did. Sorry for the annoyance!!
