### ISSUE TITLE
Seamless Jellyfin User Synchronization Enhancement

### ISSUE THREAD

**Issue by Zar3leck** [Fallenbagel/jellyseerr#986]
### **Summary:**

This proposal aims to extend Jellyseerr's functionality by enabling seamless user synchronization between Jellyseerr and Jellyfin. The goal is to simplify user management by providing a unified interface to create, modify, and delete accounts, while ensuring data consistency between the two systems.

### Desired Behavior

**Key Features:**

- [ ]  Creating Jellyfin users from Jellyseerr:

- Automatic generation of strong passwords and email delivery.
- Assignment of predefined Jellyfin roles based on needs. 

- [ ] Synchronization of user information:

-   Real-time updates of profile information (name, email, etc.) between both systems.
-   Synchronization of password changes.

- [ ] Centralized management of roles and permissions:

- Definition of specific Jellyfin roles within Jellyseerr.
- Assignment of these roles to users during creation or modification.

- [ ] Intuitive user interface:

- Overview of Jellyfin and local users.
- Filters and sorting to facilitate user search.
- Modification history for transparent tracking.

**Benefits:**

- Simplified user management: Centralization of operations within Jellyseerr.
- Enhanced security: Automatically generated strong passwords.
- Data consistency: Real-time synchronization of user information.
- Flexibility: Custom configuration of roles and permissions.

**Technical Implementation (brief overview):**

- Use of the Jellyfin API: To create, modify, and delete Jellyfin users.
- Synchronization mechanisms: To maintain data consistency between the two systems.
- User interface: Integration of features into the existing Jellyseerr interface.

**Next steps:**

- Development of core features: User creation, modification, and deletion.
- Unit and integration testing: To ensure code quality.
- Documentation: Creation of detailed documentation for users and developers.
- Community: Soliciting feedback from the Jellyseerr community to improve the proposal.

### Additional Context

Gemini gave me a little boost in writing this post. This AI model totally got what I was trying to say and explained it perfectly. I hope it's clear to you all! Huge thanks to the devs for their awesome work. Keep up the great work!

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
So you want Jellyseerr to manage Jellyfin users. You could have just written that instead of asking Gemini to write 50 lines. I find it very disrespectful to ask an AI to write a bunch of crap that we have to take the time to figure out instead of taking a few minutes to write the feature request.

Managing users is not the purpose of Jellyseerr, there are other apps like jfa-go or wizarr that aims to do that.
