### ISSUE TITLE
Not Displaying Availible 4K Badge

### ISSUE THREAD

**Issue by Panda260** [Fallenbagel/jellyseerr#987]
### Description

On the discovery pages for TV shows and movies, as well as in collections, when a movie is only available in 4K, there is no 4K badge. You can only see that the movie is available in 4K when you click on it. it is not displayed anywhere else.

### Version

Latest dev

### Steps to Reproduce

Just request something only in 4K and then search for the movie, you will not see a 4K Green Badge

### Screenshots

![image](https://github.com/user-attachments/assets/1934032c-2e59-491b-8a76-af3fcfaf5ab6)
![image](https://github.com/user-attachments/assets/49256814-9a24-4e91-9110-723c0570a27f)
![image](https://github.com/user-attachments/assets/74f7ab69-573b-4291-b21e-948ab23ed468)
![image](https://github.com/user-attachments/assets/fdb1379b-368b-49f2-912f-93ae57346c6a)

### Platform

desktop

### Device

All

### Operating System

All

### Browser

Chrome

### Additional Context

On All Platform

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is not a bug. This is by design.

**Comment by Panda260** [comment]
> This is not a bug. This is by design.

um, okay, it works, but if I'm honest, wrong/error, can you explain to me what the idea behind it was, to only show the 1080p versions and not the 4k version, what's the point of that?

**Comment by Fallenbagel** [comment]
> > This is not a bug. This is by design.
> 
> um, okay, it works, but if I'm honest, wrong/error, can you explain to me what the idea behind it was, to only show the 1080p versions and not the 4k version, what's the point of that?

This is how it's implemented in overseerr. Whwre the availability green check is for only 1080p. 4k one doesnt show. It's just not implemented. So it's not a bug. It's a feature request. Please use the issue template accordingly and request for a feature request not a bug report.

**Comment by Panda260** [comment]
found it https://github.com/sct/overseerr/pull/3636
