### ISSUE TITLE
[Feature Request] Forgot Password Redirect to Emby's URL Format

### ISSUE THREAD

**Issue by msmcpeake** [Fallenbagel/jellyseerr#99]
### Description

Minor request. Currently, the link directs to Jellyfin's URL **http://address/web/#!/forgotpassword.html**.  Emby's forgot password URL is **http://address/web/index.html#!/startup/forgotpassword.html**

### Desired Behavior

Possibly update the URL syntax when the Emby environment variable is enabled.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Oh. I forgot to test this out while i was testing emby. Thanks for pointing it out!
This would be easy to implement 🤔

**Comment by douglasparker** [comment]
Hey @Fallenbagel,

I'm not sure if this is a regression or if just based on an older version of Jellyseerr, but I am experiencing this bug when using the image: `fallenbagel/jellyseerr:preview-postgres`.

See issue #628

**Comment by Fallenbagel** [comment]
> Hey @Fallenbagel,
> 
> I'm not sure if this is a regression or if just based on an older version of Jellyseerr, but I am experiencing this bug when using the image: `fallenbagel/jellyseerr:preview-postgres`.
> 
> See issue #628

Did you add the env variable?

**Comment by douglasparker** [comment]
> > Hey @Fallenbagel,
> > I'm not sure if this is a regression or if just based on an older version of Jellyseerr, but I am experiencing this bug when using the image: `fallenbagel/jellyseerr:preview-postgres`.
> > See issue #628
> 
> Did you add the env variable?

I did, but I guess it doesn't like quotes around emby! It's resolved now.
