### ISSUE TITLE
Auto log out when account is disabled in Emby

### ISSUE THREAD

**Issue by zer0ish** [Fallenbagel/jellyseerr#999]
### Description

I'm not sure if this is a bug, or a feature request, since I'm not sure what the intended behaviour should be for these situations.

I noticed that when I disable an account, whether through removing the user from the Emby LDAP group or simply checking the Disable account option in Emby for the user. They can still make requests using Jellyseerr. 

I would expect the behaviour to be once disabled, they are forcibly logged out so they can no longer access the Jellyseerr portal.

I'm not sure why it doesn't sync this from Emby to Jellyseerr.

If I remove the user from the Emby LDAP group, then remove the device from Emby Devices in settings, it kicks them out and they can no longer login to Emby. 

For Emby, you can achieve this by removing the Device they logged into, from the Devices section in settings. Once removed, they can't access the site anymore. 

Jellyseerr does show up in the Devices for the user when they log into the Jellyseerr portal, but even after removing the Device in Emby, it doesn't deny them access until the user themselves logout of Jellyseerr, which they don't do.

It would be nice to have some kind of option to disable the account in Jellyseerr if it can't sync with the Emby Devices.
Or a task to check if someone is disabled in Emby and if so, disable them in Jellyseerr, and when re-enabled, re-eneble it in Jellyseerr.

### Version

1.9.2

### Steps to Reproduce

1. Have a user created in Emby.
2. Have user logged in on Jellyseerr portal.
3. Disable the user account in Emby.
4. Have the user refresh the page, or close the browser and open it again.
5. User will still have access.

### Platform

desktop

### Device

All devices

### Operating System

Windows and Android

### Browser

Chrome, Edge, Brave, Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is not a bug. This should be a feature request

**Comment by zer0ish** [comment]
> This is not a bug. This should be a feature request. Please recreate the issue using the proper template so we can keep track easily (or to make things easier you could edit this issue to use the same format as the feature request too which you can find from other issues)

I just created the Feature request for this thanks.
